### ISSUE TITLE
color-no-hex should optionally not report for variable assignment

### ISSUE THREAD

**Issue by mehcode** [stylelint/stylelint#1006]
Something like `ignore: ["variables"]`.

**Comment by jeddy3** [comment]
Would using the [special disable comments](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#turning-rules-on-and-off) not suffice here? e.g.

```css

/* stylelint-disable color-no-hex */

:root { --custom-property-name: #000; }
$scss-and-precss-variable-name: #000;
$scss-map: (name: #000);
@less-variable-name: #000;
stylus-variable-name = #000
...

/* stylelint-enable color-no-hex */

...
```
