### ISSUE TITLE
Add ignore: ["consecutive-duplicates"] option to declaration-block-no-duplicate-properties

### ISSUE THREAD

**Issue by arkhi** [stylelint/stylelint#1021]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

An option `except: "consecutive"`

It is better explained in [csslint documentation for the rule `duplicate-properties`](https://github.com/CSSLint/csslint/wiki/Disallow-duplicate-properties).

> Which rule, if any, is this issue related to?

`declaration-block-no-duplicate-properties`

> What CSS is needed to reproduce this issue?

e.g.

```css
.foo {
    background-color: #fff;
    background-color: rgba(255, 255, 255, 0.5);
}
```

> What stylelint configuration is needed to reproduce this issue?

e.g.

```json
{
  "rules": {
    "declaration-block-no-duplicate-properties": true
  }
}
```

> Which version of stylelint are you using?

`4.4.0`
