### ISSUE TITLE
unit-case

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1025]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

New rule `unit-quantities-case`. Check case of units. Options: "lower"|"upper"

Example:

```css
a {
  margin: 10PX;
}
```

```css
a {
  margin: 10px;
}
```
