### ISSUE TITLE
value-keyword-case

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1027]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

New rule `unit-keywords-case`. Check case of units. Options: "lower"|"upper"

```css
a {
  display: block;
}
```

```css
a {
  display: BLOCK;
}
```
