### ISSUE TITLE
postcss-media-queries-parser

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1033]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

@jeddy3 @davidtheclark What do you think create separate repo `postcss-media-queries-parser` for parsing media queries to `media_query`, `expression`, `media_type`, `media_feature` nodes (based on postcss-value-parser). This made it possible to check units (use in `unit-*` rules) inside `expression` (`px`, `dpi` and etc). In the future it may be handy for other uses. Similar issue in `postcss` https://github.com/postcss/postcss/issues/782

**Comment by davidtheclark** [comment]
Yeah, I think that's a very good idea.

**Comment by jeddy3** [comment]
As @TrySound said, can't we already use `postcss-value-parser` here? In the doc it has any example of parsing a media feature: https://github.com/TrySound/postcss-value-parser#div

**Comment by evilebottnawi** [comment]
@jeddy3 I tried to use, but it is very inconvenient. Problem with `(`, `)`, each use of the outputs the function node, but in media queries may include many `(`, `)`. Try to parse

```css
@media 
  only screen and (min-width: 100px),
  not all and (min-width: 100px),
  not print and (min-height: 100px),
  (color),
  (min-height: 100px) and (max-height: 1000px),
  handheld and (orientation: landscape)
{
  html { background: red; }
}
```
