### ISSUE TITLE
Code comment to opt out of linting for section of code.

### ISSUE THREAD

**Issue by bjankord** [stylelint/stylelint#105]
Just found about this project, it looks great! Haven't read through all the docs so not sure if this exists already, but I'd like the ability to opt-out of linting a section of code by adding comments in my stylesheet similar to [eslint](http://eslint.org/docs/user-guide/configuring.html#configuring-rules).

Something like

````css
.foo {
 color: #f00;
}

/* stylelint-disable */
#bar {color: #0f0 !important;}
/* stylelint-enable */
```
