### ISSUE TITLE
selector-pseudo-element-case

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1058]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Valid:
```css
body::BEFORE {
    background-color: red;
    content: ' + ';
}
```

```css
body::before {
    background-color: red;
    content: ' + ';
}
```
