### ISSUE TITLE
selector-pseudo-class-case

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1059]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Both valid:

```css
body:HOVER {
    background-color: red;
}
```

```css
body:hover {
    background-color: red;
}
```
