### ISSUE TITLE
selector-id-unique

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1067]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Throw error if use double only unique id

```css
#test {
    color: red;
}

#test {
    color: blue;
}
```

But normal if

```css
#test {
    color: red;
}

#test a {
    color: blue;
}
```
