### ISSUE TITLE
selector-pseudo-class-parentheses-space-inside

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1073]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Valid with both:

```css
input:not( [type="submit"] ) {
    border: 1px solid #ccc;
    padding: 3px;
}

a:nth-child( 3 ) {
    color: red;
}
```

```css
input:not([type="submit"]) {
    border: 1px solid #ccc;
    padding: 3px;
}

a:nth-child(3) {
    color: red;
}
```
