### ISSUE TITLE
 function-url-no-scheme-relative 

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1084]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Good:
```css
.example {
  background: url(//www.google.com/images/example);
}
```

Bad:
```css
.example {
  background: url(http://www.google.com/images/example);
}
```

```css
.example {
  background: url(https://www.google.com/images/example);
}
```

**Comment by Nirazul** [comment]
I'm not sure which way it should be enforced as your "good" example is described as an anti-pattern:
[Reference](http://www.paulirish.com/2010/the-protocol-relative-url/)

**Comment by ntwb** [comment]
> I'm not sure which way it should be enforced as your "good" example is described as an anti-pattern:

I agree, you should no longer use `//`, use `http://` or `https://`

Wondering if enforcing `http://` or `https://` could be included in the [function-url-data-uris](https://github.com/stylelint/stylelint/tree/master/src/rules/function-url-data-uris) rule with a name change to `function-url-uris`?

**Comment by jeddy3** [comment]
> Wondering if enforcing http:// or https:// could be included in the function-url-data-uris rule with a name change to function-url-uris?

Interesting suggestion. I'm wondering if offering two rules provides more flexibility though. Given `function-url-protocol: "http"|"https"|"relative"` (which keeps `relative` available as an option as these things tend to go around and around), you could have:

```json
{ 
  "rules": {
     "function-url-data-uris": "never",
     "function-url-protocol": "https"
   }
}
```

i.e. Disallow data URIs in source files and, *if the url contains a protocol*, it must be `https`. This configuration *allows for relative and absolute paths* to assets.

Another example is how `function-url-data-uris` can be used to enforce *only* data URIs are used (i.e. no protocols and no relative/absolute paths):

```json
{ 
  "rules": {
     "function-url-data-uris": "always"
   }
}
```

I think this is something that would be difficult (or at least confusing) to do if we merged this proposal into `function-url-data-uris`.

**Comment by evilebottnawi** [comment]
@jeddy3 sound good. Relative with domain or without domain (with protocol or without)?

**Comment by ntwb** [comment]
> So my suggestion, is a new rule: function-url-protocol: "http"|"https"|"relative". Thoughts?

Nice @jeddy3, this looks great 👍

**Comment by davidtheclark** [comment]
I was thinking from the discussion above that maybe we need `function-url-no-relative-protocol`. The asset itself might determine whether you use `http` or `https`, so why would you want to lock in to one or the other?

**Comment by evilebottnawi** [comment]
@davidtheclark sometimes i need to use only relative. Be good have generic rule for this. May be `function-url-format`: "relative" | "absolute", and `options`: { "protocol": true | false }. Plus this will then add another option if you need it.

**Comment by davidtheclark** [comment]
I think those should be separate rules. Because I may not want to *always* use absolute protocols, but when I do I want to *always* include the protocol.

**Comment by jeddy3** [comment]
> The asset itself might determine whether you use http or https, so why would you want to lock in to one or the other?

I was thinking of this use case: a team prefers to use secure assets i.e. those over https. If a secure version of the asset isn't available then a team member must disable the rule with stylelint commands and provide a reason. 

> The asset itself might determine whether you use http or https

This is a good point. Perhaps adding a forth option to the proposed `function-url-protocol` rule e.g. ` "http"|"https"|"absolute"|"relative"` - where `"absolute"` is either http or https?

So, you'd use:

```json
{
  "rules": {
    "function-url-protocol": "absolute",
  }
}
```

I think, because the rule name contains "protocol", it's clear that such a configuration would allow these styles:

```css
a {
  background: url("x.jpg"); /* ignored because no protocol used */
  background: url("../x.jpg"); /* ignored because no protocol used */
  background: url("/x.jpg"); /* ignored because no protocol used */
  background: url("http://www.google.com/x.jpg");
  background: url("https://www.google.com/x.jpg");
}
```

But disallow:

```css
a {
  background: url("//www.google.com/x.jpg");
}
```

If we think the preference for secure assets isn't valid, we can just restrict the options to `"absolute"|"relative"`.
