### ISSUE TITLE
declaration-no-invalid

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1085]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Good:
```css
body {
    width: 500px;
}
```

```css
body {
    width: 0;
}
```

Bad:
```css
body {
    width: 500;
}
```
