### ISSUE TITLE
selector-attribute-brackets-space-inside

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1086]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Options: "always" | "never"

Both valid:

```css
a[ href^="http" ] {
    color: #ff0000;
}
```

```css
a[href^="http"] {
    color: #ff0000;
}
```
