### ISSUE TITLE
Missing closing quote error in scss file

### ISSUE THREAD

**Issue by smlombardi** [stylelint/stylelint#1108]
Stylelint 6.0.3 (command line) flags the content line in this code as an error:
```scss
  &.preview-example-live {
    &:before {
      font-family: 'FontAwesome';
      content: '\f0e7 Live example';
    }
  }
```

with this error
```
documentation.scss
 786:35  ✖  Unclosed quote   CssSyntaxError
```

**Comment by davidtheclark** [comment]
Huh. CssSyntaxErrors always arise from PostCSS itself in the parsing stage so we may have to file an issue there. But let's investigate further, first.

I am unable to reproduce this. Over at [AST explorer](https://astexplorer.net/) that snippet works without a syntax error. And I have written a test in stylelint to try to reproduce it and cannot. Can you provide some more context? It's possible that something else is going wrong which resulted in this error indirectly.

**Comment by smlombardi** [comment]
The entire block is
```scss
// PREVIEW "EXAMPLE" BOXES, AS ON BS.COM
.preview-example {
  background-color: #fff;
  position: relative;
  padding: 40px 9px 9px;
  border: 1px solid #e3e3e3;
  border-radius: 3px;
  margin: 20px 0;

  &:before {
    content: 'Example';
    position: absolute;
    font-size: 9px;
    top: 0;
    left: 0;
    padding: 3px 7px;
    text-transform: uppercase;
    background-color: #f5f5f5;
    border: 1px solid #e3e3e3;
    border-top: 0;
    border-left: 0;
    letter-spacing: .1em;
  }

  &.preview-example-live {
    &:before {
      font-family: 'FontAwesome';
      content: '\f0e7 Live example';
    }
  }

  +.preview-code {
    margin-top: -25px;
    margin-bottom: 20px;
  }
}
```

**Comment by davidtheclark** [comment]
Just to verify. Are you using `syntax --scss` when you run this?

**Comment by smlombardi** [comment]
```
staryu:sass stevelombardi$ stylelint syntax --scss *.scss


documentation.scss
 786:35  ✖  Unclosed quote   CssSyntaxError
````

Is this correct?

**Comment by smlombardi** [comment]
stylelint also flags a missing quote at the column of the closing quote here, after `'Helvetica Neue'`:

`$font-family-ps-bold-italic:    'PrecisionSans_W_BdIt', 'Helvetica Neue', Arial, sans-serif;`

```
_variables.scss
 861:72  ✖  Unclosed quote   CssSyntaxError
```

**Comment by davidtheclark** [comment]
No I mistyped first: `stylelint --syntax scss *.scss` The option is `syntax` and the value is `scss`.

**Comment by jeddy3** [comment]
FYI, I can't reproduce with the just-released `6.1.0`.

@smlombardi Do you want to try `6.1.0` and [double check](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/css-processors.md#parsing-non-standard-syntax) you've set the syntax option correctly?

**Comment by PhiLhoSoft** [comment]
I got this one because I forgot to specify the syntax option, too...

**Comment by evilebottnawi** [comment]
@smlombardi ping

**Comment by smlombardi** [comment]
Just tried it in command line with 6.2.2:
```
staryu:sass stevelombardi$ stylelint syntax --scss *.scss
documentation.scss
 741:35  ✖  Unclosed quote   CssSyntaxError
staryu:sass stevelombardi$ 
```
```scss
  &.preview-example-live {
    &:before {
      font-family: 'FontAwesome';
      content: '\f0e7 Live example';
    }
  }
```
