### ISSUE TITLE
function-url-quotes & font-weight-notation should ignore non-standard syntax

### ISSUE THREAD

**Issue by PhiLhoSoft** [stylelint/stylelint#1133]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Bug if you intent to fully support Sass (Scss) syntax.

> Which rule, if any, is this issue related to?

Several, see below.

> What CSS is needed to reproduce this issue?

```scss
@mixin font-face($family, $font-path, $file-name, $weight, $style)
{
	$file-path: $font-path + $file-name;
	@font-face
	{
		font-family: '#{$family}';
		src:
			url($file-path + '.woff2') format('woff2'),
			url($file-path + '.woff') format('woff'),
			url($file-path + '.ttf')  format('truetype');
		font-weight: #{$weight};
		font-style: #{$style};
	}
}

$font-path: '../fonts/';
$font-name: 'OpenSans';

@include font-face($font-name, $font-path, 'OpenSans-Light', '300', 'normal');
@include font-face($font-name, $font-path, 'OpenSans-Italic', 'normal', 'italic');
@include font-face($font-name, $font-path, 'OpenSans-Bold', 'bold', 'normal');
@include font-face($font-name, $font-path, 'OpenSans-Regular', 'normal', 'normal');
```
[font-declarations.scss.txt](https://github.com/stylelint/stylelint/files/234811/font-declarations.scss.txt)

> What stylelint configuration is needed to reproduce this issue?

```yaml
rules:
  function-url-quotes: "single"
  font-weight-notation: "named-where-possible"
```

> Which version of stylelint are you using?

6.2.1

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint --syntax scss *.scss`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Yes, it's related to SCSS variables and mixins.

> What did you expect to happen?

No warnings to be flagged. SCSS generates no syntax error on this code, and produces the right CSS.

> What actually happened (e.g. what warnings or errors you are getting)?

The following warnings were flagged:

```shell
font-declarations.scss
 16:8   ×  Expected single quotes around url argument         function-url-quotes
 16:8   ×  Expected single quotes around url argument         function-url-quotes
 17:8   ×  Expected single quotes around url argument         function-url-quotes
 17:8   ×  Expected single quotes around url argument         function-url-quotes
 18:8   ×  Expected single quotes around url argument         function-url-quotes
 18:8   ×  Expected single quotes around url argument         function-url-quotes
 19:16  ×  Unexpected invalid font-weight name "#{$weight}"   font-weight-notation
```
It doesn't like concatenation: `url($file-path + '.woff2')` and variable in place of the font name.
