### ISSUE TITLE
selector-attribute-operator-space-after/before

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1138]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

All valid:
```css
a[target = _blank] {
    background-color: #ff0000;
}
```
```css
a[target= _blank] {
    background-color: #ff0000;
}
```
```css
a[target =_blank] {
    background-color: #ff0000;
}
```
