### ISSUE TITLE
selector-max-empty-lines

### ISSUE THREAD

**Issue by dryoma** [stylelint/stylelint#1142]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Not sure if these are bugs, but could cause problems. There are situations where extra blank lines are accepted by stylelint, which is in most cases undesirable. The only way of preventing this I found is to set `"max-empty-lines": 0`

> Which rule, if any, is this issue related to?

"max-empty-lines"
"selector-list-comma-newline-after"
"block-opening-brace-newline-after"

> What CSS is needed to reproduce this issue?

```css
// 1) Both are technically correct, yet both clearly breach the code style
.u-myComp,

.U-myComp {
  ...
}

.u-myComp,
foo
.U-myComp {
  ...
}
// 2) There is no way to force no extra line here. Except setting `max-empty-lines` to 0, which is often undesirable.
.U-myComp {

  margin: 0
}
```
There might be other cases.

> What stylelint configuration is needed to reproduce this issue?

The relevant rules are:
```json
{
  "rules": {
    "max-empty-lines": 1,
    "selector-list-comma-newline-after": "always",
    "block-opening-brace-newline-after": "always-multi-line",
  }
}
```

> Which version of stylelint are you using?

`6.2.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

```js
.pipe(gulpPostCSS([
  // nested(),
  stylelint(),
  reporter({
    clearMessages: true,
    throwError: true
  })
], {
  syntax: scssSyntax
}))
```

> What did you expect to happen?

No extra blank lines or some settings to disallow them except `"max-empty-lines": 1`

> What actually happened (e.g. what warnings or errors you are getting)?
