### ISSUE TITLE
Can't inline disable a lint rule set by and extended config set

### ISSUE THREAD

**Issue by jonrohan** [stylelint/stylelint#1185]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

I'm trying to disable a lint error with an inline `stylelint-disable` and it's not disabling it. From what I can tell this is happening because my rule is in the extended `stylelint-config-standard`

> Which rule, if any, is this issue related to?

`declaration-block-no-ignored-properties`

> What CSS is needed to reproduce this issue?

```css
.column {
  /* disable reason */
  /* stylelint-disable declaration-block-no-ignored-properties */
  display: inline-block;
  float: none;
  /* stylelint-enable declaration-block-no-ignored-properties */
}
```

> What stylelint configuration is needed to reproduce this issue?

e.g.

```json
{
  "extends": "stylelint-config-standard",
  "rules": {
    "stylelint-disable-reason": "always-before"
  }
}
```

> Which version of stylelint are you using?

`6.2.2`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

I'm seeing this behavior through both CLI

`bin/stylelint "app/assets/stylesheets/**/*.scss" --config app/assets/stylesheets/.stylelintrc --syntax scss`

And the atom linter-stylelint plugin https://atom.io/packages/linter-stylelint

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

I'm using scss syntax

> What did you expect to happen?

No warnings

> What actually happened (e.g. what warnings or errors you are getting)?

I got the `declaration-block-no-ignored-properties` warning

```shell
❯ bin/stylelint "app/assets/stylesheets/**/*.scss" --config app/assets/stylesheets/.stylelintrc --syntax scss

app/assets/stylesheets/custom/site/utilities.scss
 27:5  ✖  Unexpected property "float" that is ignored because of "display: inline-block"   declaration-block-no-ignored-properties
```
