### ISSUE TITLE
selector-type-no-unknown

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1254]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Bad
```css
htmlelement {
  color: red;
}
```

God:
```css
section {
  color: red;
}
```

Search and include html library, which can validate html tags
