### ISSUE TITLE
selector-pseudo-colon-no-invalid-space

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1255]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Valid:
```css
a:hover {
  color: red;
}
```

```css
a
:hover {
  color: red !important;
}
```

With one options: "never"

**Comment by evilebottnawi** [comment]
Spaces before always are invalid

**Comment by davidtheclark** [comment]
How about `selector-pseudo-colon-no-space-around`.

If there's just a "never" option, seems to me it should be a `-no-` rule.

**Comment by evilebottnawi** [comment]
@davidtheclark sound good
@jeddy3 What do you think?

**Comment by davidtheclark** [comment]
If you or anyone wants to start on this feel free. @jeddy3 can comment on the name whenever he's back.

**Comment by evilebottnawi** [comment]
@davidtheclark i think we should add options `"ignore": ["nested"]` for
```scss
a {
  :hover,
  :focus {
    color: red;
  }
}
```

**Comment by davidtheclark** [comment]
Yeah, makes sense.

**Comment by evilebottnawi** [comment]
@jeddy3 @davidtheclark we should revise the rule, because (with space after)
```css
a ::after {
    content: "1";
    color: red;
}
```
is valid construction for pseudo-elements.

**Comment by evilebottnawi** [comment]
With pseudo classes always invalid space before and after. May be rename to selector-pseudo-classes-colon-no-space-around?

**Comment by davidtheclark** [comment]
Or we could just make `selector-pseudo-colon-no-space-after`

**Comment by evilebottnawi** [comment]
@davidtheclark for pseudo-classes invalid and before. Maybe
1. `selector-pseudo-classes-colon-no-space-before`
2. `selector-pseudo-classes-colon-no-space-after`
3. `selector-pseudo-element-colon-no-space-after`
?

**Comment by davidtheclark** [comment]
Might be simpler with:
- `selector-pseudo-colon-no-space-after`
- `selector-pseudo-classes-colon-no-space-around`

**Comment by evilebottnawi** [comment]
@davidtheclark `selector-pseudo-classes-colon-no-space-around` sound good, but `selector-pseudo-colon-no-space-after` may duplicate errors from the previous rules.

**Comment by jeddy3** [comment]
```css
a ::after {
    content: "1";
    color: red;
}
```

Is that really valid? Wow.

Sounds like there's three things going on here.

1. Disallowing *invalid* spaces in *pseudo-classes*.
2. Disallowing *invalid* spaces in *pseudo-elements*.
2. Allowing a user to specify a space or no space before the colon in *pseudo-elements*.

Does that sound about right? If so, does the following sound?:

- `selector-pseudo-class-colon-no-invalid-space: true` (checks for space before and after)
- `selector-pseudo-element-colon-no-invalid-space: true` (checks for space after)
- `selector-pseudo-element-colon-space-before: "always"|"never"

>  i think we should add options "ignore": ["nested"]

Is this even valid?:

```scss
a {
  :hover,
  :focus {
    color: red;
  }
}
```

I thought you had to use the *nesting selector* (even in SCSS) in this situation e.g.

```scss
a {
  &:hover,
  &:focus {
    color: red;
  }
}
```

**Comment by evilebottnawi** [comment]
@jeddy3 valid in SCSS, we get
```css
a :hover,
a :focus {
  color: red;
}
```
And non valid in CSS.
