### ISSUE TITLE
Bug: Various valid selector types incorrectly reporting as unknown type selectors

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#1352]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Bug: Various valid selector types incorrectly reporting as unknown type selectors:

• `:lang(x)`
• `:nth-child(x)`, `:nth-last-child(x)`, `:nth-last-of-type(x)`, `:nth-of-type(x)` parenthesis values
• `acronym`, `applet`, `big`, `hgroup`, `strike`, `submit`, `tt`

> Which rule, if any, is this issue related to?

 `selector-type-no-unknown`

> What CSS is needed to reproduce this issue?

#### `:lang`:
```css
:lang(X),
:lang(he-il) { 
  color: pink;
}
```

> Via https://css-tricks.com/almanac/selectors/l/lang/
> > _"The matching of X against the element's language value is performed case-insensitively for characters within the ASCII range. The identifier X does not have to be a valid language name."_

#### `nth-*`:
```css
.one li:nth-child(1)
.two :nth-last-child(-n+2) :nth-last-child(1),
.three :nth-of-type(3n+1),
.four:nth-of-type(even) {
  color: pink;
}
```

#### General: `acronym`, `applet`, `big`, `hgroup`, `strike`, `submit`, `tt`
```css

applet,
acronym,
big,
hgroup,
strike,
submit,
tt{
  color: pink;
}
```
> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "selector-type-no-unknown": true
  }
}
```

> Which version of stylelint are you using?

 `6.5.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint --config .stylelintrc test.css`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors you are getting)?

Using the following consolidated CSS:
```css
:lang(x),
:lang(he-il),
.one li:nth-child(1)
.two :nth-last-child(-n+2) :nth-last-child(1),
.three :nth-of-type(3n+1),
.four:nth-of-type(even),
applet,
acronym,
big,
hgroup,
strike,
submit,
tt{
  color: pink;
}
```

The following warnings were flagged:
```shell
11:7 Unexpected unknown type selector "x" (selector-type-no-unknown) [stylelint]
12:7 Unexpected unknown type selector "he-il" (selector-type-no-unknown) [stylelint]
14:22 Unexpected unknown type selector "-n" (selector-type-no-unknown) [stylelint]
14:25 Unexpected unknown type selector "2" (selector-type-no-unknown) [stylelint]
14:44 Unexpected unknown type selector "1" (selector-type-no-unknown) [stylelint]
15:21 Unexpected unknown type selector "3n" (selector-type-no-unknown) [stylelint]
15:24 Unexpected unknown type selector "1" (selector-type-no-unknown) [stylelint]
16:19 Unexpected unknown type selector "even" (selector-type-no-unknown) [stylelint]
17:1 Unexpected unknown type selector "applet" (selector-type-no-unknown) [stylelint]
18:1 Unexpected unknown type selector "acronym" (selector-type-no-unknown) [stylelint]
19:1 Unexpected unknown type selector "big" (selector-type-no-unknown) [stylelint]
20:1 Unexpected unknown type selector "hgroup" (selector-type-no-unknown) [stylelint]
21:1 Unexpected unknown type selector "strike" (selector-type-no-unknown) [stylelint]
22:1 Unexpected unknown type selector "submit" (selector-type-no-unknown) [stylelint]
23:1 Unexpected unknown type selector "tt" (selector-type-no-unknown) [stylelint]
```
