### ISSUE TITLE
Add severity and message to property-*-white/blacklist rules

### ISSUE THREAD

**Issue by woble** [stylelint/stylelint#1364]
> Feature request.

Allow custom severity and message for property-*-white/blacklist rules.

> Reason.

`Unexpected value "X" for property "Y"`doesn't really explain what value is accepted. One would have to dig through internal rules and guidelines to figure out what is accepted.

> Which rule, if any, is this issue related to?

For example `property-value-whitelist`

> Basic CSS example.

```css
:root {
    --order_0: 0;
}

.foo {
    z-index: 0; /* would not validate with following setup */
}

.baz {
    z-index: var(--order_0); /* would validate with following setup */
}
```

> Proposed setup.

```json
{
    "rules": {
        "property-value-whitelist": {
            "z-index" : [
                ["/^var\\(.*\\)/"],
                {
                    "severity": "error",
                    "message": "Expected a variable for property z-index."
                }
            ]
        }
    }
}
```
