### ISSUE TITLE
Unknown word error when SASS variables are interpolated using PostCSS plugin in Gulp 

### ISSUE THREAD

**Issue by mshick** [stylelint/stylelint#1368]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug where the following lines generate `Unknown word` errors:

* `@lost gutter #{map-get(("gutter": $grid-gutter-width), "gutter")}`
* `.#{$sprite-name} {`

> Which rule, if any, is this issue related to?

The error is `Unknown word` and it halts processing of the file. It must register as a syntax error.

> What CSS is needed to reproduce this issue?

e.g.

```scss
@mixin sprites($sprites) {
  @each $sprite in $sprites {
    $sprite-name: nth($sprite, 10);
    .#{$sprite-name} {
      @include sprite($sprite);
    }
  }
}
```

```scss
$grid-gutter-width: 20px;
@lost gutter #{map-get(("gutter": $grid-gutter-width), "gutter")};
```

> What stylelint configuration is needed to reproduce this issue?

Any, seemingly. I just extend the standard config, but get it regardless.

```json
{
  "extends": "stylelint-config-standard"
}
```

> Which version of stylelint are you using?

e.g. `6.5.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

through a custom gulp task. It looks like this:

```js
gulp.task('stylelint', () => {
  return gulp.src(`styles/**/*.{sass,scss}`)
    .pipe(postcss([
      stylelint({configFile: `styles/.stylelintrc`}),
      reporter({clearMessages: true, throwError: true})
    ]), {syntax: require('postcss-scss')});
});
```

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Yes, it relates to SCSS / SASS variables.

> What did you expect to happen?

No errors.

> What actually happened (e.g. what warnings or errors you are getting)?

```
Message:
    .../styles/base/_sprite.scss:664:8: Unknown word
    $sprite-name: nth($sprite, 10);
    .#{$sprite-name} {
       ^
      @include sprite($sprite);
```

Also, I have searched the existing issues and stackoverflow. None seems to apply exactly to this situation, for instance #1161, where using the `syntax` option was the fix, however that isn't available when using stylelint as a postcss plugin as I am. I do use the postcss-scss syntax, as shown in the code above.
