### ISSUE TITLE
New rule `no-restate-default-property`

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1477]
Error if you use:
```css
div {
  display: block;
}
```
or
```css
nobr {
    white-space: nowrap;
}
```

And etc. I can create repo, where we can collect default properties. @ntwb i think you are interested in this :)
