### ISSUE TITLE
Rule idea: `no-magic-numbers`

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1486]
Output error on strange value:
```css
.class {
  height: 23.3px;
  width: 37px;
}
```
With option `ignore: []`.
We should determined that it is `magic numbers`.
@ntwb can help us, because it is in https://github.com/ntwb/stylelint-config-wordpress#best-practices---handbook
