### ISSUE TITLE
selector-max-specificity crashes on :not pseudo-class with multiple params

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1504]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

```shell
stylelint '**/*.{css,scss}' --ignore-path .gitignore --syntax scss --color
```

Output:
```shell
undefined
```
And exit with code `1`.
> What CSS is needed to reproduce this issue?

e.g.

```scss
.pagination {
    &-item {
        &.pagination-item-away {
            &:not(.pagination-item-away-1, .pagination-item-away-2) {
                @media #{$xs-only} {
                    display: none;
                }
            }
        }
    }
}
```

> What stylelint configuration is needed to reproduce this issue?

Does not matter, because after debbuging, i get error `Invalid CSS selector`

> Which version of stylelint are you using?

e.g. `6.7.0`

I think trouble with multiple values in `not selector`, also in `function cssSyntaxError` in `standalone.js` we get error without `name`, `file` and other properties of `Error` class.
