### ISSUE TITLE
selector-type-no-unknown does not like keyframes with decimal value

### ISSUE THREAD

**Issue by nikolas6** [stylelint/stylelint#1513]
Stylelint 6.7.0 complains when keyframe animation has decimal value like "50.001%".

Sample:
```css
@keyframes loadingAnimation1 {
  0% {
    transform: translate3d(0, 0, 0);
  }
  50% {
    transform: translate3d(100%, 0, 0);
  }
  50.001% {
    transform: translate3d(-100%, 0, 0);
  }
  100% {
    transform: translate3d(0, 0, 0);
  }
}
```
