### ISSUE TITLE
Add comment-*-marker-newline-* rules

### ISSUE THREAD

**Issue by alexander-akait** [stylelint/stylelint#1516]
- [ ] `comment-opening-marker-newline-before`
- [ ] `comment-closing-marker-newline-after`

Valid

``` css
 /* Comment */
div,
 /* Comment */,
.class {
  /* Comment */
  display: inline;
  /* Comment */
}
 /* Comment */
```

and etc.

Invalid:

``` css
div {
  display: inline; /* Some comment */
}
```

and etc.

**Comment by jeddy3** [comment]
Sgtm.

- Name: `comment-no-inline`
- Primary option: `true`
- Secondary options: none
- Message: "Unexpected inline comment"
- Section: "Comment"

Does anyone have any queries about this, or shall I label it was as ready?

**Comment by ntwb** [comment]
Need to ensure compatibility with the `max-line-length` rule and `ignore: ["non-comments"]` option
https://github.com/stylelint/stylelint/tree/master/src/rules/max-line-length#ignore-non-comments

**Comment by jeddy3** [comment]
I think that any conflict that arises from turning on the rule in this proposal and `max-line-length` rule with its `ignore: ["non-comments"]` option [will need to be resolved by the user](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/faq.md#how-do-i-manage-conflicts-between-rules).

Any other queries, or shall I label up?

**Comment by davidtheclark** [comment]
> will need to be resolved by the user.

Agreed.

**Comment by ntwb** [comment]
All good 👍

**Comment by davidtheclark** [comment]
Thought about it another minute and I'm not thriled about the name `comment-no-inline`, because "inline comment" is used to refer to Sass/Less-style `//` comments (e.g. https://en.wikipedia.org/wiki/Comment_(computer_programming)). Can we think of another name?

**Comment by ntwb** [comment]
Pretty much there are two comment types, "block" or "inline" (also referred to as "line")

Broadly speaking both the comments below in programming languages both the comments in this code are referred to as `inline` comments...
```css

div {
  /* Some comment */
  display: inline; /* Some comment */
}
```

I searched through that Wikipedia reference and the one below, hunting for a generised term relating to "shared", "same line", "end of line" etc and nothing really stood out, the only thing I came up with was `comment-no-end-of-line` though I don't think that is the exactly succinct either.
https://en.wikipedia.org/wiki/Comparison_of_programming_languages_(syntax)#Comments

**Comment by m-allanson** [comment]
Would these be considered warnings?

```css
div {
  /* comment */ display: block;
}

div {
  display: /* comment */ block;
}
```

If so, the rule is to prevent a comment from appearing on the same line as any CSS statement. Maybe `comment-always-newlines` or `comment-no-shared-line` would work as the rule name?

**Comment by jeddy3** [comment]
`comment-no-shared-line` sounds like the best so far to me.

**Comment by jeddy3** [comment]
I've come to realise that when we struggle to name something (`*-no-empty-line-before`, `blockless-groups` etc) it's generally because we veering off our usual path.

I think what we're trying to achieve with this rule can be done with our usual `*-newline-before/after` approach. It'll be more powerful too.

- `comment-opening-marker-newline-before`
- `comment-closing-marker-newline-after`

Want to disallow shared line comments? e.g.

```css
div {
  /* comment */ display: block;
  display: /* comment */ block;
  display: block;  /* comment */
}
```

Use:

```js
"comment-opening-marker-newline-before": "always"
"comment-closing-marker-newline-after": "always"
```

Want to allow end of line comments but disallow comments like this?:

```css
div {
  /* comment */ display: block;
  display: /* comment */ block;
}
```

```js
"comment-closing-marker-newline-after": "always"
```

We can take it further and add:

- `comment-opening-marker-space-before`

Want to allow comments on lines by themselves and comments at the end of lines (but with single space before it) e.g.

```css
div {
  /* comment */
  display: block; /* comment */
}
```

```js
"comment-opening-marker-space-before": "always-shared-line"
"comment-closing-marker-newline-after": "always"
```

Sound good?
