### ISSUE TITLE
Apply property-* and unit-* rules to @support conditionals

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1553]
``` css
@supports (box-shadow: 0 0 2px black inset) {
  a {
    box-shadow: 0 0 2px black inset
  }
}
```

Ref: [Feature queries spec](https://www.w3.org/TR/css3-conditional/#at-supports)

**Comment by jeddy3** [comment]
I renamed the rule as [we already have](https://github.com/stylelint/stylelint/issues/1505) an issue for applying `unit-*` rules to all conditional rules.

**Comment by jeddy3** [comment]
On second thoughts, I've made the other issue just about the `unit-*` rules checking `@media` values and this one about general support for `@support`. I've done this because I'm unsure whether adding supporting for `@support` is worth the effort.

On initial inspection it appears to be a *significant* amount of work, and for little benefit as the way `@support` is typically used means things will be caught elsewhere in the source e.g.

Given this CSS:

```css
@supports (box-shadow: 0 0 2px black inset) {
  a {
    box-shadow: 0 0 2px black inset
  }
}
```

And this config:

```json
{
  "rules": {
    "color-named": "never"
  }
}
```

We'd get the following warning:

```console
3:20 Unexpected "black" (color-named)
```

And the same for something like:

```css
@supports (display: flex) {
  a {
    display: flex
  }
}
```

```json
{
  "rules": {
    "declaration-property-value-blacklist": { "display": ["flex"] }
  }
}
```

So, we're basically adding significant complexity to all these rules (e.g. we'll need to find a way to parse and index `@supports` parameters, as all these rules just use `root.walkDecls()` at the moment), and a ton of work, just for an *extra* warning.

Perhaps we can revisit this when `@support` becomes more widely used, but at the moment I'm in favour of closing this issue.
