### ISSUE TITLE
declaration-block-no-ignored-properties should allow float: none

### ISSUE THREAD

**Issue by octoxan** [stylelint/stylelint#1569]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

This rule should not throw an error if the float property is set to 'none'. You CAN float: none; and display: inline. I know you could put the float: left in a different media query, but that doesn't change the fact that float none is perfectly functional with display: inline. 

> Which rule, if any, is this issue related to?

declaration-block-no-ignored-properties

> What CSS is needed to reproduce this issue?

```css
@media (min-width: 600px) {
  .foo {
    float: left;
  }
}
@media (min-width: 900px) {
  .foo {
    float: none;
    display: inline;
  }
}
```
