### ISSUE TITLE
Add stylelint-disable-next-line disableRanges command

### ISSUE THREAD

**Issue by giladgray** [stylelint/stylelint#1614]
Would be super cool to add a `stylelint-disable-next-line` flag a la [TSLint](https://github.com/palantir/tslint#rule-flags) so my comments could always live on their own line.

**current syntax:**

```scss
.selector {
  // this color is essential
  color: blue !important; // stylelint-disable-line declaration-no-important
}

.selector2 {
  // this color is essential
  // stylelint-disable declaration-no-important
  color: blue !important; 
  // stylelint-enable declaration-no-important
  background: etc...;
}
```

**proposed syntax:**

```scss
.selector {
  // this color is essential
  // stylelint-disable-next-line declaration-no-important
  color: blue !important; 
  background: etc...;
}
```
