### ISSUE TITLE
Add ignore: ["comments"] option to max-line-length

### ISSUE THREAD

**Issue by giladgray** [stylelint/stylelint#1615]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Feature request for a new `ignore` option value for `max-line-length` rule to ignore line length _within_ comments.

Currently it supports an option to ignore _non-comments_ which honestly makes no sense to me. I would much rather ignore line length inside comments because they can easily be long (our source code includes long markdown documentation blocks) and enforce line length for the source code itself. A good example of a long comment line is one including a link to a very long URL which easily exceeds any reasonable line length limits.

> Which rule, if any, is this issue related to?

`max-line-length`

> What CSS is needed to reproduce this issue?

```css
/* @see http://lorem-ipsum-dolor-sit.amet/consectetur/adipisicing/elit/maxime/temporibus/quidem/ipsa/aspernatur-voluptas-rerum-labore-odit.omnis?dignissimos=obcaecati */
/* ^ line above is way too long but i can't break the link onto multiple lines. */
.foo {
  color: pink;
}
```

> Expected configuration to validate above source code:

```json
{
  "rules": {
    "max-line-length": ["100", {
      "ignore": ["comments"]
    }]
  }
}
```

Note: `"ignore"` option currently only supports `"non-comments"` value.

> Which version of stylelint are you using?
 
`6.8.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Node API + gulp plugin

> What did you expect to happen?

"No warnings to be flagged."

> What actually happened (e.g. what warnings or errors you are getting)?

Line in question is flagged as being way too long.
