### ISSUE TITLE
"at-rule-no-unknown" and mixins?

### ISSUE THREAD

**Issue by smlombardi** [stylelint/stylelint#1633]
All my mixins are flagged as warnings with `at-rule-no-unknown`.  This seems odd.

For example:
```scss
@mixin alert($bg, $bdr, $icon, $text: $pb-gray-700) {
  color: $text;
  background-color: $bg;
  background-image: url($icon);
  border-color: $bdr;
  i {
    color: $bdr;
  }
}
```
and
```scss
.alert-danger {
  @include alert($state-danger-bg, $state-danger-border, $icon-danger);
}
```
Which are both valid scss are flagged as warnings.  I had to disable the rule.
