### ISSUE TITLE
"Unknown word" error for interpolated value with function

### ISSUE THREAD

**Issue by niksy** [stylelint/stylelint#1640]
> Bug description

When trying to use function inside SCSS interpolation, stylelint reports syntax error with message "Unknown word".

```sh
index.scss
 17:44  ✖  Unknown word   CssSyntaxError
```

> How to reproduce

Input SCSS:

```scss
.foo {
	$var:foo;
	background-image:#{$var}bar;
}

.bar {
	$var:to-upper-case(foo);
	background-image:#{$var}bar;
}

.bad {
	$var:to-upper-case(foo);
	background-image:url(#{$var}bar);
}

.baz {
	background-image:url(#{to-upper-case(foo)}bar); // This is where error is triggered
}
```

Output CSS with node-sass 3.8.0:

```css
.foo {
  background-image: foobar; }

.bar {
  background-image: FOObar; }

.bad {
  background-image: url(FOObar); }

.baz {
  background-image: url(FOObar); }
```

---

Using latest stylelint with SCSS parser.

Is this related to stylelint or postcss-scss?
