### ISSUE TITLE
selector-attribute-operator-blacklist: only blacklists first element in array. 

### ISSUE THREAD

**Issue by rosven** [stylelint/stylelint#1644]
**BUG:**  `selector-attribute-operator-blacklist:`

when configuring ` "selector-attribute-operator-blacklist": ["*=","~=","|=","^="], `only the first token` "*="` is blacklisted. Other tokens are let through. i.e: 

**This is considered an error:**

```css
[title*='t1'] {
  border: 5px solid #FFF;
}
```

**The following are legal with this configuration:** 

```css
[class^='t2'] {
  background: #FFF;
}

[class|='t3'] {
  background: #FFF;
}
```

**.stylelintrc:**

```json
{
  "extends": "stylelint-config-standard",
  "rules": {
    "selector-attribute-operator-blacklist": ["*=","~=","|=","^="],
  }
}
```

stylelint version: **7.0.1**
stylelint-config-standard version: **11.0.0**

**Expected** 
```shell
npm run lint
 xx:x  ✖  Unexpected operator "*="           selector-attribute-operator-blacklist
 xx:x  ✖  Unexpected operator "^="           selector-attribute-operator-blacklist
 xx:x  ✖  Unexpected operator "|="           selector-attribute-operator-blacklist
```
**Got**
```shell
npm run lint
 xx:x  ✖  Unexpected operator "*="           selector-attribute-operator-blacklist
```
