### ISSUE TITLE
Expand regex option documentation across rules

### ISSUE THREAD

**Issue by rosven** [stylelint/stylelint#1650]
**BUG: selector-class-pattern** 
Does not seem to handle regex expressions properly.

When testing the example as in the documentation: 

```json
"selector-class-pattern": "/foo-[a-z]+/",
````

Both selectors fail, but only the first should fail in theory. 
```css
.foo-BAR {
  color: #FFF;
}

.foo-bar {
  color: #FFF;
}
```

It was wanted to ban following patterns in my css files since the selectors are imported as variables in javascript. 

```css
.test-class {
  color: #FFF;
}
```

And instead allow

```css
.testClass {
  color: #FFF;
}
```

stylelint version: **7.0.1**
stylelint-config-standard version: **11.0.0**

**.stylelintrc:**
```json
{
  "extends": "stylelint-config-standard",
  "rules": {
    "selector-class-pattern": "/[a-z][a-z0-9A-Z]+/",
  }
}
```

The regex `\([a-z][a-z0-9A-Z]+)\` works fine and can be tested at: http://regexr.com/

```css
.testClass {
  color: #00F;
}

.test-class {
	color: #00F;
}
```
**Expected:**
```shell
 x:x  ✖  Expected class selector ".test-class" to match specified pattern   selector-class-pattern
```

**Got:**
```shell
 x:x  ✖  Expected class selector ".testClass" to match specified pattern    selector-class-pattern
 x:x  ✖  Expected class selector ".test-class" to match specified pattern   selector-class-pattern
```
