### ISSUE TITLE
block-closing-brace-newline-after: ignores array of rules in ignored at-rules

### ISSUE THREAD

**Issue by niksy** [stylelint/stylelint#1651]
## Description

When using `block-closing-brace-newline-after`, array of ignored at-rules in `ignoreAtRules` is ignored.

## How to reproduce

`index.scss`

```scss
@if $foo == block {
	display:block;
} @else {
	display:inline-block;
}
```

`.stylelintrc`

```json
{
	"rules": {
		"block-closing-brace-newline-after": ["always", {
			"ignoreAtRules": ["else"]
		}]
	}
}
```

CLI output when using `stylelint index.scss --syntax scss`

```sh
index.scss
 3:2  ✖  Expected newline after "}"   block-closing-brace-newline-after
```
