### ISSUE TITLE
How to disable "declaration-colon-newline-after"?

### ISSUE THREAD

**Issue by marvinhagemeister** [stylelint/stylelint#1668]
I'm extending the `stylelint-config-standard` configuration and would love to disable a few rules. But the `declaration-colon-newline-after` in particular only supports the values `always` and `always-multi-line` and not `never`. So I'm unable to deactivate this specific rule.

> Which rule, if any, is this issue related to?

e.g. `declaration-colon-newline-after`

> What CSS is needed to reproduce this issue?

```css
@font-face {
  font-family: 'foo';
  src: url('fonts/foo.eot');
  src: url('fonts/foo.eot?#iefix') format('embedded-opentype'),
    url('fonts/foo.woff2') format('woff2'),
    url('fonts/foo.woff') format('woff'),
    url('fonts/foo.ttf') format('truetype');
}
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "extends": "stylelint-config-standard",
  "rules": {
    "declaration-colon-newline-after": "never"
  }
}
```

> Which version of stylelint are you using?

e.g. `7.0.2`
