### ISSUE TITLE
comment-no-empty

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1677]
Disallow empty comments.

Invalid:
```css
/* */
div {
  /* */
  color: red;
  /* */
}
/* */
```

Valid:
```css
/* Some comment */
div {
  /* Some comment */
  color: red;
 /* display: block; */
 /* Some comment */
}
/* Some comment */
```
