### ISSUE TITLE
Add ignoreAtRules: [] option to max-nesting-depth

### ISSUE THREAD

**Issue by aaronbushnell** [stylelint/stylelint#1705]
I'd like to ignore nested media queries when using `max-nesting-depth`.

Given:
```json
{
  "rules": {
    "max-nesting-depth": [1, {
      ignore: ["at-rules-without-declaration-blocks"]
    }],
  }
}
```

I expect:
```css
.module {
  padding: 1rem;

  .a-nested-item {
    color: red;

    /* An error should occur here*/
    .a-further-nested-item {
      color: green;
    }

    /* This should not throw an error */
    @media (min-width: 50em) {
      color: green;
    }
  }
}
```

What I got:
```css
.module {
  padding: 1rem;

  .a-nested-item {
    color: red;

    /* An error occurred here*/
    .a-further-nested-item {
      color: green;
    }

    /* Another error occurred here*/
    @media (min-width: 50em) {
      color: green;
    }
  }
}
```

- **Stylelint version:** 7.0.3
- **Running via:** PostCSS + Atom plugin
- **Related to non-standard syntax?**: Yes, nesting.
