### ISSUE TITLE
Add ignoreTypes: [] option to selector-no-type

### ISSUE THREAD

**Issue by Garbee** [stylelint/stylelint#1706]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

This is a feature request for `selector-no-type` to be allowed a whitelist of types to be used.

> Which rule, if any, is this issue related to?

`selector-no-type`

> What CSS is needed to reproduce this issue?

e.g.

```css
fieldset:disabled .a-button {
  color: pink;
}
```

> What stylelint configuration is needed to reproduce this issue?

e.g.

```yaml
extends: stylelint-config-standard
rules:
  selector-no-type: true
```

> Which version of stylelint are you using?

`7.0.3`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Automated through webpack.

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Not initially, but we are using Scss so our source looks more like `fieldset:disabled &` over having the selector directly behind the type.

> What did you expect to happen?

I expect a configuration option to allow us to specifically allow `fieldset` (or any other given elements to the whitelist) to not trigger the `unexpected type error`.

> What actually happened (e.g. what warnings or errors you are getting)?

Unexpected type error on the line defining the disabled fieldset target.
