### ISSUE TITLE
New rule: `no-missing-comment`

### ISSUE THREAD

**Issue by VPenkov** [stylelint/stylelint#1719]
Can we get a rule where there *has* to be a comment at the beginning in each file?

Valid result:
```css
/* This is a comment */
.rule { margin: 0; }
```

Invalid result:
```css
.rule { margin: 0; }
```
