### ISSUE TITLE
New rule: `comment-pattern`

### ISSUE THREAD

**Issue by VPenkov** [stylelint/stylelint#1720]
Can we get a regex pattern rule for comments? That way we can enforce doc blocks for styleguides.

**Comment by evilebottnawi** [comment]
@VPenkov can you give example? Be better format issue as template

**Comment by jeddy3** [comment]
Can we get some examples of how this would work? I'm curious how'd you'd differentiate between doc blocks and, say, shared end of line single line comments e.g.

```css
/**
 * What does here?
 */
.button {
  top: 10px; /* magic number for header */
}
```

Perhaps calling this `comment-multi-line-pattern` would help?

Once we know a few more details we can work out whether this should be a plugin or a rule.
