### ISSUE TITLE
declaration-block-no-redundant-longhand-properties

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1735]
Ref: https://github.com/CSSLint/csslint/wiki/Require-shorthand-properties
Ref: https://github.com/CSSLint/csslint/issues/668

I don't know best name for rule :smile: 

Throw error if we use all 4 values, also throw errors if we use top and left, top and left and right.
Example:
```css
a {
  padding-top: 1px;
  padding-right: 2px;
  padding-bottom: 3px;
  padding-left: 4px; /* Throw error, need `padding: 1px 2px 3px 4px;` */
}
```

```css
a {
  padding-top: 5px;
  padding-right: 5px;
  padding-bottom: 5px; /* Throw error, need `padding: 1px 2px 3px;` */
}
```

```css
a {
  padding-top: 5px;
  padding-right: 5px; /* Throw error, need `padding: 1px 2px;` */
}
```
Also add option `minProperties`(maybe rename) to control how many properties throw errors.

**Comment by Arcanemagus** [comment]
Might want to create a label or milestone to track these "CSSLint compatibility" issues.

**Comment by davidtheclark** [comment]
Milestone sounds good. Just created one.

**Comment by jeddy3** [comment]
Lets only check for when *all four* longhand properties are used. Warning when there are only *three* or *two* longhand properties will lead to second guessing the author's intent e.g.

```css
a {
  margin: 10px;
}

/* the authors intent is to override everything *but* the top margin */
a.primary {
  margin-bottom: 0;
  margin-left: 0;
  margin-right: 0;
}
```

I assume that's why the CSSLint rule only checks for *all four* properties too.

**Comment by evilebottnawi** [comment]
@jeddy3 example without `top` and no throw errors, only if you have all 4 options, or (top and right and bottom), or (top and right)

**Comment by jeddy3** [comment]
> or (top and right and bottom), or (top and right)

I'm strugglingly to understand this bit. Can you explain it again? 

Doesn't:

```css
padding: 1px 2px;
```

Equal:

```
padding-top: 1px;
padding-bottom: 1px;
padding-left: 2px;
padding-right: 2px;
```

**Comment by evilebottnawi** [comment]
@jeddy3 
if i use
```
a {
  padding-top: 1px;
  padding-right: 2px;
  padding-bottom: 3px; 
}
```
I can short to `padding: 1px 2px 3px`, but only if i use `top`, `right` and `bottom`, if i have no `top` or `right` not throw error.

**Comment by davidtheclark** [comment]
I'll try to help clarify. I think the rule looks for `padding-[side]` declarations, and then if all of them are used suggests that you use the `padding` shorthand.

**Comment by davidtheclark** [comment]
> Also add option minProperties(maybe rename) to control how many properties throw errors.

I don't see this in the CSSLint rule so let's not consider clarifying and creating it essential for now.

**Comment by evilebottnawi** [comment]
@davidtheclark i thinkw e should throw errors on all variants:
```css
a {
  padding-top: 1px;
  padding-right: 2px;
  padding-bottom: 3px;
  padding-left: 4px; /* Throw error, need `padding: 1px 2px 3px 4px;` */
}
```

```css
a {
  padding-top: 5px;
  padding-right: 5px;
  padding-bottom: 5px; /* Throw error, need `padding: 1px 2px 3px;` */
}
```

```css
a {
  padding-top: 5px;
  padding-right: 5px; /* Throw error, need `padding: 1px 2px;` */
}
```
But `CSSLint` throw error only on 4 properties, `"minProperties": 4` allow throw error only on first example (need for csslint-compat).
