### ISSUE TITLE
Add option `first-nested-before-at-rule` in `except` to `at-rule-empty-line-before`

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1755]
Configuration:
```json
{
"at-rule-empty-line-before": [
  "always",
  {
    "except": [
      "blockless-after-same-name-blockless",
      "first-nested"
    ],
    "ignore": [
      "after-comment"
     ]
  }
]
}
```
Allow use construction with (if you using `always`):
```scss
item {
        @include clearfix();
        @extend .list-group-item;
        @extend .list-group-item-small;
        position: relative;
}
```
