### ISSUE TITLE
Rule idea: function-no-unknown

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1779]
Valid:
```css
a {
  filter: blur(10px);
}
```

Invalid:
```css
a {
  filter: blurr(10px);
  color: rgbaa(10, 10, 10, 1);
}
```
