### ISSUE TITLE
Rule idea: no-tabs

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1781]
Why? I don't see tab anywhere in my code:
Valid, but i wan't to invalid:
```css
/*	Some comment with tabs	*/
a::before {
  content: "	Opts here tab:(";
}
```
Or in nonstandard syntax(SCSS)
```scss
.#{$class-selector}			a { // I really do not like the tab
    color: #fff;
}
```

**Comment by jeddy3** [comment]
```scss
.#{$class-selector}			a { // I really do not like the tab
    color: #fff;
}
```

Is that a dupe of https://github.com/stylelint/stylelint/issues/1592?

So, it's tabs within comments and content strings you wish to disallow? I'm wary of adding a wide-reaching rule to do this, one that could conflict with things like https://github.com/stylelint/stylelint/issues/1592 or `indentation`.

Is there another approach here? Smaller, more focused rules perhaps? Or we could push this to a plugin?
