### ISSUE TITLE
False positives for @apply mixins with root-no-standard-properties

### ISSUE THREAD

**Issue by kevinSuttle** [stylelint/stylelint#1789]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Allowing mixin definitions (for later use with `@apply`) inside of `:root` triggers a warning. 

> Which rule, if any, is this issue related to?

`root-no-standard-properties`

> What CSS is needed to reproduce this issue?

```css
:root {
  --ThemeAnimationStyles {
      transition-duration: .2s;
      transition-timing-function: cubic-bezier(.075, .820, .165, 1);
  }
}
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "root-no-standard-properties": true
  }
}
```

> Which version of stylelint are you using?

`7.1.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Visual Studio Code plugin

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Maybe? 

> What did you expect to happen?

 "No warnings to be flagged."

> What actually happened (e.g. what warnings or errors you are getting)?

"The following warnings were flagged:"

```
Unexpected standard property:  transition-duration
```
