### ISSUE TITLE
New rules: block-opening-brace-before and -after

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#18]
I will work on this.

**Comment by davidtheclark** [comment]
For this and most of the other whitespace-related ones --- do we want to leave the whitespace entirely open-ended, or just give the keyword options "space" and "newline"? Do we imagine scenarios when somebody might want to do something weird like use 4 spaces, a tab, 2 newlines, a carriage return, etc.? It would certainly simplify things if we only had "space" and "newline" as keywords for the options ... Thoughts?

**Comment by davidtheclark** [comment]
Disclosure: I'm kind of leaning towards keywords myself, because it makes things much simpler and I have this sense that anything other than space/newline is a serious edge case ...

**Comment by MoOx** [comment]
Go simple indeed !

**Comment by jeddy3** [comment]
Agreed.

**Comment by davidtheclark** [comment]
I'm throwing out the single- vs multi-line distinction for this rule unless somebody requests it. It would add significant complexity that I would rather not build in for a questionable use-case. The only use-case I can think of is a styleguide that wants this:

```css
body { color: pink; }

a
{
  color: pink;
  background: orange;
}
```

But I think pretty much everybody would prefer consistency before that brace ... either:

```css
body { color: pink; }

a {
  color: pink;
  background: orange;
}
```

or:

```css
body
{ color: pink; }

a
{
  color: pink;
  background: orange;
}
```

... since I think the only reason to have a newline before the brace is to clearly demarcate the selector
