### ISSUE TITLE
Do not compare selectors ending in pseudo classes to selectors ending in pseudo elements in no-descending-specificity

### ISSUE THREAD

**Issue by eviltwin** [stylelint/stylelint#1811]
With the following CSS:

```css
.Button {
  display: inline-block;
  margin: 0;
  padding: 0.75em 1em;
}

.Button:not(.disabled):active {
  padding-top: calc(0.75em + 1px);
  padding-bottom: calc(0.75em - 1px);
  box-shadow: inset 0 1px 0 rgba(0, 0, 0, 0.16);
}

.Button::-moz-focus-inner {
  border: 0;
  padding: 0;
}
```

and the following `.stylelintrc` in the same directory:

```json
{
  "rules": {
    "no-descending-specificity": true
  }
}
```

When I run the command: `stylelint Button.css`

I get the warning:

```shell
button.css
 13:1  ✖  Expected selector ".button::-moz-focus-inner" to come before selector ".button:not(.disabled):active"   no-descending-specificity
```

but, since `.Button::-moz-focus-inner` is actually selecting a pseudo element within the `.Button`, the rules don't conflict and I wouldn't expect to get a warning about specificity. (Unless my understanding of the CSS is flawed here..?)

stylelint version 7.1.0
