### ISSUE TITLE
Add stylelint-disable-no-empty rule

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1814]
Disable empty `stylelint-disable` in files.
Invalid:

``` css
/* stylelint-disable */
.selector {
  color: red;
}
```

``` css
.selector {
  color: red; // stylelint-disable
}
```

Valid:

``` css
/* stylelint-disable color-named */
.selector {
  color: red;
}
```

``` css
.selector {
  color: red; // stylelint-disable color-named
}
```

Some people in the team think that turning off `stylelint`, review will be faster accepted. Be good if CI down for this bad guys :smiling_imp:
