### ISSUE TITLE
New rules: value-list-comma-newline-*

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#183]
To compliment the `value-list-common-space-*` rules to provide multi-line value list functionality. E.g. given:

```js
value-list-comma-newline-after: [2, "always-multi-line"]
value-list-comma-space-after: [2, "always-single-line"]
value-list-comma-space-before: [2, "never"]
```

You'd be able to enforce these two types of value lists in the same CSS document:

```css
a {
  font-family: sans, serif, monospace /* value-list single-line with space after */
}

b {
  box-shadow: 1px 1px 1px #000, /* value-list multi-line with newline after... */
    2px 2px 1px 1px #ccc inset,     /* ... */
    2px 2px 1px 2px #ccc inset;     /* ... */
}
```

Ref #178
