### ISSUE TITLE
Add support of `font-display` property

### ISSUE THREAD

**Issue by ArmorDarks** [stylelint/stylelint#1837]
``` css
@font-face {
  font-display: swap|auto|fallback;
}
```

returns

```
✖  Unexpected unknown property "font-display"   property-no-unknown
```

That property still in draft, but already supported by Chrome.

[Details](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display).
