### ISSUE TITLE
Add support of `text-size-adjust` property

### ISSUE THREAD

**Issue by ArmorDarks** [stylelint/stylelint#1838]
``` css
 html { text-size-adjust: 100%; }
```

returns

```
✖  Unexpected unknown property "text-size-adjust"   property-no-unknown
```

I agree that it's non-standard property, but it's used by mobile browsers.

[Details](https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust).
