### ISSUE TITLE
Should rule-nested-empty-line-before skip the first nested rule?

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#185]
The first rule in the document is ignored by default. Should this behaviour be replicated for the first nested rule. For example, this is a common pattern:

```css
@media (--md-viewport) {
  .Project-body {
    display: flex;
    flex-direction: row-reverse;
  }

  .Project-media {
    flex: 1;
  }

  .Project-copy {
    flex: 2;
  }
}
```

Empty lines before nested rules, except for the first nested rule.

Should this be the default behaviour of `"always"` (like it is for first rule in the document) or should there be a `"always-except-first"` option?
