### ISSUE TITLE
False positive when a list of animations is used in no-unknown-animations

### ISSUE THREAD

**Issue by thykka** [stylelint/stylelint#1902]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

If `animation-name` contains more than one identifier, the subsequent identifiers are incorrectly detected as `no-unknown-animations`, regardless of whether the animations are actually defined. 

> Which rule, if any, is this issue related to?

`no-unknown-animations`

> What CSS is needed to reproduce this issue?

```css
.myElement {
  animation-name: doThis, doThat;
}

@keyframes doThis {
  0% { opacity: 0; }
  100% { opacity: 1; }
}

@keyframes doThat {
  0% { opacity: 1; }
  100% { opacity: 0; }
}
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "no-unknown-animations": true,
  }
}
```

> Which version of stylelint are you using?

`6.0.3`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

PostCSS/CSSNext via Gulp

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

no.

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors you are getting)?

The following warning was flagged:

```shell
test.css
2:19  ✖  Unexpected unknown animation name "doThis, doThat"   no-unknown-animations
```
