### ISSUE TITLE
Fresh install throw me "Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by MoOx** [stylelint/stylelint#1914]
```
TypeError: Cannot read property 'length' of undefined
    at exports.default (/Users/moox/Sync/Development/phenomic/docs/node_modules/stylelint/dist/utils/isStandardSyntaxDeclaration.js:28:38)
    at /Users/moox/Sync/Development/phenomic/docs/node_modules/stylelint/dist/rules/custom-property-empty-line-before/index.js:30:51
    at /Users/moox/Sync/Development/phenomic/docs/node_modules/postcss/lib/container.js:207:28
    at /Users/moox/Sync/Development/phenomic/docs/node_modules/postcss/lib/container.js:163:26
    at AtRule.each (/Users/moox/Sync/Development/phenomic/docs/node_modules/postcss/lib/container.js:129:22)
    at AtRule.walk (/Users/moox/Sync/Development/phenomic/docs/node_modules/postcss/lib/container.js:162:21)
    at /Users/moox/Sync/Development/phenomic/docs/node_modules/postcss/lib/container.js:165:32
    at Rule.each (/Users/moox/Sync/Development/phenomic/docs/node_modules/postcss/lib/container.js:129:22)
    at Rule.walk (/Users/moox/Sync/Development/phenomic/docs/node_modules/postcss/lib/container.js:162:21)
    at /Users/moox/Sync/Development/phenomic/docs/node_modules/postcss/lib/container.js:165:32
```

To reproduce: 

```
git clone https://github.com/MoOx/phenomic.git
npm i
npm test
```

Maybe it's related to recent change for #1870 ?

**Comment by paulyoung** [comment]
Perhaps it's this line: https://github.com/stylelint/stylelint/pull/1894/files#diff-a70d9fa5a4645b7792581f70b486141bR21

**Comment by EvanLovely** [comment]
Yep, I'm getting it too; this commit, 0d28164, introduced it. I'm getting it on sass mixins that have child selectors such as:

```scss
@mixin smart-grid($row-items: 4, $gutter: $grid-gutter) {
  $column: (100% / $row-items);
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  > * {
    margin-bottom: $gutter;
    @if $row-items > 1 {
      width: calc(#{$column} - (#{$gutter} / 2));
    } @else {
      width: 100%;
    }
  }
}
```
