### ISSUE TITLE
Syntax Error for custom property sets in no-descending-specificity

### ISSUE THREAD

**Issue by woble** [stylelint/stylelint#1999]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

When using [postcss-apply](https://github.com/pascalduez/postcss-apply) in combination with `no-descending-specificity` rule, two things happen.

1. Using `gulp-postcss` errors out.
2. Using `CLI` return unexpected output.

> Which rule, if any, is this issue related to?

`no-descending-specificity`

> What CSS is needed to reproduce this issue?

```css
:root {
    --foo: {
        color: white;
        background-color: black;
    };
}
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
    "rules":
    {
        "no-descending-specificity": true
    }
}
```

> Which version of stylelint are you using?

e.g. `7.4.2`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

1. Using `gulp-stylelint` returns an error and breaks the build process because, presumably, the gulp-stylelint can't handle what stylelint is returning.
```
TypeError in plugin 'gulp-stylelint'
Message:
    Cannot read property 'toUpperCase' of undefined
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

2. Using `cli` (`stylelint foo.pcss --config stylelint.json`) returns just this with above example:
`2:5     Cannot parse selector`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Yes, use of `postcss-apply`.

> What did you expect to happen?

No warnings to be flagged.
