### ISSUE TITLE
Rule `no-descendant-selector`

### ISSUE THREAD

**Issue by threehams** [stylelint/stylelint#2008]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Feature request: new rule to disallow descendant selectors or direct-descendant selectors (configurable), independently from nesting or specificity rules.

The purpose of this is to prevent writing selectors which cross component boundaries, or the unnecessary use of descendant selectors, when isolating styles within a component. This type of selector is extremely difficult to catch manually during code review.

> Which rule, if any, is this issue related to?

Similar to selector-max-specificity and max-nesting-depth. However, the issue here is selector scope rather than specificity, and nesting is strictly a stylistic rule.

> What CSS is needed to reproduce this issue?

Example of breaking component boundaries with descendant selectors (pseudocode for template):

Outer component:
```html
<div class="price-breakdown">
  <ul>
    <li>$4,000</li>
    <li>$1,000</li>
    <li>$800</li>
    <li><tooltip type="list" items="['Tax', 'Shipping']">Other Fees</tooltip></li>
  </ul>
</div>
```

Inner component:
```html
<div class="tooltip">
  { content }
  <ul>
    <for item in items>
      <li class="tooltip-item">{ item }</li> 
    </for>
  </ul>
</div>
```

```css
.price-breakdown ul li {
  margin-bottom: 10px;
}

.tooltip-item {
  margin-bottom: 5px; // this is overwritten from the outside!
}
```

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No.

> What did you expect to happen?

`stylelint: Unexpected descendant selector (no-descendant-selector)`

I'll do the work for this if it's agreed that it's good to add to core. It's not specific to any methodology.

**Comment by evilebottnawi** [comment]
@threehams can you give more examples?

**Comment by davidtheclark** [comment]
Seems like a fine idea to me.

**Comment by threehams** [comment]
Sure, here's a longer example in React. Imagine these are split up into 8 different files (4 JS, 4 CSS):

```jsx
/* @flow */

import React from 'react';

function Avatar({ name, imageUrl }) {
  return (
    <img src={imageUrl} className="avatar-image" alt={name} />
  );
}

function MediaBlock({ children, left }) {
  return (
    <div className="media">
      <div className="media-left">
        { left }
      </div>
      <div className="media-body">
        { children }
      </div>
    </div>
  );
}

function Card({ children, heading, imageName, imageUrl }) {
  return (
    <div className="card">
      <div className="card-heading">
        { heading }
      </div>
      <div className="card-image">
        <img src={imageUrl} alt={imageName} />
      </div>
      <div className="card-body">
        { children }
      </div>
    </div>
  );
}

function App() {
  const name = 'Namey McNameFace';
  const avatar = <Avatar imageUrl="http://placecage.com/400/400" name={name} />;
  const heading = (
    <MediaBlock left={avatar}>
      { name }
    </MediaBlock>
  );
  return (
    <div id="home">
      <Card heading={heading} imageUrl="http://placecage.com/800/400" imageName="cage!">
        Here is some important stuff!
      </Card>
    </div>
  );
}
```

```css
#home .card .card-body {
  padding: 10px;
}

.card {
  border: 1px solid #333;
  width: 100%;
}

.card .card-heading {
  font-size: 14px;
}

.card .card-body {
  padding: 5px;
}

.card img {
  width: 100%;
}

.media {
  display: block;
}

.media-left {
  float: left;
}

.media-body {
  display: table-cell;
}

.avatar-image {
  height: 40px;
  width: 40px;
}
```

This rule is meant to catch three problems that can happen when working with more than a couple developers:

1. The first selector completely ignores component boundaries, and changes padding on the body of a panel on a specific page. Later on, when a new art director shows up, he decides to standardize on 15px of padding for all components, across the board. A 30-minute task turns into a week of searching through 20,000 lines of nested CSS to find and change the thousands of overrides applied to hundreds of components this way.
2. The selectors `.card .card-heading` and `.card .card-body` are already namespaced. The nesting adds nothing and increases the size of the compiled CSS (this is pretty minor, but adds up).
3. The most difficult to catch in review - `.card img` ends up applying a 100% width to the image inside the Avatar component.

This is a small example, but component hierarchies will easily go 50+ levels deep.
