### ISSUE TITLE
False positives with SCSS maps in color-named

### ISSUE THREAD

**Issue by ThePeach** [stylelint/stylelint#2009]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

This is a bug related to `color-named` and happens when a variable name has the same name of a key of a map

The needed SCSS snippet to trigger this is the following:

``` css
@function color($key) {
  @if map-has-key($colors, $key) {
    @return map-get($colors, $key);
  }
  return null;
}

// Color palette
$colors: (
  white: #FFFFFF,
  grey: #333333
);

$color-footer: color(white) !default;
```

> What stylelint configuration is needed to reproduce this issue?

``` json
{
  "rules": {
    "color-named": "never"
  }
}
```

> Which version of stylelint are you using?

`7.5.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

via `gulp-stylelint`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

"Yes, it's related to SCSS maps."

> What did you expect to happen?

"No warnings to be flagged."

> What actually happened (e.g. what warnings or errors you are getting)?

"The following warnings were flagged:"

``` shell
test.css
  10:3   ✖  Unexpected named color "white"    color-named
  11:3   ✖  Unexpected named color "grey"     color-named
  14:22  ✖  Unexpected named color "white"    color-named
```
