### ISSUE TITLE
Rule idea `declaration-property-require-support`

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#2025]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Require use support for property (properties) and value (units). We love flex, but some browser not support their or have not fully support (example UC browser or old Android 4.1, 4.2 not support flex-wrap and flex-shrink). Sometimes we forget about this, be good have rule which reminds us of this. Also be good be able to specify more than one property such as an array (use flex is good, but if you use flex and flex-wrap need require support). 

**If you have any ideas about changing arguments that can be used `not`, `or`, `and` operators welcome to discussion.**

> Which rule, if any, is this issue related to?

`declaration-property-require-support`

> What CSS is needed to reproduce this issue?

`declaration-property-require-support: [{'display': 'flex'}]`

Error:
```css
.foo {
  display: flex;
}
```
No error:
```css
.foo {
  @support (display: flex) {
    display: flex;
  }
}
```

`declaration-property-require-support: [{'display': 'flex', 'flex-wrap': 'wrap'}]`

Error:
```css
  a {
    display: flex; 
  }
```
```css
  a {
    flex-wrap: wrap;
  }
```
No error:
```css
a {
  @support (display: flex) and (flex-wrap: wrap) {
    display: flex;
    flex-wrap: wrap;
  }
}
```

`declaration-property-require-support: [{"display": "flex", "flex-wrap": "wrap"}, {"text-align-last": ".*"}]`
Error:
```css
a {
  text-align-last: justify;
}
```
```css
a {
  text-align-last: start;
}
```
No error:

```css
a {
  @support (text-align-last: justify) {
    text-align-last: justify;
  }
}
```
```css
a {
  @support (text-align-last: start) {
    text-align-last: start;
  }
}
```

> What stylelint configuration is needed to reproduce this issue?

e.g.
Examples:
```json
{
  "rules": {
    "declaration-property-require-support": [{"display": "flex"}]
  }
}
```

```json
{
  "rules": {
    "declaration-property-require-support": [{"display": "'flex", "flex-wrap": "wrap"}]
  }
}
```

```json
{
  "rules": {
    "declaration-property-require-support": [{"display": "'flex", "flex-wrap": "wrap"}, {"text-align-last": ".*"}]
  }
}
```

> Which version of stylelint are you using?

no matter

> How are you running stylelint: CLI, PostCSS plugin, Node API?

no matter

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

no matter

> What did you expect to happen?

no matter

> What actually happened (e.g. what warnings or errors you are getting)?

no matter
