### ISSUE TITLE
Bug - Not validating trailing colon

### ISSUE THREAD

**Issue by pedroivorbgrodrigues** [stylelint/stylelint#2026]
Hello fellow devs,

According to w3c css validator, the snippet below is not valid because of the trailing colon, but the linter gave me no errors. It was a misstype but took me a lot to figure out the css file was the problem not something else. I used the standard configuration on atom linter-stylelint plugin.

```css
.counter: {
  min-width: 100%;
  border: solid 3px red;
}
```

linter-stylelint version: 3.5.0
stylelint: 7.5.0
stylelint-config-standard: ^14.0.0
