### ISSUE TITLE
The `declaration-colon-newline-after` rule has no `never` option.

### ISSUE THREAD

**Issue by jtfairbank** [stylelint/stylelint#2060]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Feature Request: A new option to never have a newline after a declaration's colon.

> Which rule, if any, is this issue related to?

`declaration-colon-newline-after`

> What CSS is needed to reproduce this issue?

With the new option, the following are valid:

```css
.foo {
  border: 3px solid red;
}
```

```css
.foo {
  border: 3px
          solid
          red;
}
```

With the new option, the following are invalid:

```css
.foo {
  border:
    3px solid red;
}
```

```css
.foo {
  border:
    3px
    solid
    red;
}
```

> What stylelint configuration is needed to reproduce this issue?

e.g.

```json
{
  "rules": {
    "indentation": ["tab", {
      "except": ["value"]
    }]
  }
}
```

> Which version of stylelint are you using?

I'm using stylelint via the gulp-stylelint wrapper.  The versions of each are:

  * gulp-stylelint: `3.4.0`
  * stylelint: `7.4.2`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Using Gulp, via gulp-stylelint.

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No.

> What did you expect to happen?

I expected `declaration-colon-newline-after` to disallow newlines immediately after the colon, which could be combined with other value and declaration rules to enforce a particular declaration/value coding style.

> What actually happened (e.g. what warnings or errors you are getting)?

The option doesn't exist just yet. :)
