### ISSUE TITLE
New rules: block-closing-brace-space and -newline

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#21]
I will work on this very soon.

**Comment by davidtheclark** [comment]
If `space` looks like this

```css
body {
  color: pink; }
```

`newline` looks like this

```css
body {
  color: pink;
}
```

But a `newline` convention would also have to do this

```css
@media print {
  body {
    color: pink;
  }
}
```

So the question is: how could we effectively enforce `newline` give that the closing brace might be *nested*?

Are we really looking instead at the space *after the last semicolon*?

**Comment by MoOx** [comment]
> Are we really looking instead at the space after the last semicolon?

I think so. Or maybe just check there is a newline without counting  spaces (which might be done by the `indent` rule).

**Comment by davidtheclark** [comment]
This one is weird when I try to think it through ...

It seems that maybe we should have `block-closing-brace-space-before`? I say that because I don't think any styleguide would say you should have a space *after* the closing brace: really, I'm betting everybody would choose to either enforce nothing or enforce newline after. If we had `block-closing-brace-space-before` it would just take `"always"|"never"` as its options, no object. Does that seem like a reasonable restriction?

**Comment by MoOx** [comment]
What about

```css

body {
  color: pink;
}body {
  color: pink;
}body {
  color: pink;
}
```
-after might make sense :)
