### ISSUE TITLE
block-opening-brace-newline-after complains about comments before newline

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#210]
In my opinion, ideally it would not complain about 

```css
.foo { /* something here */
  color: pink;
}
```
