### ISSUE TITLE
Problem with declaration-empty-line-before

### ISSUE THREAD

**Issue by horosgrisa** [stylelint/stylelint#2154]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

I use postcss-sorting and I have follow css:
```css
.class{
  position: relative;
  z-index: 10;

  list-style: none;

  text-align: center;

  li {
    position: relative;

    display: inline-block;

    margin-right: 10px;
    margin-bottom: 3px;
    padding-left: 23px;

    cursor: pointer;
  }
}
```

This work normal, but when i add at-rule `@each` from postcss-each:
```css
.class{
  @each $val, $i in (#d70206, #f05b4f, #f4c63d) {
    .ct-series-$i::before {
      border-color: $val;
      background-color: $val;
    }
  }
  
  position: relative;
  z-index: 10;

  list-style: none;

  text-align: center;

  li {
    position: relative;

    display: inline-block;

    margin-right: 10px;
    margin-bottom: 3px;
    padding-left: 23px;

    cursor: pointer;
  }
}
```
I obtain error: `Unexpected empty line before declaration` because stylelint don't understant this keyword.

> Which rule, if any, is this issue related to?

`declaration-empty-line-before`

> What stylelint configuration is needed to reproduce this issue?

e.g.

```json
{
  "extends": "stylelint-config-standard",
  "rules": {
    "declaration-empty-line-before":["never",{
      "except": [],
      "ignore": [ "after-declaration"]
      }]
  }
}
```

> Which version of stylelint are you using?

`7.6.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Atom editor linter & gulp-stylelint

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Yes, it's related to postcss-for.

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors you are getting)?

The following warnings were flagged:

```shell
index.css
 9:3  ✖  Unexpected empty line before declaration   declaration-empty-line-before
```

**Comment by jeddy3** [comment]
@horosgrisa Thank you for using the template.

I think the rule is behaving as expected. You've configured `declaration-empty-line-before` to `never` (ignoring `after-declaration`) and you have an empty line before the `position: relative;` declaration on line 9.

If you want to enforce the following code style:

```css
.class{
  @each $val, $i in (#d70206, #f05b4f, #f4c63d) {
    .ct-series-$i::before {
      border-color: $val;
      background-color: $val;
    }
  }
  
  position: relative;
  z-index: 10;

  list-style: none;

  text-align: center;

  li {
    position: relative;

    display: inline-block;

    margin-right: 10px;
    margin-bottom: 3px;
    padding-left: 23px;

    cursor: pointer;
  }
}
```

Then try:

```css
{
  "extends": "stylelint-config-standard",
  "rules": {
    "declaration-empty-line-before":["always", {
      "except": ["first-nested"],
      "ignore": [ "after-declaration"]
      }]
  }
}
```

i.e. There should be an empty line before a declaration. Except, if the declaration _is the first nested_ one then there should not be an empty line. Additionally, if the declaration _comes after_ another declaration then it is ignored.
