### ISSUE TITLE
Add selector-pseudo-element-no-invalid rule

### ISSUE THREAD

**Issue by salzhrani** [stylelint/stylelint#2155]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

a new rule warn about writing a decedent to a pseudo element

> Which rule, if any, is this issue related to?

```css
.foo::after .bar {
  color: pink;
}
```

> Which version of stylelint are you using?

7.6.0

> How are you running stylelint: CLI, PostCSS plugin, Node API?

e.g. "CLI with `stylelint --config myconfig *.css`"

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

it also affects scss

```scss
.foo::after {
  .bar {
    color: pink;
  }
}
```

> What did you expect to happen?

a warning like: Pseudo elements have no descendants

> What actually happened (e.g. what warnings or errors you are getting)?

no errors
