### ISSUE TITLE
block-closing-brace-newline-after complaining about phantom }

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#218]
The code:

```css
.ht-Select-input,
.ht-Select-skin {
  @extend input-base; /* 2, 3 */
  @extend input-skin; /* 2, 3 */
  padding-right: calc(var(--Select-arrow-size) + var(--size-spacing-nano));
}
```

I'm getting complaints from this rule for both extends. It must be treating those as at-rules with blocks or something, then complaining because the comments come after instead of a newline. I'll look into it soon.
