### ISSUE TITLE
proposed rule-nested-empty-line-after

### ISSUE THREAD

**Issue by mmase** [stylelint/stylelint#2187]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

New rule

> Which rule, if any, is this issue related to?

`rule-nested-empty-line-after`

--

Using, `rule-nested-empty-line-before`, you can achieve most of this except for the last nested item:

```scss
.item {
  color: black;
  
  div {
    color: red;
  }
  
  span {
    color: blue;
  }
               // I want to make this line break to be a mandatory never
}
```

which would require this to look like:

```scss
.item {
  color: black;
  
  div {
    color: red;
  }
  
  span {
    color: blue;
  }
}
```

From what I can tell, this isn't possible with current rules so perhaps a `rule-nested-empty-line-after` with option `only: ["last-nested"]` or `except: ["not-last-nested"]`

Thoughts?
