### ISSUE TITLE
False positive for non standard selectors in no-duplicate-selectors

### ISSUE THREAD

**Issue by cookch10** [stylelint/stylelint#2199]
When using stylelint `v7.6.0` as follows: 

package.json (simplified):

``` json
{
  "scripts": {
    "lint:styles": "stylelint --syntax scss \"src/**/*.scss\""
  }
}
```

My .stylelintrc config (uses stylelint-config-standard `v11.0.0`):

``` json
{
  "extends": "stylelint-config-standard",
  "rules": {
    "function-url-quotes": "none",
    "selector-pseudo-element-colon-notation": "single"
  }
}
```

given the following Sass (scss file): [Sassmeister gist](http://www.sassmeister.com/gist/3f1e0e4872439b81ed369b8d972506ff)

``` scss
.widget-container {
  $variation-without-image: #{"&[data-variation^=without_image]"};
  $has-buttons: #{"&[data-has-buttons]"};

  #{$variation-without-image} {
    & {
      #{$has-buttons} {
        .grid.widget__grid {
          border: 1px solid red;
        }
      }
    }

    .grid.widget__grid {
      border: 1px solid orange;
    }
  }
}
```

``` shell
npm run lint:styles
```

The following results in an error:

``` shell
:5  ×  Unexpected duplicate selector ".widget-container #{$variation-without-image}"   no-duplicate-selectors
```

There is no duplicate selector here.  If I change the Sass to the following (which yields the same output):  given the following Sass (scss file), there is no error observed: [Sassmeister gist](http://www.sassmeister.com/gist/ea0e16f3b14eaa86f7f2ba7355c0bbf2)
``` scss
.widget-container {
  $variation-without-image: #{"&[data-variation^=without_image]"};
  $has-buttons: #{"&[data-has-buttons]"};

  #{$variation-without-image} {
    #{"#{$has-buttons}"} {
      .grid.widget__grid {
        border: 1px solid red;
      }
    }

    .grid.widget__grid {
      border: 1px solid orange;
    }
  }
}
```
