### ISSUE TITLE
Add except: ["after-same-name"] option to at-rule-empty-line-before

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint#2211]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

I want to add `except: ["after-same-name"]` option to `at-rule-empty-line-before`.

> Which rule, if any, is this issue related to?

`at-rule-empty-line-before`

> What did you expect to happen?

Be able to separate at-rules with empty line, but have no empty lines between at-rules. It's currently possible only with blockless at-rules. I want to make this option work like:

```json
{
    "rule-nested-empty-line-before": ["always", {
        "except": ["after-rule"]
    }]
}
```

So with this config:

```json
{
    "at-rule-empty-line-before": ["always", {
        "except": ["after-same-name"]
    }]
}
```

The following pattern are considered warnings:

```css
a {
    display: block;
    
    @media (min-width: 100px) {}

    @media (min-width: 200px) {}
    @media (min-width: 300px) {}
}
```

```css
@import "_fonts.css";
@media (min-width: 100px) {}

@media (min-width: 200px) {}
```

The following pattern are not considered warnings:

```css
a {
    display: block;
    
    @media (min-width: 100px) {}
    @media (min-width: 200px) {}
    @media (min-width: 300px) {}
}
```

```css
@import "_fonts.css";

@media (min-width: 100px) {}
@media (min-width: 200px) {}
```

I can add this option if you'll approve it.
