### ISSUE TITLE
rule-empty-line-before ignore after-comment option

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#228]
For `rule-empty-line-before` I would like to ignore rules after comments, so that in my CSS I could have either:

```css
/* comment */

a {
  color: pink;
}
```

Or

```css
/* comment */
a {
  color: pink;
}
```
