### ISSUE TITLE
Add ignore: ["comments"] option to max-empty-lines

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#2356]
Ref: https://github.com/stylelint/stylelint/issues/2343

**Comment by sendilkumarn** [comment]
I will give this one a shot

**Comment by jeddy3** [comment]
> I will give this one a shot

Awesome. 

We should quickly clarify the workings of this option before you start on it. Mainly, are we proposing this option would ignore _all_ comments or just "non"-shared-line comments (FYI, in stylelint we call comments that do not live on a line _by themselves_ "shared-line comments", but I don't think we have a name for comments that do live on a line by themselves). 

Given the following config, what warning do you think should be flagged?

```js
max-line-length: [15, { ignore: ["comments"] }]
```

```css
/* single line non-shared-line comment */

/* 
 * multi-line
 * non-shared-line comment
 */

a {
  color: red; /* shared-line comment that pushes line over 15 */
}
```

Depending on what we decide, we might need to be more specific with the option keyword.
