### ISSUE TITLE
Require top-level rules to be nested within an & { ... }

### ISSUE THREAD

**Issue by JacobDB** [stylelint/stylelint#2484]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Feature request

> Which rule, if any, is this issue related to?

Possibly `selector-nested-pattern`

> What CSS is needed to reproduce this issue?

Invalid:

```css
.foo {
    color: pink;
}
````

Valid:

```css
.foo {
    & {
        color: pink;
    }
}
```

> What stylelint configuration is needed to reproduce this issue?

N/A

> Which version of stylelint are you using?

`7.10.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Node API, with gulp-stylelint

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Yes, it's related to nesting.

> What did you expect to happen?

A warning to be flagged when parsing a top-level rule that has properties that are not nested. Some examples:

Invalid:

```css
.foo {
    color: pink;
}

.foo {
    color: pink;

    &.-valid {
        color: teal;
    }

    .bar {
        color: red;
    }
}
```

Valid:

```css
.foo {
    & {
        color: pink;
    }
}

.foo {
    & {
        color: pink;
    }

    &.-variant {
        color: teal;
    }

    .bar {
        color: red;
    }
}
```

> What actually happened (e.g. what warnings or errors you are getting)?

To my knowledge, no rule exists that can accomplish this.
