### ISSUE TITLE
Only the first element of the array whitelisted in media-feature-name-whitelist/blacklist

### ISSUE THREAD

**Issue by bsrdjan** [stylelint/stylelint#2536]
When array of future names defined for the `media-feature-name-whitelist` rule, only the first feature name of the array is whitelisted and errors reported for others.

CSS to reproduce:

```css
media only screen and (max-width: 1200px) {
  .ui-container {
    max-width: 1200px;
    margin: 0 auto;
  }
}

@media only screen and (min-width: 600px) {
  .ui-container {
    max-width: 600px;
    margin: 0 auto;
  }
}
```

stylelint configuration to reproduce:

```js
module.exports = {
  "extends": "stylelint-config-standard",

  "rules": {
    "media-feature-name-whitelist": [ "max-width", "min-width" ]
  }
};
```

stylelint version: 7.10.1, tested from the command line:

```shell
stylelint test.css

test.css
 8:25  ✖  Unexpected media feature name "min-width"   media-feature-name-whitelist
```
