### ISSUE TITLE
at-rule-empty-line-before "nested" exception and ignore

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#256]
To allow for CSS like this:

```css
a {
  @extend link;
  color: pink;
}
```
