### ISSUE TITLE
Add stylelint-at-rule-no-children to list of plugins

### ISSUE THREAD

**Issue by adityavm** [stylelint/stylelint#2568]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

New rule where block declarations are disallowed inside at rules (mostly conditionals and nested).

---

**Examples**

Valid CSS  
```css
.foo {
  color: red;

  @media screen and (max-width: 480px) {
    color: blue;
  }
}
```

Invalid CSS  
```css
.foo {
  color: red;
}

@media screen and (max-width: 480px) {
  .foo {
    color: blue;
  }
}
```

**Reasoning**

This is to avoid:

1. Whole selectors declared inside conditional at rules.
2. Having multiple unnecessary declarations of the same selector in different parts of the file.

Long story short, this is a way to consolidate all declarations for a selector, so that a anyone looking through a file can be confident that their first hit for a selector is the only declaration they should be concerned with.

(Sidenote: This still allows multiple declarations outside of conditionals, because we want to allow overriding styles when the situation calls for it. We have been using this guideline within my team at work and it's made a lot of the CSS easier to understand between multiple devs.)

**Code**
I have the code + tests ready [adityavm/stylelint-at-rule-no-children][1].

[1]: https://github.com/adityavm/stylelint-at-rule-no-children
