### ISSUE TITLE
`declaration-empty-line-before` `ignore` and `except` issue

### ISSUE THREAD

**Issue by ArmorDarks** [stylelint/stylelint#2758]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug.

For some strange reason, when I specify `except` after `ignore`, rules defined in `except` does not work at all, like they do not exist.

If I specify `ignore` after `except`, for some reason `ignore` rules stops to apply.

Maybe I'm missing something and simply do not understand how exactly should Stylelint `except` and `ignore` rules work.

> Which rule, if any, is this issue related to?

`declaration-empty-line-before`

> What CSS is needed to reproduce this issue?

```css
.test {
  position: relative;

  display: inline-block;

  // comment
  line-height: 1;

  font-family: '#{$ekzo-icon-font}';

  // comment
  font-style:  normal;
  font-weight: normal;

  border:  0;
  height: 0;
  width: 0;
}
```

> What stylelint configuration is needed to reproduce this issue?

```yaml
  declaration-empty-line-before:
    - always
    - ignore:
      - after-comment
      - after-declaration
      - inside-single-line-block
    - except:
      - first-nested
```

or

```yaml
  declaration-empty-line-before:
    - always
    - except:
      - first-nested
    - ignore:
      - after-comment
      - after-declaration
      - inside-single-line-block
```

> Which version of stylelint are you using?

`8.0.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint *.scss``

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Nope

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors you are getting)?

```shell
source/_test.scss
 2:3  ×  Expected empty line before declaration   declaration-empty-line-before
```

![sublime_text_2017-07-17_21-15-04](https://user-images.githubusercontent.com/4460311/28282992-07ceff64-6b35-11e7-9588-b1b5910f0fdc.png)

Or if I place `except` before `ignore`:

```shell
source/_test.scss
  7:3  ×  Expected empty line before declaration   declaration-empty-line-before
 12:3  ×  Expected empty line before declaration   declaration-empty-line-before
 13:3  ×  Expected empty line before declaration   declaration-empty-line-before
 16:3  ×  Expected empty line before declaration   declaration-empty-line-before
 17:3  ×  Expected empty line before declaration   declaration-empty-line-before
```

![sublime_text_2017-07-17_21-14-25](https://user-images.githubusercontent.com/4460311/28282973-f786eeb4-6b34-11e7-8aac-17a7c182e5f4.png)

**Comment by jeddy3** [comment]
@ArmorDarks Thank for your using the template and for the in-depth report.

I think this is simply because your YAML is incorrectly structured.

```json
{
  "rules": {
    "declaration-empty-line-before": [
      "always",
      {
        "except": [
          "first-nested"
        ],
        "ignore": [
          "after-comment",
          "after-declaration",
          "inside-single-line-block"
        ]
      }
    ]
  }
}
```

Is equilvant to:

```yml
---
rules:
  declaration-empty-line-before:
  - always
  - except:
    - first-nested
    ignore:
    - after-comment
    - after-declaration
    - inside-single-line-block
```

Whereas your example is equivalent to the following three value array, which is not what stylelint expects:

```yml
{
  "declaration-empty-line-before": [
    "always",
    {
      "ignore": [
        "after-comment",
        "after-declaration",
        "inside-single-line-block"
      ]
    },
    {
      "except": [
        "first-nested"
      ]
    }
  ]
}
```
