### ISSUE TITLE
Fix parseError in selector-max-id

### ISSUE THREAD

**Issue by jonathantneal** [stylelint/stylelint#2783]
After recently updating Stylelint, I’ve started seeing errors from nested selectors within property sets. The errors look like this:

```
Cannot parse selector   parseError
```

The CSS looks like this:

```css
:root {
	--test-property-set: {
		& any-selector {
			& any-selector {
				color: #00ff00;
			}
		}
	};
}
```

Here is a test case with a test.css and package.json so that you can replicate the issue. Run `npm test` or `npm run test:scss` to see the error (in either syntax):

https://github.com/jonathantneal/postcss-tests/tree/master/stylelint-test-00
