### ISSUE TITLE
False negatives on "property-no-unknown"

### ISSUE THREAD

**Issue by Mottie** [stylelint/stylelint#2811]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Using the [online stylelint demo](https://stylelint.io/demo/), I can enter the following css which does not provide any errors or warnings:

```css
body {
  d: huh;
  r: wha;
  x: test;
  y: whoa;

  /* not valid in SCSS or LESS validators, but ok in stylelint */
  $: ok;
}

```

Also, the property values can be changed to almost anything and remain valid:

```css
body {
  x: "test" this is weird;
  y: #fff;
}
```

> Which rule, if any, is this issue related to?

`property-no-unknown`

> What CSS is needed to reproduce this issue?

See above

> What stylelint configuration is needed to reproduce this issue?

Default provided by the online demo.

> Which version of stylelint are you using?

`8.0.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Online demo.

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Yes, entering the same css into [w3c css validation service](https://jigsaw.w3.org/css-validator/#validate_by_input) or [CSS Lint](http://csslint.net/) shows these as invalid entries.

The above CSS also "appears" valid to [SCSS](https://www.sassmeister.com/) and [LESS](https://lesstester.com/), but only if you remove the `$: ok;` property.

> What did you expect to happen?

To see a "property-no-unknown" error.

> What actually happened (e.g. what warnings or errors you are getting)?

The CSS appears valid.
