### ISSUE TITLE
Add rule to validate color functions

### ISSUE THREAD

**Issue by Mottie** [stylelint/stylelint#2816]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

RGB(A) and HSL(A) color definition warnings are missing.

> Which rule, if any, is this issue related to?

A new rule is required.

> What CSS is needed to reproduce this issue?

```css
a {
  color: rgb(200%, 20%); /* min 3 definition */
  color: rgb(0, 0, 0, 0, 0, 0, 0); /* max 3 definitions */
  color: rgba(0); /* min 4 definitions */
  color: rgba(0, 0, 0, 0, 0, 0, 0); /* max 4 definitions */
  color: rgba(0, 0, 0, 100%); /* alpha channel can not be a percentage */
}

b {
  color: hsl(0); /* min 3 definitions */
  color: hsl(100%); /* hue can not be a percentage (number, deg, rad or turn) */
  color: hsl(0, 0, 0, 0, 0, 0, 0); /* max 3 definitions; */
  color: hsl(0, 50, 50); /* saturation & lightness must be percentages */
  color: hsla(0); /* min 4 definitions */
  color: hsla(0, 0, 0, 0, 0, 0, 0); /* max 4 definitions */
  color: hsla(0, 0%, 0%, 0%); /* alpha channel can not be a percentage */
}
```

> What stylelint configuration is needed to reproduce this issue?

Default configuration used by the [online demo](https://stylelint.io/demo/).

> Which version of stylelint are you using?

`8.0.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Online demo.

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No, this is standard syntax.

> What did you expect to happen?

For RGB(A) colors:
* WARNING/ERROR: There must be 3 rgb and 4 rgba definitions.
* WARNING?: RGB colors can be either an integer or a percentage. Out of bound values do not cause errors.
* WARNING/ERROR: Alpha channel setting can not be a percentage.
* WARNING/ERROR: Don't mix integers and percentages ([ref](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#RGB_example)).

For HSL(A) colors:
* WARNING/ERROR: There must be 3 hsl and 4 hsla definitions.
* WARNING/ERROR: Hue (H) definition must be an integer. Out of bound values do not cause errors.
* WARNING/ERROR: Saturation/Lightness must be percentages. Out of bound values do not cause errors.
* WARNING/ERROR: Alpha channel setting can not be a percentage.

Update:

[According to MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#Examples), you can also use a functional syntax in Firefox v52+ (not yet supported in other browsers):

* Space-separated function parameters rather than commas.
* Percentages for alpha values.
* Angles for the hue component in `hsl()` colors.

```css
/* these are valid definitions (no commas, use slash) */
rgb(255 0 153 / 1)
rgb(255 0 153 / 100%)
hsl(270 60% 50% / .15)
hsl(270 60% 50% / 15%)
/* valid use of deg, rad or turn */
hsl(270deg, 60%, 70%)
hsl(4.71239rad, 60%, 70%)
hsl(.75turn, 60%, 70%)
```

> What actually happened (e.g. what warnings or errors you are getting)?

Everything looks legit - no warnings/errors.
