### ISSUE TITLE
declaration-empty-line-before

### ISSUE THREAD

**Issue by agordeev-zz** [stylelint/stylelint#2841]
8.0.0
`declaration-empty-line-before`

```css
.class {
    display: block;

    &::after { // comment
        content: '';
    }
}
```
```json
"declaration-empty-line-before": [ "always", {
    "except": [
        "after-declaration",
        "first-nested"
    ],
    "ignore": [
        "after-comment"
    ]
}],
```
```shell
Expected empty line before declaration   declaration-empty-line-before
```

The problem appeared in 8.0.0 (was 7.12.0). All errors are equal, there is a comment on the same line with selector.
