### ISSUE TITLE
[Feature Request] add support to autofix space-before or space-after rules

### ISSUE THREAD

**Issue by ctf0** [stylelint/stylelint#2873]
> Which rule, if any, is this issue related to?

- "function-comma-space-after": "always-single-line",
```css
.has-info {
        transform: translate(0,-25%);
    }
```

- "block-opening-brace-space-before": "always",
```css
.help{
    font-size: 16px;
}
```

> Which version of stylelint are you using?

- 8.1.1

> How are you running stylelint: CLI, PostCSS plugin, Node API?

- `stylelint abc.scss --fix`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

missing space auto-added

> What actually happened (e.g. what warnings or errors you are getting)?

```shell
 117:31  ✖  Expected single space after "," in a single-line function   function-comma-space-after
 233:14  ✖  Expected single space before "{"                            block-opening-brace-space-before
```
