### ISSUE TITLE
Autofix not working

### ISSUE THREAD

**Issue by gkatsanos** [stylelint/stylelint#2883]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

The auto fix is not working

> Which rule, if any, is this issue related to?

all rules

> What CSS is needed to reproduce this issue?

any SCSS

> What stylelint configuration is needed to reproduce this issue?
```json
{
  "extends": "stylelint-config-standard",
  "rules": {
    "at-rule-empty-line-before": null
  }
}
```
> Which version of stylelint are you using?

8.1.1

> How are you running stylelint: CLI, PostCSS plugin, Node API?

`stylelint "**/*.scss" --syntax scss --fix`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

SCSS.

> What did you expect to happen?

Autofixing to work
> What actually happened (e.g. what warnings or errors you are getting)?

No Autofixing

**Comment by hudochenkov** [comment]
Autofixing is available for a limited amount of rules. What rules exactly aren't autofixed?

**Comment by gkatsanos** [comment]
Indentation, empty line before @ rules, lowercase hexcodes are three that come to mind, I can post a full log tomorrow morning but 0 things are fixed from a very long list of warnings.

**Comment by jeddy3** [comment]
@gkatsanos Thanks for the report and for using the template.

I'm unable to reproduce this using `8.1.1`.

```console
stylelint "**/*.scss" --syntax scss --fix
```

Given `test.scss` of:

```css
@MEDIA (min-width: 50px) {
 b { 
  color: #FFFFFF;
}
}
```

Changes the contents to:

```css
@media (min-width: 50px) {
  b { 
    color: #fff;
  }
}

```

As @hudochenkov pointed out, only a limited number (9 to be exact) stylistic rules that are currently autofixed; marked by ("Autofixable") in the [list of rules](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md).

If these rules aren't autofixing for you, can you please create a reproducible test repo for us so we can help you get to the bottom of this?

**Comment by gkatsanos** [comment]
Is it possible this has to do with folder permissions? (stylelint is installed as an npm package locally)

**Comment by jeddy3** [comment]
> Is it possible this has to do with folder permissions?

Seems unlikely as it'd likely throw a permissions error when trying to access a folder or write the changes back to the file.

> (stylelint is installed as an npm package locally)

I also ran it with a locally installed package, both as a npm run-script and via `./node_modules/.bin/stylelint`.

What OS are you on?

**Comment by gkatsanos** [comment]
Mac OSX Sierra 10.12.6 .

**Comment by hudochenkov** [comment]
@gkatsanos can you provide a repository with a minimal reproducible case?

**Comment by gkatsanos** [comment]
Will do, I'll have access to that tomorrow morning.

**Comment by gkatsanos** [comment]
This is only one of the files:
```scss
/* COLOR GUIDELINE */

/* alizarin */
$red: #d61f26;
$red-75: #df6147;
$red-50: #e89076;
$red-25: #f2c3b1;
$red-dark: #9B0A0A;
$red-dark-2: #ae1b1f;

$doro-red-mid: #f22821;
$doro-red: #f13c3c; /* This should be the $red, after updating all the color codes */
$doro-red-light: #ff6561;

/* sunglow */
$yellow-strong: #ffaa00; /* cta sunglow hover */
$yellow: #ffc713; /* cta sunglow active */
$yellow-75: #ffd360;
$yellow-50: #ffe094;
$yellow-25: #ffeec7;
$yellow-border: #fcbf0a; /* popups */
$yellow-searchbox: #ffd85a;

/* black bean */
$purple: #45233e;
$purple-75: #654a5e;
$purple-50: #8c7685;
$purple-25: #bcafb7;
$purple-darker: #361830;

/* skyblue */
$blue: #00a6de;
$blue-75: #00b6e4;
$blue-50: #72c9eb;
$blue-25: #bae1f4;

/* midnight blue */
$midnight-blue-dark: #2d333c;
$midnight-blue: #343b46;
$midnight-blue-light: #424b5a;
$basic-text-color: #343b46;
$basic-text-color-75: #585963;
$basic-text-color-50: #83828a;
$basic-text-color-25: #b7b5ba;

/* others */

$green: #00C269;
$green-light: #00d56e; /* cta green hover */
$green-strong: #00b25d;

$orange-strong: #fc5010; /* cta orange hover */
$orange: #f87C1B; /* cta orange active */

$midnight-overlay: rgba(52, 58, 70, .8);
$white-overlay: rgba(245, 245, 246, .8);
$gray-transparency: rgba(52, 58, 70, .85);
$gray-dark: #464b45; /* action icons on address popup */
$gray-stronger: #7F7F7F; /* for text color in readonly or disabled form elements, textfields, selects */
$gray-strong: #9f9fa1; /* cta gray hover */
$gray-mid-strong: #b7b5ba;
$gray: #bbbdc0; /* box colour 1 */
$gray-mid: #d8d8d8; /* box colour 2 --- & --- cta gray active */
$gray-light: #ebebeb; /* box colour 3 */
$gray-lighter: #f5f5f6; /* modest gray 100 */
$offwhite: #f9fafa; /* modest gray 50 */
$pale-off-white: #fbfefb; /*bg on white spinner */
$white: #ffffff;
$spinner-bg: #dedede; /* spinner background */
$dark-transparency: rgba(0, 0, 0, 0.71);

$gray-opaque: rgba(0, 0, 0, 0.2);
$gray-shadow: rgba(131, 130, 138, 0.5);
$lightbox-overlay: rgba(0, 0, 0, 0.8);
$white-transparent: rgba(255, 255, 255, 0.7);
$black-50: rgba(0, 0, 0, 0.5);
$rl-overlay: $white-transparent;

//social buttons
$fb-bg: #38579d;
$fb-bg-light: #4165B7;
$fb-bg-strong: #304A84;

$google-bg: #317cff;
$google-bg-light: #5492ff;
$google-bg-strong: #0265ff;

$foodora-pink: #D70F64;

body {
	background: $gray-lighter;
}
```

Output:
![image](https://user-images.githubusercontent.com/1768834/30364591-30fb7c98-9865-11e7-81bd-71baba803f96.png)

Command:
`stylelint "**/*.scss" --fix`
