### ISSUE TITLE
Add except: ["inside-block"] to rule-empty-line-before

### ISSUE THREAD

**Issue by octoxan** [stylelint/stylelint#2887]
This is a bug where the rule "rule-empty-line-before" doesn't work properly, telling me something needs a new line when it should not.

> Which rule, if any, is this issue related to?

"rule-empty-line-before"

> What CSS is needed to reproduce this issue?

e.g.

```css
.foo-foo {
	font-size: .75em;
}

.foo {
	text-align: center;
	.bar {
		font-style: italic;
	}
}
```

> What stylelint configuration is needed to reproduce this issue?

e.g.

```json
{
  "rules": {
    "rule-empty-line-before": ["always", {
        except: ["inside-block-and-after-rule", "first-nested"]
      }]
  }
}
```

> Which version of stylelint are you using?

8.1.1

> How are you running stylelint: CLI, PostCSS plugin, Node API?

With npm and inside of phpstorm.

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Nesting, scss.

> What did you expect to happen?

No warnings to be flagged. I want a warning on if there's no empty lines before non-nested rules, and if there's any empty lines on nested rules. .bar is nested, and should not throw an error.

> What actually happened (e.g. what warnings or errors you are getting)?

.bar throws an error "Expected empty line before rule", but should fall under either first-nested or inside-block-and-after-rule

**Comment by jeddy3** [comment]
@octoxan Thanks for the report and for using the template.

I believe the rule is behaving correctly here as `.bar` is inside a block, but it is _after a declaration and not a rule_.

The following is an unusual style that I've not seen before:

```css
.foo {
	text-align: center;
	.bar {
		font-style: italic;
	}
}
```

Most requests are for:

```css
.foo {
	text-align: center;

	.bar {
		font-style: italic;
	}
}
```

However, I see no harm in adding an `except: ["inside-block"]` secondary option to the rule to allow this code style. @octoxan Please consider contributing this option if you have time. There's [a section in the Developer Guide](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#adding-an-option-to-an-existing-rule) on how to get started.
