### ISSUE TITLE
length-zero-no-unit doesn't warn in some cases.

### ISSUE THREAD

**Issue by XhmikosR** [stylelint/stylelint#2940]
Recently we switched the Bootstrap repo to stylelint. Things seem good so far :)

Now, one thing I noticed is that even though I have `length-zero-no-unit` set to `true`, we don't get any warning for the following case:

```scss
@mixin make-col-offset($size, $columns: $grid-columns) {
  margin-left: percentage($size / $columns);
}
```

`$size/$columns` can be 0 thus resulting to `margin-left: 0%;`.

I hope this is the right place to report the issue.

Thanks in advance!

EDIT: that's with stylelint 8.1.1.

**Comment by XhmikosR** [comment]
After reading the docs more carefully, I see that **length** refers to distance measurements only. 

Still if I change the mixin to return pixels I still don't get any warning.

```scss
@mixin make-col-offset($size, $columns: $grid-columns) {
  $num: $size / $columns;
  margin-left: if($num == 0, 0, round($num) + px);
}
```
