### ISSUE TITLE
Document using the built-in rules and plugins with non-standard syntax better

### ISSUE THREAD

**Issue by hoschi** [stylelint/stylelint#2952]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug where "at directives" in a SCSS file are not recognized.

> Which rule, if any, is this issue related to?

`at-rule-now-unknown`

> What CSS is needed to reproduce this issue?

```css
@import '~assets/styles-global/gridConfig';
@import '~assets/styles/colors';
$slick-font-path: "slick-carousel/slick/fonts/" !default;

@function slick-font-url($url) {
    @if function-exists(font-url) {
        @return font-url($url);
    }

    @else {
        @return url($slick-font-path + $url);
    }
}

@font-face {
    font-family: "slick";
    src: slick-font-url("slick.eot");
    src: slick-font-url("slick.eot?#iefix") format("embedded-opentype"), slick-font-url("slick.woff") format("woff"), slick-font-url("slick.ttf") format("truetype"), slick-font-url("slick.svg#slick") format("svg");
    font-weight: normal;
    font-style: normal;
}
$slider-opacity-active: 1;
$slider-opacity-inactive: 0.25;
$slider-arrow-circle-diameter: 48px;
$slider-arrow-to-slider-offset: 48px;
$slider-arrow-to-container-offset: 48px;
$slider-arrow-position-offset: $slider-arrow-circle-diameter + $slider-arrow-to-slider-offset;
```

> What stylelint configuration is needed to reproduce this issue?

e.g.

```json
{
    "extends": "stylelint-config-standard",
    "rules": {
        "indentation": 4,
        "property-no-unknown":[true, {
            "ignoreProperties":["composes"]
        }],
        "selector-pseudo-class-no-unknown":[true, {
            "ignorePseudoClasses":["global"]
        }]
    },
    "ignoreFiles": [
        "node_modules/",
        "compiled/"
    ]
}
```

> Which version of stylelint are you using?

`8.1.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

```bash
 stylelint -s scss src/components/slider/slider.scss 
```

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

SCSS

> What did you expect to happen?

No warnings to be flagged.
e.g. @function see here http://sass-lang.com/documentation/file.SASS_REFERENCE.html#Function_Directives__function_directives

> What actually happened (e.g. what warnings or errors you are getting)?

```shell
src/components/slider/slider.scss
  5:1  ✖  Unexpected unknown at-rule "@function"   at-rule-no-unknown
  6:5  ✖  Unexpected unknown at-rule "@if"         at-rule-no-unknown
  7:9  ✖  Unexpected unknown at-rule "@return"     at-rule-no-unknown
 10:5  ✖  Unexpected unknown at-rule "@else"       at-rule-no-unknown
 11:9  ✖  Unexpected unknown at-rule "@return"     at-rule-no-unknown

```
