### ISSUE TITLE
New rule: rule-no-shorthand-property-overrides

### ISSUE THREAD

**Issue by ai** [stylelint/stylelint#302]
Plugin can find accidental overrides:

```css
.module {
    background-repeat: no-repeat;
    background: url(lion.jpg);
    /* Oops! This will repeat. */
}
```

https://github.com/postcss/postcss/issues/224
