### ISSUE TITLE
unit "x" (image-set)

### ISSUE THREAD

**Issue by strarsis** [stylelint/stylelint#3026]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A new unit to be added to defaults.

> Which rule, if any, is this issue related to?

`unit-no-unknown`

> What CSS is needed to reproduce this issue?

e.g.

```css
.foo {
  background-image:
    image-set(
      url(../images/background-blended.jpg?size=400&quality=10) 1x,
      url(../images/background-blended.jpg?size=800&quality=10) 2x,
      url(../images/background-blended.jpg?size=1200&quality=10) 3x
    );
  background-position: top center;
  background-repeat: no-repeat;
}
```

> What stylelint configuration is needed to reproduce this issue?

e.g.

```json
{
  "extends": "stylelint-config-standard",
    "rules": {
      "no-empty-source": null
    }
}
```

> Which version of stylelint are you using?

e.g. `7.12.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

webpack loader

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Unsure.

> What did you expect to happen?

No errors to be flagged.

> What actually happened (e.g. what warnings or errors you are getting)?

Lint error:
````
Unexpected unknown unit "x"   unit-no-unknown
Unexpected unknown unit "x"   unit-no-unknown
Unexpected unknown unit "x"   unit-no-unknown
````

```shell
test.css
 4:65  ✖  Unexpected unknown unit "x"   unit-no-unknown
 5:65  ✖  Unexpected unknown unit "x"   unit-no-unknown
 6:66  ✖  Unexpected unknown unit "x"   unit-no-unknown
```

I want to use the `image-set` syntax (PostCSS polyfill https://github.com/SuperOl3g/postcss-image-set-polyfill).
In case this is deemed to be not standard enough for being added to default config, what would be the best practice for adding this unit as correct to my stylelint configuration?
