### ISSUE TITLE
Document `!important` caveat in `no-descending-specificity`

### ISSUE THREAD

**Issue by pke** [stylelint/stylelint#3052]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug where the rule claims wrong ordering.

> Which rule, if any, is this issue related to?

`no-descending-specificity`

> What CSS is needed to reproduce this issue?

```css
a,
a:hover,
a:active {
  color: #6c9cd3;
}

footer a {
  color: white !important; /* override all links */
}
```

> What stylelint configuration is needed to reproduce this issue?

"stylelint": "^8.3.1",
"stylelint-config-standard": "^18.0.0",

> Which version of stylelint are you using?

`8.3.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

npm with `stylelint "src/**/*.css"`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

no

> What did you expect to happen?

No warnings to be flagged

> What actually happened (e.g. what warnings or errors you are getting)?

The following warnings were flagged:

```shell
 72:1  ×  Expected selector "footer a" to come before selector "a:hover"          no-descending-specificity
 72:1  ×  Expected selector "footer a" to come before selector "a:active"         no-descending-specificity
 78:1  ×  Expected selector "a:focus" to come before selector "footer a:hover"    no-descending-specificity
 78:1  ×  Expected selector "a:focus" to come before selector "footer a:active"   no-descending-specificity
```

**Comment by hudochenkov** [comment]
Thanks for the report and for using the template.

Rule checks selectors only. It doesn't check declarations in a rule, and whether rule with lower selector specificity has declaration which is outweights declaration in a rule with higher selector specificity.

`a:hover` has specificity `0,0,1,1`. `footer` has specificity `0,0,0,2`. Rule works as expected.

On the other side it's still show violations if there is a clearly a set of more specific selectors:

```css
a,
a:hover,
a:active {
  color: #6c9cd3;
}

footer a,
footer a:hover,
footer a:active {
  color: white;
}
```

```
 7:1  ✖  Expected selector "footer a" to come before selector "a:hover"    no-descending-specificity
 7:1  ✖  Expected selector "footer a" to come before selector "a:active"   no-descending-specificity
```

While rule is still works as expected and reports correctly, it feels incorrect.

You can disable violation for this use case:

```css
a,
a:hover,
a:active {
    color: #6c9cd3;
}

/* stylelint-disable-next-line no-descending-specificity */
footer a {
    color: white;
}
```
