### ISSUE TITLE
hierarchicalSelectors option 

### ISSUE THREAD

**Issue by magsout** [stylelint/stylelint#309]
I just add `hierarchicalSelectors`option in https://github.com/stylelint/stylelint-config-cssrecipes

With this code it's work:

```css
.r-Grid {
  color: red;
}

  .r-Grid-cell {
    text-align: center;
  }
```

But not with this one:

```css
:root {
  --Grid: #fff;
}

.r-Grid {
  color: red;
}

  .r-Grid-cell {
    text-align: center;
  }
```

I have that error:

```
6:3     ⚠  Expected indentation of 4 spaces at line 6 (indentation) [stylelint]
```

Line 6 is ` color: red;` If I add 4 spaces before its value, there is no more error.
