### ISSUE TITLE
False negatives nested at-if in selector-max-id

### ISSUE THREAD

**Issue by BenjaminWFox** [stylelint/stylelint#3105]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug where "selector-max-id" is not applied if the selector is followed by an SCSS @if statement.

> Which rule, if any, is this issue related to?

"selector-max-id"

> What CSS is needed to reproduce this issue? (SCSS)

e.g.

```css
$p: 4;

Not a violation:
#temp #two {
  @if ($p == 4) {
    font-size: 4em;
  }
  
  color: #000;
}

A violation:
#temp #two {  
  color: #000;
}

```

> What stylelint configuration is needed to reproduce this issue?

e.g.

```json
{
  "rules": {
    "selector-max-id": 1
  }
}
```

> Which version of stylelint are you using?

8.4.0

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Sublimetext 3 with SublimeLinter-contrib-stylelint
AND
Webpack with stylelint-webpack-plugin

(issue shows up with both)

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Yes, it's related to SCSS @if

> What did you expect to happen?

selector-max-id should be applied regardless of what follows in the block

> What actually happened (e.g. what warnings or errors you are getting)?

selector-max-id was not applied when the block started with @if
