### ISSUE TITLE
Webkit Pseudo Class display warning no-unknown

### ISSUE THREAD

**Issue by aviram83** [stylelint/stylelint#3151]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

this is a bug with webkit Pseudo Class

> Which rule, if any, is this issue related to?

selector-pseudo-class-no-unknown

> What CSS is needed to reproduce this issue?

e.g.

```less
      .viewport {
        &::-webkit-scrollbar {
          width: 15px;
          height: 15px;
          background-color: transparent;
        }

        &::-webkit-scrollbar-thumb {
          border-radius: 10px;
          border: 4px solid #fff;
          background-color: #c2c2c2;
          height: 60px;
        }

        &::-webkit-scrollbar-track {
          background-color: #fff;
        }

        &::-webkit-scrollbar-thumb:vertical {
          border: 4px solid rgba(0, 255, 255, 0);
          background-clip: content-box;
        }
```

> What stylelint configuration is needed to reproduce this issue?

e.g.

```json
{
  "extends": "stylelint-config-recommended",
}
```

> Which version of stylelint are you using?

`8.4.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

"npx stylelint "src/**/*.less""

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

"Yes, using ampersand in LESS"

> What did you expect to happen?

"No warnings to be flagged."

> What actually happened (e.g. what warnings or errors you are getting)?

e.g. "The following warnings were flagged:"

```shell
test.less
Unexpected unknown pseudo-class selector ":vertical"   selector-pseudo-class-no-unknown
```
