### ISSUE TITLE
Mangled Styled Components

### ISSUE THREAD

**Issue by AriLFrankel** [stylelint/stylelint#3189]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug where files containing styled components are mangled by the stylelint --fix 

> Which rule, if any, is this issue related to?

N/A

> What CSS is needed to reproduce this issue?

This is an example styled component that is destroyed
```js
\

export const div = styled.div`
  border: none;
  background-color: rgba(0, 0, 0, .12);
  height: 1px;
  margin-top: 0px;
  margin-bottom: 0px;
  margin-right: 0px;
  margin-left: ${props => props.marginLeft};
`;
```

> What stylelint configuration is needed to reproduce this issue?
This is taken from https://www.styled-components.com/docs/tooling#stylelint
```json
{
  "processors": ["stylelint-processor-styled-components"],
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-styled-components"
  ],
  "syntax": "scss"
}
```

> Which version of stylelint are you using?

`^9.1.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint <PATH/TO/FILE> --fix`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

To lint the CSS with no other changes to the file

> What actually happened (e.g. what warnings or errors you are getting)?

The code is replaced with 
```css
.selector1 {
  border: none;
  background-color: rgba(0, 0, 0, 0.12);
  height: 1px;
  margin-top: 0;
  margin-bottom: 0;
  margin-right: 0;
  margin-left: $dummyValue;
}
```

```shell
test.css
1:21    Expected 2 spaces (indentation)
```
