### ISSUE TITLE
[SCSS] Unexpected unknown at-rule "@extend"

### ISSUE THREAD

**Issue by Rouberg** [stylelint/stylelint#3190]
I seem meet a question when use scss with stylelint, is there anything wrong with my config?

## .stylelintrc.yml
```YAML
processors:
  - stylelint-processor-html
extends: stylelint-config-standard
syntax: scss
plugins:
  - stylelint-scss
rules:
  no-empty-source: ~
  block-no-empty: ~
  color-no-invalid-hex: true
  comment-empty-line-before:
    - always
    - ignore:
      - stylelint-commands
      - after-comment
  indentation:
    - 2
    - except:
      - value
  max-empty-lines: 1
  unit-whitelist: [ px, '%', em ]
#  at-rule-no-unknown:
#    - true
#    - {ignoreAtRules: ['extend']}
```

### src/styles/flex.scss
```SCSS
%flex-left-center {
  display: flex;
  justify-content: flex-start;
  align-items: center;
}

%flex-center {
  display: flex;
  justify-content: center;
  align-items: center;
}
```
### src/style/var.scss
```SCSS
$breath: 15px;
$color-primary: #00b0ff;
$color-title: #646464;
$font-title: 15px;
$height-title: 40px;
$bg-title: #f7f7f7;
```
## src/components/namespace-title.vue
now, in my *.vue file, my style tag's content like this:
```SCSS
  @import '../styles/flex';
  @import '../styles/var';
  $line-height: $font-title * 1.2;

  .title {
    margin: 0;
    font-weight: normal;
    line-height: $line-height;
    height: $height-title;
    color: $color-title;
    font-size: $font-title;
    padding: (($height-title - $line-height) / 2) $breath;
    background-color: $bg-title;
    box-sizing: border-box;
    @extend %flex-left-center;

    &::before {
      content: ' ';
      display: inline-block;
      width: $line-height * 0.2;
      height: $line-height * 0.9;
      background-color: $color-primary;
      margin-right: ( $line-height / 2 );
    }
  }
```
## webpack config (part)
```javascript
const StyleLintPlugin = require('stylelint-webpack-plugin')
module.exports = {
  plugins:[
    new StyleLintPlugin({
      files: ['**/*.vue', '**/*.scss', '**/*.css'],
      syntax: 'scss'
    })
  ]
}
```
then, webpack will throw error link this:
```log
**ERROR** in  src/components/namespace-title.vue
 16:3  ✖  Expected empty line before at-rule     at-rule-empty-line-before
 16:3  ✖  Unexpected unknown at-rule "@extend"   at-rule-no-unknown
```
Uh~ my Node version is 8.9.4 and my NPM version is 5.6.0,
my devDependencies ls:

+  "autoprefixer": "^7.2.6",
+   "babel-core": "^6.26.0",
+    "babel-loader": "^7.1.2",
+    "babel-plugin-syntax-dynamic-import": "^6.18.0",
+    "css-loader": "^0.28.9",
+    "eslint": "^4.15.0",
+    "eslint-config-standard": "10.2.1",
+    "eslint-friendly-formatter": "^3.0.0",
+    "eslint-loader": "^1.9.0",
+    "eslint-plugin-html": "^4.0.2",
+    "eslint-plugin-import": "^2.8.0",
+    "eslint-plugin-node": "^5.2.1",
+    "eslint-plugin-promise": "^3.6.0",
+  "eslint-plugin-standard": "^3.0.1",
+  "eslint-plugin-vue": "^4.2.2",
+  "extract-text-webpack-plugin": "^3.0.2",
+  "file-loader": "^1.1.6",
+  "html-webpack-plugin": "^2.30.1",
+  "json-loader": "^0.5.7",
+  "node-sass": "^4.7.2",
+  "optimize-css-assets-webpack-plugin": "^3.2.0",
+  "postcss-loader": "^2.1.0",
+  "postcss-pxtorem": "^4.0.1",
+  "pug": "^2.0.0-rc.4",
+  "pug-loader": "^2.3.0",
+  "sass-loader": "^6.0.6",
+  "style-loader": "^0.20.1",
+  "stylefmt": "^6.0.0",
+  "stylelint": "^8.0.0",
+  "stylelint-config-standard": "^18.1.0",
+  "stylelint-processor-html": "^1.0.0",
+  "stylelint-scss": "^2.4.0",
+  "stylelint-webpack-plugin": "^0.10.3",
+  "uglifyjs-webpack-plugin": "^1.1.8",
+  "url-loader": "^0.6.2",
+  "vue-html-loader": "^1.2.4",
+  "vue-loader": "^13.7.0",
+  "vue-style-loader": "^3.1.0",
+  "vue-template-compiler": "^2.5.13",
+  "webpack": "^3.10.0",
+  "webpack-dev-server": "^2.11.1",
+  "webpack-merge": "^4.1.1",
+  "yaml-loader": "^0.5.0"

I think it's a common question but why I didn't query some related in issue list and I'm comfused about this. I can upgrade stylelint config file's rule `at-rule-no-unknown` to avoid this error simple but I think I should not do like this.
