### ISSUE TITLE
Add ignore: ["selectors-within-list"] to no-descending-specificity

### ISSUE THREAD

**Issue by sindresorhus** [stylelint/stylelint#3196]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

> Which rule, if any, is this issue related to?

`no-descending-specificity`

> What CSS is needed to reproduce this issue?

```css
a {
	color: #000;
}

a:hover {
	text-decoration: underline;
}

h1,
h2,
h3,
h4,
h5,
h6,
a,
button {
	user-select: none;
	cursor: default;
}
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "no-descending-specificity": true
  }
}
```

> Which version of stylelint are you using?

9.1.1

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

I expected it to not trigger the `no-descending-specificity` rule as it's common to write CSS like this.

> What actually happened (e.g. what warnings or errors you are getting)?

It triggered the rule on the `a,`. It would be unnatural to move the `a:hover` below the `...h5, h6, a,...`.

I don't think it should trigger when the selector is part of multiple selectors. Or there should at least be an option to achieve this.
