### ISSUE TITLE
Add rule to enforce custom properties be specified at the top of the scope

### ISSUE THREAD

**Issue by sindresorhus** [stylelint/stylelint#3198]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

I would like to enforce that custom properties be specified at the top of the current scope, for readability reasons.

Fail:

```css
.foo {
  color: pink;
  --margin: 10px;
  margin: var(--margin);
}
```

Pass:

```css
.foo {
  --margin: 10px;
  color: pink;
  margin: var(--margin);
}
```

I would also like an option to require a newline after the group of custom properties:

```css
.foo {
  --margin: 10px;
  --color: pink;

  color: var(--color);
  margin: var(--margin);
}
```
