### ISSUE TITLE
selector-type-whitelist/blacklist rule

### ISSUE THREAD

**Issue by kristerkari** [stylelint/stylelint#3224]
I don't know if this is possible already, but I would like to whitelist or blacklist certain types of selectors.

e.g.

```js
"selector-type-whitelist": ["class"]
```
valid:
```css
.foo {
  line-height: 1;
}

.foo, .bar {
  line-height: 1;
}
```

invalid: 
```css
#foo {
  line-height: 1;
}

a {
  line-height: 1;
}

input[type=text] {
  line-height: 1;
}
```
