### ISSUE TITLE
`stylelint-disable-line` not working

### ISSUE THREAD

**Issue by thiagommedeiros** [stylelint/stylelint#3227]
I have some variables that are inserted in the `head` by a JS function, so these variables don't exist for the stylelint and it throws the following error: `variable '--primary-color' is undefined and used without a fallback`.

I'm trying to disable the stylelint:

``` css
.optionBox.selected {
  border: 2px solid var(--primary-color); /* stylelint-disable-line */
}
```

But it not works!

Does anyone have a suggestion to fix it? 

Thanks!
