### ISSUE TITLE
stylelint doesn't validate SCSS-specific at-rules

### ISSUE THREAD

**Issue by beastdestroyer** [stylelint/stylelint#3293]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?
This is a bug where stylelint detects the valid SCSS at-rules such as '@mixin' and '@include' as unknown and unexpected. (I tested all and all give errors)

> Which rule, if any, is this issue related to?
The rule that pops up is 'Unexpected unknown at-rule'

> What CSS is needed to reproduce this issue?
creating a random SCSS mixin, this was the one currently on my screen:
```scss
@mixin transition($name, $time, $function) {
  transition: $name $time $function;
  -moz-transition: $name $time $function;
  -ms-transition: $name $time $function;
  -o-transition: $name $time $function;
  -webkit-transition: $name $time $function;
}
```
Again, it also gave errors with other SCSS at-rules

> What stylelint configuration is needed to reproduce this issue?
I installed the extension through VSCode marketplace, then ran in a command-line: 'npm install -g stylelint-config-recommended', therefore meaining I used the "recommended" config.

> Which version of stylelint are you using?
From installing through VSCode and installing via npm, it seems my version is '9.0.0'

> How are you running stylelint: CLI, PostCSS plugin, Node API?
VSCode extension

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?
Yes, it's related to SCSS at-rules

> What did you expect to happen?
I expected no warnings to be flagged since '@mixin' is valid SCSS, as well as @if, @extends etc..

> What actually happened (e.g. what warnings or errors you are getting)?
The warning flagged: 'Unexpected unknown at-rule'

```shell
test.css
Unexpected unknown at-rule "@mixin" (at-rule-no-unknown)
```
