### ISSUE TITLE
Add `declaration-block-no-redundant-longhand-properties` autofix

### ISSUE THREAD

**Issue by imvetri** [stylelint/stylelint#3304]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

`stylelint --fix` should convert redundant longhand properties to shorthand
> Which rule, if any, is this issue related to?

`declaration-block-no-redundant-longhand-properties`

> What CSS is needed to reproduce this issue?

Following will throw error

```css
  a {
    padding-top: 1px;
    padding-right: 2px;
    padding-bottom: 3px;
    padding-left: 4px; 
}
```

> What stylelint configuration is needed to reproduce this issue?

e.g.

```json
{
  "rules": {
    "declaration-block-no-redundant-longhand-properties": [true, {
        "severity": "warning"
    }],
  }
}
```

> Which version of stylelint are you using?

e.g. `9.2.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

This should work despite the method chose to run stylelint

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

```css
  a {
    padding-top: 1px;
    padding-right: 2px;
    padding-bottom: 3px;
    padding-left: 4px; 
}
```
should convert above to following

```css
a {
  padding: 1px 2px 3px 4px;
}
```

> What actually happened (e.g. what warnings or errors you are getting)?

No fix currently available

Further notes: Currently this is being discussed in https://github.com/stylelint/stylelint/issues/3068. But that has lot of other rules, so creating a separate one for this rule in case I could write a fix.
