### ISSUE TITLE
How can I allow `-webkit-appearance`

### ISSUE THREAD

**Issue by hbrls** [stylelint/stylelint#331]
I'd like it to apply to webkit only. And `autoprefixer` does not prefix it as expected.

But the rule warns about `property-no-vendor-prefix`. `property-whitelist` does not help.

I cannot think of a way other than disable the line.

**Comment by TrySound** [comment]
@hbrls But autoprefixer support appearance.

**Comment by TrySound** [comment]
https://github.com/postcss/autoprefixer-core/blob/master/data/prefixes.coffee#L338-L341

**Comment by jeddy3** [comment]
@hbrls As TrySound mentions, `autoprefixer` now supports `appearance`. Try updating your autoprefixer version first.

I'll try to address your other comments too... :)

> But the rule warns about property-no-vendor-prefix. property-whitelist does not help.

That's right. Each rule is independent of each other. `property-whitelist` is for creating a subset of allowed properties that you want to use in your project.

> I cannot think of a way other than disable the line.

Yeap, I think that's the right approach for situations like this:

```css
/* stylelint-disable property-no-vendor-prefix */
.rule-with-appearance-in {
  -webkit-appearance: normal;
  ...
}
/* stylelint-enable property-no-vendor-prefix */

.more-rules {
  ..
}
```

We could add an option to the `property-no-vendor-prefix` rule that would allow a user to exclude certain properties, but that's probably overkill for these kind of edge-cases which can be handled by disabling the rule inline.
