### ISSUE TITLE
"font-family-no-duplicate-names" - broken

### ISSUE THREAD

**Issue by dvlden** [stylelint/stylelint#3368]
**Describe the bug? (A clear and concise description of what the bug is)**

Rule: `font-family-no-duplicate-names` is not working as described when set to `true` for scss syntax.

**Which rule, if any, is this issue related to?**

`font-family-no-duplicate-names`

**What CSS is needed to reproduce this issue?**

> This example is working... 

```css
.foo {
  font-family: "Helvetica", Helvetica, sans-serif;
}
```

> This example is not working...

```scss
.foo {
  font: {
     family: "Helvetica", Helvetica, sans-serif;
  }
}
```

**What stylelint configuration is needed to reproduce this issue?**

```json
{
  "rules": {
    "font-family-no-duplicate-names": true
  }
}
```

**Which version of stylelint are you using?**

`9.2.1`

**How are you running stylelint: CLI, PostCSS plugin, Node API?**

CLI with `stylelint --sytnax=scss \"src/**/**.scss\"`

**Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?**

Yes, it's related to Scss.

**What did you expect to happen?**

To get an error, such as: `✖  Unexpected duplicate name Helvetica`

**What actually happened (e.g. what warnings or errors you are getting)?**

Nothing, it passes the linting.
