### ISSUE TITLE
Autofix does not take // stylelint-disable for length-zero-no-unit

### ISSUE THREAD

**Issue by trollepierre** [stylelint/stylelint#3393]
> Clearly describe the bug

When I stylelint this code, there is no problem.

When I stylelint --fix this code, the line is changed in      " flex: 0 0 0; "

```css
&.without-qualification {
      // Disabled lint rule for IE 11 style hack
      // stylelint-disable length-zero-no-unit
      flex: 0 0 0px;
    }
```

> Which rule, if any, is the bug related to?

Maybe only this one: e.g. ` length-zero-no-unit`

> What CSS is needed to reproduce the bug?

> What stylelint configuration is needed to reproduce the bug?
None

> Which version of stylelint are you using?

 9.2.1

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint src/**/*.vue src/**/*.css src/**/*.scss`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No

> What did you expect to happen?

No autofix

> What actually happened (e.g. what warnings or errors did you get)?

It autofixed the disabled line
