### ISSUE TITLE
Nested css default element and different class throwing error for no-descending-sepcificity

### ISSUE THREAD

**Issue by sethstha** [stylelint/stylelint#3399]
> Clearly describe the bug

When given style to default CSS elements like `ul li a` along with the different CSS class like `.tagcloud a` throws error of alignment. When I place the second one on top. It throws error saying same for the second.

> Which rule, if any, is the bug related to?

`no-descending-specificity`

> What SCSS is needed to reproduce the bug?

```SCSS
ul {
    
    li {
        
        a {
            color: $color-white;
            
            &:hover {
                color: $color-primary;
            }
        }
    }
}

.tagcloud {
    
    a {
        border-color: $color-white;
        
        &:hover {
            border-color: $color-primary;
        }
    }
    
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "extends": [
    "stylelint-config-wordpress/scss"
  ],

  "rules": {
    "no-eol-whitespace": [ true, {
      "ignore": ["empty-lines"]
    } ],
    "font-family-no-missing-generic-family-keyword": null,
    "value-no-vendor-prefix": true
  }
}
```

> Which version of stylelint are you using?

`9.3.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint _footer.scss`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to SCSS nested properties.

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors did you get)?

```shell
_footer.scss
17:2  ✖  Expected selector ".tagcloud a" to come before selector "ul li a:hover"   no-descending-specificity
```
