### ISSUE TITLE
Fix false positives for system-ui font-family-name-quotes

### ISSUE THREAD

**Issue by ScottSmith95** [stylelint/stylelint#3454]
> Clearly describe the bug

`system-ui` is a [standard](https://caniuse.com/#feat=font-family-system-ui) font keyword that should be exempted from the `font-family-name-quotes` rule.

> Which rule, if any, is the bug related to?

`font-family-name-quotes`

> What CSS is needed to reproduce the bug?

```css
body {
font-family: system-ui, -apple-system, 'Segoe UI', 'Roboto', 'Oxygen-Sans', 'Ubuntu', 'Cantarell', 'Helvetica Neue', sans-serif; }
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
	"rules": {
		"font-family-name-quotes": "always-unless-keyword",
	}
}
```

> Which version of stylelint are you using?

`9.3.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

`$ stylelint 'styles/build/*.css'`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No. See: https://drafts.csswg.org/css-fonts-4/#system-ui-def

> What did you expect to happen?

`system-ui` should be treated as other system font keywords as referenced in #1295.

> What actually happened (e.g. what warnings or errors did you get)?

e.g. "The following warnings were flagged:"

```shell
Expected quotes around "system-ui"   font-family-name-quotes
```
