### ISSUE TITLE
Stylelint ignore directives are not honoured when using --fix

### ISSUE THREAD

**Issue by BPScott** [stylelint/stylelint#3459]
Given a file with `/* stylelint-disable */` blocks. Ignored errors are honoured when running `stylelint`, but they are not when running `stylelint --fix`. **This leads to --fix modifying content within disabled blocks that should not be modified**.

> Which rule, if any, is the bug related to?

All rules seem to be affected, though the following test uses `color-hex-case`, `number-no-trailing-zeros` and `selector-pseudo-element-colon-notation` as examples of autofixable rules.

> What CSS is needed to reproduce the bug?

```css
.invalid-hex {
    color: #ACBEEF;
}

/* stylelint-disable  */
.invalid-hex-ignored {
    color: #ACBEEF;
}
/* stylelint-enable  */

.invalid-pseudo-colon:before {
    display: block;
}

/* stylelint-disable */
.invalid-pseudo-colon-ignored:before {
    display: block;
}
/* stylelint-enable */

.invalid-trailing-zero {
    margin: 1.000em;
}

/* stylelint-disable */
.invalid-trailing-zero-ignored {
    margin: 1.000em;
}
/* stylelint-enable */
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
   "rules": {
        "color-hex-case": "lower",
        "number-no-trailing-zeros": true,
        "selector-pseudo-element-colon-notation": "double"
   } 
}
```

> Which version of stylelint are you using?

`9.3.0`, ran using npx

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI. In a new folder, save the above css as `test.css` and the above config as `.stylelintrc`. Then run `npx stylelint 'test.css'`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

I first found this bug when testing SCSS files, but it also affects the CSS syntax

> What did you expect to happen?

Running `npx stylelint 'test.css'` correctly identifies issues on lines 2, 11 and 22. It ignores the issues within `stylelint-disable` directives:

```shell
test.css
  2:12  ✖  Expected "#ACBEEF" to be      color-hex-case
           "#acbeef"
 11:22  ✖  Expected double colon         selector-pseudo-element-colon-notation
           pseudo-element notation
 22:15  ✖  Unexpected trailing zero(s)   number-no-trailing-zeros
```

Running `npx stylelint 'test.css' --fix` autofixes the issues on lines 2, 11 and 22. The contents within `stylelint-disable` directives are untouched:

```css
.invalid-hex {
    color: #acbeef;
}

/* stylelint-disable  */
.invalid-hex-ignored {
    color: #ACBEEF;
}
/* stylelint-enable  */

.invalid-pseudo-colon::before {
    display: block;
}

/* stylelint-disable */
.invalid-pseudo-colon-ignored:before {
    display: block;
}
/* stylelint-enable */

.invalid-trailing-zero {
    margin: 1em;
}

/* stylelint-disable */
.invalid-trailing-zero-ignored {
    margin: 1.000em;
}
/* stylelint-enable */
```

> What actually happened (e.g. what warnings or errors did you get)?

Running `npx stylelint 'test.css'` works as expected.

Running `npx stylelint 'test.css' --fix` autofixes the issues on lines 2, 11 and 22. It also erroneously modifies the code blocks within `stylelint-disable` directives (lowercasing the color, adding an extra colon to the pseudo class and removing trailing zero):

```css
.invalid-hex {
    color: #acbeef;
}

/* stylelint-disable  */
.invalid-hex-ignored {
    color: #acbeef;
}
/* stylelint-enable  */

.invalid-pseudo-colon::before {
    display: block;
}

/* stylelint-disable */
.invalid-pseudo-colon-ignored::before {
    display: block;
}
/* stylelint-enable */

.invalid-trailing-zero {
    margin: 1em;
}

/* stylelint-disable */
.invalid-trailing-zero-ignored {
    margin: 1em;
}
/* stylelint-enable */
```
