### ISSUE TITLE
Fix violation position after mixin

### ISSUE THREAD

**Issue by MLefebvreICO** [stylelint/stylelint#3509]
> Clearly describe the bug

Error positioning is wrong when a mixin is used before the error scope, putting the rule's error on the wrong line (seems to depends on the size of the mixing function line numbers)

> Which rule, if any, is the bug related to?

All.

> What CSS is needed to reproduce the bug?

A mixing `is-mobile` : 
```less
.is-mobile(@rules) {
    @media screen and (max-width: 1200px) {
        @rules();
    }
}
``` 
The following code : 

```css
.something {
    color: black;

    .is-mobile({
        color: red;
        background-color: black;
    })
}

.foo {
    height: 20px;
    width: 40px;
      background-color: pink;
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "indentation": 4
  }
}
```

> Which version of stylelint are you using?

`9.4.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

* CLI with `stylelint stylesheets/** --config ../../.stylelintrc`
* VSCode plugin

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes it is related to LESS mixins.

> What did you expect to happen?

```shell
someFile.less
13:7   ✖  Expected indentation of 4 spaces (indentation)
```

> What actually happened (e.g. what warnings or errors did you get)?

```shell
someFile.less
10:7   ✖  Expected indentation of 4 spaces (indentation)
```
