### ISSUE TITLE
[Indentation] not handled correctly when property is prefixed by *

### ISSUE THREAD

**Issue by onigoetz** [stylelint/stylelint#358]
Hi,

it seems the indentation doesn't check correctly when I use `*` hacks with the property name

```
rules: {
    "indentation": [2, 4],
}	
```

```css
.Button {
    position: relative;

    display: inline-block;
    *display: inline;
    zoom: 1;

    *border: 0;
    border-width: 4px;
    border-style: solid;
    border-radius: 4px;
}
```

```
input.css
5:5	⚠  Expected indentation of 4 spaces at line 5 (indentation) [stylelint]
8:5	⚠  Expected indentation of 4 spaces at line 8 (indentation) [stylelint]
```
