### ISSUE TITLE
Fix false positives for functional pseudo classes in no-descending-specificity

### ISSUE THREAD

**Issue by Hypnosphi** [stylelint/stylelint#3604]
> Clearly describe the bug

There are false positives for `no-descending-specificity` when using CSS Modules

> Which rule, if any, is the bug related to?

`no-descending-specificity`

> What CSS is needed to reproduce the bug?

```css
:global(.buildResultsSummaryTable) span {
  color: #444;
}
 
:global(.buildResultsSummaryTable) span:nth-child(2) {
  color: #666;
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "no-descending-specificity": true
  }
}
```

> Which version of stylelint are you using?

`9.5.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint --ignore-path .eslintignore \"src/**/*.css\"`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

CSS Modules

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors did you get)?

The following warnings were flagged:

```shell
Expected selector ":global(.buildResultsSummaryTable) span:nth-child(2)" to come before selector ":global(.buildResultsSummaryTable) span" (no-descending-specificity)
```
