### ISSUE TITLE
Linter for wrong gradient syntax

### ISSUE THREAD

**Issue by ai** [stylelint/stylelint#362]
We have a lot of code with old gradient syntax like:

```css
body {
  background: linear-gradient(left, black, white);
}
```

Maybe we should create a linter for it?

/cc @davidtheclark
