### ISSUE TITLE
Fix TypeError: Cannot read property 'search' of undefined in linebreaks

### ISSUE THREAD

**Issue by keenwon** [stylelint/stylelint#3635]
> Clearly describe the bug

"TypeError: Cannot read property 'search' of undefined"

> What CSS is needed to reproduce the bug?

style.less

```less
.scrollbar() {
  &::-webkit-scrollbar-track {
    background-color: #F5F5F5;
  }
  &::-webkit-scrollbar {
    width: 6px;
    height: 6px;
    background-color: #F5F5F5;
  }
  &::-webkit-scrollbar-thumb {
    background-color: #e0e0e0;
  }
}
.m-header-center {
  height: 46px;
  background: #404040;
}
.mui-select-dropdown-menu-item {
  line-height: 14px;
}
.f-clr{
  zoom:1;
  &:after{display:block;clear:both;visibility:hidden;height:0;overflow:hidden;content:".";}
}
.f-fr{
  float: right;
}
.f-dn {
  display: none;
}
```

> What stylelint configuration is needed to reproduce the bug?

e.g.

```js
module.exports = {
    extends: 'stylelint-config-standard',
    rules: {
        indentation: 4,
        linebreaks: 'unix',
        'no-descending-specificity': [true, {
            severity: 'warning'
        }]
    }
};
```

> Which version of stylelint are you using?

`9.5.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

e.g. "CLI with `stylelint "style.less" --fix`"

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

e.g. "Yes, it's related to LESS nested properties."

> What did you expect to happen?

e.g. "No warnings to be flagged."

> What actually happened (e.g. what warnings or errors did you get)?

e.g. "The following warnings were flagged:"

```shell
TypeError: Cannot read property 'search' of undefined
    at complain (/home/keenwon/Test/xxxxxxxxxx/node_modules/stylelint/lib/rules/block-closing-brace-newline-before/index.js:79:63)
    at check (/home/keenwon/Test/xxxxxxxxxx/node_modules/stylelint/lib/rules/block-closing-brace-newline-before/index.js:64:11)
    at /home/keenwon/Test/xxxxxxxxxx/node_modules/postcss-less/node_modules/postcss/lib/container.js:241:28
    at /home/keenwon/Test/xxxxxxxxxx/node_modules/postcss-less/node_modules/postcss/lib/container.js:148:26
    at Rule.each (/home/keenwon/Test/xxxxxxxxxx/node_modules/postcss-less/node_modules/postcss/lib/container.js:114:22)
    at Rule.walk (/home/keenwon/Test/xxxxxxxxxx/node_modules/postcss-less/node_modules/postcss/lib/container.js:147:21)
    at /home/keenwon/Test/xxxxxxxxxx/node_modules/postcss-less/node_modules/postcss/lib/container.js:150:32
    at Root.each (/home/keenwon/Test/xxxxxxxxxx/node_modules/postcss-less/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/home/keenwon/Test/xxxxxxxxxx/node_modules/postcss-less/node_modules/postcss/lib/container.js:147:21)
    at Root.walkRules (/home/keenwon/Test/xxxxxxxxxx/node_modules/postcss-less/node_modules/postcss/lib/container.js:239:25)

```

**Comment by jeddy3** [comment]
@keenwon Thanks for the report and for using the template. 

If possible, please can you create the smallest reproducible example possible, e.g. the smallest snippet of Less code combined with the smallest config that triggers the error, so that we can better diagnose the issue for you. For example, try stripping out rules and bits of Less until there is no error. This will help us determine which rule is causing the problem.

**Comment by keenwon** [comment]
@jeddy3 

According to the error stack, I guess it is `block-closing-brace-newline-before`

```shell
TypeError: Cannot read property 'search' of undefined
    at complain (/home/keenwon/Test/xxxxxxxxxx/node_modules/stylelint/lib/rules/block-closing-brace-newline-before/index.js:79:63)
    at check (/home/keenwon/Test/xxxxxxxxxx/node_modules/stylelint/lib/rules/block-closing-brace-newline-before/index.js:64:11)
    at /home/keenwon/Test/xxxxxxxxxx/node_modules/postcss-less/node_modules/postcss/lib/container.js:241:28
    at /home/keenwon/Test/xxxxxxxxxx/node_modules/postcss-less/node_modules/postcss/lib/container.js:148:26
    at Rule.each (/home/keenwon/Test/xxxxxxxxxx/node_modules/postcss-less/node_modules/postcss/lib/container.js:114:22)
    at Rule.walk (/home/keenwon/Test/xxxxxxxxxx/node_modules/postcss-less/node_modules/postcss/lib/container.js:147:21)
    at /home/keenwon/Test/xxxxxxxxxx/node_modules/postcss-less/node_modules/postcss/lib/container.js:150:32
    at Root.each (/home/keenwon/Test/xxxxxxxxxx/node_modules/postcss-less/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/home/keenwon/Test/xxxxxxxxxx/node_modules/postcss-less/node_modules/postcss/lib/container.js:147:21)
    at Root.walkRules (/home/keenwon/Test/xxxxxxxxxx/node_modules/postcss-less/node_modules/postcss/lib/container.js:239:25)
```

**Comment by jeddy3** [comment]
> According to the error stack, I guess it is `block-closing-brace-newline-before`

Makes sense. Any idea which bit of the Less might be causing the rule to trip up?

**Comment by keenwon** [comment]
```less
.f-clr{
  &:after{display:block;clear:both;visibility:hidden;height:0;overflow:hidden;content:".";}
}
```

```shell
stylelint "style.less" --fix
```

```js
module.exports = {
    extends: 'stylelint-config-standard',
    rules: {
        indentation: 4,
        linebreaks: 'unix',
        'no-descending-specificity': [true, {
            severity: 'warning'
        }]
    }
};
```
