### ISSUE TITLE
Fix false positives for comments within selector lists in selector-type-case

### ISSUE THREAD

**Issue by XhmikosR** [stylelint/stylelint#3698]
> Which rule, if any, is the bug related to?

` selector-type-case`

> What CSS is needed to reproduce the bug?

```less
.alert-dismissable, // The misspelled .alert-dismissable was deprecated in 3.2.0.
.alert-dismissible {
  padding-right: (@alert-padding + 20);

  // Adjust close link position
  .close {
    position: relative;
    top: -2px;
    right: -21px;
    color: inherit;
  }
}
```

> What stylelint configuration is needed to reproduce the bug?

https://github.com/twbs/bootstrap/blob/97b95a524e7a413dca4278ee1cc9570c38ff5f25/grunt/.stylelintrc

> Which version of stylelint are you using?

`9.6.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Grunt

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Less

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors did you get)?

```
41:24 × Expected "The" to be "the" selector-type-case
```

v9.5.0 seems to be fine. After updating to 9.6.0 I'm getting this.
