### ISSUE TITLE
Fix false positives for universal selector in no-descending-specificity

### ISSUE THREAD

**Issue by yukipastelcat** [stylelint/stylelint#3738]
```scss
.something {
  & > * {
    &:not(:first-child) {
      margin-right: 16px;
    }
    &:not(:last-child) {
      margin-left: 16px;
    }
  }
  &-element {
    & > * { /*Expected selector ".something-element > *" to come before selector ".something > *:not(:first-child)" (no-descending-specificity) */
      &:not(:first-child) {
        margin-top: 16px;
      }
      &:not(:last-child) {
        margin-bottom: 16px;
      }
    }
  }
}
```

My stylelint.config.js:
```javascript
module.exports = {
  extends: ['stylelint-config-recommended-scss'],
};
```
