### ISSUE TITLE
selector-list-comma-newline-after add option to "keep current"

### ISSUE THREAD

**Issue by JCKodel** [stylelint/stylelint#3843]
> What is the problem you're trying to solve?

When selector-list-comma-newline-after is always:
```css
h1,
h2,
h3,
h4,
h5,
h6
{
    padding: 0;
}
```

I don't like it, so I would rather prefer:

```css
h1, h2, h3, h4, h5, h6
{
    padding: 0;
}
```

This behavior can be set with "never-multi-line";

But:

```css
.this .is a .long .selector1, .this .is a .long .selector2, .this .is a .long .selector3, .this .is a .long .selector4
{
    padding: 0;
}
```

I would like to be:
```css
.this .is a .long .selector1,
.this .is a .long .selector2,
.this .is a .long .selector3,
.this .is a .long .selector4
{
    padding: 0;
}
```

> What solution would you like to see?

A rule to "don't mess with this, I'll choose it based on what my eyes are more pleased".
