### ISSUE TITLE
False positives for font-family in font-family-no-missing-generic-family-keyword

### ISSUE THREAD

**Issue by hirokishirai** [stylelint/stylelint#3848]
> Clearly describe the bug

Thanks for great work of stylelint community.

There is False positives for font-family in font-family-no-missing-generic-family-keyword(I'm sorry If this is not Bug).
When I specified `font-family` with `"my_original_font_family_name" !important`, stylelint showed me bellow error.

```
path/to/_my_original_fonts.scss
 23:16  ✖  Unexpected missing generic font family   font-family-no-missing-generic-family-keyword
```

But, font-family: `"my_original_font_family_name"` is defined by `@font-face`.

When I specified `font-family` with `my_original_font_family_name !important`(without `""`), stylelint test is passed.

This issue is similar to #3033 ?

> Which rule, if any, is the bug related to?

font-family-no-missing-generic-family-keyword

> What CSS is needed to reproduce the bug?

```scss
/* scss */
@font-face {
  font-family: "my_original_font_family_name";
  src: font-url("my_original_font_family_name.eot?fooooo");
  src:
    font-url("my_original_font_family_name.eot?fooooo#iefix") format("embedded-opentype"),
    font-url("my_original_font_family_name.woff2?fooooo") format("woff2"),
    font-url("my_original_font_family_name.ttf?fooooo") format("truetype"),
    font-url("my_original_font_family_name.woff?fooooo") format("woff"),
    font-url("my_original_font_family_name.svg?fooooo#my_original_font_family_name") format("svg");
  font-weight: normal;
  font-style: normal;
}

[class^="icon-"],
[class*=" icon-"] {
  font-family: "my_original_font_family_name" !important;
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "font-family-no-missing-generic-family-keyword": true
  }
}
```

> Which version of stylelint are you using?

9.9.0

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint "**/*.scss" --config stylelint.config.js`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

I guess No.

> What did you expect to happen?

No warnings in this case.

> What actually happened (e.g. what warnings or errors did you get)?

e.g. "The following warnings were flagged:"

```
path/to/_my_original_fonts.scss
 23:16  ✖  Unexpected missing generic font family   font-family-no-missing-generic-family-keyword
```

**Comment by jeddy3** [comment]
@hirokishirai Thanks for the report and for using the template.

I believe this rule is correctly detecting a violation. It ensures that a _generic font family_ is used every time a _list of family names_ is used _outside of a `@fontface` definition_.

To appease the rule you'll need to add a generic font family to your list of family names e.g.

```css
[class^="icon-"],
[class*=" icon-"] {
  font-family: "my_original_font_family_name", sans-serif !important;
}
```

The list of generic font families can be found [in the specification](https://www.w3.org/TR/css-fonts-3/#generic-font-families).

> When I specified font-family with my_original_font_family_name !important(without ""), stylelint test is passed.

That's strange. I'm unable to reproduce this behaviour. I get a violation message regardless of whether the family name is quoted or not. If this problem persists, can you create a reproducible test repo so we can investigate further, please?
