### ISSUE TITLE
auto fix for `declaration-colon-newline-after` lead to another issue

### ISSUE THREAD

**Issue by wKich** [stylelint/stylelint#3853]
> Clearly describe the bug

Some rule ignore `indentation` rule and as result after auto fix I receive error about indentation and should call auto fix second time to fix my files. If I try to use `prettier-stylelint` than I get unfixable indentation error, because stylelint is called once.

> Which rule, if any, is the bug related to?

`declaration-colon-newline-after`. I think this happen because of PR #3588

> What LESS is needed to reproduce the bug?

```less
:local {
  .root {
    &:active .box {
      background: #e1e1e1;
      box-shadow: 0 -1px 0 0 rgba(0, 0, 0, 0.1), 0 0 0 1px rgba(0, 0, 0, 0.2),
        inset 0 1px 2px 0 rgba(0, 0, 0, 0.1);
    }
  }
}
```

> What stylelint configuration is needed to reproduce the bug?

```yaml
extends:
  - stylelint-config-standard
  - stylelint-config-css-modules
```

> Which version of stylelint are you using?

```
    "stylelint": "^9.9.0",
    "stylelint-config-css-modules": "^1.3.0",
    "stylelint-config-standard": "^18.2.0",
```

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint "./**/*.less" --fix`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

I think No.

> What did you expect to happen?

Correctly formatted file:
```less
:local {
  .root {
    &:active .box {
      background: #e1e1e1;
      box-shadow:
        0 -1px 0 0 rgba(0, 0, 0, 0.1),
        0 0 0 1px rgba(0, 0, 0, 0.2),
        inset 0 1px 2px 0 rgba(0, 0, 0, 0.1);
    }
  }
}
```

> What actually happened (e.g. what warnings or errors did you get)?

After first auto fix I receive:
```less
:local {
  .root {
    &:active .box {
      background: #e1e1e1;
      box-shadow:
        0 -1px 0 0 rgba(0, 0, 0, 0.1),
 0 0 0 1px rgba(0, 0, 0, 0.2),        /* <--- Here line with indentation error */
        inset 0 1px 2px 0 rgba(0, 0, 0, 0.1);
    }
  }
}
```
