### ISSUE TITLE
URL anchors are detected as invalid hex colors

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#387]
In the following CSS: (I've truncated the base64 hex string for readability)

```css
@font-face {
	font-family: dashicons;
	src: url(data:application/font-woff;charset=utf-8;base64, ABCDEF==) format("woff"),
		url(../fonts/dashicons.ttf) format("truetype"),
		url(../fonts/dashicons.svg#dashicons) format("svg");
	font-weight: normal;
	font-style: normal;
}
```

I get a warning: 
```
10:29	⚠  Unexpected invalid hex color "#dashicons" (color-no-invalid-hex) [stylelint]
```
