### ISSUE TITLE
Conflicting rules: block-opening-brace-space-before and media-query-list-comma-newline-after 

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#388]
Using the following CSS rules there appears to be conflicts between the `block-opening-brace-space-before` and `media-query-list-comma-newline-after` rules:

When using the following rules:
```
    "block-opening-brace-newline-after": [ 2, "always" ],
    "block-opening-brace-space-before": [ 2, "always" ],
    "media-query-list-comma-newline-after": [ 2, "always-multi-line" ],
    "media-query-list-comma-space-after": [ 2, "always-single-line" ],
    "media-query-list-comma-space-before": [ 2, "never" ],
```

Example 1: Given the following CSS:  (Single space between `) {` on line 1)

```css
@media only screen and (max-width: 640px), screen and (max-height: 400px) {
	.upload-php .mode-grid .media-sidebar{
		max-width: 100%;
	}
}
```

The following warning is displayed:
```
1187:38	⚠  Expected single space before "{" (block-opening-brace-space-before) [stylelint]
```

Example 2: Altering the CSS to: (Newline after the `,`)

```css
@media only screen and (max-width: 640px), 
screen and (max-height: 400px) {
	.upload-php .mode-grid .media-sidebar{
		max-width: 100%;
	}
}
```

The following warning is displayed:
```
1188:38	⚠  Expected single space before "{" (block-opening-brace-space-before) [stylelint]
```

Example 3: Altering the CSS to: (No whitespace between `){` on line 1)

```css
@media only screen and (max-width: 640px), screen and (max-height: 400px){
	.upload-php .mode-grid .media-sidebar{
		max-width: 100%;
	}
}
```

The following warning is displayed:
```
1186:73	⚠  Expected single space before "{" (block-opening-brace-space-before) [stylelint]
1187:38	⚠  Expected single space before "{" (block-opening-brace-space-before) [stylelint]
```
