### ISSUE TITLE
Autoprefixer and property-no-vendor-prefix

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#395]
Sorry if this isn't the clearest bug report, trying to wrap my head around all of this :smirk: 

We use autoprefixer to manage vendor prefixes, one issue I now have is how to lint vendor prefixes and issues with the `property-no-vendor-prefix` rule

We commit the vendor prefixes added by Autoprefixer to our primary repo, as such we have CSS code with the `-webkit-box-shadow` vendor prefix, if based on our browser configs a vendor prefix is no longer required then Autoprefixer will remove that vendor prefix and then that code is also no longer in our repo

```css
.wp-core-ui .button.focus,
.wp-core-ui .button:focus,
.wp-core-ui .button-secondary:focus,
.wp-core-ui .button-link:focus {
    -webkit-box-shadow:
        0 0 0 1px #5b9dd9,
        0 0 2px 1px rgba(30, 140, 190, 0.8);
    box-shadow:
        0 0 0 1px #5b9dd9,
        0 0 2px 1px rgba(30, 140, 190, 0.8);
}
```

Now given the rule docs for [property-no-vendor-prefix](https://github.com/stylelint/stylelint/blob/master/src/rules/property-no-vendor-prefix/README.md) I'm not sure if what I am doing is right or wrong.

We have the following Stylelint rule defined: `"property-no-vendor-prefix": 2,

For the above CSS I get the following warning:
```
165:2	⚠  Unexpected vendor-prefixed property "-webkit-box-shadow" (property-no-vendor-prefix) [stylelint]
```

We use `grunt-postcss` and here's my relevant lint grunt task from our `Gruntfile.js`:

```js
			lint: {
				options: {
					syntax: require('postcss-scss'),
					processors: [
						autoprefixer({
							browsers: ['Android >= 2.1', 'Chrome >= 21', 'Edge >= 1', 'Explorer >= 7', 'Firefox >= 17', 'Opera >= 12.1', 'Safari >= 6.0'],
							cascade: false,
							remove: true  // Remove old vendor prefixes
						}),
						stylelint(config),
						reporter({
							clearMessages: true
						})
					],
				},
				expand: true,
				cwd: SOURCE_DIR,
				src: [
					'**/*.css',
					'**/*.scss'
				]
			}
```

If I change my Autoprefixer browser config to `browsers: ['last 2 versions'],` aagin I see the same warning:

```
165:2	⚠  Unexpected vendor-prefixed property "-webkit-box-shadow" (property-no-vendor-prefix) [stylelint]
```

Using the Autoprefixer demo with the above CSS and browser configs I'm expecting the browser config using the `last 2 versions` to be the only config that reports a warning, I shouldn't get a warning for my config as `Android >= 2.1` component of my browser config requires the `-webkit-box-shadow` vendor prefix.

This can be tested using https://autoprefixer.github.io/ and the above CSS example, test by pasting that CSS and then testing each of these browser config settings: `Android >= 2.1` and `last 2 versions`
