### ISSUE TITLE
Allow arbitrary whitespace with comment-space-inside

### ISSUE THREAD

**Issue by MadLittleMods** [stylelint/stylelint#403]
[`comment-space-inside`](https://github.com/stylelint/stylelint/blob/master/src/rules/comment-space-inside/README.md) should only apply when content is on the same line as the start and end indicators(`/*` and `*/`) single line comments

Adding a `always-single-line` like other rules already have isn't quite enough to cover every basis, but would satisfy my need.

Currently this throws a warning/error if `comment-space-inside: 'always'`:
```css
.foo {
	/*
	opacity: 0;
	pointer-events: none;
	*/
}
```

If content is on same line as `/*` or `*/` then the space should be necessary but only to appropriate piece. I expect this to pass when `comment-space-inside: 'always'`:
```css
.foo {
	/* opacity: 0;
	pointer-events: none;
	*/
}
```
