### ISSUE TITLE
Prevent "PX" or "Px" to be converted to lower case 

### ISSUE THREAD

**Issue by xsteadybcgo** [stylelint/stylelint#4048]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

"A feature. As I don't find the appropriate option"

> Which rule, if any, is this issue related to?

 `unit-case`  `white-blacklist`

> What CSS is needed to reproduce this issue?

```css
/*input*/
.foo {
  width: 75px; 
  border: 1PX solid #333;
}

```

> What stylelint configuration is needed to reproduce this issue?

e.g.

```json
{
  "rules": {
    "unit-case": ["lower"]
  }
}
```

> Which version of stylelint are you using?

e.g. `^10.0.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

e.g. "CLI with `stylelint`"

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

e.g. "Yes, it's related to LESS maps."

> What did you expect to happen?
in my project , i use the postcss-plugin -- "postcss-pxtorem". This plugin will convert my css unit value 'px' to 'rem', and when you do not want this convertion , you should use "PX" or "Px" instead of "px".

e.g. 
```css
/*output*/
.foo {
  width: 75px; 
  border: 1PX solid #333;
}
```

> What actually happened (e.g. what warnings or errors you are getting)?

e.g. 

```css
/*output*/
.foo {
  width: 75px; 
  border: 1px solid #333;
}
```

when intergrating with stylelintint , I don't want this tool to fix it as i hope my "px" coexit with "PX" or "Px" .

I have tried the options , for example: "unit-case" , but it does not have the ignore unit option as a second option. Such as:
```
{
  "rules": {
    "unit-case": ["lower", ignoreUnit: /px/i ]
  }
}
```

The "white-blacklist" does not support regexp expresion but only string or []string.

```json
{
  "rules": {
    "white-blacklist": [/px/i, "em", etc...]
  }
}
```
