### ISSUE TITLE
Fix false positives for escaped multi-line in `string-no-newline`

### ISSUE THREAD

**Issue by AlexWayfer** [stylelint/stylelint#4057]
> Clearly describe the bug

I want to split large strings for aesthetic reasons with enabled `string-no-newline` rule.

There is the quote from [the specs](https://www.w3.org/TR/CSS2/syndata.html#strings), including:

> And also: "It is possible to break strings over several lines, for aesthetic or other reasons, but in such a case the newline itself has to be escaped with a backslash (\)."

But for some reason escaped newlines are forbidden in Stylelint.

> Which rule, if any, is the bug related to?

`string-no-newline`

> What CSS is needed to reproduce the bug?

```css
background-image: url(
  "data:image/svg+xml;utf8,\
  <svg fill='black' height='24' \
    viewBox='0 0 24 24' width='24' \
    xmlns='http://www.w3.org/2000/svg'\
  ><path d='M7 9l5 5 5-5z'/></svg>"
);
```

> What stylelint configuration is needed to reproduce the bug?

```yaml
extends: stylelint-config-standard
```

> Which version of stylelint are you using?

`9.10.1`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `stylelint assets/styles/`.

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No.

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors did you get)?

The following warnings were flagged:

```shell
 116:197  ✖  Expected line length to be no more than 80 characters                                               max-line-length
```

**Comment by hudochenkov** [comment]
Thanks for the report and for using the template.

I can't reproduce this error with the following code:

```css
.hello {
  background-image: url(
    "data:image/svg+xml;utf8,\
    <svg fill='black' height='24' \
      viewBox='0 0 24 24' width='24' \
      xmlns='http://www.w3.org/2000/svg'\
    ><path d='M7 9l5 5 5-5z'/></svg>"
  );
}
```

Looks like you're also has `max-line-length: 80` in your config. I can't reproduce error with this rule enabled as well.

Could you check please what is actual CSS, which triggers warning? Maybe there are many indentation symbols, and line is actually bigger than 80 symbols.

**Comment by hudochenkov** [comment]
Looks like our demo is misleading, it doesn't show problem, when CLI shows.

For the following CSS:

```css
.hello {
  background-image: url("data:image/svg+xml;utf8,\
	  <svg fill='black' height='24' \
		viewBox='0 0 24 24' width='24' \
		xmlns='http://www.w3.org/2000/svg'\
	  ><path d='M7 9l5 5 5-5z'/></svg>");
}
```

I got this violation:

```
2:51  ✖  Unexpected newline in string   string-no-newline
```

Looks like it's a bug.

As the issue has been labelled "help wanted", please consider [contributing a fix](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#fixing-a-bug-in-an-existing-rule).

P. S. In original issue violation is incorrect, which confused me.
