### ISSUE TITLE
Fix false positives for multi-line url() in max-line-length

### ISSUE THREAD

**Issue by AlexWayfer** [stylelint/stylelint#4059]
> Clearly describe the bug

There are false positives for max line length when there are spaces inside `url()` content.

> Which rule, if any, is the bug related to?

`max-line-length`

> What CSS is needed to reproduce the bug?

```css
div {
  background-image: url(
    "data:image/svg+xml;utf8,<svg fill='black' height='24' viewBox='0 0 24 24' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M7 9l5 5 5-5z'/></svg>"
  );
}
```

> What tests are not passing?

```js
{
  code:
    "a {\n  background: url(\n    'something something  something'\n  );\n}"
}
```

> What stylelint configuration is needed to reproduce the bug?

```yaml
rules:
  max-line-length:
    - 20
```

> Which version of stylelint are you using?

`9.10.1`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `stylelint "**/*.css"`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No.

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors did you get)?

The following warnings were flagged: 

```shell
70:102  ✖  Expected line length to be no more than 80 characters                                               max-line-length
```

**Comment by hudochenkov** [comment]
Thanks for the report and for using the template.

Issue caused not because of space in url, but because `url("")` is multi-line.

This is not caused violations:

```css
div {
	background-image:
	url("data:image/svg+xml;utf8,<svg fill='black' height='24' viewBox='0 0 24 24' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M7 9l5 5 5-5z'/></svg>");
}
div {
	background-image: url("data:image/svg+xml;utf8,<svg fill='black' height='24' viewBox='0 0 24 24' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M7 9l5 5 5-5z'/></svg>");
}
```

This are causing false negative violations:

```css
div {
	background-image: url(
		"data:image/svg+xml;utf8,<svg fill='black' height='24' viewBox='0 0 24 24' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M7 9l5 5 5-5z'/></svg>");
}
div {
	background-image: url("data:image/svg+xml;utf8,<svg fill='black' height='24' viewBox='0 0 24 24' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M7 9l5 5 5-5z'/></svg>"
	);
}
```

As the issue has been labelled "help wanted", please consider [contributing a fix](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#fixing-a-bug-in-an-existing-rule).
