### ISSUE TITLE
Add property-requirelist or declaration-property-requirelist

### ISSUE THREAD

**Issue by kristerkari** [stylelint/stylelint#4063]
> What is the problem you're trying to solve?

I would like to have a new rule that would require user defined properties to be always grouped together. What I personally need it something that would require `font-family`, `font-size`, `line-height` and `color` all to be defined when styling a text.

I tried to find a rule like this by using search, but did not find anything, so please close this issue if something like this already exists.

> What solution would you like to see?

A new rule that would do the same thing that `at-rule-property-requirelist` does, but for plain properties or for properties inside a declaration.
https://github.com/stylelint/stylelint/tree/master/lib/rules/at-rule-property-requirelist

**Comment by hudochenkov** [comment]
Could you give us some examples of possible configuration, examples with violations, and examples without violations, please?

**Comment by kristerkari** [comment]
# property-requirelist

Specify a requirelist of properties.

```css
    font-size: 18px; font-family: 'foo';
/** ↑                ↑
 *  required property names */
```

## Options

`["array", "of", "properties"]`

Given:

```js
["font-size", "font-family", "line-height"]
```

The following patterns are considered violations:

```css
font-family: 'foo';
font-size: 18px;
```

```css
font-family: 'foo';
line-height: 24px;
```

The following patterns are *not* considered violations:

```css
font-family: 'foo';
font-size: 18px;
line-height: 24px;
```

**Comment by evilebottnawi** [comment]
@kristerkari it is related to recent comment to `stylelint-declaration-block-no-ignored-properties`? I can provide more example and better example of configuration, this rule will be successor for linting properties

**Comment by kristerkari** [comment]
> it is related to recent comment to `stylelint-declaration-block-no-ignored-properties`?

No, this is just something that I would need in a project where I want to make sure that every text has certain properties set. The configuration would be what I posted above.

I think that you are thinking about a different type of rule.

**Comment by hudochenkov** [comment]
If CSS rule has at least one of the properties defined in config, and doesn't have at least one property from this list, then it's considered a violation. Do I understand correctly?

Given list of properties from your first message:

```
["font-family", "font-size", "line-height", "color"]
```

This cases would be considered violations:

```css
/* violation. Shorthand is not allowed */
p {
    font: 18px/32px sans-serif;
    color: #333;
}
```

```css
/* violation, regardless link almost all the time inherit font-* properties from a parent */
a {
    color: blue;
}
```

```css
/* violation, regardless font almost never change on hover */
a {
    font-family: sans-serif;
    font-size: 18px;
    line-height: 32px;
    color: blue;
}
a:hover { /* violation for this rule */
    color: red;
}
```
