### ISSUE TITLE
Could not find extending for npm lib in yml conf

### ISSUE THREAD

**Issue by Vorobeyko** [stylelint/stylelint#4064]
> Clearly describe the bug
1. I set $PATH like 
```sh
export PATH="$PATH:./node_modules/.bin:`pwd`/tests/lints/node_modules/.bin"
```
2. And from root folder run stylelint
And i get error:
Error: Could not find "stylelint-config-recommended". Do you need a `configBasedir`?

> Which rule, if any, is the bug related to?

> What CSS is needed to reproduce the bug?
Never mind

> What stylelint configuration is needed to reproduce the bug?

I used yml config - `.stylelint.yml` with next content:
```
extends: stylelint-config-recommended
rules:
  indentation: 2
  font-family-no-missing-generic-family-keyword: null
  at-rule-no-unknown: null
  no-descending-specificity: null
  property-no-unknown:
    - true
    - ignoreProperties:
        - "composes"
        - "r"
  selector-pseudo-class-no-unknown:
    - true
    - "ignorePseudoClasses": ["global"]
```

> Which version of stylelint are you using?

e.g. `9.9.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?
"stylelint 'src/**/*.css`"

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

no

> What did you expect to happen?

Lib will be received correct path to lib from node_modules
I suggest changing the module `utils/getModulePath` by adding:
```js
  if (!path && !lookup.startsWith(".") && !lookup.startsWith("/")) {
    path = require.resolve(lookup);
  }
```
And I know for parameter ‘config-basedir’. But I don’t want use it

> What actually happened (e.g. what warnings or errors did you get)?

e.g. "The following warnings were flagged:"

```shell
test.css
Error: Could not find "stylelint-config-recommended". Do you need a `configBasedir`?
```
