### ISSUE TITLE
Add keyframe-selector-notation

### ISSUE THREAD

**Issue by MartijnCuppens** [stylelint/stylelint#4065]
### What is the problem you're trying to solve?

In animations the as well the `from/to` syntax as the `0%/100%` syntax can be used.

For example:
```css
@keyframes animation-1 {
  from {
    color: red;
  }
  to {
    color: blue;
  }
}

@keyframes animation-2 {
  0% {
    color: green;
  }
  100% {
    color: yellow;
  }
}
```

### What solution would you like to see?

A new rule that would determine which approach you should use. Not sure how this should be implemented, because sometimes you'll have an animation which looks like this:

```css
@keyframes animation-2 {
  20% {
    color: green;
  }
  100% {
    color: yellow;
  }
}
```
Which will lead to a mix of `20%` and `to` if the `from/to` syntax is preferred.
