### ISSUE TITLE
Extra empty line within declaration blocks, block-opening-brace-empty-line-after and declaration-block-max-empty-lines

### ISSUE THREAD

**Issue by alkorlos** [stylelint/stylelint#4068]
I have:
```js
stylelint.config.js
```

```js
module.exports = {
	plugins: 'stylelint-order',
	rules: {
		'order/properties-order': [
			{
				emptyLineBefore: 'always',
				noEmptyLineBetween: true,
				properties: [
					'width',
					'height'
				]
			},
			{
				emptyLineBefore: 'always',
				noEmptyLineBetween: true,
				properties: [
					'font-size',
					'font-family'
				]
			},
			{
				emptyLineBefore: 'always',
				noEmptyLineBetween: true,
				properties: [
					'background-repeat'
				]
			}
		],
		'block-closing-brace-empty-line-before': 'never'
	}
};
```

If source css will be
```css
.test {
	
	width: 100%;


	font-size: 14px;
	height: 100%;


	font-family: "Arial", "Helvetica", sans-serif;
	background-repeat: no-repeat;
	
}
```

Output css will be
```css
.test {
	
	width: 100%;
	height: 100%;


	font-size: 14px;
	font-family: "Arial", "Helvetica", sans-serif;

	background-repeat: no-repeat;
}
```

But I need
```css
.test {
	width: 100%;
	height: 100%;

	font-size: 14px;
	font-family: "Arial", "Helvetica", sans-serif;

	background-repeat: no-repeat;
}
```

Is there a way to leave only one empty line only between the group of properties? Now it seems that there rules "block-opening-brace-empty-line-after" and "declaration-block-max-empty-lines" are not enough.
"block-opening-brace-empty-line-after": Require or disallow an empty line after the opening brace of blocks.
"declaration-block-max-empty-lines": Limit the number of adjacent empty lines within declaration blocks.
Previously, this was partly fixed by "declaration-empty-line-before: never", but after updating  "stylelint" from 9.8.0 to 10.0.1 it deletes all the empty lines within declaration blocks.
