### ISSUE TITLE
selector-pseudo-class-no-unknown: support `:defined`

### ISSUE THREAD

**Issue by lkraav** [stylelint/stylelint#4080]
> What is the problem you're trying to solve?

https://html.spec.whatwg.org/multipage/semantics-other.html#selector-defined

Best practice for eliminating FOUC when using custom elements https://developers.google.com/web/fundamentals/web-components/customelements#prestyle

Example:

```css
app-drawer:not(:defined) {
  /* Pre-style, give layout, replicate app-drawer's eventual styles, etc. */
  display: inline-block;
  height: 100vh;
  opacity: 0;
  transition: opacity 0.3s ease-in-out;
}
```

> What solution would you like to see?

selector-pseudo-class-no-unknown: should probably natively support `:defined`, as it's already shipped in modern browsers.

Your thoughts?
