### ISSUE TITLE
Fix false positives for variables in function-calc-no-invalid

### ISSUE THREAD

**Issue by vilchik-elena** [stylelint/stylelint#4114]
There are false positives for less and scss variables containing `-`

> Which rule, if any, is the bug related to?

`function-calc-no-invalid`

> What CSS is needed to reproduce the bug?

for less

```css
.foo {
	height: calc(100% - (@a-height + @b-margin-top));
}
```
for scss
```css
.foo {
	height: calc(100% - ($a-height + $b-margin-top));
}
```

> What stylelint configuration is needed to reproduce the bug?
```json
{
  "rules": {
    "function-calc-no-invalid": true
  }
}
```

> Which version of stylelint are you using?

`10.1.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `stylelint file.less --config myconfig.json`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to less and scss variables

> What did you expect to happen?

No warnings to be flagged

> What actually happened (e.g. what warnings or errors did you get)?

The following warnings were flagged (for less case), a pair of issues per dash in a variable name

```shell
 2:25  ✖  Expected space before "-" operator   function-calc-no-invalid
 2:26  ✖  Expected space after "-" operator    function-calc-no-invalid
 2:37  ✖  Expected space before "-" operator   function-calc-no-invalid
 2:38  ✖  Expected space after "-" operator    function-calc-no-invalid
 2:44  ✖  Expected space before "-" operator   function-calc-no-invalid
 2:45  ✖  Expected space after "-" operator    function-calc-no-invalid
```

There was a bug fix done (#3908) to fix variables inside interpolation for both less and scss, but for simple variable there are still FPs. Note that for scss as soon as I wrap variables inside interpolation, issues disappear :
```
.foo {
	height: calc(100% - (#{$a-height} + #{$b-margin-top}));
}
```

**Comment by hudochenkov** [comment]
Thanks for the report and for using the template.

Looks like it's the same problem as https://github.com/stylelint/stylelint/issues/4102. @ota-meshi could you take a look, please?

**Comment by ota-meshi** [comment]
Hello!

I checked about `SCSS`.
In the case of `SCSS`, I think that there is no problem in the current behavior.

When I tried [here](https://www.sassmeister.com/), the following `SCSS` syntax seems to be invalid:

```scss
$a-height: 10px;
$b-margin-top: 20px;

.foo {
  height: calc(100% - ($a-height + $b-margin-top));
}
```

The following SCSS syntax is valid:

```scss
$a-height: 10px;
$b-margin-top: 20px;

.foo {
  height: calc(100% - (#{$a-height} + #{$b-margin-top}));
}
```

In this syntax, there is no problem with the `function-calc-no-invalid` rule.

I checked about `less`.
In the case of `less`, as some of you said, there is a problem with the current behavior.

When I tried [here](http://lesscss.org/less-preview/), the following `less` syntax is valid:

```less
@a-height: 10px;
@b-margin-top: 20px;

.foo {
	height: calc(100% - (@a-height + @b-margin-top));
}
```

In this syntax, there is false positive in the `function-calc-no-invalid` rule.

This is a bug but I'm not familiar with `less`.
Please let me know if you know the character codes available for `less` variables.
