### ISSUE TITLE
New rule: selector-pseudo-class-no-unspaced-operator

### ISSUE THREAD

**Issue by fpuga** [stylelint/stylelint#4127]
> What is the problem you're trying to solve?

I'm reviewing _stylelint_ and _prettier_ to standardize a css formatting tool in our team. We are going to use _stylelint_ but prefer an output as much closer to _prettier_ as possible in many aspects.

One of the things that _prettier_ does is introduce a whitespace around operators in the pseudo class `nth-child`

As example, prettier converts this css:

```css
.table-checks td:nth-child(n+2) {
    text-align: center;
}
```
to this:

```css
.table-checks td:nth-child(n + 2) {
    text-align: center;
}
```

but there is not (or i don't find) an option to check this in _stylelint_

As there is already [a rule like this for functions](https://stylelint.io/user-guide/rules/function-calc-no-unspaced-operator/) it would make sense have another one for pseudo selectors.

> What solution would you like to see?

A new rule that implements the proposed check.
