### ISSUE TITLE
Fix false negatives for except: ["after-closing-brace"] in block-closing-brace-empty-line-before

### ISSUE THREAD

**Issue by Jamiewarb** [stylelint/stylelint#4129]
> Clearly describe the bug

The `"block-closing-brace-empty-line-before"` rule with the `"except": "after-closing-brace"` does not seem to be working any longer. Rather, the behaviour seems to be identical, whether or not the except is added.

> Which rule, if any, is the bug related to?

It is specifically relating to the single exception, `"after-closing-brace"` that can be added to `"block-closing-brace-empty-line-before"`.

> What CSS is needed to reproduce the bug?

e.g.

```scss
.a {

    .b {
        cursor: pointer;
    }

} // Unexpected empty line before closing brace

.a {

    &__b {
        cursor: pointer;
    }

} // Unexpected empty line before closing brace

.a {

    &__b {
        cursor: pointer;
    }
} // No warnings shown here
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "block-closing-brace-empty-line-before": ["never", {
      "except": ["after-closing-brace"]
    }]
  }
}
```

> Which version of stylelint are you using?

9.3.0 and 10.1.0 - Occurring on both.

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

Via CLI: 

```bash
stylelint 'resources/**/*.(s?(a|c)ss|vue)' --syntax scss
```

and via Webpack: 
```javascript
plugins: [
    new StyleLintPlugin({
        configFile: '.stylelintrc',
        context: 'resources/assets',
        files: '**/*.(s?(a|c)ss|vue)',
        syntax: 'scss',
    }),
]
```

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to SCSS nested properties.

> What did you expect to happen?

One warning should have flagged for the third example above. No warnings should be flagged for the first two examples, as they correctly have a new line after the closing brace, as per the docs.

> What actually happened (e.g. what warnings or errors did you get)?

The following warnings are flagged:

```shell
test.scss
✖  7:1 Unexpected empty line before   block-closing-brace-empty-line-before
           closing brace
✖  15:1 Unexpected empty line before   block-closing-brace-empty-line-before
           closing brace
```
