### ISSUE TITLE
Invalid Option: Invalid option value "null," for rule

### ISSUE THREAD

**Issue by iliyaZelenko** [stylelint/stylelint#4168]
> Clearly describe the bug

CLI command `stylelint "./src/styles/**/*.sass" --fix --syntax sass` gives errors:

```
Invalid Option: Invalid option value "null," for rule "block-closing-brace-empty-line-before"
Invalid Option: Invalid option value "null," for rule "block-closing-brace-newline-after"
Invalid Option: Invalid option value "null," for rule "block-closing-brace-newline-before"
Invalid Option: Invalid option value "null," for rule "block-closing-brace-space-before"
Invalid Option: Invalid option value "null," for rule "block-opening-brace-newline-after"
Invalid Option: Invalid option value "null," for rule "block-opening-brace-space-after"
Invalid Option: Invalid option value "null," for rule "block-opening-brace-space-before"
Invalid Option: Invalid option value "null," for rule "declaration-block-semicolon-newline-after"
Invalid Option: Invalid option value "null," for rule "declaration-block-semicolon-space-after"
Invalid Option: Invalid option value "null," for rule "declaration-block-semicolon-space-before"
```

Even when I put a valid value, for examplen `"block-closing-brace-empty-line-before": never,` then the error still remains:

```
Invalid Option: Invalid option value "never," for rule "block-closing-brace-empty-line-before"
```

> What CSS is needed to reproduce the bug?

Even an empty scs

> What stylelint configuration is needed to reproduce the bug?

`.stylelintrc.yaml`:

```yaml
rules:
  "block-closing-brace-empty-line-before": null,
  "block-closing-brace-newline-after": null,
  "block-closing-brace-newline-before": null,
  "block-closing-brace-space-before": null,
  "block-opening-brace-newline-after": null,
  "block-opening-brace-space-after": null,
  "block-opening-brace-space-before": null,
  "declaration-block-semicolon-newline-after": null,
  "declaration-block-semicolon-space-after": null,
  "declaration-block-semicolon-space-before": null,
  "declaration-block-trailing-semicolon": null
```

> Which version of stylelint are you using?

 `10.1.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `stylelint "./src/styles/**/*.sass" --fix --syntax sass`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to SASS.

> What did you expect to happen?

No errors.

> What actually happened?

Errors.
