### ISSUE TITLE
Make --report-needless-disables CLI flag respect stylelint-disable commands

### ISSUE THREAD

**Issue by saiichihashimoto** [stylelint/stylelint#4203]
> Clearly describe the bug

When using `--report-needless-disables`, it ignores all of my `stylelint-disable`s.

> Which rule, if any, is the bug related to?

all

> What CSS is needed to reproduce the bug?

```css
/* stylelint-disable selector-max-type */
/* stylelint-disable selector-max-universal */

*,
::after,
::before {
	box-sizing: border-box;
	padding: 0;
	margin: 0;
}

a {
	color: inherit;
	text-decoration: inherit;
}

```

> What stylelint configuration is needed to reproduce the bug?

e.g.

```json
{
  "rules": {
    "selector-max-type": 0,
    "selector-max-universal": 0
  }
}
```

> Which version of stylelint are you using?

Commit `d3a6cb47fc2d5c59e61f6fac618c6121b316b97c` (it comes with some `--report-needless-disables` fix that I need since the last release)

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

`stylelint --report-needless-disables`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

The problem applies to both

> What did you expect to happen?

For it to disable the rules

> What actually happened (e.g. what warnings or errors did you get)?

They were not disabled, receive these errors:
```
src/index.css
  6:1  ✖  Expected "*" to have no more than 0 universal selectors        selector-max-universal
 14:1  ✖  Don't style html elements. It leads to css specificity issues  selector-max-type
```

Without the flag, these errors do not appear.

I messed up reporting #4190, it happens even without `--fix`.
