### ISSUE TITLE
New rule/options: newline support for *function-parentheses-*-inside`

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#421]
Ref: https://github.com/stylelint/stylelint/pull/406 & https://github.com/stylelint/stylelint/issues/405

* [ ] `"always-single-line"|"never-single-line"` options for existing rule `function-parentheses-space-inside`
* [ ] `"always"|"always-multi-line"|"never-multi-line"` options for new rule `function-parentheses-newline-inside`

So that we can check for the following code style:

```css
.foo {
    background: linear-gradient(
        45deg,
        rgba(215, 215, 215, 1) 0%,
        rgba(215, 215, 215, 1) 25%,
        rgba(53, 53, 53, 1) 65%,
        rgba(53, 53, 53, 1) 100%
    );
}
```
