### ISSUE TITLE
Use GitHub Actions

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#4273]
We've recently discussed (and implemented) a few changes to improve our experience maintaining stylelint: https://github.com/stylelint/stylelint/issues/4244, https://github.com/stylelint/stylelint/issues/3499, #4245 etc.

Another area of possible improvement is continuous integration, if only because Appveyor has been troublesome recently.

[GitHub Actions](https://github.com/features/actions) could help us here. We could test on multiple version of node across windows, nix and mac within GitHub [as detailed in this blog post](https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/).

(Later down the line, we could look into things [like publishing to npm via Actions](https://medium.com/faun/automate-your-npm-publish-with-github-actions-dfe8059645dd) too.)

---

I've added stylelint to the [GitHub Actions waiting list](https://github.com/features/actions/signup?account=stylelint). Hopefully, it'll be processed soon and we can start investigating. (I had originally signed up with my personal account as I hadn't realised that wouldn't also be for stylelint.)

**Comment by ybiquitous** [comment]
Recently I tried GitHub Actions. Very fast. 👍 
(Perhaps the back-end may be Azure Pipelines)

**Comment by jeddy3** [comment]
> Recently I tried GitHub Actions. Very fast.

That's good to hear!

> But I feel Travis is easier than GitHub Actions for the YAML settings.

I believe GitHub Actions now use YAML. From the [blog post](https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/) mentioned [above](https://github.com/stylelint/stylelint/issues/4273#issue-491732753), this is all we need to test stylelint on 3 node version across 3 operating systems:

```yaml
jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [8, 10, 12]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    
    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
```
