### ISSUE TITLE
add limit for  selector nesting length

### ISSUE THREAD

**Issue by gaollard** [stylelint/stylelint#4288]
> What is the problem you're trying to solve?

I found in some program of my team the selector nesting length is more than 5, for example:

```css
.container .box .list .item div a span {
  color: red;
}
```

it is difficult for cover the span color. the better way is split css modules like BEM. so I want to make a limit of selector nesting length. 

but there is not (or i don't find) an option to check this in stylelint.

> What solution would you like to see?

A new rule that implements the proposed check.

sorry for my poor english.
