### ISSUE TITLE
Fix unfixed errors not being reported

### ISSUE THREAD

**Issue by guchongxi** [stylelint/stylelint#4289]
> Clearly describe the bug

when I was running `stylelint '**/*.scss'`, I got code error, like this

```shell
yarn run v1.10.1
$ stylelint '**/*.scss'

style/mixins.scss
 47:5  ✖  Expected "display" to come before "color" in group "Box Model"             order/properties-order
 50:5  ✖  Expected "overflow" to come before "line-height" in group "Box Model"      order/properties-order

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

when I was running `stylelint '**/*.scss' --fix`, there is no code error

```shell
yarn run v1.10.1
$ stylelint '**/*.scss' --fix
✨  Done in 4.87s.
```

I think the error has been fixed, but I check code, the error is not be fixed and there is no report for them

> What stylelint configuration is needed to reproduce the bug?

.stylelintrc.js

```js
module.exports = {
  extends: [
    'stylelint-config-standard',
    'stylelint-config-recommended-scss',
    'stylelint-config-rational-order',
    'stylelint-prettier/recommended',
  ],
  plugins: ['stylelint-scss', 'stylelint-declaration-block-no-ignored-properties'],
  rules: {
    'plugin/declaration-block-no-ignored-properties': true,
    'unit-no-unknown': [
      true,
      {
        ignoreUnits: ['rpx'],
      },
    ],
    'selector-type-no-unknown': [
      true,
      {
        ignoreTypes: ['radio', 'ec-canvas', 'rich-text', 'dxd-icon', 'page'],
      },
    ],
    'no-empty-source': null,
  },
};
```

> Which version of stylelint are you using?

`11.0.0`

> What did you expect to happen?

report all unfixed errors.

> What actually happened (e.g. what warnings or errors did you get)?

Unfixed errors NOT be reported.

**Comment by vankop** [comment]
Thanks for report, could you provide css that you are using?

**Comment by guchongxi** [comment]
Here is my code in test.scss

```scss
@mixin text-overflow($num, $line-height: 36) {
  @if $num==1 {
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
    word-break: break-all;
  } @else {
    color: #fff;
    display: -webkit-box;
    max-height: $line-height * $num + rpx;
    line-height: $line-height + rpx;
    overflow: hidden;
    word-break: break-all;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: $num;
  }
}
```
