### ISSUE TITLE
Add config overrides option

### ISSUE THREAD

**Issue by soullivaneuh** [stylelint/stylelint#4311]
> What is the problem you're trying to solve?

We are working on a global CS tool including stylelint for both `.css` and `.scss` file (with the scss plugin).

Some CSS rules does not have to apply on `.scss` file. Please see our issue for details: https://gitlab.com/nexylan/pretty/issues/23

> What solution would you like to see?

Have the possibility to define a `overrides` section on the configuration file.

The way eslint does it seem pretty good: https://eslint.org/docs/user-guide/configuring#disabling-rules-only-for-a-group-of-files

We may do something like this:

```yaml
plugins:
  - stylelint-scss
extends:
  - stylelint-config-standard
  - stylelint-config-recommended-scss
  - stylelint-config-prettier
overrides:
  files:
    - '*.scss'
  rules:
    function-name-case: null
```

Or include the plugin on `overrides`:

```yaml
extends:
  - stylelint-config-standard
  - stylelint-config-prettier
overrides:
  files:
    - '*.scss'
  plugins:
    - stylelint-scss
  extends:
    - stylelint-config-recommended-scss
```

As `overrides` would be able to handle any config as the root one, you have a lot of possibilities.

Regards
