### ISSUE TITLE
Add value-no-empty rule

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint#4312]
> What is the problem you're trying to solve?

Lately I've been noticing on website properties without values. Browser ignores them, but it could be a possible error.

> What solution would you like to see?

 New rule to avoid missing values. The following patterns are considered violations:

```css
a {
    color: ;
}

a {
    color:;
}

a {
    color: /* comment */;
}
```

I'm not sure about the name. Should it be `value-no-empty` or `declaration-property-value-no-empty`?

I would like to implement this rule myself.
