### ISSUE TITLE
Fix false positives interpolation in function-calc-no-invalid

### ISSUE THREAD

**Issue by AlexWayfer** [stylelint/stylelint#4336]
> Clearly describe the bug

There are false positives for two complex SCSS/SASS expressions in `calc()`.

> Which rule, if any, is the bug related to?

`function-calc-no-invalid`

> What CSS is needed to reproduce the bug?

```scss
left: calc(
  -#{$li_padding} +
  #{$button_padding}#{if($button_padding == 0, 'px', '')} -
  #{$border_width}
);
```

> What stylelint configuration is needed to reproduce the bug?

e.g.

```yaml
rules:
  function-calc-no-invalid: true
```

> Which version of stylelint are you using?

`11.1.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `stylelint test.scss`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to SCSS variables, interpolation and ternary `if`.

> What did you expect to happen?

No errors to be flagged.

> What actually happened (e.g. what warnings or errors did you get)?

The following errors were flagged:

```shell
test.scss
 2:4  ✖  Expected a valid expression   function-calc-no-invalid
```
