### ISSUE TITLE
`stylelint-disable-next-line` not working for `selector-pseudo-class-blacklist`

### ISSUE THREAD

**Issue by ashfahan** [stylelint/stylelint#4368]
> Clearly describe the bug

`stylelint-disable-next-line` not ignoring `selector-pseudo-element-blacklist`

> Which rule, if any, is the bug related to?

selector-pseudo-element-blacklist

> What CSS is needed to reproduce the bug?

e.g.

```scss
button {
  color: #fff;

  // stylelint-disable-next-line selector-pseudo-element-blacklist
  &:hover {
    text-decoration: none;
  }

  &:disabled {
    pointer-events: none;
    opacity: .5;
  }
}
```

> What stylelint configuration is needed to reproduce the bug?

e.g.

```json
{
  "rules": {
    "selector-pseudo-class-blacklist": ["focus", "hover", "active", "disabled"],
  }
}
```

[Stylelint Demo](https://stylelint.io/demo#N4Igxg9gJgpiBcIBGBXALmiA7ABMAOrjpADYQBO8OAxAGb0DchhOOA9GzgM5oCeJMEgEssaALRQhXAIZIBYrDAAe44Yu6CYYTOTEAHLjBRQIYzQFsYosXOlgA1sJ4scAMngALCADcY5PC6saMrisJDk0mhC2FRY2DBMRAC+zETukjJyMFABRKx6ECLBujC+olyx8YmsrBB6dkJ8VAB0AKzVOClYSSAANCBcvKLSSggDYFxcfeDYtEIA5mMERPgg5CgCXKtUyzU4q4YC2hT6hsamYCTSkzZXDk5o2zgA2qu0EGAoW337IF6+5FWvV+diiviBvwysgEUFWAF0XF0uiAkkA) not sure if link is perm or not

> Which version of stylelint are you using?

11.1.1

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `stylelint src/**/*.scss`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to SCSS

> What did you expect to happen?

No warnings to be flagged

> What actually happened (e.g. what warnings or errors did you get)?

The following warnings were flagged:

```shell
src/test.scss
    ×  Unexpected pseudo-class "hover"    selector-pseudo-class-blacklist
```

Workaround:

`stylelint-disable selector-pseudo-element-blacklist` seems to work fine but i wanted to disabled line instead of whole file
