### ISSUE TITLE
Fix autofix combination for selector-attribute-brackets-space-inside and string-quotes

### ISSUE THREAD

**Issue by in-in** [stylelint/stylelint#4395]
> Clearly describe the bug

![193061572678088](https://user-images.githubusercontent.com/8797432/68067427-ce802f00-fd57-11e9-9c73-f3e1f698a8af.png)

The combination of the two rules completely destroys the attribute selector :scream: 
```js
"selector-attribute-brackets-space-inside": "always",
"string-quotes": "single",
```

> Which rule, if any, is the bug related to?

`selector-attribute-brackets-space-inside`
`string-quotes`

> What CSS is needed to reproduce the bug?
```css
[aria-expanded="true"] {
  display: none;
}
```

> What stylelint configuration is needed to reproduce the bug?
```js
module.exports = {
  rules: {
    "selector-attribute-brackets-space-inside": "always",
    "string-quotes": "single",
  },
}
```

> Which version of stylelint are you using?

`11.1.1`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

`npx stylelint style.css --config .stylelintrc.js --fix`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

"No"

> What did you expect to happen?

```css
[ aria-expanded='true' ] {
  display: none;
}
```

> What actually happened (e.g. what warnings or errors did you get)?

```css
[ aria-expanded'"tru'" ] {
  display: none;
}
```

PS. I think the problem is in this `string-quotes` rule. Because it can' t fix this `[ aria-expanded="true" ]` selector, but it breaks it.
