### ISSUE TITLE
Got stylelint error with rule "property-no-unknown"

### ISSUE THREAD

**Issue by laozhu** [stylelint/stylelint#4403]
## Environment

- Visual Studio Code
- Stylelint plugin
- Stylelint 11.1.1

## CSS modules test case

```css
@value colors: './colors.css';
@value primary, secondary from colors;

.base {
  color: primary;
  content: 'base';
}

.composed {
  composes: base;
}

.composedWith {
  compose-with: base;
}

.flexible {
  composes: flex from './utils.css';
  flex-direction: column;
}

:global(.js) .progressive {
  display: block;
}

:export {
  white: #111;
  black: #000;
}
```

## Stylelint config

```javascript
module.exports = {
  defaultSeverity: 'error',
  extends: [
    'stylelint-config-standard',
  ],
  rules: {
    'selector-pseudo-class-no-unknown': [
      true,
      {
        ignorePseudoClasses: ['export', 'import', 'global', 'local', 'external'],
      },
    ],
    'at-rule-no-unknown': [
      true,
      {
        ignoreAtRules: ['value'],
      },
    ],
    'property-no-unknown': [
      true,
      {
        ignoreProperties: ['composes', 'compose-with'],
        ignoreSelectors: [':export', /^:import/],
      },
    ],
  },
};
```

## Stylelint error message

![image](https://user-images.githubusercontent.com/1212457/68524098-67392080-02fd-11ea-8b3d-4f9546e05c9b.png)

```
stylelint: Invalid option name "ignoreSelectors" for rule "property-no-unknown"
```

## Rule "property-no-unknown" docs

<https://stylelint.io/user-guide/rules/property-no-unknown>
