### ISSUE TITLE
stylelint-disable not working. Errors still showing in reports.

### ISSUE THREAD

**Issue by TidyLuke** [stylelint/stylelint#4430]
> Clearly describe the bug

I've placed `/* stylelint-disable */` and `/* stylelint-enable */` around a block of styles, the errors however are still showing in my reports. This is the same if I try to ignore a single line or a block of styles.

> Which rule, if any, is the bug related to?

The rule I'm trying to disable is `declaration-no-important` but it's not working when making generic disable calls either.

> What CSS is needed to reproduce the bug?

```css
// The block that I'm trying to ignore
@media (prefers-reduced-motion: reduce) {
	*, *:before, *:after {
		animation-duration: .001s !important;
		transition-duration: .001s !important;
	}
}

// What I've tried
@media (prefers-reduced-motion: reduce) {
	*, *:before, *:after {
		/* stylelint-disable declaration-no-important */
		animation-duration: .001s !important;
		transition-duration: .001s !important;
		/* stylelint-enable */
	}
}

@media (prefers-reduced-motion: reduce) {
	*, *:before, *:after {
		/* stylelint-disable */
		animation-duration: .001s !important;
		transition-duration: .001s !important;
		/* stylelint-enable */
	}
}

@media (prefers-reduced-motion: reduce) {
	*, *:before, *:after {
		animation-duration: .001s !important; /* stylelint-disable-line */
		transition-duration: .001s !important; /* stylelint-disable-line */
	}
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
      "declaration-no-important": true
  }
}
```

> Which version of stylelint are you using?

`12.0.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

gulp-stylelint

Options for gulp-stylelint:

```javasrcipt
styleLint({
	failAfterError: task.isDist,
	reporters: [{ formatter: 'verbose', console: true }],
	debug: true,
	fix: true,
})
```

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

SCSS

> What did you expect to happen?

No warnings to be flagged

> What actually happened (e.g. what warnings or errors did you get)?

The following warnings were flagged:

```shell
/assets/scss/base/general.scss
 72:31  ✖  Unexpected !important   declaration-no-important
 73:32  ✖  Unexpected !important   declaration-no-important

1 source checked
/assets/scss/base/general.scss

2 problems found
 severity level "error": 2
  declaration-no-important: 2
```
