### ISSUE TITLE
Auto fix doesn't works on less files when there are syntax errors

### ISSUE THREAD

**Issue by clyfish** [stylelint/stylelint#4452]
> Clearly describe the bug

Auto fix doesn't works on less files when there are syntax errors

> Which rule, if any, is the bug related to?

All Autofixable rules
e.g. `indentation`

> What CSS is needed to reproduce the bug?

filename: `a.css`
```css
a {
width: 100px;
}
```

filename: `a.less`
```css
a {
width: 100px;
}
```

filename: `b.css`
```css
a {
width: 100px;
}
a
```

filename: `b.less`
```css
a {
width: 100px;
}
a
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "indentation": 2
  }
}
```

> Which version of stylelint are you using?

`11.1.1`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `npx stylelint a.css a.less b.css b.less --fix`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Perhaps no

> What did you expect to happen?

All 4 files get formatted.

> What actually happened (e.g. what warnings or errors did you get)?

`b.less` is not modified, with output:
```
b.less
 4:1  ✖  Unknown word   CssSyntaxError
```
