### ISSUE TITLE
Add option to ignore first-nested to comment-empty-line-before

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#455]
I'd like this so that the following works:

```css
.foo {
  /* something something */
  color: pink;
}
```
