### ISSUE TITLE
`/* stylelint-disable */` comment not working

### ISSUE THREAD

**Issue by MadLittleMods** [stylelint/stylelint#456]
The `/* stylelint-disable */`  [inline comment rule disabling](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#turning-rules-on-and-off) seem to not be applying with `stylelint@2.0.0`

The following will still throw `value-list-comma-space-after` errors:

```css
.foo {
  /* stylelint-disable value-list-comma-space-after */
  foo: bar,baz,qux;
  /* stylelint-enable */
}
```
