### ISSUE TITLE
Fix autofix for comments within value lists in indentation

### ISSUE THREAD

**Issue by jdelStrother** [stylelint/stylelint#4620]
> Clearly describe the bug

The indentation rule seems to mangle font-face declarations in unexpected ways with `--fix`

> Which rule, if any, is the bug related to?

`indentation`

> What code is needed to reproduce the bug?

```css
@font-face {
  font-family: 'Lato';
  font-style: normal;
  font-weight: 400;
  src:
       url('/lato-v11-latin-regular.woff2') format('woff2'), /* Chrome 26+, Opera 23+ */
       url('/lato-v11-latin-regular.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}
```

> What stylelint configuration is needed to reproduce the bug?

e.g.

```json
{
  "rules": {
    "indentation": 2
  }
}
```

> Which version of stylelint are you using?

`13.2.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `yarn run stylelint --fix foo.css`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No

> What did you expect to happen?

It changes foo.css to something like:

```css
@font-face {
  font-family: 'Lato';
  font-style: normal;
  font-weight: 400;
  src:
     url('lato-v11-latin-regular.woff2') format('woff2'), /* Chrome 26+, Opera 23+ */
     url('lato-v11-latin-regular.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}
```

> What actually happened (e.g. what warnings or errors did you get)?

It changes foo.css to:

```css
@font-face {
  font-family: 'Lato';
  font-style: normal;
  font-weight: 400;
  src:
    url('/lato-v11-latin-regular.woff2') format('woff2'),
       url('/lato-v11-latin    r.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}
```

Before & after:
```diff
--- a/src.css
+++ b/foo.css
@@ -3,7 +3,7 @@
   font-style: normal;
   font-weight: 400;
   src:
-       url('/lato-v11-latin-regular.woff2') format('woff2'), /* Chrome 26+, Opera 23+ */
-       url('/lato-v11-latin-regular.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
+    url('/lato-v11-latin-regular.woff2') format('woff2'),
+       url('/lato-v11-latin    r.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
 }
```

Note the missing first comment, and the random whitespace inserted into the second url.

I _think_  the bug is triggered due to the first comment being in the middle of the `src` definition.  At least, if I remove the first comment, --fix behaves as expected.
