### ISSUE TITLE
Add ignoreSelectors: [] to block-opening-brace-space-before

### ISSUE THREAD

**Issue by charlessuh** [stylelint/stylelint#4624]
> What is the problem you're trying to solve?

I'm running into CSS where developers use more than a single space before an opening brace in some situations, such as the following keyframe example with `0%`, `50%`, and `100%`, to make the code easier to read:

```css
@keyframes example {
	0%   { transform: none; }
	50%  { transform: rotate(45deg); }
	100% { transform: rotate(90deg); }
}
```

> What solution would you like to see?

An `ignoreSelectors` option (similar to how other rules have this secondary option) for the `block-opening-brace-space-before` rule, which would let me exclude selectors that contain `%`, for example.

Note that the rule currently has an `ignoreAtRules` option, which is only concerned about the opening brace of the block, not of any nested rules inside of them.

**Comment by jeddy3** [comment]
@charlessuh Thanks for the clearly written request and for using the template.

I agree that it's a valid use case and there's a precedent for an `ignoreSelectors: []` secondary option. 

I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to add a new option](https://stylelint.io/developer-guide/rules#add-an-option-to-a-rule) in the Developer guide.

---

If you use this option, nothing is stopping your developers from misaligning the values. For example:

```css
@keyframes example {
	0%   { transform: none; }
	50%            { transform: rotate(45deg); }
	100% { transform: rotate(90deg); }
}
```

You can, however, [write a plugin](https://stylelint.io/developer-guide/plugins) to enforce alignment. There was a discussion about it in https://github.com/stylelint/stylelint/issues/769. I suggest making the plugin configurable so that users can target specific selectors and conflicts with `block-opening-brace-space-before` avoided.
