### ISSUE TITLE
no-descending-specificity with "empty" definition

### ISSUE THREAD

**Issue by bkdotcom** [stylelint/stylelint#4637]
# Clearly describe the bug

"false-positive" with "empty" definitions  (see below)

# Which rule, if any, is the bug related to?

no-descending-specificity

# What code is needed to reproduce the bug?

```css
    nav {
      display: inline-block;
      a {
        display: inline-block;
      }
    }

    a,
    button,
    label {
      &:focus,
      &:hover {
        color: #333;
        text-decoration: none;
      }
    }
```

results in 
`Expected selector "a" to come before selector "nav a"`
(there is no "a" selector... only a:focus & a:hover)!

swapping to 
```css
    a,
    button,
    label {
      &:focus,
      &:hover {
        color: #333;
        text-decoration: none;
      }
    }

    nav {
      display: inline-block;
      a {
        display: inline-block;
      }
    }
```
results in 
`Expected selector "nav a" to come before selector "a:focus"`

# What stylelint configuration is needed to reproduce the bug?

"default"

```json
{
  "extends": "stylelint-config-standard",
  "rules": {
    "rule-empty-line-before": null,
	"at-rule-no-unknown": [ true, {
      "ignoreAtRules": ["extend", "at-root", "debug", "warn", "error", "if", "else", "for", "each", "while", "mixin", "include", "content", "return", "function"]
    }]
  }
}
```

# Which version of stylelint are you using?

`13.2.0`

# How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `npx stylelint ./scss`

# Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

¯\\\_(ツ)_/¯
Yes, it's related to SCSS nested properties?

# What did you expect to happen?

No warnings to be flagged.

# What actually happened (e.g. what warnings or errors did you get)?

```shell
Expected selector "a" to come before selector "nav a"`
```
(there is no "a" selector... only a:focus & a:hover)!
