### ISSUE TITLE
Add hue-degree-notation

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#4721]
> What is the problem you're trying to solve?

I'd like to enforce a consistent hue notation.

From https://github.com/stylelint/stylelint/issues/4718#issuecomment-619336037:

"- consider being opinionated about using the `deg` suffix where applicable, e.g. in the first parameter for `hsl()` and the last non-alpha parameter for `lch()`. Again, because this clarifies that the range lies between `0-360`."

References:

- [Spec](https://www.w3.org/TR/css-color-4/#typedef-hue)
- [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#HSL_colors)

> What solution would you like to see?

A new rule that lets me enforce either a `<number>` or `<angle>` notation for `<hue>`.

Primary option: `string: "number"|"angle"`

With `"number"` the following are valid:

```css
a { 
  color: hsl(198 28% 50%);
  color: lch(56.29% 19.86 236.62 / 50%);
  ..
}
```

With `"angle"` the following are valid:

```css
a { 
  color: hsl(198deg 28% 50%);
  color: lch(56.29% 19.86 1turn / 50%);
  hsl(4.71239rad, 60%, 70%);
  ..
}
```

I can, if desired, enforce the [type of angle](https://www.w3.org/TR/css3-values/#angle-value) using [`unit-whitelist`](https://stylelint.io/user-guide/rules/unit-whitelist).

Any thoughts about the use case, name or options?
