### ISSUE TITLE
Add blank line after declaration but before nested rule.

### ISSUE THREAD

**Issue by AlexanderKositsyn** [stylelint/stylelint#4722]
Does stylelint has a rule for "empty line after declaration"?

```less
// The following patterns are considered violations:
.class-1 {
    margin-bottom: 0;
    display: flex;
    .class-2 {

    }
}

// The following patterns are not considered violations:
.class-12 {
    margin-bottom: 0;
    display: flex;

    .class-2 {

    }
}
```
If it not implemented do you think it would be right rule for better understanding style code?
