### ISSUE TITLE
Autofix not working for color-hex-case

### ISSUE THREAD

**Issue by hornta** [stylelint/stylelint#4736]
> Clearly describe the bug

color-hex-case are not autofixed

> Which rule, if any, is the bug related to?

color-hex-case

> What code is needed to reproduce the bug?

e.g.

```css
.foo {
  color: #F6FAF9;
}
```

> What stylelint configuration is needed to reproduce the bug?

e.g.

```json
{
  "rules": {
    "color-hex-case": "lower"
  }
}
```

> Which version of stylelint are you using?

13.3.3

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `npx stylelint "**/*.less" --fix
> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No

> What did you expect to happen?

The fix should be applied.

> What actually happened (e.g. what warnings or errors did you get)?

The fix wasn't applied.

```shell
test.css
2:10    Expected "#F6FAF9" to be "#f6faf9"
```

**Comment by jeddy3** [comment]
@hornta Thanks for the report and for using the template.

I wasn't able to reproduce this locally.

```less
// fix.less
.foo {
  color: #F6FAF9;
}
```

With:

```console
npx stylelint "**/*.less" --fix
```

Becomes:

```less
// fix.less
.foo {
  color: #f6faf9;
}
```

Feel free to reopen this issue with a minimum reproducible repo.
