### ISSUE TITLE
Autofix not working for rule-empty-line-before

### ISSUE THREAD

**Issue by hornta** [stylelint/stylelint#4737]
The autofix isn't working for rule-empty-line-before when used in nested LESS rules.

> Which rule, if any, is the bug related to?

rule-empty-line-before

> What code is needed to reproduce the bug?

e.g.

```css
.foo {
  color: blue;
  button {
    color: red;
  }
}
```

> What stylelint configuration is needed to reproduce the bug?

e.g.

```json
{
  "rules": {
    "rule-empty-line-before": [ "always-multi-line", {
      except: ["first-nested"],
      ignore: ["after-comment"],
    } ]
  }
}
```

> Which version of stylelint are you using?

13.3.3

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `npx stylelint "**/*.less" --fix`"

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to LESS nested rules.

> What did you expect to happen?

The autofix to have been applied to my code.

> What actually happened (e.g. what warnings or errors did you get)?

The autofix wasn't applied.

```shell
test.css
3:3   Expected empty line before rule (rule-empty-line-before)
```

**Comment by jeddy3** [comment]
@hornta Thanks for using the template.

I can't reproduce this locally:

```less
.foo {
  color: blue;
  button {
    color: red;
  }
}
```

Is autofixed to:

```less
.foo {
  color: blue;

  button {
    color: red;
  }
}
```

You can reopen with a reproducible repo. See https://github.com/stylelint/stylelint/issues/4735 and https://github.com/stylelint/stylelint/issues/4735.
