### ISSUE TITLE
Fix CssSyntaxError for escaped mixin name

### ISSUE THREAD

**Issue by keith0305** [stylelint/stylelint#4740]
> Clearly describe the bug

Stylelint is not able to recognize escaped mixin name - when \ occurs right after . (dot).

> Which rule, if any, is the bug related to?

`CssSyntaxError`

> What code is needed to reproduce the bug?
```less
.test-mixin() {
	padding-top: 1rem;
}

// totally valid mixin in LESS.
.test-\!mixin2() {
	padding-bottom: 1rem;
}

// also a totally valid mixin.
.\!test-mixin3() {
	padding-right: 1rem;
}

.btn-primary {
	.test-mixin();
	.test-\!mixin2(); // 👌 no issue
	.\!test-mixin3(); // CssSyntaxError here
}
```

> What stylelint configuration is needed to reproduce the bug?

Any rules

> Which version of stylelint are you using?

`13.3.3`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

Node.js API with gulp

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's a LESS-specific syntax.

> What did you expect to happen?

Stylelint able to parse the LESS file.

> What actually happened (e.g. what warnings or errors did you get)?

The following warnings were flagged:

```shell
 18:2  ×  At-rule without name   CssSyntaxError
```
