### ISSUE TITLE
False positive: function-calc-no-invalid

### ISSUE THREAD

**Issue by hornta** [stylelint/stylelint#4741]
> Clearly describe the bug

There are false positives for when using less variables like in my code example.

> Which rule, if any, is the bug related to?

function-calc-no-invalid

> What code is needed to reproduce the bug?

e.g.

```css
a {
  font-size: calc(100vh - (@gaming-responsibility-height + @casino-navbar-h + @header-height-desktop + @casino-titlebar-h));
}
```

> What stylelint configuration is needed to reproduce the bug?

e.g.

```json
{
  "rules": {
    "function-calc-no-invalid": true
  }
}
```

> Which version of stylelint are you using?

13.3.3

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `stylelint "**/*.less"`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

It's related to less syntax.

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors did you get)?

The following warnings were flagged:

```shell
Expected space after "-" operator (function-calc-no-invalid)
Expected space before "-" operator (function-calc-no-invalid)
Expected space after "-" operator (function-calc-no-invalid)
Expected space before "-" operator (function-calc-no-invalid)
```
