### ISSUE TITLE
Fix autofix for values containing comments in length-zero-no-unit

### ISSUE THREAD

**Issue by srmcconomy** [stylelint/stylelint#4754]
> Clearly describe the bug

Autofix can delete comments and produce incorrect fixes when there are infix comments (comments within the content of a property value)

> Which rule, if any, is the bug related to?

Happened for me with `length-zero-no-unit`

> What code is needed to reproduce the bug?

```css
.a {
  box-shadow: -0.25rem 0rem 0rem rgba(0, 0, 0, 0), /* comment */
    inset -0.25rem 0rem 0rem rgba(0, 0, 0, 0); /* comment */
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "length-zero-no-unit": true
  }
}
```

> Which version of stylelint are you using?

`13.3.3`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `npx stylelint test.css --fix`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No, this is plain css

> What did you expect to happen?

The css above gets fixed as
```css
.a {
  box-shadow: -0.25rem 0 0 rgba(0, 0, 0, 0), /* comment */
    inset -0.25rem 0 0 rgba(0, 0, 0, 0); /* comment */
}
```

> What actually happened (e.g. what warnings or errors did you get)?

the css gets set to
```css
.a {
  box-shadow: -0.25rem 0 0 rgba(0, 0, 0, 0),
    inset -0.25rem 0000rgba(0, 0, 0, 0); /* comment */
}
```
(note the first comment is gone, and the invalid `0000rgba` is present on the third line)
