### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by szepeviktor** [stylelint/stylelint#4771]
With basic `stylelint-config-standard"` v13.3.3

```css
.u-show\@focus: active,
.u-show\@focus: focus {
    position: static !important;
    width: auto;
    height: auto;
    overflow: visible;
    clip: auto;
    white-space: normal;
    -webkit-clip-path: none;
    clip-path: none;
}
```

```
TypeError: Cannot read property 'startsWith' of undefined
    at test.css:1:1
    at module.exports (node_modules/stylelint/lib/utils/isStandardSyntaxSelector.js:18:15)
    at module.exports (node_modules/stylelint/lib/utils/isStandardSyntaxRule.js:17:7)
    at node_modules/stylelint/lib/rules/selector-pseudo-class-no-unknown/index.js:123:10
    at node_modules/stylelint/node_modules/postcss/lib/container.js:135:18
    at Root.each (node_modules/stylelint/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (node_modules/stylelint/node_modules/postcss/lib/container.js:131:17)
    at node_modules/stylelint/lib/rules/selector-pseudo-class-no-unknown/index.js:119:8
    at node_modules/stylelint/lib/lintSource.js:214:8
    at Array.map (<anonymous>)
    at node_modules/stylelint/lib/lintSource.js:206:18
```
