### ISSUE TITLE
Fix false negatives for consecutive space for single-line comments in comment-whitespace-inside

### ISSUE THREAD

**Issue by ThiefMaster** [stylelint/stylelint#4776]
> What is the problem you're trying to solve?

My codebase as messy comments like this in some files:

```css
/*
        Default Styles and layout for Conf-pages
        Do not custom this CSS
    */

/*     ------Wrapper------ */

/*     this is the wrapper of whole conference page */

.conf {
  width: 100%;
  border: none;
  margin: 0;
}

/*
    Header
*/
```

> What solution would you like to see?

I would like to have a rule that fixes it like this:

```css
/*
Default Styles and layout for Conf-pages
Do not custom this CSS
*/

/* ------Wrapper------ */

/* this is the wrapper of whole conference page */

.conf {
  width: 100%;
  border: none;
  margin: 0;
}

/*
Header
*/
```

Here are some smaller examples of what should be valid/invalid:

```css
/* valid */

/*
also
valid
*/

/*invalid*/
/*        invalid */

/*
  invalid
  more
  text
*/
```

An edge case is a multiline comment that only consists of a single line. This could be converted to single-line.

I think this behavior could be added to `comment-whitespace-inside` since it is not very useful right now anyway (`never` results in awful style, `always` allows lots of weird consecutive whitespace)
