### ISSUE TITLE
Fix TypeError: Cannot read property 'length' of undefined in time-min-milliseconds 

### ISSUE THREAD

**Issue by klimashkin** [stylelint/stylelint#4782]
After upgrading from 13.2.0 to 13.4.0 I've started getting following errors:

1. **Animation**
```css
.progressStop {
  animation: none;
}
```
Throws error
<img width="343" alt="Screen Shot 2020-05-17 at 2 37 27 AM" src="https://user-images.githubusercontent.com/576077/82140946-5bb43e00-97e7-11ea-84b1-56bf155a7abb.png">
Changing it to 
```css
.progressStop {
  animation-name: none;
}
```
fixes the problem

2. **Transition**
This code
```css
.progressTo100Only {
  transition: opacity var(--button-progress-fadeout-duration) var(--button-progress-fadeout-delayTo100Only) ease-out;
}
``` 
make stylelint fail with 
<img width="864" alt="Screen Shot 2020-05-17 at 2 36 30 AM" src="https://user-images.githubusercontent.com/576077/82140927-39babb80-97e7-11ea-8eda-12afe6cdeab1.png">
Could not find a workaround
