### ISSUE TITLE
Fix error message for alpha-value-notation

### ISSUE THREAD

**Issue by icleolion** [stylelint/stylelint#4792]
> Clearly describe the bug
For whatever reason the error message for alpha-value-notation rule when set to `percentage` incorrectly expects 0.14 to be 14.000000000000002%.

> Which rule, if any, is the bug related to?
alpha-value-notation set to `percentage`

> What code is needed to reproduce the bug?
```css
.testclass {
	box-shadow: 0 3px 3px -2px rgba(0, 0, 0, 0.2), 0 3px 4px 0 rgba(0, 0, 0, 0.14), 0 1px 8px 0 rgba(0, 0, 0, 0.12) !important;
}
```

> What stylelint configuration is needed to reproduce the bug?
```json
module.exports = {
	extends: `stylelint-config-standard`,
	rules: {
		'alpha-value-notation': `percentage`,
	},
}
```

> Which version of stylelint are you using?
13.5.0

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?
CLI with `stylelint  **/*.vue **/*.css` and the stylelint v0.84.0 VS Code extension 

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?
standard css

> What did you expect to happen?
Error message to state "expects 0.14 to be 14%".

> What actually happened (e.g. what warnings or errors did you get)?
![image](https://user-images.githubusercontent.com/47498402/82380452-61e12f00-9a20-11ea-8df5-f57125c92d46.png)

As you can see on the same line it's managed to convert the other numbers to percentages, it's only 0.14 that's wrong throughout my whole codebase.
