### ISSUE TITLE
Add ignoreSelectors: [] to max-nesting-depth

### ISSUE THREAD

**Issue by emattias** [stylelint/stylelint#4805]
I need an option in `max-nesting-depth` to allow nesting for certain attributes (either specified specifically or with regex). 

Here's an example of what I am talking about:

```scss
.foo {
  &[disabled] { // <- I want to allow this
    opacity: 0.4;
  }
  &.bar { // <- but disallow this.
    color: red;
  }
}
```
