### ISSUE TITLE
declaration-colon-space "-after and -before" could not be found!

### ISSUE THREAD

**Issue by davincif** [stylelint/stylelint#4813]
> Clearly describe the bug
 
When running npx sass-lint --verbose says: Rule `declaration-colon-space-before` could not be found!

> Which rule, if any, is the bug related to?

```declaration-colon-space-afert```
```declaration-colon-space-before```

> What code is needed to reproduce the bug?

I've being trying to make the AirBnB css style guide to workout with stylelint, but it has been very difficult for the lack of legacy maintainability, so I've being surching in the docs how to "translate" what the old sass-lint file of them do to the new specs. But this property in particular is in the docs' rule list but it throws me this error.

so just run ```npx sass-lint --verbose``` against any css file.

> What stylelint configuration is needed to reproduce the bug?

```yml
files:
  include:
  - 'src/index.css'
  - 'src/**/*.css'
  - 'public/**/*.css'
  ignore:
  - './src/assets/**'
  - './node_modules/**'
  - './docs/**'
  - './trash/**'

# add found here: https://gist.github.com/DanielaValero/b3a72b2f3d0c85c1985d5d2d7497f347
plugins:
- stylelint-order
- stylelint-scss
- stylelint-selector-bem-pattern
- stylelint-declaration-use-variable
rules:
  selector-max-id: 0
  indentation: 2
  declaration-colon-space-after: always
  declaration-colon-space-before: never
  block-opening-brace-space-before: always
  declaration-block-single-line-max-declarations: 1
  rule-nested-empty-line-before:
  - always
  - ignore:
    - after-comment
  rule-non-nested-empty-line-before:
  - always
  - ignore:
    - after-comment
  comment-empty-line-before:
  - always
  - ignore:
    - stylelint-commands
  plugin/selector-bem-pattern:
    componentName: "[A-Z]+"
    componentSelectors:
      initial: "^\\\\.{componentName}(?:-[a-z]+)?$"
      combined: "^\\\\.combined-{componentName}-[a-z]+$"
    utilitySelectors: "^\\\\.util-[a-z]+$"
  declaration-property-value-blacklist:
    "/^border/":
    - none
  at-rule-blacklist:
  - extend
  max-nesting-depth: 3
  declaration-no-important: true
  selector-max-compound-selectors: 3
  selector-no-qualifying-type: true
  no-duplicate-selectors: true
  block-no-empty: true
  at-rule-empty-line-before:
  - always
  - ignoreAtRules:
    - import
    - first-nested
  at-rule-name-case: lower
  color-hex-case: lower
  color-hex-length: long
  color-no-invalid-hex: true
  no-indistinguishable-colors: true
  string-quotes: single
  value-no-vendor-prefix: true
  value-list-comma-newline-after: always
  value-list-comma-space-after: always-single-line
  shorthand-property-no-redundant-values: true
  comment-whitespace-inside: always
  function-comma-space-after: always-single-line
  function-comma-space-before: never
  length-zero-no-unit: true
  number-no-trailing-zeros: true
  declaration-block-trailing-semicolon: always
  declaration-block-no-duplicate-properties: true
  declaration-block-no-ignored-properties: true
  stylelint-disable-reason: always-after
  scss/selector-no-redundant-nesting-selector: true
```

> Which version of stylelint are you using?

`1.13.1`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

were installed and present in the configuration file:
```
stylelint-order
stylelint-scss
stylelint-selector-bem-pattern
stylelint-declaration-use-variable
```

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

no

> What did you expect to happen?

not given the error

> What actually happened (e.g. what warnings or errors did you get)?

the msg: Rule `declaration-colon-space-before` could not be found!

I'm really sorry if all this is a silly question and I'm missing something obvius, but I've being stuck in things like this for a while now, and even it do is a dump question I would like to know it so I can move on.

Many Thanks, Leonardo Da Vinci.
