### ISSUE TITLE
Add ignoreComments: [] to comment-empty-line-before

### ISSUE THREAD

**Issue by dobogo** [stylelint/stylelint#4814]
> What is the problem you're trying to solve?

I use PurgeCSS and its special comment to whitelist some rules from it.
https://purgecss.com/whitelisting.html#in-the-css-directly

I've got an unwanted error when I use `comment-empty-line-before`:

```css
/* purgecss start ignore */
.special-rule {
    color: red;
}
/* purgecss end ignore */
/* ↑ Expected empty line before comment   comment-empty-line-before */
```

Rule used here:
```json
{
    "comment-empty-line-before": ["always", {
        "except": ["first-nested"],
        "ignore": ["after-comment", "stylelint-commands"]
    }]
}
```

> What solution would you like to see?

`ignorePattern` option that specify regex matching comments to be ignored.

Example:
```json
{
    "comment-empty-line-before": ["always", {
        "except": ["first-nested"],
        "ignore": ["after-comment", "stylelint-commands"],
        "ignorePattern": "^\\s*purgecss"
    }]
}
```
