### ISSUE TITLE
Add support for descriptions in stylelint command comments

### ISSUE THREAD

**Issue by glen-84** [stylelint/stylelint#4840]
> What is the problem you're trying to solve?

Describing/justifying disable directives, so that they aren't used unless necessary, and other developers know why they were used.

> What solution would you like to see?

See the equivalent in ESLint:
- https://github.com/eslint/rfcs/pull/33
- https://github.com/eslint/eslint/issues/11806
- https://github.com/eslint/eslint/pull/12699

Example:

```scss
a {
    // stylelint-disable-next-line declaration-no-important -- A really good reason here.
    color: red !important;
}
```
