### ISSUE TITLE
Running stylelint via NPM script does not lint all files

### ISSUE THREAD

**Issue by Merott** [stylelint/stylelint#4846]
**Here's a small demo repository for this issue: https://github.com/Merott/stylelint-test**

> Clearly describe the bug

When running stylelint via an NPM script, some CSS files aren't linted. The same files _are_ linted when running `stylelint` directly.

> Which rule, if any, is the bug related to?

N/A

> What code is needed to reproduce the bug?

Check the demo repo: https://github.com/Merott/stylelint-test

The code doesn't seem to matter, but here's an example:

```css
.box {

  transform: translateX(-100%);
  background-image: linear-gradient(
    90deg,
    rgba(255, 255, 255, 0) 0,
    rgba(255, 255, 255, 0.3333) 30%,
    rgba(255, 255, 255, 0.6666) 70%,
    rgba(255, 255, 255, 0)
  );
}
```

> What stylelint configuration is needed to reproduce the bug?

```js
{
  extends: ['stylelint-config-standard'],
}
```

> Which version of stylelint are you using?

`13.6.1`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `stylelint **/*.css`, and `npm run lint`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No

> What did you expect to happen?

See the same errors when running `stylelint` directly or via NPM script

> What actually happened?

Here's the result running `./node_modules/.bin/stylelint **/*.css`:

```
src/nested/styles-nested.css
3:3   ✖  Unexpected empty line before declaration                   declaration-empty-line-before
4:19  ✖  Expected newline after ":" with a multi-line declaration   declaration-colon-newline-after

src/styles.css
3:3   ✖  Unexpected empty line before declaration                   declaration-empty-line-before
4:19  ✖  Expected newline after ":" with a multi-line declaration   declaration-colon-newline-after

styles-top.css
3:3   ✖  Unexpected empty line before declaration                   declaration-empty-line-before
4:19  ✖  Expected newline after ":" with a multi-line declaration   declaration-colon-newline-after
```

But, when run via `npm run lint`:

```
src/styles.css
3:3   ✖  Unexpected empty line before declaration                   declaration-empty-line-before
4:19  ✖  Expected newline after ":" with a multi-line declaration   declaration-colon-newline-after
```
