### ISSUE TITLE
Fix false positives for maps in value-keyword-case

### ISSUE THREAD

**Issue by MrVladevoit** [stylelint/stylelint#4882]
> Clearly describe the bug

Rule value-keyword-case highlight syntax inside [LESS lookups](http://lesscss.org/features/#maps-feature-using-variable-variables-in-lookups) in [LESS maps](http://lesscss.org/features/#maps-feature). 

> Which rule, if any, is the bug related to?

value-keyword-case

> What code is needed to reproduce the bug?

e.g.

```LESS
@map: {
  key: valueName1 valueName2;
}
```

> What stylelint configuration is needed to reproduce the bug?

e.g.

```json
{
  "rules": {
    "value-keyword-case": "lower",
  }
}
```

> Which version of stylelint are you using?

13.6.1

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

"Webstorm plugin"

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

"Yes, it's related to LESS maps."

> What did you expect to happen?

"No warnings inside LESS maps syntaxes."

> What actually happened (e.g. what warnings or errors did you get)?

 Expected "valueName1" to be valuename1

**Comment by malsf21** [comment]
Hi @MrVladevoit,

Thank you for using the issue template! I can the behaviour that you listed [with this demo](https://stylelint.io/demo#N4Igxg9gJgpiBcIACBbAhgB3gAmAHQDttsBrGATxwDc0AbAVxgDk0UYBGbGh51mAJgDchAL4gANCADO5AgBc0ADwQhaMKVIngIBAGYBLAOYr8RbHhAAnemqkWcp4sQvdGAWjLkA7hEtQ3YGhSMPbmqhBeMJYWhMQioiAiQA).

However, I believe the rule is working as intended. [As this entry in the docs says](https://stylelint.io/user-guide/rules/value-keyword-case),

> Keyword values which are paired with non-properties (e.g. `$vars` and custom properties), and do not conform to the primary option, can be ignored using the `ignoreKeywords: []` secondary option.

And in this case, `key` is a custom property to LESS, with an infinite set of keyword values. If you know you will only use a certain set of variables, you could use `ignoreKeywords: []` on that set of variables.

If you would like instead, you could also use [`ignoreProperties: []`](https://stylelint.io/user-guide/rules/value-keyword-case#ignoreproperties-regex-regex-non-regex) option on `value-keyword-case` and select `key` as one of your properties; that should resolve the problem.

That being said, there may be something that we can do to resolve this issue and make it more convenient for LESS developers. I'll tag this as needs discussion in the meantime, but let me know if the comments made sense!

**Comment by MrVladevoit** [comment]
@malsf21 , thanks for your answer ! 

The LESS lookups it's not a keywords or CSS values. I don't understand why i must add this values to ignoreKeywords: []. 

If i write lookups outside of LESS maps stylelint will not to warning me.

```less 
@set: blueColor greenColor redColor;

each(@set{
   .color2--@{value} {
     color: @@value;
     }
});
```

But if i write lookups inside LESS maps it will be error: 

```less
@blueColor: blue;
@greenColor: green;
@redColor: red;
@yellowColor: yellow;
@orangeColor: orange;
@blackColor: black;
@whiteColor: white;

@set: {
  one: blueColor greenColor redColor;
  two: yellowColor orangeColor;
  three: whiteColor blackColor;
}

each(@set[one]{
   .color--@{value} {
     color: @@value;
     }
  });
```

See [demo](https://stylelint.io/demo#N4Igxg9gJgpiBcIACAjANgVxgYQmiATvAATpYDcAOgHZIDmBMM1u+RxDT1VtjUrhEnx5IAnjDT4A7gPbjJEKSMIBDanRx5BxVepgj0KsAGtZJQyZFSAFgEsALprYkbD-TRpIAzjHslgNMQ61DDmmE6EHIzMssR8sjxB9lIQJPLSsboaCYHE9tbRLnaOsRamWgQ8AL65nj72AExhWLGcMRVxMPwVPIEwRtYAFN6+ANoQIQC6AdRBxAB0kGwAtMtIwABuKuFVxDNzQUvaSEhb4YkHNbPEVQCUvbP9YEMjjftBixUNq+tnWLvvOZHdgnP7ua5zK5BO6JEAAGhAXlE1HsKgAHggQGgYF4vPDwBMAGa2OiY96UEAEDDYrwU-y5IIUsHLYwwUQpAhQZZgFQ+OnECnSGAECm5K5VEBVIA)

I think that stylelint cannot parse LESS maps correctly.
