### ISSUE TITLE
selector-no-type rule doesn't exclude the nesting selector (&)

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#499]
Ref: https://github.com/stylelint/stylelint/issues/489#issuecomment-155576063

> What about nesting and [type selection](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#selector)? This is currently considered an error if `selector-no-type` is turned on and you are nesting per the spec:

```css
.foo {
    color: orange;

    & [class*=bar] {
        color: blue
    }
}
```

> **Edit:** in this instance `postcss-selector-parser` considers the `&` a tag.

Pinging @ben-eb. Is the _nesting selector_ a selector you'd consider parsing for? If so, I'll create an issue in `postcss-selector-parser`. Otherwise, we'll handle it at our end.
