### ISSUE TITLE
How to bug fix `no-descending-specificity`?

### ISSUE THREAD

**Issue by andrejsharapov** [stylelint/stylelint#4993]
package.json

```js
    "@nuxtjs/stylelint-module": "^4.0.0",

    "stylelint-config-prettier": "^8.0.2",
    "stylelint-config-standard": "^20.0.0",

    "stylelint": "^13.7.2",
```

stylelint.config.js
```js
module.exports = {
  extends: ['stylelint-config-standard', 'stylelint-config-prettier'],
  rules: {
    'no-empty-source': true,
    'at-rule-no-unknown': [
      true,
      {
        ignoreAtRules: [
          'function',
          'if',
          'for',
          'else',
          'each',
          'include',
          'mixin',
          'return',
          'extend',
        ],
      },
    ],
  },
}
```

dark.scss
The first time I use it at once in two classes, and below - only in one.
```css
  .ps {
    &__thumb {
      &-x,
      &-y {
        background-color: $dark_text;
      }
    }

    &__rail {
      &-x,
      &-y {
        border-radius: $bdrs * 2;
        background-color: $dark_bdrs;

        &:hover,
        &.ps--clicking {
          background-color: $dark_bdrs;

          .ps__thumb {
            &-x,
            &-y {
              background-color: $dark_text;
            }
          }
        }
      }

      &-y {
        width: 9px;

        &.ps--clicking,
        &:hover {
          width: 15px;
        }
      }
    }
  }
```

error message:
	`Expected selector ".theme--dark .ps__rail-y" to come before selector ".theme--dark .ps__rail-y:hover"   no-descending-specificity`
How to fix it? What should the code look like then?
