### ISSUE TITLE
Categorizing style rules with line breaks

### ISSUE THREAD

**Issue by AnatoleLucet** [stylelint/stylelint#5043]
> What is the problem you're trying to solve?

I like to split hunks of style by adding some line breaks to categorize style rules.
For example:
```css
div {
  height: 100px;
  width: 100px;

  display: flex;
  align-items: center;

  background-color: gray;
  color: black;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);

  border: 1px solid blue;
  border-radius: 20px;

  font-size: 16px;
  font-weight: 600;
}
```

It's really smooth to read.

> What solution would you like to see?

Maybe a simple rule?
