### ISSUE TITLE
Check against custom property registration

### ISSUE THREAD

**Issue by shgysk8zer0** [stylelint/stylelint#5061]
> Check custom property types against `@property` rules or custom property registration.

> What solution would you like to see?

Add a rule allowing to specify custom property registrations such that `--primary-color` must be a `"<color>"`. This rule should accept a file path accepting a CSS file containing [`@property`](https://developer.mozilla.org/en-US/docs/Web/CSS/@property) declarations or a JSON file that is compatible with [`CSS.regsiterProperty()`](https://developer.mozilla.org/en-US/docs/Web/API/CSS/RegisterProperty). It may further check that all usage of registered custom properties are used correctly, such that `height: var(--primary-color)` is invalid.

### CSS
```css
@property --primary-color {
  syntax: "<color>";
  inherits: true;
  initial-value: red;
}

/* ...*/
```

### JSON
```json
[{
  "name": "--primary-color",
  "syntax": "<color>",
  "inherits": true,
  "initial-value": "red"
}]
```
