### ISSUE TITLE
Fix false positives for :is() and :where() in *-specificity

### ISSUE THREAD

**Issue by jonathantneal** [stylelint/stylelint#5065]
I noticed a false positive error coming from a pending release of normalize that uses `:where()`.

Here is a sample of the CSS being flagged.

```css
/**
 * Remove the margin on nested lists in Chrome, Edge, and Safari.
 */

:where(dl :is(dl, ol, ul), :is(ol, ul) dl) {
  margin-block-end: 0;
  margin-block-start: 0;
}

/**
 * 1. Add the correct box sizing in Firefox.
 * 2. Correct the inheritance of border color in Firefox.
 */

:where(hr) {
  box-sizing: content-box; /* 1 */
  color: inherit; /* 2 */
  height: 0; /* 1 */
}

/**
 * 1. Correct the inheritance and scaling of font size in all browsers.
 * 2. Correct the odd `em` font sizing in all browsers.
 */

:where(pre) {
  font-family: monospace, monospace; /* 1 */
  font-size: 1em; /* 2 */
}
```

And here are the errors reported from that sample:

```
✖  Expected selector ":where(hr)" to come     no-descending-specificity
   before selector ":where(dl :is(dl, ol,
   ul), :is(ol, ul) dl)"
✖  Expected selector ":where(pre)" to come    no-descending-specificity
   before selector ":where(dl :is(dl, ol,
   ul), :is(ol, ul) dl)"
✖  Expected selector ":where(b, strong)" to   no-descending-specificity
   come before selector ":where(dl :is(dl,
   ol, ul), :is(ol, ul) dl)"
```

The `:where()` CSS pseudo-class function takes a selector list as its argument, and selects any element that can be selected by one of the selectors in that list.

This is useful for writing large selectors in a more compact form, and also for writing selectors with 0 specificity.

> Which rule, if any, is the bug related to?

```
:where()
```

> What code is needed to reproduce the bug?

☝️See the top comment.

> What stylelint configuration is needed to reproduce the bug?

e.g.

```json
{
  "extends": "stylelint-config-standard"
}
```

> Which version of stylelint are you using?

e.g. `13.8.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

```
stylelint evergreen.css
```

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No, `:switch()` ships Firefox 78, Safari 14, & Chrome 88 📌.

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors did you get)?

☝️See the top comment.

> Additional notes:

📌 _Chrome is v87 at the time of this writing. Firefox shipped v78 in June, and Safari shipped v14 in September_
