### ISSUE TITLE
Indentaion fixer fails with comment in font-face's src

### ISSUE THREAD

**Issue by szepeviktor** [stylelint/stylelint#5067]
> Clearly describe the bug

messes up URL-s, please see output below

> Which rule, if any, is the bug related to?

`indentation`

> What code is needed to reproduce the bug?

```css
/* ibm-plex-sans-regular - latin-ext_latin */
@font-face {
    font-family: 'IBM Plex Sans';
    font-style: normal;
    font-weight: 400;
    src: url('../fonts/ibm-plex-sans-v7-latin-ext_latin-regular.eot'); /* IE9 Compat Modes */
    src: local('IBM Plex Sans'), local('IBMPlexSans'),
         url('../fonts/ibm-plex-sans-v7-latin-ext_latin-regular.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
         url('../fonts/ibm-plex-sans-v7-latin-ext_latin-regular.woff2') format('woff2'), /* Super Modern Browsers */
         url('../fonts/ibm-plex-sans-v7-latin-ext_latin-regular.woff') format('woff'), /* Modern Browsers */
         url('../fonts/ibm-plex-sans-v7-latin-ext_latin-regular.ttf') format('truetype'), /* Safari, Android, iOS */
         url('../fonts/ibm-plex-sans-v7-latin-ext_latin-regular.svg#IBMPlexSans') format('svg'); /* Legacy iOS */
  }
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "indentation": 4
  }
}
```

> Which version of stylelint are you using?

13.8.0

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

`npx stylelint src/assets/scss/_fonts.scss --fix`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

no

> What did you expect to happen?

valid CSS

> What actually happened (e.g. what warnings or errors did you get)?

e.g. "The following warnings were flagged:"

```diff
+        url('../fonts/ibm-plex-sans-v7-latin-ext_latin-700.eot?#iefix') format('embedded-opentype'),
+         url(        /ibm-plex-sans-v7-latin-ext_latin-700.woff2') format('woff2'),
+         url('../fonts/ibm-plex-sans-v7-        _latin-700.woff') format('woff'),
+         url('../fonts/ibm-plex-sans-v7-latin-ext_latin-700.t        at('truetype'),
+         url('../fonts/ibm-plex-sans-v7-latin-ext_latin-700.svg#IBMPlexSans') format('s        ; /* Legacy iOS */
```

Cc @weva-io
