### ISSUE TITLE
Fix false positives for spaceless operators in unit-case

### ISSUE THREAD

**Issue by superchow** [stylelint/stylelint#5083]
> Clearly describe the bug

I want my Less variable to be itself，but it always changed to lowercase.

> Which rule, if any, is the bug related to?

 `value-keyword-case`

> What code is needed to reproduce the bug?

```css
.u-input(@lineHeight, @paddingTop, @paddingBottom) {
  height: 1px*@lineHeight;
  padding-top: 1px*@paddingTop;
  padding-bottom: 1px*@paddingBottom;
  line-height: 1px*@lineHeight;
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "value-keyword-case":  ["lower", {
      "ignoreTypes": [/@\w+/]
    }],
  }
}
```

> Which version of stylelint are you using?

`12.0.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

"CLI with `stylelint "**/*.css" --config myconfig.json`"

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

"Yes, it's related to Less nested properties."

> What did you expect to happen?

`@lineHeight` should not to be `@lineheight` In the example, after run `stylelint "**/*.css" --config myconfig.json`. How to keep it self ?
