### ISSUE TITLE
SCSS variables order

### ISSUE THREAD

**Issue by borodean** [stylelint/stylelint#518]
Since $variables are getting interpreted as properties by [postcss-scss](https://github.com/postcss/postcss-scss), stylelint takes them into account when checking for [`rule-properties-order`](http://stylelint.io/?/src/rules/rule-properties-order/README.md) rule. If you set it to `alphabetical`, stylelint complains about variables not being sorted, which makes no sense if their order is determined by the order of computations:

```scss
@mixin size($size) {
  // You don't want these variables to be automatically sorted:
  $size: unpack($size, 2);
  $important: if(length($size) == 3, !important, null);
  $width: nth($size, 1);
  $height: nth($size, 2);
  width: if($width != none, $width $important, null);
  height: if($height != none, $height $important, null);
} 
```

However, when variables are not involved in any algorythms, you *may* want them to be sorted:

```scss
.masthead {
  // These variables order doesn't matter,
  // could be automatically sorted:
  $background: #c00;
  $height: 120px;
  background: $background;
  height: $height;
  line-height: $height;

  &_inner {
    background: invert($background);
    color: $background;
  }
}
```

What do you think could be done about that?

cc @ai @ben-eb
