### ISSUE TITLE
max-nesting-depth - ignore specific pseudo classes

### ISSUE THREAD

**Issue by LukeSamkharadze** [stylelint/stylelint#5310]
> What is the problem you're trying to solve?

I want to ignore only specific pseudo classes. In Angular its very common to use `:host` pseudo class, so this always takes 1 place in calculating nested depth

> What solution would you like to see?

``` JS
rules: {
    'max-nesting-depth': [
        1,
        {
            ignoreAtRules: [':host'],
        },
    ],
},
```

**Comment by jeddy3** [comment]
@LukeSamkharadze Thanks for the request and for using the template.

The use case makes sense.

We can add an `ignorePseudoClasses: []` secondary option.

Like the [`ignore: ["pseudo-classes"]` one](https://stylelint.io/user-guide/rules/max-nesting-depth#ignore-pseudo-classes), it'll:

> Ignore rules where the __first selector in each selector list item is a pseudo-class__

Only this time the __first selector in each selector list item__ matches one of the specified pseudo-classes.

So, given:

```json
{
  "rules": {
    "max-nesting-depth": [0, {
      "ignorePseudoClasses": ["hover", "active"]
   }]
}
```

The following are valid:

```css
.a {
  &:hover {  /* ignored */
    .b { /* 1 */
      top: 0;
    }
  }
}
```

```css
.a {
  &:hover, &:active {  /* ignored */
    .b { /* 1 */
      top: 0;
    }
  }
}
```

But the following aren't:

```css
.a {
  &:visited { /* 1 */
    .b { /* 2 */
      top: 0;
    }
  }
}
```

```css
.a {
  &:hover, &:visited {  /* 1 */
    .b { /* 2 */
      top: 0;
    }
  }
}
```

I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to add a new option](https://stylelint.io/developer-guide/rules#add-an-option-to-a-rule) in the Developer guide.

Please branch off the `v14` branch to help us manage conflicts leading up to our next major release.
