### ISSUE TITLE
rule-no-duplicate-properties font-face declaration

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#533]
I get error this code:
```css
@font-face {
    font-family: "Glyphicons Halflings";
    src: url("../fonts/glyphicons-halflings-regular.eot");
    src:
        url("../fonts/glyphicons-halflings-regular.eot?#iefix") format("embedded-opentype"),
        url("../fonts/glyphicons-halflings-regular.woff2") format("woff2"),
        url("../fonts/glyphicons-halflings-regular.woff") format("woff"),
        url("../fonts/glyphicons-halflings-regular.ttf") format("truetype"),
        url("../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular") format("svg");
}
```
But it is normal add font-face to your css. Maybe add options to ignore some properties?
