### ISSUE TITLE
Fix autofix for multiline comments in no-eol-whitespace

### ISSUE THREAD

**Issue by hacknug** [stylelint/stylelint#5379]
> Clearly describe the bug

`stylelint --fix` isn't able to remove the extra space at the end of the line.

> Which rule, if any, is the bug related to?

[`no-eol-whitespace`](http://stylelint.io/user-guide/rules/no-eol-whitespace/)

> What code is needed to reproduce the bug?

```css
/**
 * 1. Make replaced elements `display: block` by default as that's
 *    the behavior you want almost all of the time. Inspired by
 *    CSS Remedy, with `svg` added as well.
 *
 *    https://github.com/mozdevs/cssremedy/issues/14
 * 
 * 2. Add `vertical-align: middle` to align replaced elements more
 *    sensibly by default when overriding `display` by adding a
 *    utility like `inline`.
 *
 *    This can trigger a poorly considered linting error in some
 *    tools but is included by design.
 * 
 *    https://github.com/jensimmons/cssremedy/issues/14#issuecomment-634934210
 */

.yolo { color: lime; }

```

> What stylelint configuration is needed to reproduce the bug?

[Stylelint Demo link](https://stylelint.io/demo/#N4Igxg9gJgpiBcID0AqFAdAdgAhdgjAHTYCyAhgNYzYBOMADgDZlgxTYyMwC2MmALgGdsAAygBLQUzIBPeNgBGjCGAojFM7LABmZAK6N+2MsP4ALMvwDkgrLmwPs56gpgWAbuIg1sMiHuwAdzIBY0ZuCEEjMkZGbAhtJzNqfnFeYgBJTClxOnYFGTs8RwBhAGUy7AAlHjYZABog8XNRQXcAc3UyKFh2EyDORkIiosdsM35+ekF4JCR25rM9BUJIbiQIgC9Yd0EkMEFBOl4oGSRJQT0YPfwAFlHRgCZiAEEe0XcYGlSwGIBaGLidqYeTccQ9LjqfgQMJAnB0aSsdicWoCYQROijRyCPiCcRKTQFLQwXQGIyBZI4CCfGg0cHiTDtUQSKTMGTqIndCSM4xYhx6VKMZqaIVUUQMoWYGAiYY4DBysYAFTMkmwvxw-Dp7XaX2M2HoEG8jE0kGy4K+bGwktSPK+NG82AZ2EEEF4fKchsYwgUAsdwgZYEYel6GmJeOBsvs7omUxmcwW5mWq1dSAAVri0hFsvtDsc6udDlcbrcAMQXK5rXgCP4ANgAzLcAJwNx74AAMRSQWCwhD8ymwwDVEGUNHkQt4AG5sABfLAgeogQQyARkAAeCHAh3n4AgmG0QI3wDs2HQIBoBmup-kR5wjlPlj+564f0wED+ekwFFfgUwV6c55gepjwcU8lBUCgXzfHh6H4QoEH-K4gNvECdxHSC-gZdxASgP5klXP9NUQ4CTx3bgq34dDoNggiAKQsZT1gQMyBoSwvEwP4wNUdCoD0JhxF+fgYD+MA9CiV0-noe16C+VJL3gwjAOIhiYCYljUl3DjlC418-h4viBKEySIGk75xDk+QAG1iIcBS6LGAdrLvEA4W8GA-ys5D7JQ00cRE1JPl03ihQMwQ-kCRZdPEbRtAtassKDOTHIcABdRzZ085K7JQxjmDUtjNPA9DBDMbxzBCHCjJM2C-mpO1zVseTaKUkBtF3CjdDBY1uKC-jLCEzAyF4Br5Fs5rWurDrxC6nSwUOBl2j+HUpTpMA-kmrqqBkQJvCgGiiM809tA-MB1PY35GFWnTMOwvbFIOlrjtO4SYkut8PykFg2BqkzLG8W6spIo7MBO-LJRgZjFpYiQ+AonTX2yfhyuYnCJDoEHd3+5rNu0FjeF0lTctYjSru4A1vhCfhMfuk5xDINbwf4PQ6BfQb+rez9v1-Rr9vokABpOSHwQBOgTHQ66hV27m7t5nTYEEVhMG5BapBUqL+OFKmZbfPTgr6gEKLSMmKKfcyEOlpzZZ6gy-hxLgTu8YazYB08dKomQbf8GhWE1i2oNXTU6ZxMFIGUbIfZQq7MHioWoH8JQhMEZhiuE11yMd0b7sj6OKsiZp8ofQ3SsfC9w5Iq7aRgdoDAhilmmuehPtL09Kpk92dI-L8IB-JvFxRe2aAknFgzfJjDnQjvOZ722VOhAfphgYe-hRcjx45ruuZGpr7un-u-lg6TV877v4I8ryM68m8vJQlzMRPpKnJEsTuCXrg09Pe-Us8hx0rGTLmqiOkjJ0JSkCGDHuH5miH0nlLZ2IAHwmyXqTaqYMOIklcu5Ry95GDBBkA1AGDhL5X1PDAVcrAYIYK-vZUCWkKBcDHmQbQgkB6CFZizPGnFaHXDwffFC+4aBRBfNcQSksP74KcjfNyd9KG8wYUwlOZEYbv2kdgT+Xkf6OD-vdeBF42FCV+DiP8p5lCBC+KeWB2jnz8wTg3VgAJGGmPglgnBoU8SMmfGA+czULEJx4PxYcxMYCgIZEJWRDj5BONkNw+6HDhLKFcQtBQLFbFuz+Cg1wrVb7hL5jAGkZjmoxMDLnIBiTPqCKCVKOxTDDFwOwZEvJ0SaGxKKQkpJ-VAlpLQZkkiMRnF-G4GScQqTgn1N5gUuJ80OKtJtjYoS6T0GOJqb0+J7jhmeIaYVYyfAJklNsSAlBoSaDVJ6ZEvpAyhlShGU5GJmzMDbKmR9WxByjm1NwTbeaKyLlrNGY0m5dzSkPNmZ0yRWTjm4Mud5fxA88LPQMQs4xDjYEh28LhEhqS+DtHMNU4qpVwUkUrDDRBMF3YdIycC7Ap8qGLLqV8+yhCvLENIQwSmUir5OT4QIqUUQ2BKNZZo1lp4JEUNZShKIMguDWnkdwcqDUP5pWInyh+qcCW10EgCjCZpYDPOcbi08j9oTPxbt8d2KSSXzMspgqlYKaVjDpZSkhZDmXmuUShA5wlRL6oklJVuuL6UtVyByoR3KQCiPvgK4EZryU8O6fYge+KBA+spQyPEsA3luKEmkmhPKr6qPsuolKsCcrMSJuxBQIRlYzMqWEsuOSEXNULXlDSpagFqrmV0iJVqC0EyLU9GJQc-GhzKfsmNWqTn9MMIMjxnbVLFoKlxPtSL2JqqeQs0FLj3nptWVOwmPbGnzv8YuitrayUuxrYc61JF60zt7eu85QkpWrnxtO06jt8Bbu7flGJAcpoTL3aHEdHa61dobWdfdg7gmVrPSCl5oUx2pFvTqkAl6noLumaU5dUGlk3snYBp9+UUMtqBdUqUuTz3KVwxpE14Gj1CspauhNtreb2qZTR-lcCY2Pu3WxBNvN2Ww0DSI5RCrfWCpZcK+87G43MrEbzJN5pU3tA+bMzNwbBNyoyrAoG6MQNkTpns8D6HunQdOeO+DpGHrA2Q6nQOFaDPtrXWm0zGnHp4as6h2x1GFnEdrfdTTT172EuQcEx2bYnMWfylYmFx6QDwrPaFrTElmIw2SDiUKemKmyc1SuozsGJ2brGs5jSDc6ACGS9cNzQkMtRa88wrDeWfMFfYiq+uaHh1Ze1WZhksAVynT-I8WBXBGTmD+JsL4b5263MdU7Zq-nKOcr-K+6bbBab00sEzPRoGl2tYw9S2BNM6YxVW8zfDh7COedPQhvbK3GbMwi-oqLMWLtLf2wzNbCXivOBS+V9VyaqvnbM5dg712hIsUZEJTZalkWbaqW1nbi2JDPcO8DstYOfqzy+x57bAHqZPb+AARyuDQYlkgKKVl0+0-TW3DO9Jy45uHy38dfCJwI0nX3bOWvswpjdnzds44Z4ToZzPXMEdJURv7sDXbDjCiqVVMye4zQuBMvgOEEgeyZrs8nnzN48wtnobgrgB5cG6BMkb9p-1RJlrr-X6Ev2SgWibyIPdDXVTu9Uh7ZmEGzcBSL0TMjstnOw5QhjTkmPkJ90Qv1-C+NcoE7y6TJERNOuFdGuRkms1eRzWMPNKjYE7zR5YTU+IBSzKSVQIQX3Kui5IznvuefJh0h9IJb6XxfrMJs5Tk9Vf-41+Rfn+vRem8Q9b6UjH1bO-b277G10CgGQt9Z+39nCHc-IrWNPgaaPhcRrs4vif+N5ZK4pvI1fs+4YaQBVPHfQpBc6bAxUtndGzNL4N8TyV1nh+naydV7fds0czaQUTub8EIWXe3+yK88i8o8oULucKXc3mvMj+g8C8scsSJgoURWSW1wZWaqFeZ2Y+cBO+YBSBy8BKUBWSbu1eIBc8Q8hBr8xBoGr4iMPWCyscywXAX+M8yK+8eiJg92MBsWzUECJO3BruvBCG8UVwfwm020NAOEJBJEZBzUYhG6V+UqN+IS8+q6xmcGAevMihAuJOQube0OmOHOimohMQ4hl++h1+G+ba2SuBTkuhlhfSa4AW-+psHYt46U04IA04QAA) with the config and code to reproduce the issue.

> Which version of stylelint are you using?

`v13.13.1`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `stylelint ./src/**/*.css --fix`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No.

> What did you expect to happen?

I expected the two extra spaces at the end of those lines to be removed when using `--fix` as suggested by the docs: _The fix option can automatically fix most of the problems reported by this rule._

> What actually happened (e.g. what warnings or errors did you get)?

Nothing.
