### ISSUE TITLE
Getting a lot of weird property 'x' must come before property 'y'

### ISSUE THREAD

**Issue by DanGamble89** [stylelint/stylelint#538]
I have the problem across multiple files, but i'll give 1 exert:

Sorry for the length but i figured it would be better to be as verbose as possible.
```
27:3	⚠  Expected property "font-size" to come before property "margin-bottom" (rule-properties-order) [stylelint]
29:3	⚠  Expected property "font-weight" to come before property "line-height" (rule-properties-order) [stylelint]
60:3	⚠  Expected property "display" to come before property "flex-direction" (rule-properties-order) [stylelint]
64:3	⚠  Expected property "border-top" to come before property "padding-bottom" (rule-properties-order) [stylelint]
97:3	⚠  Expected property "font-size" to come before property "margin-bottom" (rule-properties-order) [stylelint]
99:3	⚠  Expected an empty line between property "color" and property "line-height" (rule-properties-order) [stylelint]
111:3	⚠  Expected property "font-family" to come before property "margin-bottom" (rule-properties-order) [stylelint]
125:3	⚠  Expected property "font-weight" to come before property "margin-bottom" (rule-properties-order) [stylelint]
138:3	⚠  Expected property "background-position" to come before property "order" (rule-properties-order) [stylelint]
149:5	⚠  Expected property "height" to come before property "flex-grow" (rule-properties-order) [stylelint]
156:7	⚠  Expected property "height" to come before property "flex-basis" (rule-properties-order) [stylelint]
```

Stylelint config:
```.stylelintrc
{
  "rules": {
    "color-hex-case": [2, "lower"],
    "color-hex-length": [2, "short"],

    "number-leading-zero": [2, "always"],
    "number-max-precision": [1, 3],
    "number-no-trailing-zeros": [2],
    "number-zero-length-no-unit": [2],

    "function-comma-space-after": [2, "always-single-line"],
    "function-comma-space-before": [2, "never"],
    "function-parentheses-space-inside": [2, "never-single-line"],

    "value-no-vendor-prefix": [2],

    "value-list-comma-space-after": [2, "always"],
    "value-list-comma-space-before": [2, "never"],

    "property-no-vendor-prefix": [2],

    "declaration-bang-space-after": [2, "never"],
    "declaration-bang-space-before": [2, "always"],
    "declaration-colon-space-after": [2, "always"],
    "declaration-colon-space-before": [2, "never"],
    "declaration-no-important": [1],

    "declaration-block-semicolon-newline-after": [2, "always-multi-line"],
    "declaration-block-semicolon-newline-before": [2, "never-multi-line"],
    "declaration-block-semicolon-space-after": [2, "always-single-line"],
    "declaration-block-semicolon-space-before": [2, "never"],

    "nesting-block-opening-brace-newline-before": [2, "always-multi-line"],

    "block-closing-brace-newline-after": [2, "always-single-line"],
    "block-closing-brace-newline-before": [2, "always-multi-line"],
    "block-closing-brace-space-before": [2, "always-single-line"],
    "block-no-empty": [2],
    "block-opening-brace-newline-after": [2, "always-multi-line"],
    "block-opening-brace-space-after": [2, "always-single-line"],
    "block-opening-brace-space-before": [2, "always"],

    "selector-combinator-space-after": [2, "always"],
    "selector-combinator-space-before": [2, "always"],
    "selector-no-universal": [1],
    "selector-no-vendor-prefix": [2],
    "selector-pseudo-element-colon-notation": [2, "double"],

    "selector-list-comma-space-after": [2, "always-single-line"],
    "selector-list-comma-space-before": [2, "never"],

    "rule-nested-empty-line-before": [2, "always-multi-line", {
      "except": ["first-nested"],
      "ignore": ["after-comment"]
    }],
    "rule-no-duplicate-properties": [2],
    "rule-no-shorthand-property-overrides": [2],
    "rule-trailing-semicolon": [2, "always"],

    "rule-properties-order": [2, [
      {
        "emptyLineBefore": true,
        "properties": [
          "content"
        ]
      },
      {
        "emptyLineBefore": true,
        "properties": [
          "position",
          "top",
          "right",
          "bottom",
          "left",
          "z-index"
        ]
      },
      {
        "emptyLineBefore": true,
        "properties": [
          "align-content",
          "align-items",
          "align-self",
          "flex",
          "flex-basis",
          "flex-direction",
          "flex-flow",
          "flex-grow",
          "flex-shrink",
          "flex-wrap",
          "justify-content",
          "order"
        ]
      },
      {
        "emptyLineBefore": true,
        "properties": [
          "display",
          "height",
          "margin",
          "margin-top",
          "margin-right",
          "margin-bottom",
          "margin-left",
          "max-height",
          "max-width",
          "padding",
          "padding-top",
          "padding-right",
          "padding-bottom",
          "padding-left",
          "width"
        ]
      },
      {
        "emptyLineBefore": true,
        "properties": [
          "font-family",
          "font-size",
          "font-style",
          "font-weight",
          "letter-spacing",
          "line-height",
          "text-decoration"
        ]
      },
      {
        "emptyLineBefore": true,
        "properties": [
          "background",
          "background-attachment",
          "background-color",
          "background-image",
          "background-position",
          "background-repeat",
          "background-size",
          "border",
          "border-top",
          "border-right",
          "border-bottom",
          "border-left",
          "border-radius",
          "border-top-left-radius",
          "border-top-right-radius",
          "border-bottom-right-radius",
          "border-bottom-left-radius",
          "box-shadow",
          "color",
          "cursor",
          "opacity",
          "overflow",
          "overflow-x",
          "overflow-y",
          "visibility"
        ]
      },
      {
        "emptyLineBefore": true,
        "properties": [
          "transform",
          "transition"
        ]
      }
    ]],

    "media-feature-colon-space-after": [2, "always"],
    "media-feature-colon-space-before": [2, "never"],
    "media-feature-name-no-vendor-prefix": [2],
    "media-feature-range-operator-space-after": [2, "always"],
    "media-feature-range-operator-space-before": [2, "always"],

    "media-query-parentheses-space-inside": [2, "never"],

    "indentation": [2, 2],
    "string-quotes": [2, "single"]
  }
}
```

SCSS:
```scss
@import '../../config/variables';
@import '../../helpers/media-queries';
@import '../../helpers/mixins';

/*
|--------------------------------------------------------------------------
| Events - Upcoming
|--------------------------------------------------------------------------
|
| @prefix: eve-
|
*/
.eve-Upcoming {
  padding-top: 5.81%;
  padding-bottom: 4.96%;
}

/*
|--------------------------------------------------------------------------
| Events - Upcoming - Title
|--------------------------------------------------------------------------
|
*/
.eve-Upcoming_Title {
  margin-bottom: 20px;

  font-size: 26px;
  line-height: 32px;
  font-weight: 400;

  @include MQ(md) {
    font-size: 42px;
    line-height: 52px;
  }
}

/*
|--------------------------------------------------------------------------
| Events - Upcoming - List
|--------------------------------------------------------------------------
|
*/
.eve-Upcoming_List {
  margin: 0;
  padding: 0;

  list-style: none;
}

/*
|--------------------------------------------------------------------------
| Events - Upcoming - Item
|--------------------------------------------------------------------------
|
*/
.eve-Upcoming_Item {
  align-items: center;
  flex-direction: column;

  display: flex;
  padding-top: 25px;
  padding-bottom: 37px;

  border-top: 1px solid #ced5d9;

  @include MQ(sm) {
    flex-direction: row;
  }
}

/*
|--------------------------------------------------------------------------
| Events - Upcoming - Item content
|--------------------------------------------------------------------------
|
*/
.eve-Upcoming_ItemContent {
  flex: 1;
  order: 2;

  color: #092557;

  @include MQ(sm) {
    order: 1;
  }
}

/*
|--------------------------------------------------------------------------
| Events - Upcoming - Item meta
|--------------------------------------------------------------------------
|
*/
.eve-Upcoming_ItemMeta {
  margin-bottom: 8px;

  font-size: 18px;
  line-height: 28px;
  color: map-get($Colors, lightBlue);
}

/*
|--------------------------------------------------------------------------
| Events - Upcoming - Item title
|--------------------------------------------------------------------------
|
*/
.eve-Upcoming_ItemTitle {
  margin-bottom: 2px;

  font-family: $Font_Myriad;
  font-size: 20px;
  line-height: 26px;
}

/*
|--------------------------------------------------------------------------
| Events - Upcoming - Item text
|--------------------------------------------------------------------------
|
*/
.eve-Upcoming_ItemText {
  margin-bottom: 0;

  font-weight: 400;
  line-height: 28px;
}

/*
|--------------------------------------------------------------------------
| Events - Upcoming - Item media
|--------------------------------------------------------------------------
|
*/
.eve-Upcoming_ItemMedia {
  order: 1;

  background-position: center;
  background-size: cover;

  @include MQ(sm) {
    order: 2;
  }

  &[style] {
    flex-basis: #{'@height'};
    flex-grow: 0;

    height: 240px;
    margin-bottom: 20px;
    width: 100%;

    @include MQ(sm) {
      flex-basis: 155px;

      height: 128px;
      margin-bottom: 0;
      margin-left: 20px;
      width: auto;
    }
  }
}
```
