### ISSUE TITLE
Autofix not working when scss file somewhere contains /* stylelint-disable-next-line */

### ISSUE THREAD

**Issue by nicolaskopp** [stylelint/stylelint#5423]
if any SCSS file contains the following line:

`/* stylelint-disable-next-line */`

e.g.

```scss
/* stylelint-disable-next-line */
burger-menu {
  display: none;
}
```

then the `--fix` option does not work and ALL autofixeable errors inside the file remain unfixed when running the `--fix` option.

e.g. consider this exampleFile.scss:

```scss
.burger-menu {
  position: fixed;;
}
/* stylelint-disable-next-line */
burger-menu {
  display: none;
}
```
Note the double semicolon on line 2.

now run:

`npx stylelint exampleFile.scss --fix`

result: Double semicolon is not fixed.

However, if I remove `/* stylelint-disable-next-line */` and thus have the following exampleFile.scss:

```scss
.burger-menu {
  position: fixed;;
}
burger-menu {
  display: none;
}
```

The double semiclon will be fixed by stylelints --fix option.

> What stylelint configuration is needed to reproduce the bug?

```js
module.exports = {
  extends: 'stylelint-config-standard',
  rules: {
    'indentation': 2,
    'no-descending-specificity': null,
    'at-rule-no-unknown': null,
    'number-leading-zero': 'never',
    'declaration-empty-line-before': 'never',
    'value-keyword-case': null
  }
};

```

> Which version of stylelint are you using?

13.13.1

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Nope

> What did you expect to happen?

autofix

> What actually happened (e.g. what warnings or errors did you get)?

no autofix
