### ISSUE TITLE
combinator selector spaces and new line

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#544]
Config 
```json
{
    "rules" : {
        "selector-combinator-space-after": [
            2,
            "always"
        ],
        "selector-combinator-space-before": [
            2,
            "always"
        ]
    }
}
```

My code:
```scss
// WordPress Generated Classes
// http://codex.wordpress.org/CSS#WordPress_Generated_Classes
.aligncenter {
    display: block;
}

.alignnone {
    @include inline-block();
}

.alignleft {
    float: left;
    margin-right: $margin-base;
}

.alignright {
    float: right;
    margin-left: $margin-base;
}

.content-image {
    margin-bottom: 1em;
    max-width: 100%;
    text-align: center;

    > a {
        display: block;
    }

    > a > img,
    > img { // error here
        @extend .img-thumbnail;
    }
}
```

Error:
```bash
31:5	⚠  Expected single space before ">" combinator (selector-combinator-space-before) [stylelint]
```
I need space between combinator.
