### ISSUE TITLE
font-smoothing rule-properties-order

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#546]
Parts of config
```json
{
    "properties": [
        "font-family",
        "src",
        "font",
         "font-style",
         "font-variant",
        "font-weight",
        "font-stretch",
        "font-size",
        "font-smoothing",
    ]
},
{
    "properties": [
        "content",
        "quotes"
]
 }
```

```scss
.test {
     text-rendering: auto;
     font-family: FontAwesome;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    content: "\f00c"
}
```

I get error
```bash
99:29	⚠  Expected property "content" to come before property "-moz-osx-font-smoothing" (rule-properties-order)
```

In spec https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth:
For webkit: -webkit-font-smoothing
For firefox: -moz-osx-font-smoothing
