### ISSUE TITLE
string-quotes in // comments

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#547]
```scss
// Automatically set modal's width for larger viewports
.test {
    color: #fff;
}
```

Error:
```bash
1:27	⚠  Expected double quotes (string-quotes) [stylelint]
```

I think we don't need checking string-quotes types in comments.
