### ISSUE TITLE
disabling-linters

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#549]
https://github.com/brigade/scss-lint#disabling-linters-via-source
http://eslint.org/docs/user-guide/configuring.html#configuring-rules

Sometimes i need write for ie
```scss
.container {
    display: block !important;
    // scss-lint:disable DuplicateProperty
    // IE fallback
    display: inline;
    // scss-lint:enable DuplicateProperty
    position: relative;
    margin: 0;
    zoom: 1;
    vertical-align: middle;
}
```

Or 
```scss
.block {
    // scss-lint:disable DuplicateProperty
    // Fallback for flex
    display: block;
    display: flex;
    // scss-lint:enable DuplicateProperty
}
```
New browsers uses flex, another block. 
How can I disable a specific rule?
Also maybe add rules a similar rule `DisableLinterReason` as scss-lint?

**Comment by jeddy3** [comment]
Does:

```css
/* stylelint-disable selector-no-id, declaration-no-important  */
#id {
  color: pink !important;
}
/* stylelint-enable */
```

not work? (as per https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#turning-rules-on-and-off).

If not, perhaps it's something to do with the comment style?
