### ISSUE TITLE
Add support for combined @supports properties

### ISSUE THREAD

**Issue by chrish-d** [stylelint/stylelint#5495]
> What is the problem you're trying to solve?

When adding multiple `@supports` properties, stylelint incorrectly expects a closing parenthesis.

![Screenshot 2021-08-23 at 17 14 59](https://user-images.githubusercontent.com/8567692/130481587-3fa8a5a9-e42f-4b6c-9010-01f5380990b4.png)

> What solution would you like to see?

As this is valid CSS, we should provide support for it by not flagging it as a linting error.

To re-create:

```css
.test {
  gap: 1em;

  @supports not (display: flex; gap: 1em) {
    & > * {
      margin-bottom: 1em;

      &:last-of-type {
        margin-bottom: 0;
      }
    }
  }
}
```
