### ISSUE TITLE
Selector-list no-descending-specificity

### ISSUE THREAD

**Issue by Zirak** [stylelint/stylelint#5497]
> What is the problem you're trying to solve?

When writing a selector list with some shared "base" selectors, different people at different times may write them out differently, creating inconsistencies. For example:

```css
/*
  given something like:
  <div><div class="foo bar"></div></div>
*/

.foo,
.foo.bar {
  color: red;
}

div .foo {
  color: purple;
}
```

The first selector list may be written in one of two ways:

```css
/* A */
.foo,
.foo.bar { ... }

/* B */
.foo.bar,
.foo { ... }
```

> What solution would you like to see?

We would like to standardise on either A or B; however a solution which only rejects B would also be beneficial.

A rule very similar to the [`no-descending-specificity`](https://stylelint.io/user-guide/rules/list/no-descending-specificity) rule which operates not at the stylesheet level, but at the selector list level.

If there's interest, I'd be willing to create a PR for this. Thanks for your time.

**Comment by jeddy3** [comment]
@Zirak Thanks for the request and for using the template.

Can you provide a couple more examples please, perhaps real-world ones?

I'm struggling to understand the use case as the patterns in both A or B seem redundant, i.e. the compound selector `.foo.bar` will select a _subset_ of the simple selector `.foo`, and it, therefore, doesn't make sense to have them in the same selector list.

It seems better to split them into separate rules, e.g.:

```css
.foo {
  font-weight: bold;
  color: red;
}

.foo.bar {
  color: blue;
}
```

```html
<div class="foo">Test</div>
<div class="foo bar">Test</div>
```

Where the second `<div>` will be both blue and bold.

**Comment by jeddy3** [comment]
Feel free to reopen with clarification.

**Comment by Zirak** [comment]
agh, sorry for the extreme forgetfulness

> Can you provide a couple more examples please, perhaps real-world ones?

Sure thing. This was in a rather rare case of dueling specificities. If I remember correctly, it was a button styled with both our own styling and a 3rd-party style system, something like:

```html
<div class="container external-container">
  <button class="fancy-button external-button external-disabled">Hello!</button>
</div>
```

```css
/* our code */
.container .fancy-button {
  color: peachpuff;
}

/* 3rd-party code, injected after ours */
.external-button.external-disabled {
  color: gray;
}
```

The combination of the two led to their styles overriding ours, which for this case wasn't peachy. Someone in the team changes our code to:

```css
/* our code */
.container .fancy-button.external-disabled, /* new code, written in the B way shown in first comment */
.container .fancy-button {
  color: peachpuff;
}

/* 3rd-party code remains the same */
```

I don't recall whether we went ahead with this method out of laziness or refactored so it won't be a problem, but it surprised me still that it was not a lint error. Intuitively, it seems like selectors in a selector list should be written in order of ascending specificity, just like selectors not in the same selector list.

Do tell if clarification is still needed, and thanks again!
