### ISSUE TITLE
block-closing-brace-newline-* and at-rule-empty-line-* for some at-rule

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#550]
```scss
@mixin line-on-sides($count-lines: 1, $width: 145px, $color: #fff, $margin: 20px) {
    display: inline-block;
    position: relative;
    vertical-align: middle;
    text-align: center;
    line-height: .5;

    &:before,
    &:after {
        @if $count-lines == 1 {
            border-top: 1px solid $color;
            height: 3px;
        } @else if $count-lines == 2 {
            border-top: 1px solid $color;
            border-bottom: 1px solid $color;
        } @else {
            @error "$count-lines may be 1 or 2, was #{$count-lines}.";
        }

        position: absolute;
        top: 50%;
        width: $width;
        height: $count-lines * 2 + 1px;
        content: "";
    }

    &:before {
        right: 100%;
        margin-right: $margin;
    }

    &:after {
        left: 100%;
        margin-left: $margin;
    }
}
```

Errors:
```bash
13:10	⚠  Expected newline after "}" (block-closing-brace-newline-after) [stylelint]
13:11	⚠  Expected empty line before at-rule (at-rule-empty-line-before) [stylelint]
16:10	⚠  Expected newline after "}" (block-closing-brace-newline-after) [stylelint]
16:11	⚠  Expected empty line before at-rule (at-rule-empty-line-before) [stylelint]
```

I think we need discussion about `block-closing-brace-newline-after`, `block-closing-brace-newline-before`, `at-rule-empty-line-before`, `at-rule-empty-line-after` for control structure.
What do you thinks?
