### ISSUE TITLE
Comments not taken into account when using rule-properties-order

### ISSUE THREAD

**Issue by DanGamble89** [stylelint/stylelint#554]
Sorry, me again :D

**.stylelintrc:**
```
  "rule-properties-order": [2, [
      {
        "emptyLineBefore": true,
        "properties": [
          "line-height"
        ]
      },
      {
        "emptyLineBefore": true,
        "properties": [
          "color"
        ]
      },
    ]
  ]
```

**CSS:**
```css
body {
  line-height: map(fonts, lineHeights, base, normal);

  /* Go easy on the eyes and use something other than `#000` for text */
  color: map(colors, dark);
}
```

**Error:**
```
62:3	⚠  Expected an empty line between property "color" and property "line-height" (rule-properties-order) [stylelint]
```
