### ISSUE TITLE
ignore comment-empty-line-before for stylelint-disable and stylelint-enable

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#555]
```css
.nav-pills-center {
    /* stylelint-disable rule-no-duplicate-properties */
    // Fallback for flex
    display: inline-block;
    display: flex;
    /* stylelint-enable */
    justify-content: center;
}
```

```bash
6:5	⚠  Expected empty line before comment (comment-empty-line-before) [stylelint]
```
