### ISSUE TITLE
Add ignore: ["consecutive-duplicates-with-same-prefixless-values"] to declaration-block-no-duplicate-properties

### ISSUE THREAD

**Issue by MightyCreak** [stylelint/stylelint#5607]
> What is the problem you're trying to solve?

I can't have both `declaration-block-no-duplicate-properties` and this CSS:
```css
.item {
    width: -moz-fit-content;
    width: fit-content;
}
```

I can use [ignore: ["consecutive-duplicates-with-different-values"]](https://stylelint.io/user-guide/rules/list/declaration-block-no-duplicate-properties#ignore-consecutive-duplicates-with-different-values), but it's not exactly the same because I would still like to have an error if I have this kind of CSS:
```css
.item {
    width: 50%;
    width: 100%;
}
```

Source:
* MDN for `fit-content`: https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content

> What solution would you like to see?

Maybe a new option such as `ignore: ["consecutive-duplicates-with-vendor-specific-values"]` ?
