### ISSUE TITLE
Document behaviour better for *-no-vendor-prefix

### ISSUE THREAD

**Issue by Andy-QT** [stylelint/stylelint#5664]
> Clearly describe the bug

Autofix creates false output in CSS-file

> Which rule, if any, is the bug related to?

`property-no-vendor-prefix`

> What code is needed to reproduce the bug?

```css
.input,
.select {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  -webkit-transition: height 0.1s ease;
  -moz-transition: height 0.1s ease;
  -o-transition: height 0.1s ease;
  transition: height 0.1s ease;
}
```

> What Stylelint configuration is needed to reproduce the bug?

e.g.

```json
{
  "rules": {
    "property-no-vendor-prefix": "true"
  }
}
```

> Which version of Stylelint are you using?

e.g. `14.0.1`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

"CLI with `npx stylelint "src/**/*.{css,sass,scss}" --fix`"

> What did you expect to happen?

e.g. "No warnings to be flagged."

> What actually happened (e.g. what warnings or errors did you get)?
```css
.input,
.select {
	box-sizing: border-box;
	box-sizing: border-box;
	box-sizing: border-box;
	transition: height 0.1s ease;
	transition: height 0.1s ease;
	transition: height 0.1s ease;
	transition: height 0.1s ease;
}
```

```shell
151:2  ✖  Unexpected vendor-prefix "-webkit-box-sizing"  property-no-vendor-prefix
152:2  ✖  Unexpected vendor-prefix "-moz-box-sizing"     property-no-vendor-prefix
154:2  ✖  Unexpected vendor-prefix "-webkit-transition"  property-no-vendor-prefix
155:2  ✖  Unexpected vendor-prefix "-moz-transition"     property-no-vendor-prefix
156:2  ✖  Unexpected vendor-prefix "-o-transition"       property-no-vendor-prefix
```
