### ISSUE TITLE
comment-empty-line-before bug?

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#567]
```scss
.nav-pills-center {
    /* stylelint-disable rule-no-duplicate-properties */
    // Fallback for flex
    display: inline-block;
    display: flex;
    /* stylelint-enable */
    justify-content: center;
}
```

```bash
6:5	⚠  Expected empty line before comment (comment-empty-line-before) [stylelint]
```
Not ignore stylelint directive? (v 3.0.2)
