### ISSUE TITLE
block-opening-brace-newline-before: "always" doesn't respect indentation

### ISSUE THREAD

**Issue by EvanShaw** [stylelint/stylelint#5673]
> Clearly describe the bug

Setting `block-opening-brace-newline-before` to `"always"` with the default indentation (2) moves the opening brace to the next line but does not indent the brace at all.

> Which rule, if any, is the bug related to?

 `block-opening-brace-newline-before`

> What code is needed to reproduce the bug?

Any SCSS block or any nested combination of blocks will produce the same results.

> What Stylelint configuration is needed to reproduce the bug?

```json
{
  "customSyntax": "postcss-scss",
  "rules": {
    "block-opening-brace-newline-before": "always"
  }
}
```

> Which version of Stylelint are you using?

`14.0.1`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `stylelint "stylelint.scss" --config stylelint.json`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to SCSS but also affects CSS (I didn't check Less).

> What did you expect to happen?

I expect that the opening brace will respect indentation. For example, given the following SCSS:
```scss
.standalone{
  display: flex;
}

.parent {
  display: flex;

  .child {
    display: flex;
  }
}
```
I expect running --fix on stylelint will produce this:
```scss
.standalone
{
  display: flex;
}

.parent
{
  display: flex;

  .child
  {
    display: flex;
  }
}
```

> What actually happened (e.g. what warnings or errors did you get)?

Stylelint simply moves the brace to the next line without indenting it at all, like this:
```scss
.standalone
{
  display: flex;
}

.parent
 {
  display: flex;

  .child
 {
    display: flex;
  }
}
```
The indentation is only correct for `.standalone` because there was no whitespace before the opening brace before formatting. But both the opening braces of `.parent` and `.child` are preceded by just 1 space (the whitespace before formatting). I expect `.parent`'s opening brace to be indented 0 spaces and `.child`'s opening brace to be indented 2 spaces.
