### ISSUE TITLE
Add declaration-block-multi-line-min-declarations

### ISSUE THREAD

**Issue by ademaro** [stylelint/stylelint#5724]
### What is the problem you're trying to solve?

Enforce a selector and attribute to be on the same line if there is only one attribute

### What solution would you like to see?

For rule `"declaration-block-multi-line-min-declarations": 2` for example, this would error:
```css
.selector {
  color: #111;
}
```
I would like to see a fix like this:
```css
.selector { color: #111; }
```
But such selectors should be left unchanged:
```css
.selector2 {
  color: #111;
  background-color: #aaa;
}
```
