### ISSUE TITLE
No way to disable max-line-length rule

### ISSUE THREAD

**Issue by jzempel** [stylelint/stylelint#581]
Once it has been set, I'm unable to disable `max-line-length`. I've tried the following:

```css
/* stylelint-disable max-line-length */
.class { foo: with-a-value-that-exceeds-max-line-length; }
/* stylelint-enable */
```

also

```css
/* stylelint-disable */
.class { foo: with-a-value-that-exceeds-max-line-length; }
/* stylelint-enable */
```

and, finally

```json
{
  "extends": "stylelint-config-custom",
  "rules": {
    "max-line-length": null
  }
}
```

where `stylelint-config-custom` defines a `"max-line-length": 80` rule. I'm using stylelint version 3.1.2.

**Comment by davidtheclark** [comment]
Are you able to disable other rules just fine, and this one is the exception?

**Comment by jzempel** [comment]
That's correct. For example, I'm using:

```css
/* stylelint-disable declaration-no-important */
.bg-blue { background-color: blue !important; }
/* stylelint-enable*/
```

and it works as expected.
