### ISSUE TITLE
Unexpected unknown function `"-webkit-gradient"` & `"color-stop"`  function-no-unknown

### ISSUE THREAD

**Issue by adhamfarrag** [stylelint/stylelint#5960]
### What steps are needed to reproduce the bug?

I'm having this css class in my project. It has `-webkit-gradient` and inside of it, it has `color-stop`.

```css
.text-line {
  -webkit-animation-duration: 1.25s;
  animation-duration: 1.25s;
  -webkit-animation-fill-mode: forwards;
  animation-fill-mode: forwards;
  -webkit-animation-iteration-count: infinite;
  animation-iteration-count: infinite;
  -webkit-animation-name: placeHolderShimmer;
  animation-name: placeHolderShimmer;
  -webkit-animation-timing-function: linear;
  animation-timing-function: linear;
  background: #f6f6f6;
  background: -webkit-gradient(
    linear,
    left top,
    right top,
    color-stop(8%, #f6f6f6),
    color-stop(18%, #f0f0f0),
    color-stop(33%, #f6f6f6)
  );
  background: linear-gradient(to right, #f6f6f6 8%, #f0f0f0 18%, #f6f6f6 33%);
  background-size: 800px 104px;
  height: 96px;
  position: relative;
}
```

### What Stylelint configuration is needed to reproduce the bug?

It's [Nuxt stylelint-module](https://github.com/nuxt-community/stylelint-module)
```js
module.exports = {
  extends: "stylelint-config-recommended-vue",
  rules: {
    "at-rule-no-unknown": [
      true,
      {
        ignoreAtRules: [
          "tailwind",
          "apply",
          "variants",
          "responsive",
          "screen",
        ],
      },
    ],
    "declaration-block-trailing-semicolon": null,
    "no-descending-specificity": null,
  },
};

```

### How did you run Stylelint?

Nuxt.js handles that.

### Which version of Stylelint are you using?

`14.4.0`

### What did you expect to happen?

To not have bugs or to find it supported in Stylelint documentations.

### What actually happened?

```bash
 64:15  ✖  Unexpected unknown function "-webkit-gradient"  function-no-unknown
 68:5   ✖  Unexpected unknown function "color-stop"        function-no-unknown
 69:5   ✖  Unexpected unknown function "color-stop"        function-no-unknown
 70:5   ✖  Unexpected unknown function "color-stop"        function-no-unknown

```

### Does the bug relate to non-standard syntax?

No.
