### ISSUE TITLE
Ignore comments after declaration-block-semicolon-newline-after

### ISSUE THREAD

**Issue by satazor** [stylelint/stylelint#598]
At the moment, comments are ignored if they have exactly one space after the semi-colon. I would like the behavior to simply ignore comments after the semi-column. Consider this:

```css
body {
  -moz-osx-font-smoothing: grayscale;  /* Font smoothing tweaks for MacOSx in Gecko */
  -webkit-font-smoothing: antialiased; /* Font smoothing tweaks for MacOSx in Webkit */
}
```

Would cause an error which sucks because I want to make these two comments aligned.
Could we change this behavior? Perhaps adding an option?
