### ISSUE TITLE
Fix false positives for interpolation in keyframes-name-pattern

### ISSUE THREAD

**Issue by jdufresne** [stylelint/stylelint#5997]
### What steps are needed to reproduce the bug?

test.scss

```scss
$frames: ("one", "two", "three");

@each $name in $frames {
  @keyframes frame-#{$name} {
    /* CSS ... */
  }
}
```

```
$ npx stylelint test.scss

test.scss
 4:14  ✖  Expected keyframe name to be kebab-case  keyframes-name-pattern
```

The name is kebab case, but due to the string interpolation, the line is flagged as an error.

This was originally file at https://github.com/stylelint-scss/stylelint-config-standard-scss/issues/16 but I was instructed to move it here.

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "extends": "stylelint-config-standard-scss"
}
```

### How did you run Stylelint?

npx stylelint test.scss

### Which version of Stylelint are you using?

`14.6.1`

### What did you expect to happen?

No problems to be reported.

### What actually happened?

```
test.scss
 4:14  ✖  Expected keyframe name to be kebab-case  keyframes-name-pattern
```

### Does the bug relate to non-standard syntax?

Yes it uses SCSS string interpolation.
