### ISSUE TITLE
improve handling of url() in max-line-length

### ISSUE THREAD

**Issue by onlywei** [stylelint/stylelint#605]
With the settings:

```json
{
  "rules": {
    "declaration-colon-space-after": "always-single-line",
    "max-line-length": 100
  }
}
```

And the code:

```css
.foo {
  background-image:
      url('url-that-is-more-than-100-chars-long');
}
```

The `declaration-colon-space-after` will throw a warning here.
