### ISSUE TITLE
Impossible to disable max-line-length rule?

### ISSUE THREAD

**Issue by onlywei** [stylelint/stylelint#606]
Is the `max-line-length` rule impossible to disable? If I have:

```css
.foo {
  /* stylelint-disable */
  background-url: url('url-that-is-too-long');
  /* stylelint-enable */
}
```

This seems to still throw errors.
