### ISSUE TITLE
selector-no-type throwing errors when using :nth-child and keyframes

### ISSUE THREAD

**Issue by danielgamble** [stylelint/stylelint#609]
I recreated it here: https://github.com/danielgamble/styletest

Just needs an `npm install`

**Comment by keithamus** [comment]
I've also just noticed `selector-no-type` fails for keyframes as well:

```css
@keyframes spin {
  0% { /* selector-no-type complains here */
    transform: rotate(0deg);
  }
  100% { /* selector-no-type complains here */
    transform: rotate(360deg);
  }
}
```
