### ISSUE TITLE
rule: base64 limit

### ISSUE THREAD

**Issue by richex-cn** [stylelint/stylelint#6196]
### What is the problem you're trying to solve?

I don't think it is recommended to record resources in CSS.

Maybe consider adding a Base64 limit rule. The purpose is to limit CSS size, avoid resources in CSS or limit resource size.

### What solution would you like to see?

Rule like this:

```js
module.exports = {
  rules: {
    'base64-limit': { maxLength: 1024 }
    // or
    // 'base64-limit': false
  }
}
```

Example:

```css
/** 'base64-limit': { maxLength: 1024 } */
background-image: url('data:image/png;base64,iVBO...<more than 1024 character>...kJggg=='); // error
background-image: url('data:image/png;base64,iVBO...<less than 1024 character>...kJggg=='); // pass

/** 'base64-limit': { maxLength: 0 } */
background-image: url('data:image/png;base64,iVBO='); // error; Disable any Base64 by passing in maxLength: 0

/** 'base64-limit': false */
background-image: url('data:image/png;base64,iVBO...<any length character>...kJggg=='); // pass
```

Maybe can also consider passing the MIME Type:

```css
/** 'base64-limit': { maxLength: 1024, 'application/x-font-ttf': false } */
background-image: url('data:image/png;base64,iVBO...<more than 1024 character>...kJggg=='); // error
@font-face {
  font-family: fontName;
  src: url('data:application/x-font-ttf;charset=utf-8;base64,AAEA...<any length character>...AAAj') format('truetype'); // pass
}

/** 'base64-limit': { maxLength: 1024, 'application/x-font-ttf': 10240 } */
background-image: url('data:image/png;base64,iVBO...<more than 1024 character>...kJggg=='); // error
@font-face {
  font-family: fontName;
  src: url('data:application/x-font-ttf;charset=utf-8;base64,AAEA...<more than 10240 character>...AAAj') format('truetype'); // error
}
@font-face {
  font-family: fontName;
  src: url('data:application/x-font-ttf;charset=utf-8;base64,AAEA...<less than 10240 character>...AAAj') format('truetype'); // pass
}
```

The above example is judged by Base64 string length, It would be better if we could limit the number by binary bytes.
