### ISSUE TITLE
Curly braces always on new line with 4 spaces indent

### ISSUE THREAD

**Issue by jdescelliers** [stylelint/stylelint#6200]
Hi

Basically (and in advance, sorry for the folks that would only accept CSS with 2 spaces) I would like to apply the following on my scss files:

```scss
.some-class/*no space after the selector*/
{
    font-size: 12px;
}
```

Here's my `stylelintrc.json` in the root directory:
```json
{
  "extends": "stylelint-config-standard",
  "customSyntax": "postcss-less",
  "rules": {
    "block-opening-brace-newline-after": "always",
    "block-opening-brace-space-before": "always-single-line",
    "indentation": 4,
    "string-quotes": "single"
  }
```

here's the thing, apparently this this file is considered valid:

```scss
body {
    font-family: 'Arial, Helvetica', sans-serif;
    font-size: 14px;
}
```

What am I missing here?
