### ISSUE TITLE
An error is occured when lint @apply rules

### ISSUE THREAD

**Issue by morishitter** [stylelint/stylelint#624]
I tried to lint CSS code that uses [@apply rules](http://tabatkins.github.io/specs/css-apply-rule/) by [postcss-apply](https://github.com/pascalduez/postcss-apply), but the following error is occured.

```
Message:
    Cannot read property '0' of null
```

and here is my CSS code.

```css
:root {
  --truncate: {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
}
```

I wish your help. Thanks.

**Comment by jeddy3** [comment]
Hi @morishitter 

I was able to lint the following CSS without errors:

```css
:root {
  --toolbar-theme: {
    background-color: rebeccapurple;
    color: white;
    border: 1px solid green;
  };
  --toolbar-title-theme: {
    color: green;
  };
}

.toolbar {
  @apply --toolbar-theme;
}
.toolbar__title {
  @apply --toolbar-title-theme;
}
```

Can you paste in your config and let us know what version of stylelint you're using please, so that we can get to the bottom of this for you? :)
