### ISSUE TITLE
Add visual cascades option to indentation

### ISSUE THREAD

**Issue by silverwind** [stylelint/stylelint#628]
The following should not be considered a error with an option which could be called `visualCascade` or possibly `alignAtColon`:
```css
body {
    -webkit-filter: invert(100%);
            filter: invert(100%);
}
```
