### ISSUE TITLE
Wrong position of `string-quotes` offenses with code comments

### ISSUE THREAD

**Issue by AlexWayfer** [stylelint/stylelint#6314]
### What steps are needed to reproduce the bug?

```scss
@mixin small-and-large-elements(
	/*
	Probably here should be something like `$large_element_container`,
	for example, for Cccombo input like this:
	https://gitlab.gettransport.com/site/site/merge_requests/80/diffs#28551ac9184a7e08499c6a0b6a17f78126a4defa_124_124
	Discussion:
	https://gitlab.gettransport.com/site/site/merge_requests/522#note_324681
	*/
	$small_element: '> button', $large_element: '> input',
	$small_element_on_right: false, $inline: false
) {
}
```

(with `//` the same offenses)

### What Stylelint configuration is needed to reproduce the bug?

```yaml
extends:
  - stylelint-config-standard
  - stylelint-config-standard-scss

ignorePath: .gitignore

plugins:
  - stylelint-no-unsupported-browser-features
```

### How did you run Stylelint?

CLI or Atom Editor plugin. 

### Which version of Stylelint are you using?

`14.11.0`

### What did you expect to happen?

No offenses about quotes inside comment.

### What actually happened?

```
assets/styles/lib/_small-and-large-elements.scss
 3:16  ✖  Expected double quotes  string-quotes
 3:44  ✖  Expected double quotes  string-quotes
```

![image](https://user-images.githubusercontent.com/6510020/188022448-f0be87e0-c8f8-4924-a174-98c082364f7c.png)

### Does the bug relate to non-standard syntax?

SCSS, but not sure.
