### ISSUE TITLE
Fix `value-keyword-case` false positives for mixed case `ignoreFunctions` option

### ISSUE THREAD

**Issue by Arkellys** [stylelint/stylelint#6436]
### What steps are needed to reproduce the bug?

Setup the following code:

```scss
$appColors: (
  hoveringMenu: (
    background: red;
  )
);

@function getAppColor($name, $variant...) {
  @return map.get($appColors, $name, $variant...);
}

.hoveringToolbar {
  background-color: getAppColor(hoveringMenu, background);
}
```

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "value-keyword-case": ["lower", {
      "ignoreProperties": ["$appColors"],
      "ignoreFunctions": ["getAppColor"],
    }]
  }
}
```

### How did you run Stylelint?

CLI, VSCode official Stylelint extention and Demo on the official website.

### Which version of Stylelint are you using?

`^14.14.0`

### What did you expect to happen?

I expect `hoveringMenu` to be ignored when used as value in `getAppColor()`.

### What actually happened?

I get the error:
```shell
Expected "hoveringMenu" to be "hoveringmenu" (value-keyword-case)
```

On the line:
```scss
background-color: getAppColor(hoveringMenu, hover);
```

### Does the bug relate to non-standard syntax?

SCSS

### Proposal to fix the bug

I don't know how to fix the bug, but here are some tests I made:

These are working:
```js
getAppColor(hoveringMenu, background)
"ignoreFunctions": ["/getappcolor/"]

getAppColor(hoveringMenu, background)
"ignoreFunctions": ["/getAppColor/i"]

getappcolor(hoveringMenu, background);
"ignoreFunctions": ["getappcolor"]
```

These are not working:
```js
getAppColor(hoveringMenu, background)
"ignoreFunctions": ["/getAppColor/"]

Foo(hoveringMenu, background);
"ignoreFunctions": ["Foo"]
```

Seems to be a problem of case...
