### ISSUE TITLE
'indentation' bug: "TypeError: Cannot read property '1' of null"

### ISSUE THREAD

**Issue by MoOx** [stylelint/stylelint#646]
```css
body {
  /* system font https://medium.com/designing-medium/system-shock-6b1dc6d6596f */
  font-family:
    -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu",
     "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif
  ;
}
```

```
TypeError: Cannot read property '1' of null
    at .../stylelint/dist/rules/indentation/index.js:182:84
    at matchFound (.../stylelint/dist/utils/styleSearch.js:178:5)
    at exports.default (.../stylelint/dist/utils/styleSearch.js:170:5)
    at checkMultilineBit (.../stylelint/dist/rules/indentation/index.js:178:30)
    at checkValue (.../stylelint/dist/rules/indentation/index.js:155:7)
    at .../stylelint/dist/rules/indentation/index.js:95:9
    at .../postcss/lib/container.js:73:26
    at Rule.each (.../postcss/lib/container.js:60:22)
    at Rule.walk (.../postcss/lib/container.js:72:21)
    at .../postcss/lib/container.js:76:32
```

**Comment by MoOx** [comment]
FYI, this does not create the bug

```css
body {
  /* system font https://medium.com/designing-medium/system-shock-6b1dc6d6596f */
  font-family:
    -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu",
     "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif;
}
```

Note the semicolon diff.
