### ISSUE TITLE
Add a ignore for number rules 

### ISSUE THREAD

**Issue by kjvdven** [stylelint/stylelint#6492]
### What is the problem you're trying to solve?

We use Tailwind as our Framework and I still write some css, but I refer to the theme spacings and colors for consistency. 

For linting we have the number rules (number-leading-zero, number-no-trailing-zeros) enabled, but they don't work well with the Tailwind `theme()` function. For other rules I could add options, but not for the number rules.

```scss
.example {
    --example-spacing-top: theme(spacing.3); // stylelint-disable-line number-leading-zero, number-no-trailing-zeros
    --example-color: theme(colors.red.500); // stylelint-disable-line number-leading-zero, number-no-trailing-zeros
  }
```

### What solution would you like to see?

I would like to add optional secondary options to the number rules, like for other rules. I think exception or ignore would solve this issue.

```json
 "number-leading-zero": [
  true,
  {
     "ignore": [  ]
  }
],
```

Other option would be to ignore the number if it's part of a string.

not considered problems:
```
spacing.0
colors.red.500
```

considered problems:
```
0.000
.0
01.00
```
