### ISSUE TITLE
Rule proposal: declaration-block-semicolon-newline-after

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#65]
The `-after` suffix is because I don't think a user would likely require a newline *before*.

The question of whether this kind of suffix is a suitable convention I also brought up here: https://github.com/stylelint/stylelint/issues/21#issuecomment-102209896

**Comment by MoOx** [comment]
I already saw people writing this

```css
body {
  ;background: red
  ;color: white
}
```

This is weird but it possible :)

**Comment by davidtheclark** [comment]
Ok ... but in that case they aren't using a declaration block semicolon right? What `before` would mean in my mind is something like this:

```css
body {
  background: red;
  color: white
;}
```

I mean, we *could* allow for it ...
