### ISSUE TITLE
rule-properties-order with media query

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#653]
```scss
.item {
        @media (min-width: $screen-sm-min) {
            margin-left: 74px;
            min-height: 64px;
        }

        @media (min-width: $screen-md-min) {
            margin-left: 106px;
            min-height: 96px;
        }

        @media (min-width: $screen-lg-min) {
            margin-left: 138px;
            min-height: 128px;
        }

        position: relative;
        margin-bottom: $margin-base;
        margin-left: 42px;
        border: 1px solid $gray-light;
        border-radius: 4px;
        box-shadow: 0 1px 1px rgba(0, 0, 0, .05);
        background-color: #fff;
        padding: 10px;
}
```
Output:
```
17:5	⚠  Expected property "position" to come before property "min-height" (rule-properties-order) [stylelint]
```
I think order in media queries and outside do not crossed. Separately check order in the media query and outside. Or maybe add option for this behaviour. What do you think?
