### ISSUE TITLE
Add `ratio-notation`

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/stylelint#6575]
### What is the problem you're trying to solve?

Iv recently discovered that Chrome didn't support decimals in ratio data types, but Firefox did.
e.g. `1.7/1` fails but `10/6` is OK

This is probably due to the different types accepted between Media Queries Level 3 and 4.
ref: https://developer.mozilla.org/en-US/docs/Web/CSS/ratio#syntax

### What solution would you like to see?

- Name: `ratio-notation`
- Primary option: `"number"|"integer"`
- Secondary options: none
- Autofixable: Not initially
- Message: `Expected "${primary}" ratio notation`
- Description: "Specify number or integer notation for ratio data type."
- Section: "Enforce conventions" -> "Notation"

A `foo % 1 === 0` condition should be enough to detect it.

**Comment by Mouvedia** [comment]
>  The *-notation rules are for when the same thing can be represented in two or more ways…

That's the case here.
e.g. `1.5/3` === `3/6`

Depending on the level of Media Queries it's supported or not.
It's akin to the selector-not-notation rule that I added previously.

**Comment by romainmenke** [comment]
This PostCSS plugin fixes the browser issues : https://github.com/csstools/postcss-plugins/tree/postcss-preset-env--v8/plugins/postcss-media-queries-aspect-ratio-number-values#readme

Support stats : https://mrhenry.github.io/web-tests/#de023e11-f61a-4635-a74c-e4a152251bdf

Stylelint could have a rule for it, but since it is perfectly possible to polyfill I think it might make sense to do just that :)

**Comment by Mouvedia** [comment]
@romainmenke I am not using PostCSS, so that wouldn't be a solution _for me_.
It's reassuring to see that I am not the only one who saw the need for a fix, though.

**Comment by FloEdelmann** [comment]
I think that rule should not exist to ensure browser compatibility, but to enforce a convention across the codebase:

---

### Primary option `"number"`

> [!NOTE]
> Can always be autofixed by calculating the division.

The following patterns are considered problems:

```css
a { aspect-ratio: 2 / 1; }
a { aspect-ratio: 3 / 2; }
a { aspect-ratio: 16/9; }
a { aspect-ratio: 1.7/1; }
```

The following patterns are *not* considered problems:

```css
a { aspect-ratio: 2; }
a { aspect-ratio: 1.5; }
a { aspect-ratio: 1.7778; }
a { aspect-ratio: 1.7; }
```

### Primary option `"integers"`

> [!NOTE]
> If the value is a single integer, it can be autofixed by appending `/1`.
> For decimals, it could use a [more sophisticated algorithm](https://stackoverflow.com/questions/5124743/algorithm-for-simplifying-decimal-to-fractions) for finding a human-readable fraction that approximates the decimal.

The following patterns are considered problems:

```css
a { aspect-ratio: 2; }
a { aspect-ratio: 1.5; }
a { aspect-ratio: 1.7778; }
a { aspect-ratio: 1.7/1; }
```

The following patterns are *not* considered problems:

```css
a { aspect-ratio: 2 / 1; }
a { aspect-ratio: 3 / 2; }
a { aspect-ratio: 16/9; }
a { aspect-ratio: 17/10; }
```

#### Secondary option `ignoreDecimalFraction: true` (default: `false`)

The following patterns are considered problems:

```css
a { aspect-ratio: 2; }
a { aspect-ratio: 1.5; }
a { aspect-ratio: 1.7778; }
```

The following patterns are *not* considered problems:

```css
a { aspect-ratio: 2 / 1; }
a { aspect-ratio: 3 / 2; }
a { aspect-ratio: 16/9; }
a { aspect-ratio: 1.7/1; }
```
