### ISSUE TITLE
Require tabs for indentation, but don't count tabs, or permit 

### ISSUE THREAD

**Issue by crstauf** [stylelint/stylelint#6595]
### What is the problem you're trying to solve?

I nest my CSS rules, to assist with very quickly identifying variants.

```css
.a .animate {
	transition: opacity 0.2s;
	opacity: 0;
}

	html.js .a.show .animate {
		opacity: 1;
	}
```

Stylelint allows me to force tabs be used for indentation, but throws an error about expecting zero indents on the `html.js .a.show .animate` line. This is very similar to how you would structure variations within SASS/LESS, so supporting it in CSS would be great.

Asked: https://stackoverflow.com/questions/75263748/stylelint-require-tabs-instead-of-spaces-for-indenting-but-dont-count-tabs/

### What solution would you like to see?

Option to disable counting of tabs, or behavior that identifies the definition is a variant of the previous definition, and additional indenting is permitted.
