### ISSUE TITLE
Fix `selector-not-notation` autofix for `"simple"`

### ISSUE THREAD

**Issue by FloEdelmann** [stylelint/stylelint#6606]
### What steps are needed to reproduce the bug?

```css
.foo:not(.bar, .baz) .content {
    display: none;
}
```

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "selector-not-notation": "simple"
  }
}
```

### How did you run Stylelint?

CLI `stylelint **/*.{vue,scss}`

### Which version of Stylelint are you using?

14.16.1

### What did you expect to happen?

Autofix to

```css
.foo:not(.bar):not(.baz) .content {
    display: none;
}
```

### What actually happened?

Autofix to

```css
.foo:not(.bar) .content.content {
    display: none;
}
```

### Does the bug relate to non-standard syntax?

No, only native CSS syntax is involved.

### Related issues

* https://github.com/stylelint/stylelint/issues/6236
* https://github.com/stylelint/stylelint/issues/3853
