### ISSUE TITLE
Add new *-declaration keyword options to the declaration-block-semicolon-* rules

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#663]
Ref: https://github.com/stylelint/stylelint/issues/648

Add the following options:

* `always-multi-line-declaration`
* `never-multi-line-declaration`
* `always-single-line-declaration`
* `never-single-line-declaration`

To the following rules:

* [ ] `declaration-block-semicolon-space-before`
* [ ] `declaration-block-semicolon-space-after`
* [ ] `declaration-block-semicolon-newline-before`
* [ ] `declaration-block-semicolon-newline-after`

This is so the following style:

```css
a {
  background:
    linear-gradient(
      120deg,
      color(#bfd8ee a(.95)) 20%,
      color(#cbc3f7 a(.95))
    ) fixed,
    url("https://farm7.staticflickr.com/6017/5963681346_0d620eff9a_z.jpg")
    50% 50% / cover no-repeat fixed
  ;
  color: red;
}

b { top: 0; right: 0; }
```

Can be enforced with a config like:

```json
{
  "declaration-block-semicolon-newline-after": "always-multi-line",
  "declaration-block-semicolon-newline-before": "always-multi-line-declaration",
  "declaration-block-semicolon-space-after": "always-single-line", 
  "declaration-block-semicolon-space-before": "never-single-line-declaration"
}
```
