### ISSUE TITLE
selector-anb-no-unmatchable false alarms

### ISSUE THREAD

**Issue by woldtwerk** [stylelint/stylelint#6719]
### What steps are needed to reproduce the bug?

error first line, first character
```css
@layer tailwind-components {
  .foo {
     display: block;
  }
}
```

error first line, first character
```css
:root {
  --c-foo: red;
}

```

worst part is that settings:

```json
"rules": {
      "selector-anb-no-unmatchable": null
    }
```
is completely ignored.

### What Stylelint configuration is needed to reproduce the bug?

```js
extends: [
    'stylelint-config-standard',
  ],
```

### How did you run Stylelint?

pnpm exec stylelint \"web/themes/custom/**/*.css\" --allow-empty-input --ignore-path=.gitignore --fix

### Which version of Stylelint are you using?

15.3.0

### What did you expect to happen?

no error

being able to disasble the rule

### What actually happened?

Unknown rule selector-anb-no-unmatchable selector-anb-no-unmatchable
