### ISSUE TITLE
Fix `unit-no-unknown` false positives for the second and subsequent `image-set()` with `x` descriptor

### ISSUE THREAD

**Issue by chalkygames123** [stylelint/stylelint#6721]
### What steps are needed to reproduce the bug?

Just lint the following CSS with `unit-no-unknown` turned on.

`test.css`:

```css
a {
	background-image: url('first.png'),
		image-set(url('second.png') 1x, url('second@2x.png') 2x);
	background-image: url('first.png'), url('second.png'),
		image-set(url('third.png') 1x, url('third@2x.png') 2x);
}
```

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "unit-no-unknown": [
      true
    ]
  }
}
```

### How did you run Stylelint?

CLI with `stylelint test.css`

### Which version of Stylelint are you using?

`15.3.0`

### What did you expect to happen?

No problems to be reported.

### What actually happened?

The `unit-no-unknown` rule reports the following problems when using the `x` unit in a value for an `image-set()` function.

```
test.css
 3:32  ✖  Unexpected unknown unit "x"  unit-no-unknown
 3:57  ✖  Unexpected unknown unit "x"  unit-no-unknown
 5:31  ✖  Unexpected unknown unit "x"  unit-no-unknown
 5:55  ✖  Unexpected unknown unit "x"  unit-no-unknown
```

Related: https://github.com/stylelint/stylelint/pull/4654

### Does the bug relate to non-standard syntax?

No.
