### ISSUE TITLE
Fix `function-url-quotes` autofix for double-slash comments in SCSS maps

### ISSUE THREAD

**Issue by jgerigmeyer** [stylelint/stylelint#6741]
### What steps are needed to reproduce the bug?

```scss
$test-map: (
  // test comment
  foo: 'bar'
);
```

Might be a bug with the `postcss-scss` custom syntax imported by stylelint-config-recommended-scss?

### What Stylelint configuration is needed to reproduce the bug?

```yaml
extends:
  - stylelint-config-recommended-scss

rules:
  function-url-quotes: always
```

or

```yaml
extends:
  - stylelint-config-recommended-scss

rules:
  function-url-quotes: never
```

### How did you run Stylelint?

https://stylelint.io/demo/#N4Igxg9gJgpiBcIAkAXGBnFBaAtgQwAd4ACACgB0A7Y4geluLU2MhxxkpSpoDMIISAcgBGeAE6CqASgDcVEABoQPAJYAbGADk87BCBgAPHQQ0A6dGHTpF4CJVUBzPYbSUo6eN2JZimAJ4aaiqcWJD2Kg5YYjCs7G4wUFgWVlRUYgCuGh5ePOmUYCgqdljpYmpYAI7pEEwkeGoA7nh+6PJKYY4AYhBi+Ch6fjpqNrAE1ojAXuQg-oHBXAjE02p4TAsKUzMoATBBIR0RUTEQbBywicmti8urGAtUAL4gD0A

### Which version of Stylelint are you using?

`15.3.0`

### What did you expect to happen?

No change to original code:

```scss
$test-map: (
  // test comment
  foo: 'bar'
);
```

### What actually happened?

```scss
$test-map: (
  /* test comment*/
  foo: 'bar'
);
```

### Does the bug relate to non-standard syntax?

SCSS maps
