### ISSUE TITLE
Fix `declaration-block-no-duplicate-properties` SyntaxError

### ISSUE THREAD

**Issue by yoyo837** [stylelint/stylelint#6791]
### What steps are needed to reproduce the bug?

lint error:
```scss
@mixin iosSafeAreaBottom($offset: 0px) {
  bottom: $offset;
  bottom: calc(var(--body-padding-offset-bottom) + $offset);
  bottom: calc(var(--body-padding-offset-bottom) + $offset + constant(safe-area-inset-bottom));
  bottom: calc(var(--body-padding-offset-bottom) + $offset + env(safe-area-inset-bottom, 0px));
}
```

### What Stylelint configuration is needed to reproduce the bug?

```js
module.exports = {
  extends: [
    'stylelint-config-standard',
    'stylelint-config-html/vue',
    'stylelint-config-html',
    'stylelint-config-recommended-vue/scss',
    'stylelint-config-recommended-vue',
    'stylelint-prettier/recommended',
  ],
  overrides: [
    {
      files: ['**/*.vue'],
      customSyntax: 'postcss-html',
    },
    {
      files: ['**/*.scss'],
      customSyntax: 'postcss-scss',
    },
    {
      files: ['**/*.less'],
      customSyntax: 'postcss-less',
    },
  ],
  plugins: ['stylelint-scss'],
  rules: {
    'selector-pseudo-class-no-unknown': [
      true,
      {
        ignorePseudoClasses: ['first'],
      },
    ],
    'no-descending-specificity': null,
    'font-family-no-missing-generic-family-keyword': null,
    'no-invalid-position-at-import-rule': [
      true,
      {
        ignoreAtRules: ['use', 'tailwind'],
      },
    ],
    'selector-class-pattern': null,
    'at-rule-no-unknown': [
      true,
      {
        ignoreAtRules: [
          'mixin',
          'include',
          'extend',
          'each',
          'use',
          'tailwind',
          'layer',
          'apply',
          'if',
          'else',
          'at-root',
        ],
      },
    ],
    'scss/at-rule-no-unknown': [
      true,
      {
        ignoreAtRules: [
          'mixin',
          'include',
          'extend',
          'each',
          'use',
          'tailwind',
          'layer',
          'apply',
          'if',
          'else',
          'at-root',
        ],
      },
    ],
    'selector-pseudo-element-no-unknown': [
      true,
      {
        ignorePseudoElements: ['v-deep'],
      },
    ],
    'color-function-notation': null,
    'import-notation': null,
    'length-zero-no-unit': null,
    'function-no-unknown': [
      true,
      {
        ignoreFunctions: ['env', 'constant', 'math.div', '-', 'red', 'blue', 'green'],
      },
    ],
    // less 编译 rgb(0 0 0 / 0.03) 会输出 #000000, 但编译 rgba(0, 0, 0, 0.03) 又能正确输出 rgb(0 0 0 / 0.03)
    // 先禁用
    'alpha-value-notation': null,
    'selector-not-notation': null,
    // FIXME: 迁移完毕后修复⬇️
    'scss/at-extend-no-missing-placeholder': null,
    // postcss-preset-env 好像没有默认支持 "context"
    'media-feature-range-notation': 'prefix',
  },
};

```

### How did you run Stylelint?

Cli with `stylelint '**/*.{css,scss}'`

### Which version of Stylelint are you using?

15.5.0

### What did you expect to happen?

run lint success

### What actually happened?

run lint throw SyntaxError error

### Does the bug relate to non-standard syntax?

scss
