### ISSUE TITLE
New rule: disallow percent size values that are not `0%` or `100%`.

### ISSUE THREAD

**Issue by giladgd** [stylelint/stylelint#6803]
### What is the problem you're trying to solve?

I would like to have a linting error for percent size values in CSS that are not `0%` or `100%`.
Almost all of the usages I've seen so far of percent size values that are not `0%` or `100%` could have been replaced with a more responsive alternative approach, such as using flexbox and `min`, and `max` size values.
I would like to have a Stylelint rule to discourage using such values in the first place.

Examples of popular bad usages I seen so far:
```scss
.something {
    // using flexbox is better for most cases,
    // as it considers the content of the element and neighboring elements when calculating the size of it.
    // It's possible to also configure flexbox to not consider the content of the element,
    // but when you do need such behavior, you have to deliberately configure it this way
    width: 33%;

    // Centering an element using flexbox is better
    top: 50%;

    // 99% of the usages of this that I've seen so far tried to make an element look circular,
    // but using `999px` is more responsive when the content prevents the element from being circular
    border-radius: 50%;
}
```

### What solution would you like to see?

I would like to have a new rule for this
