### ISSUE TITLE
Fix `declaration-block-no-redundant-longhand-properties` autofix for `transition`

### ISSUE THREAD

**Issue by jathak** [stylelint/stylelint#6812]
### What steps are needed to reproduce the bug?

Given code like:
```css
a {
  transition-delay: 500ms;
  transition-duration: 250ms;
  transition-timing-function: ease-in-out;
  transition-property: transform, visibility;
}
```

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "declaration-block-no-redundant-longhand-properties": true
  }
}
```

### How did you run Stylelint?

https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdilAXATkpgM4CWupEmAtLADZICe8KArAAzsC2xA3FjgJEyFKrQCuhUZhYAmDj37Y8hEuUo0KXUpgDm1AGbjMYaSxhJiMajuoRxuJYNUiN1AA74I7mPlzMVYQMIfC4AGhQAN1IyACNSOnJGJQBfEDCQAwSYADkkLjhEGAAPfPc6GAA6MGJidPAqLN0EEAxldBAS3BhMKGIOlgBtARwUDuJ-CsTMXGpITCbqCaIoJHwoDpGAXSw0jPmmgDEQriRcFoArYip62Hc6xDacccmYadwBsZAGbomOsJGL0YUx0swOpH0y16aw2CC+PxgfxAuxAKSAA

### Which version of Stylelint are you using?

`15.6.0`

### What did you expect to happen?

No problems to be reported, or, if a `declaration-block-no-redundant-longhand-properties` error is reported, the autofix should be 
```css
a {
  transition: transform 250ms ease-in-out 500ms, visibility 250ms ease-in-out 500ms;
}
```

### What actually happened?

An error of `Expected shorthand property "transition"` with an incorrect suggested autofix of:

```css
a {
  transition: transform, visibility 250ms ease-in-out 500ms;
}
```

### Does the bug relate to non-standard syntax?

No

### Proposal to fix the bug

IMO, this error shouldn't be reported at all for transitions with multiple properties (as reported in https://github.com/stylelint/stylelint/issues/4074), but if it is considered an error, then the autofix at least needs to be changed.
