### ISSUE TITLE
stylelint dont working properly with scss

### ISSUE THREAD

**Issue by AesthetiCoder** [stylelint/stylelint#6819]
### What steps are needed to reproduce the bug?

i have a normal config of stylint and i get an error of customSyntax when linting i have a normal scss file and get that error

`you should use the "customSyntax" option when linting something other than CSS`

### What Stylelint configuration is needed to reproduce the bug?

you can reproduce the error running this stylelint config 

```json
{
  "extends": "stylelint-config-standard-scss"
}
```

in the output of the vscode console i get the error, this dont happen with all the files, stylelint can work good with other files of mi projects, the file that have problems is normalize.scss from https://necolas.github.io/normalize.css/

i dont want to put a lot of code here to make this issue simple but other file stylelint has problem is my _reset.scss here is the file 

```scss
html,
body,
p,
ol,
ul,
li,
dl,
dt,
dd,
blockquote,
figure,
fieldset,
legend,
textarea,
pre,
iframe,
hr,
h1,
h2,
h3,
h4,
h5,
h6 {
  margin: 0;
  padding: 0;
}

h1,
h2,
h3,
h4,
h5,
h6 {
  font-size: 100%;
  font-weight: normal;
}

ul {
  list-style: none;
}

button,
input,
select {
  margin: 0;
}

html {
  box-sizing: border-box;
}

*,
*::before,
*::after {
  box-sizing: inherit;
}

img,
video {
  max-width: 100%;
  height: auto;
}

iframe {
  border: 0;
}

table {
  border-spacing: 0;
  border-collapse: collapse;
}

td,
th {
  padding: 0;
}
```

also this happends if i do a normal config of stylelint like this, with plugins or not the output console throw the same error

```json
  "plugins": ["stylelint-scss", "stylelint-order"],
  "customSyntax": "postcss-scss",
  "rules": {}
```

### How did you run Stylelint?

i just let my vscode format the files when saving the files, when i run 

```shell
npx stylelint "**/*.scss"
```

i dont get any output in the consele or any error

### Which version of Stylelint or dependencies are you using?

postcss: 8.4.21
postcss-scss:  4.0.6
stylelint: 15.6.0

### What did you expect to happen?

not to have this output in the consele maybe can be an error of the vscode extension that dont detect the customSyntax or is just somehing of the file normalize.scss and reset.scss

### What actually happened?

`you should use the "customSyntax" option when linting something other than CSS`
