### ISSUE TITLE
Fix `declaration-block-no-redundant-longhand-properties` autofix with `cubic-bezier()`

### ISSUE THREAD

**Issue by vossmalte** [stylelint/stylelint#6839]
### What steps are needed to reproduce the bug?

```css
.class-name {
  transition-delay: 25ms;
  transition-duration: 10ms;
  transition-property: margin;
  transition-timing-function: cubic-bezier(0, 1, 1, 1);
}
```

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "declaration-block-no-redundant-longhand-properties": true,
  }
}
```

### How did you run Stylelint?

```shell
stylelint *.css --fix
```

### Which version of Stylelint or dependencies are you using?

stylelint 15.6.1
stylelint-config-standard 33.0.0

### What did you expect to happen?

Preserve the properties when transforming to shorthand:
```css
.class-name {
  transition: margin 10ms cubic-bezier(0, 1, 1, 1) 25ms;
}
```

### What actually happened?

is automatically fixed to
```css
.class-name {
  transition: margin 10ms cubic-bezier(0 25ms;
}
```
where the further parameters and closing bracket of the timing function are lost. This is a syntax error and breaks the styles.
