### ISSUE TITLE
CLI not reporting errors after updating to 15.6.3

### ISSUE THREAD

**Issue by romainmenke** [stylelint/stylelint#6899]
HI Guys.
Something wrong after update from 15.6.2 to 15.6.3 

```css
.test {
    margin-bottom: 20zrr;     <-- incorrect unit here
}
```
With **stylelint 15.6.2**
CLI and VSCode reported:
`Unexpected unknown unit "zrr"  unit-no-unknown`

With **stylelint 15.6.3**
CLI:
no errors reported
VSCode:
`Unexpected unknown unit "zrr" (unit-no-unknown)Stylelint[unit-no-unknown](https://stylelint.io/user-guide/rules/unit-no-unknown)`

_Originally posted by @ScorpAL in https://github.com/stylelint/stylelint/issues/6879#issuecomment-1576249573_
