### ISSUE TITLE
Fix `declaration-block-no-redundant-longhand-properties` autofix for `border-width` shorthand

### ISSUE THREAD

**Issue by timkuehnlein** [stylelint/stylelint#6947]
### What steps are needed to reproduce the bug?

This syntax will raise the warning `Expected shorthand property "border-width" (declaration-block-no-redundant-longhand-properties)Stylelint[declaration-block-no-redundant-longhand-properties](https://stylelint.io/user-guide/rules/declaration-block-no-redundant-longhand-properties)`.

```CSS
div {
    border-top-width: 0px;
    border-right-width: 1px;
    border-bottom-width: 2px;
    border-left-width: 3px;
}
```

It will be fixed to the following code. (The order of the original items is not relevant.)

```CSS
div {
    border-width: 0 2px 3px 1px;
}
```

If two values should be combined, this leads to the same error:

```CSS
div {
    border-top-width: 0px;
    border-right-width: 1px;
    border-bottom-width: 2px;
    border-left-width: 1px;
}
```

becomes:

```CSS
div {
    border-width: 0 2px 1px 1px;
}
```

### What Stylelint configuration is needed to reproduce the bug?

{
  "extends": [
    "stylelint-config-standard"
  ]
}

### How did you run Stylelint?

Stylelint demo

### Which version of Stylelint or dependencies are you using?

[stylelint](https://stylelint.io/)@15.8.0
[stylelint-config-standard](https://www.npmjs.com/package/stylelint-config-standard)@33.0.0

### What did you expect to happen?

```CSS
div {
    border-top-width: 0px;
    border-right-width: 1px;
    border-bottom-width: 2px;
    border-left-width: 3px;
}
```

Should become:

```CSS
div {
    border-width: 0 1px 2px 3px;
}
```

If two values should be combined, this leads to the same error:

```CSS
div {
    border-top-width: 0px;
    border-right-width: 1px;
    border-bottom-width: 2px;
    border-left-width: 1px;
}
```

Should become:

```CSS
div {
    border-width: 0 1px 2px;
}
```

### What actually happened?

```CSS
div {
    border-top-width: 0px;
    border-right-width: 1px;
    border-bottom-width: 2px;
    border-left-width: 3px;
}
```

Wrongly becomes:

```CSS
div {
    border-width: 0 2px 3px 1px;
}
```

If two values should be combined, this leads to the same error:

```CSS
div {
    border-top-width: 0px;
    border-right-width: 1px;
    border-bottom-width: 2px;
    border-left-width: 1px;
}
```

Wrongly becomes:

```CSS
div {
    border-width: 0 2px 1px 1px;
}
```
