### ISSUE TITLE
Fix `function-linear-gradient-no-nonstandard-direction` false positives for `<color-interpolation-method>`

### ISSUE THREAD

**Issue by crystalfp** [stylelint/stylelint#6951]
### What steps are needed to reproduce the bug?

```css
button {
  background: linear-gradient(
                in oklab
                to bottom,
                red 0%,
                blue 100%
              );
}
```

### What Stylelint configuration is needed to reproduce the bug?

```yaml
extends:
  - stylelint-config-standard
  - stylelint-config-standard-vue
  - stylelint-config-standard-scss
  - stylelint-config-recommended-vue/scss
  - stylelint-config-recommended-scss

rules:
  alpha-value-notation: number
  at-rule-no-unknown: null
  color-function-notation: null
  color-hex-length: long
  comment-whitespace-inside: always
  declaration-block-single-line-max-declarations: 4
  font-family-no-missing-generic-family-keyword: true
  function-url-quotes: always
  max-nesting-depth: 3
  media-feature-name-no-vendor-prefix: true
  scss/at-rule-no-unknown: true
  scss/dollar-variable-empty-line-before: null
  scss/dollar-variable-pattern: null
  scss/selector-no-redundant-nesting-selector: null
  scss/double-slash-comment-empty-line-before: null
  selector-no-qualifying-type: null
  selector-pseudo-class-no-unknown: [true, {ignorePseudoClasses: [deep]}]
  shorthand-property-no-redundant-values: null
```

### How did you run Stylelint?

```shell
stylelint *.css --config .stylelintrc.yaml
```

### Which version of Stylelint or dependencies are you using?

15.8.0

### What did you expect to happen?

No problem to be reported

### What actually happened?

```
test.css
23:31  ✖  Unexpected nonstandard direction  function-linear-gradient-no-nonstandard-direction 
```

### Does the bug relate to non-standard syntax?

This is a recent syntax about color management in CSS
