### ISSUE TITLE
Rule idea: `prefer-unitless-number`

### ISSUE THREAD

**Issue by silverwind** [stylelint/stylelint#6985]
### What is the problem you're trying to solve?

Some properties like `line-height` offer unit and unitless variants and [are recommended](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#number) to be specified without unit so that child elements with different font height can derive a likely intended value for this inherited property. This is problematic:

```css
h1 {
  line-height: 1em;
}
```

### What solution would you like to see?

A new rule that suggests and autofixes to:

```css
h1 {
  line-height: 1;
}
```

There might be more properties that might benefit from this rule.

**Comment by ybiquitous** [comment]
@silverwind Thanks for the proposal. Sounds interesting.

I guess the existing rule [`declaration-property-unit-disallowed-list`](https://stylelint.io/user-guide/rules/declaration-property-unit-disallowed-list) may cover this case. See [this demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdugLgGwEtMYBaACxgIHMyd4UBGGAWwG4sBfLEAGhADMCeGADkkzOIhgAPcQAdhAOjABnFb3ARMgqghAZMKFOhAAnAK7CVJ+gaNGTsMHiSmkOAlpJzTEOTFMcAE8Sc0wCHBIoAhUkPDwIAHcYKBJCFRwbNCx7exNCYnJKGkyEFABtExYTAF0c+y5DFEbGjUhtagAxCFNmdz0AKxUtDVg5dUQ7YxAMoOEC0vp89xgMk04QDiA).

```json
{
  "rules": {
    "declaration-property-unit-disallowed-list": {
      "line-height": ["em"]
    }
  }
}
```

```css
a {
  line-height: 1em;
/*             ^~~ Unexpected unit "em" for property "line-height"
 */
}
```

If we'd like to disallow all units, we should specify the option like `"line-height": ["/.+/"]`, but there is no support for regex units now.

Any thoughts?
