### ISSUE TITLE
Possible to conditionally require empty lines?

### ISSUE THREAD

**Issue by corysimmons** [stylelint/stylelint#701]
I'd like to make a rule that empty lines are required before a ruleset _unless_ that ruleset is the first nested rule.

```css
.foo {
  .bar {
    color: blue;
  }

  .baz {
    color: red;
  }
}
```

The reason I need this feature is because I don't want single nested things to look like this:

```css
.foo {

  .bar {

    .baz {
      color: red;
    }

  }

}
```

That's entirely too many newlines for one ruleset. Rather it would be better if it looked like:

```css
.foo {
  .bar {
    .baz {
      color: red;
    }
  }
}
```

**Comment by davidtheclark** [comment]
@corysimmons : Does this existing rule work for you? https://github.com/stylelint/stylelint/tree/master/src/rules/rule-nested-empty-line-before

**Comment by corysimmons** [comment]
I saw that one, but nah, then we end up with weird little rulesets like:

```css
.foo {

  .bar {
  
    .baz {
      color: red;
    }
  }
}
```
