### ISSUE TITLE
Break up single/double quote rules

### ISSUE THREAD

**Issue by corysimmons** [stylelint/stylelint#704]
I want

```css
[class="foo"] {
  content: '';
}
```

**Comment by davidtheclark** [comment]
See https://github.com/stylelint/stylelint/issues/96

The main point there:

> I am not sure that distinguishing selector attribute quotes from all other "string" quotes makes a ton of sense unless we get even more granular: if the principle is that we're going to allow the user to specify a quote style in every location in which a string can be used, then it would be consistent; if not, isn't it a kind of arbitrary split to single out selector attributes?

I don't want to try to splitting out quote rules unless someone can come up with a sane schema for doing so. Ideas?

**Comment by corysimmons** [comment]
I don't think it's arbitrary to have double quotes for selectors and single quotes for everything else.

I see stuff like this all the time:

```css
[class="foo"] {
  conten: '';
  background: url('foo.jpg');
}
```
