### ISSUE TITLE
Fix `declaration-property-value-no-unknown` false negatives for nested declarations

### ISSUE THREAD

**Issue by romainmenke** [stylelint/stylelint#7062]
### What minimal example or steps are needed to reproduce the bug?

```css
.foo {
	color: 10px; /* has a warning */
	color: red;
}

.foo {
	@media (screen) {
		color: 10px; /* no warning */
		color: red;
	}
}
```

_I added `color: red` to make sure there weren't any false positives._

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "declaration-property-value-no-unknown": true
  }
}
```

### How did you run Stylelint?

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0AzCEAEwA6A7bALpADYQBO8GAjAAwAOAHgNx6EnmVkxQu4C+rXKnRZWBAAIBbbgEsAhhgAUAZzBcYuAJSj8BNhFIVq9ZmP2HO3XoQH8QAGhAoZxGADk50hCBgNPdVyQwZWUHcAhcZwBzbxxcDAxsEDIAV1dlJMo4hISk2DBiOTI5AhkIgFo6Mgg6GDICAE9ygDc5YhSYctwIcpTcAGtugHd8BAwCVJg8BNs+MMhImSiAMXJJEu8AK2UIsNg6UMRsxJBlRtdiGVw9MaTCghgzpPtpk7OGi6uCcoXo8rO5LgoEUoJkTvdHjc8HM+EA)

### Which Stylelint-related dependencies are you using?

```json
{
  "stylelint": "latest",
  "stylelint-config-standard": "latest"
}
```

### What did you expect to happen?

I expected to see two errors.  
One for each `color: 10px;`.

### What actually happened?

Only one error was reported, for the regular, unnested rule.
