### ISSUE TITLE
Fix `property-no-unknown` false positives for scroll-driven animations

### ISSUE THREAD

**Issue by renato-bohler** [stylelint/stylelint#7088]
### What minimal example or steps are needed to reproduce the bug?

```css
.view-timeline-works {
	view-timeline: --my-name block;
	view-timeline-axis: block;
	view-timeline-inset: 200px;
	view-timeline-name: --my-name;
}

.animation-range-works {
	animation-range: contain 100px;
	animation-range-start: contain;
	animation-range-end: 100px;
}

.animation-timeline-does-not-work {
	animation-timeline: view();
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "extends": [
    "stylelint-config-standard"
  ]
}
```

### How did you run Stylelint?

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0A3AljA7gWgC5oFsYAbNAOxm0wgCcBrAZwAJgAdM13dLPQk8mPCbZsBAJ7YyAQyJMARsQhg6AbnaduOfEVIVsUgB5oGQhUtXquGLX12VyDGLiEAmAAxuADgbUcrPbX49aSIhEXFJGRhfAF91MiQpMkIpfAgybBokgHNKanpmNj8klLSMrLJcoUgyXClyJgBGD29fThKCVLR0zJzKBjqaZyYauvI2uuTOst7KyhgyKCFmrx92OI4Ejq6ewLtsKAgYBkkIXCpaOhZLbZm9gSFNAAoASlj2EAAaEAAzNGIYAA5KIIEAwAwyTwApBgBgML7gdJ-bKgopMJisMEGXALKAMTFCADa7HR6MxAzEAN05xqyOwAySUCkNCgmJJTAAuusEbS0NkAGK0aaggBWDHSCNgnnhiDRGJAFKp5FwBPlxFSxxVX3Z5NwlKCNKRfPpkyZLNVmPVOIGbLIMRAMSAA)

### Which Stylelint-related dependencies are you using?

```json
{
  "stylelint": "15.10.2",
  "stylelint-config-standard": "34.0.0"
}
```

### What did you expect to happen?

The `animation-timeline` property to not be unknown.

### What actually happened?

The following error gets thrown:

```
Unexpected unknown property "animation-timeline"  property-no-unknown
```

### Do you have a proposal to fix the bug?

Add `animation-timeline` to `lib/reference/properties.js`? Though I'm not familiar with the source for this library, so I don't understand why `view-timeline` and `animation-range` properties are not unknown if they don't seem to be defined there.

I also don't comprehend why the `view` function is not being flagged as unknown as I don't see it being declared in `lib/reference/functions.js`.

So maybe we should add those as well? If that's the case, I'm happy to open a PR.
