### ISSUE TITLE
Fix `function-calc-no-unspaced-operator` false negatives when combined with properly spaced operator

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [stylelint/stylelint#7181]
### What minimal example or steps are needed to reproduce the bug?

```css
.a {
  /* Error */
  top: calc(5px+3px);
}

.b {
  /* No error */
  top: calc(5px+3px - 2px);
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "function-calc-no-unspaced-operator": true
  }
}
```

### How did you run Stylelint?

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0BDABMAOgOzWg9AFRoCiATmRGWofjngC4QAO8aYKANmABQCszAB4BqAMxCAlAG4cAXxw4kAIwz0CxAHIQ0MClRp1caJq3ZdeAkeMFoAtGgBMkmdnnYQAGhAAzAJacYDRQAWzhEGEEQ5gCkMABnOM9wCGw-AHMEECwjTBAyAFcAuNy2bLw8XO987DAGXxTbDm5bbAhbarjmFDAYKFsWXRQmMhLjApg1NzckyFTfNIAxKmChzIArOJSk2GZExDK0XLiGAE8Azl9sBlHcziGYY9yPNSPT88uGRpT022OUbCgKDIUBuIDuDAe1xAchAsiAA)

### Which Stylelint-related dependencies are you using?

```json
{
  "stylelint": "^15.10.3",
  "stylelint-config-standard": "^34.0.0"
}
```

### What did you expect to happen?

Rule should report an error for each instance of an unspaced operator.

### What actually happened?

No error is reported if the expression contains at least one properly spaced operator.

This actually caused (well, failed to catch) a real error in our codebase. We had the following code:
```css
.foo {
  top: max(-75px, min(-75px, calc(-0.33 * (100vh - 311px -61px - 50px -64px) + 15px)));
}
```
which is not valid (apparently the `-` in `-61px` and `-64px` is interpreted as the unary minus). It worked for a long time because we were using `cssnano` which changed the spacing and "fixed" the expression - but when I switched to [@csstools/postcss-minify](https://www.npmjs.com/package/@csstools/postcss-minify) which leaves the whitespace alone, the style stopped working.

@romainmenke Thought this might interest you (it's not a bug in @csstools/postcss-minify but rather a bug that was previously hidden by another minifier) :)
