### ISSUE TITLE
`function-no-unknown`: fix `linear` `xywh` `light-dark` false positives

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/stylelint#7226]
### What minimal example or steps are needed to reproduce the bug?

```css
:root {
  color-scheme: light dark;

  --text-color: light-dark(#777, #000);
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "function-no-unknown": true
  }
}
```

### How did you run Stylelint?

https://stylelint.io/demo

### See also

https://drafts.csswg.org/css-color-5/#light-dark
https://github.com/mdn/browser-compat-data/pull/20935

### Do you have a proposal to fix the bug?

1. <del>either update https://github.com/niksy/css-functions-list/blob/master/index.json</del>
2. or add an exception
