### ISSUE TITLE
Add `"ignoreLonghands": []` to `declaration-block-no-redundant-longhand-properties`

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/stylelint#7232]
## use cases

- [`text-decoration`](#text-decoration)
- [`background`](#background)

## rationale

If a browser doesn't support the new arity for a given shorthand, it will drop it altogether.
For example if we were to introduce an enhancement for the current fixer of `text-decoration` by adding support to
`text-decoration-thickness`, for a lot of users of the rule it would introduce a hard to detect regression.  
They would have to rely on `"ignoreShorthands": ["text-decoration"]` which is arguably a downgrade compared to the status quo. Hence a new option is required to be more granular and cross-browser.

### rationale for new fix

https://github.com/stylelint/stylelint/pull/6580#discussion_r1095994177
#7060

### without option

```css
a {
  text-decoration-line: underline;
  text-decoration-style: solid;
  text-decoration-color: green;
  text-decoration-thickness: 1px;
}
```
becomes
```css
a {
  text-decoration: underline solid green 1px;
}
```

### with `"ignoreLonghands": ["text-decoration-thickness"]`

```css
a {
  text-decoration-line: underline;
  text-decoration-style: solid;
  text-decoration-color: green;
  text-decoration-thickness: 1px;
}
```
becomes
```css
a {
	text-decoration: underline solid green;
	text-decoration-thickness: 1px;
}
```

### references

https://bugs.webkit.org/show_bug.cgi?id=190774
https://drafts.csswg.org/css-text-decor-4/#text-decoration-property

### implementation details

[Firefox 69 supports this feature (preffed off) under the name `text-decoration-width`, behind the pref layout.css.text-decoration-width.enabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1567282#c8).
[`text-decoration-skip` is not part of the shorthand](https://drafts.csswg.org/css-text-decor-4/#text-decoration-property) but will have to be eventually added in a separate PR. 

### browser support

https://caniuse.com/?search=text-decoration-thickness

### rationale

https://caniuse.com/background-img-opts

### example

```json
{
  "fix": true,
  "rules": {
    "declaration-block-no-redundant-longhand-properties": [
      true,
      { "ignoreLonghands": ["background-size", "background-origin", "background-clip"] }
    ],
  }
}
```

```css
a {
  background-image: none;
  background-position: 0% 0%;
  background-size: auto auto;
  background-repeat: repeat;
  background-origin: padding-box;
  background-clip: border-box;
  background-attachment: scroll;
  background-color: transparent;
}
```
becomes
```css
a {
  background: repeat scroll 0% 0% none transparent;
  background-size: auto auto;
  background-origin: padding-box;
  background-clip: border-box;
}
```

**Comment by Mouvedia** [comment]
Iv reverted to _status: needs discussion_ because on a browser that doesn't support `text-decoration-thickness`
```css
a {
  text-decoration-thickness: 1px;
}
```
will simply be ignored, but
```
a {
  text-decoration: underline solid green 1px;
}
```
will be dropped altogether because it will consider invalid.



**tl;dr**: if it's not configurable (pick between 3 or 4) it's not worth adding IMHO
i.e. it would require `ignoreProperty: ["/regex/", /regex/, "string"]`

**Comment by ybiquitous** [comment]
Hum, I think it's still worth to support `text-decoration-thickness` in the following case:

```css
a {
	text-decoration-line: underline;
	text-decoration-style: solid;
	text-decoration-color: green;
	text-decoration-thickness: 1px;

	/* ↓↓↓ autofixed */

	text-decoration: underline solid green 1px;
}
```

At the same time, we'd like to keep the current behavior if `text-decoration-thickness` is absent:

```css
a {
	text-decoration-line: underline;
	text-decoration-style: solid;
	text-decoration-color: green;

	/* ↓↓↓ autofixed */

	text-decoration: underline solid green;
}
```

Can we achieve this by the rule's implementation? @mattxwang

**Comment by Mouvedia** [comment]
That's possible, but as I have explained in the [previous comment](https://github.com/stylelint/stylelint/issues/7232#issuecomment-1762654301), it is not worth adding unless we have a new option that let's us ignore `text-decoration-thickness` for this rule.
e.g. if ignored
```css
a {
	text-decoration-line: underline;
	text-decoration-style: solid;
	text-decoration-color: green;
	text-decoration-thickness: 1px;
}
```
would autofix to
```css
a {
	text-decoration: underline solid green;
	text-decoration-thickness: 1px; // only this line is dropped if the browser doesn't support it
}
```
i.e. the existing `ignoreShorthand: : ["text-decoration"]` is not granular enough and would be considered a downgrade compared to the status quo.
