### ISSUE TITLE
Stylelint is using too modern properties

### ISSUE THREAD

**Issue by Mister-Hope** [stylelint/stylelint#7276]
### What minimal example or steps are needed to reproduce the bug?

```css
.vp-card-container {
  display: flex;
  align-content: stretch;
  align-items: stretch;
  justify-content: center;
}
```

After:

```css
.vp-card-container {
  display: flex;
  place-content: stretch center;
  align-items: stretch;
}
```

### What minimal configuration is needed to reproduce the bug?

With the default `stylelint-config-recommended`

### How did you run Stylelint?

stylelint test.css

### Which Stylelint-related dependencies are you using?

stylelint: 15.11.0
stylelint-config-recommended: 13.0.0

### What did you expect to happen?

Firefox supposed to be a major browser, and flex supposed to be a common layout.

![image](https://github.com/stylelint/stylelint/assets/33315834/29a156c8-ad92-4666-9827-3e1516c894c4)

#### Firefox DOES NOT fully support this shorthand

# My basic point is, stylelint should only auto correct something, at least it's support by every modern browsers. No body should expect something not working on all versions of firefox.

Stylelint should not correct this in recommand config.

### What actually happened?

Layout broken in firefox under this tool

### Do you have a proposal to fix the bug?

I don't think this is a bug, it should be an enhanced existing rule, not working with an existing official config
