### ISSUE TITLE
Rejected -webkit-background-clip with text value

### ISSUE THREAD

**Issue by brunodccarvalho** [stylelint/stylelint#7294]
### What minimal example or steps are needed to reproduce the bug?

```css
.gradient {
  -webkit-background-clip: text;
  background-clip: text;
  -webkit-text-fill-color: transparent;
  -moz-text-fill-color: transparent;
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "defaultSeverity": "error",
  "rules": { "property-no-vendor-prefix": true }
}
```

### How did you run Stylelint?

```shell
npx stylelint --config=.stylelintrc.json test.css
```

### Which Stylelint-related dependencies are you using?

15.11.0

### What did you expect to happen?

Since the rule does not delete the prefixed `text-fill-color` properties I expect no problems to be reported as `-webkit-background-clip: text` also seems to have [very widespread support](https://caniuse.com/background-clip-text).

`postcss/autoprefixer` has a 5 year old test to accept this [here](https://github.com/postcss/autoprefixer/tree/main/test/cases), see `background-clip.css`

### What actually happened?

```
test.css
 2:3  ✖  Unexpected vendor-prefix "-webkit-background-clip"  property-no-vendor-prefix

1 problem (1 error, 0 warnings)
```

and it is autocorrectable, so it gets replaced with `background-clip: text` if `--fix` is given
