### ISSUE TITLE
Prepare 17.0.0

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#7396]
This is an umbrella issue to capture some of the decisions we made while working on 16.0.0:

- [ ] Remove CommonJs Node.js API (and update our pure ESM deps)
- [ ] Remove deprecated `output` property in Node.js API result object

I'll create issues for these, but we'll likely want to wait at least a few months before touching them.

In the meantime, we can share any thoughts on what may be, if people have time, good things to look at in `16.x`.

It'd be amazing to see:

- more rules that help people write modern CSS consistently
- a built-in resolver so that people can lint in files in context

I think rules like [`color-format-notation`](https://stylelint.io/user-guide/rules/color-function-notation/) help our users write modern CSS code. I'm seeing code in the wild using modern CSS features like:

- `@container`
- `@layer`
- `clamp()` and other math comparison functions
- `has()`
- logical properties & values
- Nesting
- `oklch()`
- relative colours

For example:

```css
:root {
  --dk-color-black-20: oklch(20% 0 0deg);
  --dk-color-black-20-a-10: oklch(from var(--dk-color-black-20) l c h / 10%);
}

@layer defaults {
  :where(body) {
    color: var(--dk-color-black-20);
  }

  :where(a) {
    &:any-link {
      cursor: pointer;
    }

    &:hover {
      text-decoration: none;
    }
  }
}

parent-component {
  margin-inline: auto;

  &:has(child-component) {
    container: child-component / inline-size;
    display: grid;
  }
}

child-component {
  padding: clamp(1rem, 1rem + 1cqi, 2rem);

  @container parent-component (width > 40rem) {
    display: flex;
  }
}
```

There are already a [couple](https://github.com/stylelint/stylelint/issues/5430) of [open](https://github.com/stylelint/stylelint/issues/6421) issues around these, and I will try to make some time to revisit them. And I'll think about what new rules we can create to help people consistently use these modern features.

The built-in resolver already has an issue (https://github.com/stylelint/stylelint/issues/4088). It's a biggy, though, and I've added a "needs help" label because it's likely non-trivial. It'd be great to have as it'd open up linting CSS in the context of a whole CSS codebase. 

What are the things that you'd like? We can broadly discuss them here, or you can create `needs: discussion` issues for them.
