### ISSUE TITLE
Add `media-query-no-invalid` specific problem messages

### ISSUE THREAD

**Issue by coderaiser** [stylelint/stylelint#7401]
### What minimal example or steps are needed to reproduce the bug?

What is wrong with this code? How should I fix it?

```css
@media only screen and (device-width >= 375px) and (device-width <= 667px) and (orientation: landscape),
@media only screen and (max-height: 360px) and (max-width: 640px) {
    .fm {
        height: 55%;
    }

    .files {
        height: 60%;
    }
}
```

### What minimal configuration is needed to reproduce the bug?

defaults

### How did you run Stylelint?

as 🐊[**Putout** Processor CSS](https://github.com/coderaiser/putout/tree/v34.0.7/packages/processor-css)

### Which Stylelint-related dependencies are you using?

latest

### What did you expect to happen?

More detailed error, auto fix

### What actually happened?

 Unexpected invalid media query "only screen and (device-width >= 375px) and (device-width <= 667px) and (orientation: landscape)
