### ISSUE TITLE
no-descending-specificity

### ISSUE THREAD

**Issue by ai** [stylelint/stylelint#748]
One of the main problem in CSS is a different selectors specificity and unexpected overrides as result. 

For example:

```css
.parent .title {
  color: black;
}
.title {
  color: green;
}
```

So possible rules:

1. That all selectors has same specificity.
2. That all selectors has specificity less than `X`. For example, less than `0-2-0`.
3. That selector with bigger specificity (`.block.is-big .block_title`) comes only after selector with less specificity (`.block_title`).
