### ISSUE TITLE
bug in no-unknown-animations

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#749]
```scss
.test {
    animation: swiper-preloader-spin 1s steps(12, end) infinite;
}
```
⚠  Unknown animation name "steps(12, end)" (no-unknown-animations) [stylelint]
```
Steps is not animation name, it is timing function.
https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function
