### ISSUE TITLE
Add noEmptyLinesBeforeNonFirstDecls option to declaration-block-properties-order

### ISSUE THREAD

**Issue by dan-gamble** [stylelint/stylelint#752]
Replicated at: https://github.com/dan-gamble/styletest/tree/master

Give then `rule-properties-order` of:

```
'rule-properties-order': [
      {
        emptyLineBefore: true,
        properties: [
          'content'
        ]
      },
      {
        emptyLineBefore: true,
        properties: [
          'position',
          'top',
          'right',
          'bottom',
          'left',
          'z-index'
        ]
      },
      {
        emptyLineBefore: true,
        properties: [
          'display',
          'float',
          'height',
          'margin',
          'margin-top',
          'margin-right',
          'margin-bottom',
          'margin-left',
          'max-height',
          'max-width',
          'min-height',
          'min-width',
          'padding',
          'padding-top',
          'padding-right',
          'padding-bottom',
          'padding-left',
          'table-layout',
          'width'
        ]
      }
    ]
```

This CSS passes:

```
.sec {
  content: 'tree';
  
  position: absolute;
  
  top: 0;
  right: 0;
  
  bottom: 0;
  
  left: 0;
}
```

There shouldn't be any empty lines between properties in the same group.

**Comment by davidtheclark** [comment]
I'm not sure whether to consider this a bug or an enhancement. @jeddy3 ?

**Comment by dan-gamble** [comment]
I'd personally err on the side of bug because having the rule `emptyLineBefore` implies to me that's the only place an empty line should be and in the docs the only time an empty line before appears is when that option is used. Just my 2c though

**Comment by jeddy3** [comment]
I think it should be an enhancement and enabled by an explicit option (e.g. `noEmptyLines: true`), as:

1. We don't restrict empty lines above declarations else where.
2. It's going to conflict with [`comment-empty-line-before`](http://stylelint.io/user-guide/rules/comment-empty-line-before/). For example:

```css
a {
  content: "foo";

  position: absolute;
  z-index: 2;
  
  display: block;

  /* some comment about the next two declarations .e.g. "Match size to image" */
  height: 100px;
  width: 100px;
}

```

I think users need to opt-in into that kind of behaviour.

**Comment by dan-gamble** [comment]
You guys know better than me, i'm game for that :+1: 

Just realised it allows me to do the comment thing in it's current state so a switch does sound like the better way to go.

How would comments be handled if this was switched on?

**Comment by davidtheclark** [comment]
> How would comments be handled if this was switched on?

That would be a problem. You might end up with rules contradicting each other. @jeddy3, have we managed to completely avoid that so far, or do we have precedent for dealing with hit?

**Comment by jeddy3** [comment]
> have we managed to completely avoid that so far

Yep, we've always kept rules standalone and maintained that resolving conflicts is the responsibility of the user.

> How would comments be handled if this was switched on?

I think we can nip this one in the bud (and avoid the potential for conflicts) by renaming the option to `noEmptyLinesBeforeNonFirstDecls: true`. ("NonFirst" is weird though, any better suggestions?). We can then reuse the [empty line logic](https://github.com/stylelint/stylelint/blob/master/src/rules/rule-properties-order/index.js#L215) already within the rule. It also means that there will be *no conflict with* `comment-empty-line-before` as both these...:

`comment-empty-line-before: "never"`:

```css
a {
  content: "foo";

  position: absolute;
  z-index: 2;

  display: block;
  /* some comment about the next two declarations .e.g. "Match size to image" */
  height: 100px;
  width: 100px;
}
```

`comment-empty-line-before: "always"`:

```css
a {
  content: "foo";

  position: absolute;
  z-index: 2;

  display: block;

  /* some comment about the next two declarations .e.g. "Match size to image" */
  height: 100px;
  width: 100px;
}
```

... are valid as far as `noEmptyLinesBeforeNonFirstDecls: true` is concerned as each "non first" declaration is just checking if it's preceded by an empty time, which is never is.
