### ISSUE TITLE
Fix `declaration-block-no-redundant-longhand-properties` autofix for `border`

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/stylelint#7609]
### What minimal example or steps are needed to reproduce the bug?

```css
a {
	border-width: 7px;
	border-style: double;
	border-color: green;
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "declaration-block-no-redundant-longhand-properties": true
  },
  "fix": true
}
```

### How did you run Stylelint?

https://stylelint.io/demo

### Which Stylelint-related dependencies are you using?

.

### What did you expect to happen?

```css
a {
	border: 7px double green;
}
```

### What actually happened?

.

### Do you have a proposal to fix the bug?

add a custom resolver for `border`
