### ISSUE TITLE
Fix `declaration-block-no-redundant-longhand-properties` autofix conflicts

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/stylelint#7610]
### What minimal example or steps are needed to reproduce the bug?

```css
a {
	border-top-width: foo;
	border-right-width: foo;
	border-bottom-width: foo;
	border-left-width: foo;

	border-top-color: foo;
	border-right-color: foo;
	border-bottom-color: foo;
	border-left-color: foo;

	border-top-style: foo;
	border-right-style: foo;
	border-bottom-style: foo;
	border-left-style: foo;
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "declaration-block-no-redundant-longhand-properties": true
  },
  "fix": true
}
```

### How did you run Stylelint?

https://stylelint.io/demo

### What did you expect to happen?

```css
a {
	border-width: foo foo foo foo;
	border-color: foo foo foo foo;
	border-style: foo foo foo foo;
}
```
or
```css
a {
	border-top: foo foo foo;
	border-right: foo foo foo;
	border-bottom: foo foo foo;
	border-left: foo foo foo;
}
```

### What actually happened?

demo

```css
a {
	border-width: foo foo foo foo;
	border-color: foo foo foo foo;
}
```

locally

```css
a {
	border-width: foo foo foo foo;
	border-color: foo foo foo foo;
    border-left-style: foo;
}
```

@ybiquitous @jeddy3
It seems to me that it's a **major bug**.
