### ISSUE TITLE
Add support for defining default value via environment variable

### ISSUE THREAD

**Issue by titouanmathis** [stylelint/stylelint#7617]
### What is the problem you're trying to solve?

In a shareable GitLab CI configuration, I use the custom-formatter and cache CLI arguments to improve the performance of my code quality tests and upload reports t GitLab Code Quality Report feature. 

```yaml
stylelint:
  variables:
    STYLELINT_ARGS: --version
    STYLELINT_FORMATTER: node_modules/stylelint-formatter-gitlab
  script:
    - npx stylelint $STYLELINT_ARGS --custom-formatter $STYLELINT_FORMATTER --cache --cache-location .stylelintcache-$CI_NODE_INDEX
```

This can then be used by include the configuration, and specifying the `STYLELINT_ARGS` variable:

```yaml
include: 
  - path/to/stylelint.yml

stylelint:
  variables:
    STYLELINT_ARGS: path/to/my/src
```

This implementation hide the complex configurations from the final user, but also limits them in terms of what they can do. 

An ideal implementation would be to define the `--custom-formatter`, `--cache` and `--cache-location` as environment variables to make sure that they are correctly defined, while letting the final user use the command they need. 

### What solution would you like to see?

Being able to define some CLI arguments as environment variables: 

```
# Enable cache
stylelint . --cache 
STYLELINT_CACHE=true stylelint . 

# Define a custom formatter
stylelint . --custom-formatter=node_modules/formatter/index.js
STYLELINT_CUSTOM_FORMATTER=node_modules/formatter/index.js stylelint . 

# Define a custom config
stylelint . --config=path/to/config.js
STYLELINT_CONFIG=path/to/config.js stylelint . 
```

I think this could be implemented directly in `lib/cli.mjs` by setting default values when defining the flags. 

I am willing to work on this feature if this is approved.
