### ISSUE TITLE
`declaration-block-no-redundant-longhand-properties` needs to be value type aware

### ISSUE THREAD

**Issue by romainmenke** [stylelint/stylelint#7631]
```css
a {
	text-decoration-style: dotted;
	text-decoration-line: red;
	text-decoration-color: underline;
}

b {
	text-decoration-style: dotted;
	text-decoration-line: underline;
	text-decoration-color: red;
}
```

https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdugLjmAHjgLSyQBOSOAlhJsQM44CeANjPClBHjFANxZc+IqRgUqteq2qYOKcn0HZeoshEo06xSKw2cArpljkZc5QF8hmAEZohqkus1TGLdp268BDkU-Eaktpm8kYmIcrChP4SWvS6+gpKWBYgADQgAGbU7ABySAC2cIiEhQAO7AB0YAwM6eB02QDmCCAYmCgo6CDRMMYM3ZwA2lidnd1MbDBmJJCYzW5IxkjkUN2jKAC6KfVzzQBiGgVUrQBWDHT1sGV1iO3jIJPsM4NdIKxUMEzdaRsT7tNZLNGtQmotlqtXt0PvhviAdhYgA

Or even more exotic :

```css
a {
	text-decoration-style: dotted;
	text-decoration-line: ;
	text-decoration-color: underline red;
}
```

https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdugLjmAHjgLSyQBOSOAlhJsQM44CeANjPClBHjFANxZc+IqRgUqteq2qYOKQdl6iyESjTrFIrNZwCumWORlyU5PooC+IADQgAZtXYA5JAFs4iQu4AO7AHRgDAy24HSOAOYIIBiYKCjoIIT4hgyJnADaWPHxiUxsMCYkkJiRjDhIhkjkUInZKAC6WNZ2JZEAYmpuVNEAVgx0obA+IYixuSD57EXpCSCsVDBMiTb1eSzTssXh1BHllVDVtQhzC-jLIM0glkA

You could argue that in this case the input is bogus, so that the output is unexpected is fine but it does surface the underlying flaw in the implementation.

Longhand to shorthand conversion needs to fully analyze property and value pairs, check that they are valid and effectively calculate something more similar to the computed value.

Only when this passes for all known constituents properties would it be safe to combine these.

-------

The issue here is not `text-decoration` itself, but that the implementation is not sufficiently sturdy to be reliable in most cases.

An implementation that is resilient to issues of this nature will be much more complex.

I don't know if this is desirable or worth it.
