### ISSUE TITLE
[16.4.0] Cannot suppress `selector-max-universal`

### ISSUE THREAD

**Issue by boris-petrov** [stylelint/stylelint#7644]
### What minimal example or steps are needed to reproduce the bug?

```css
// stylelint-disable-next-line selector-max-universal
.limited table,
.limited table * {
  display: contents;
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "selector-max-universal": true
  }
}
```

### How did you run Stylelint?

Command line.

### Which Stylelint-related dependencies are you using?

Just Stylelint 16.4.0.

### What did you expect to happen?

The warning to be suppressed.

### What actually happened?

The warning is not suppressed. That worked in version 16.3.1.

**Comment by romainmenke** [comment]
Hi @boris-petrov,
Thank you for reporting this.

In `16.4.0` we fixed the reported source locations for this rule.
Because the location of the error is now correct (but different) you also need to place ignore comments at the correct position.

See this example :

```css
/* stylelint-disable-next-line selector-max-universal */
.a *,
.b * { /* stylelint-disable-line selector-max-universal */
	display: contents;
}

.a *,
.b * { 
	display: contents;
}
```

https://stylelint.io/demo/#N4Igxg9gJgpiBcID0AqABAZwC4E8A2MeAlgHZYC0URGAhgEYHkkwAeFxzmhMYWEATuQC2NFuQCuJIgDcY-WnjQokAHRIA6GkoA0a9XSVpgaVJlwEOFKrQYxyHGFwK8Bw0RKmz5NRcrUqsawAHPBoceDRIMhgyDABuNQBffw0tFF0NA3Rjf0DqELCIqKwYrHikkG0QADMiAgA5GiE4RFYmkJh1MAwMSvAIElqAcwQQYDU0NBUQfnECDGmI8ZJJyemMbhdBETFJGTkFRbQAbQAGAF0JtGSSRL6o4YAxAREsUYArDAG+2CDexGWaxA2HwhFIWCO01CJWw0wyQJBFnB5AeRCG5GwNBIUBo-CgkJA0JgsJAFUSQA
