### ISSUE TITLE
declaration-block-no-misaligned-values

### ISSUE THREAD

**Issue by deepfriedmind** [stylelint/stylelint#769]
I like to align my values for readability, e.g.:

```css
selector {
  property-name:             value;
  longer-property-name:      value;
  even-longer-property-name: value;
  shortprop:                 value;
}
```

This trips up the `declaration-colon-space-after` rule though, so I was wondering if it would be possible to enforce that the colon is succeeded by _at least_ one space but not care about multiple spaces?
