### ISSUE TITLE
Unknown rule no-extra-semicolons.

### ISSUE THREAD

**Issue by franck-paul** [stylelint/stylelint#7738]
### What minimal example or steps are needed to reproduce the bug?

```css
.jstElements {
  position: sticky;
  top: 0;
}

.toolbar_bottom .jstElements {
  top: inherit;
  bottom: 0;
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "extends": "stylelint-config-standard-scss",
  "rules": {
    "max-empty-lines": 4,
    "number-leading-zero": null,
    "selector-list-comma-newline-after": "always-multi-line",
    "declaration-colon-space-after": "always",
    "at-rule-no-unknown": null,
    "no-extra-semicolons": null
  }
}
```

### How did you run Stylelint?

In VSC (MacOS)

### Which Stylelint-related dependencies are you using?

```json
{
"stylelint": "16.6.1",
"stylelint-config-standard-scss": "13.1.0"
}
```

### What did you expect to happen?

No error message

### What actually happened?

Have an error message: "Unknown rule no-extra-semicolons." for each line of the css file.
