### ISSUE TITLE
Configuration commands for `declaration-block-no-duplicate-properties` changed in `16.7.0`

### ISSUE THREAD

**Issue by romainmenke** [stylelint/stylelint#7881]
### What minimal example or steps are needed to reproduce the bug?

```css
.e {
	color: #000;
	/* stylelint-disable-next-line declaration-block-no-duplicate-properties */
	color: #fff;
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "declaration-block-no-duplicate-properties": [true]
  }
}
```

### How did you run Stylelint?

[Demo `16.6.0`](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0MAEwA6A7DAXSANhAE7yoDEADNQNzZ4D0AVKgM64CeBMBAllrgC0UXqwCGAI26CsMAB5C+s1LDAExxMbl4QsgqRDABrGRGEBXAA58wWmIMvEIlmMW0xWqJg3r4IRUgoAMxC6LABfEAAaECDebgA5MQBbOER5FOsYJDBWVmjwXTiAcwQQTCxUVAwQYnNuVhqyCqqqmtV1TW1dfSJjUwtrXltce0dnV3dGhFQAbVw6mABdbCrw7EiYyCwSgDESZK0ygCtWXQLYS3zEFuqQdi4eflwmu4BGADYkL8oaqNW7g9uEohNsSoJ2GIsFANFBXjV1KN2DUNiBwkA)

[Demo `16.7.0`](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0MAEwA6A7DAXSANhAE7yoDEADNQNzZ4D0AVKgM64CeBMBAllrgC0UXqwCGAI26CsMAB5C+s1LDAExxMbl4QsgqRDABrGRGEBXAA58wWmIMvEIlmMW0xWqJg3r4IRUgoAMxC6LABfEAAaECDebgA5MQBbOER5FOsYJDBWVmjwXTiAcwQQTCxUVAwQYnNuVhqyCqqqmtV1TW1dfSJjUwtrXltce0dnV3dGhFQAbVw6mABdbCrw7EiYyCwSgDESZK0ygCtWXQLYS3zEFuqQdi4eflwmu-VR9hqo1buH7iUhNsSoJ2GIsFANFBXjV3h4XiANiBwkA)

### Which Stylelint-related dependencies are you using?

```json
{
  "stylelint": "latest",
  "stylelint-config-standard": "latest"
}
```

### What did you expect to happen?

No problems to be reported

### What actually happened?

> ERROR Unexpected duplicate "color" (declaration-block-no-duplicate-properties)[2:2-7]

### Do you have a proposal to fix the bug?

Partially revert the changes from https://github.com/stylelint/stylelint/pull/7758

**Comment by romainmenke** [comment]
In https://github.com/stylelint/stylelint/pull/7758 some changes were made to which node has the associated error.

This in turn changed how disable ranges work for this rule.

I think that it will be very common for users to disable this rules for a few lines when they set fallback values.

I am concerned that this change is a bit too disruptive for a minor version.

**Comment by ybiquitous** [comment]
@romainmenke Thanks for the report. I missed the point for `/* stylelint-disable */`.

In my opinion, this change may break some projects' lint, but I think considering the change as *major* is too much.

PR #7758 change made consistency with autofix like this. Also, `reportNeedlessDisables: true` in a configuration could help detect needless configuration comments. So, probably I don't think this may be a big problem.

```css
a {
	color: #000; /* ← removed by autofix */

	/* stylelint-disable-next-line declaration-block-no-duplicate-properties */ /* ← reported as a needless disable */
	color: #fff;
}
```
