### ISSUE TITLE
`no-duplicate-selectors` Sass mixed declarations deprecation 

### ISSUE THREAD

**Issue by portikM** [stylelint/stylelint#7893]
### What is the problem you're trying to solve?

Starting from version 1.77.7 Sass is [deprecating support for mixed declarations](https://sass-lang.com/documentation/breaking-changes/mixed-decls/). Fixing and addressing warnings produced by Sass requires wrapping nested declarations in `& {}`:

**Old way**

```scss
.example {
  color: red;

  a {
    font-weight: bold;
  }

  font-weight: normal;
}
```

**New way**

```scss
.example {
  color: red;

  a {
    font-weight: bold;
  }

  & {
    font-weight: normal;
  }
}
```

In this case Stylelint considers the `& {}` to be a duplicate selector (expected behaviour). For now I disable the `no-duplicate-selectors` rule for next line whenever I need to use the above selector, but I would like to discuss a more sophisticated solution.

### What solution would you like to see?

`allowMixedDecls` secondary option in `no-duplicate-selectors` rule (or something similar) that would allow the nested `& {}` selector.

**Comment by Mouvedia** [comment]
related: #7873

**Comment by romainmenke** [comment]
Hi @portikM,

Out of curiosity, can you give a real world example where you really need/want declarations after nested rules?

So you really need this:

```css
.example {
  color: red;

  a {
    font-weight: bold;
  }

  font-weight: normal;
}
```

But can't rewrite to:

```css
.example {
  color: red;
  font-weight: normal;

  a {
    font-weight: bold;
  }
}
```

The CSSWG thoroughly checked this to make sure it wouldn't cause issues on existing sites and found that in practice CSS authors didn't write declarations after rules in a way that actually affected the outcome. As is also the case in your example.

I am not sure why Sass is giving the guidance to use `& {}` when moving the declarations seems like a simpler way to resolve this issue.

**Comment by portikM** [comment]
> Hi @portikM,
> 
> Out of curiosity, can you give a real world example where you really need/want declarations after nested rules?
> 
> So you really need this:
> 
> ```css
> .example {
>   color: red;
> 
>   a {
>     font-weight: bold;
>   }
> 
>   font-weight: normal;
> }
> ```
> 
> But can't rewrite to:
> 
> ```css
> .example {
>   color: red;
>   font-weight: normal;
> 
>   a {
>     font-weight: bold;
>   }
> }
> ```
> 
> The CSSWG thoroughly checked this to make sure it wouldn't cause issues on existing sites and found that in practice CSS authors didn't write declarations after rules in a way that actually affected the outcome. As is also the case in your example.
> 
> I am not sure why Sass is giving the guidance to use `& {}` when moving the declarations seems like a simpler way to resolve this issue.

The screenshots I attached is actually real world use-case for this. 100% of impacted lines I've fixed over past couple days since we started using Sass 1.77.7 were declarations that follow one or more mixin. Often times we'll have some generic mixin that comes with nested rules and then we'll want to override/extend that mixin with some specific to use-case declarations. High-level example:

```scss
@mixin genericButtonMixin {
  background-color: transparent;

  .icon {
    stroke: currentColor;
  }
}

button.primary {
  @include genericButtonMixin;

  background-color: blue;
  color: red;
}
```

**Comment by Mouvedia** [comment]
There's also a case for automatic migration tools on big codebases to avoid introducing regressions.
e.g. https://sass-lang.com/documentation/cli/migrator/

**Comment by romainmenke** [comment]
Ah, yes, with mixins you can write an `at-rule` that actually represents both declarations and/or more rules. This is also the primary reason that the CSSWG changed the behavior of nesting, they work in a more interesting way when nested rules and declarations preserve their order. Unfortunately native nesting is different from how Sass works.

I get that Sass wants to provide a way for CSS authors to opt-in to the standard CSS mechanics today and that writing `& {}` is a clean way to get this. Even when the same code written as standard CSS wouldn't really make sense. It isn't wrong, but just needlessly verbose.

But eventually Sass will update and work like native CSS for all nested delcarations and you will no longer need to write `& {}`, correct?

So if we add a plugin option to help Sass authors it will only be briefly useful.

-------

Is there a wider use case for ignoring `& {}` specifically?

Have there been requests to ignore specific selectors or patterns for this rule? I couldn't spot any.

Is it better to use configuration comments to disable this rule in very specific cases?

**Comment by Mouvedia** [comment]
related discussion: https://github.com/stylelint/stylelint/issues/2198#issuecomment-274276106
similar issue: #2199

**Comment by ybiquitous** [comment]
I agree with @romainmenke. If this pattern helps only developers using Sass, it would be against our rule criteria:

https://github.com/stylelint/stylelint/blob/1232b539dfebc7a14aaa4b2d99af3af96114d776/docs/developer-guide/rules.md?plain=1#L14

Also, this issue is related to <https://github.com/stylelint-scss/stylelint-scss/issues/1020>. The stylelint-scss repo seems more suited for this discussion.

**Comment by c0d3x** [comment]
How do I solve this:
```SCSS
@mixin col-2($defaultSpan: 1) {
    @include grid-layout();
    grid-template-columns: repeat(auto-fit, minmax(40%, 0.5fr));
    > * {
        grid-column: span $defaultSpan;
        @include breakpoints.tablet() {
            grid-column: span 1;
        }
    }
    .half-width {
        grid-column: span 1;
    }
    .full-width {
        grid-column: span 2;
    }
    @include breakpoints.mobile() {
        grid-template-columns: 1fr;
        .full-width {
            grid-column: span 1;
        }
    }
    @include browserhacks.ie_only {
        .half-width {
            width: 50%;
        }
        .full-width {
            width: 100%;
        }
    }
}
```

`      │ Module Warning (from ../.yarn/__virtual__/sass-loader-virtual-42d1bf09a7/4/.yarn/berry/cache/sass-loader-npm-16.0.2-eafa07389f-10c0.zip/node_modules/sass-loader/dist/cjs.js):
      │ Deprecation Warning on line 55, column 4 of file://src/css/layout/_grid.scss:55:4:
      │ Sass's behavior for declarations that appear after nested
      │ rules will be changing to match the behavior specified by CSS in an upcoming
      │ version. To keep the existing behavior, move the declaration above the nested
      │ rule. To opt into the new behavior, wrap the declaration in `& {}`.
      │
      │ More info: https://sass-lang.com/d/mixed-decls
      │
      │ 55 |     grid-template-columns: repeat(auto-fit, minmax(40%, 0.5fr));
      │
      │
      │ src/css/layout/_grid.scss 56:5                       col-2()`

**Comment by seiyab** [comment]
My workaround (CAUTION: specificity changes):
```scss
@mixin genericButtonMixin {
  background-color: transparent;

  .icon {
    stroke: currentColor;
  }
}

button.primary {
  @include genericButtonMixin;

  &.primary{ // using `&.primary` instead of `&`
    background-color: blue;
    color: red;
  }
}
```
