### ISSUE TITLE
Fix `selector-type-no-unknown` false positives for `<custom-ident>` passed to pseudo-elements

### ISSUE THREAD

**Issue by jcayzac** [stylelint/stylelint#7911]
### What minimal example or steps are needed to reproduce the bug?

```css
html::view-transition-group(lightdark) {
	animation-timing-function:step-end;
}

:root::view-transition-old(lightdark) {
	animation-name: keep-old;
	z-index: 1;
}

:root::view-transition-new(lightdark) {
	animation-name: keep-new;
	z-index: 9999;
}
```

### What minimal configuration is needed to reproduce the bug?

```js
export default {
	extends: [
		'stylelint-config-standard',
		'stylelint-config-html',
	],
	rules: {
	},
}
```

### How did you run Stylelint?

from astro

### Which Stylelint-related dependencies are you using?

```
"stylelint": "^16.8.1",
"stylelint-config-html": "^1.1.0",
"stylelint-config-standard": "^36.0.1",
```

### What did you expect to happen?

No error, since this is [valid CSS syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/::view-transition-group#custom-ident).

### What actually happened?

`Unexpected unknown type selector "lightdark" (selector-type-no-unknown)`

### Do you have a proposal to fix the bug?

Accept any identifier in those pseudo selectors, since they can be used by the Javascript-based View Transitions API.
