### ISSUE TITLE
Add `transition-behavior` support to `declaration-block-no-redundant-longhand-properties` and `declaration-block-no-shorthand-property-overrides`

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/stylelint#7917]
### What minimal example or steps are needed to reproduce the bug?

```css
a {
  transition-behavior: foo;
  transition-delay: foo;
  transition-duration: foo;
  transition-property: foo
  transition-timing-function: foo;
}
```

```css
a {
  transition-behavior: foo;
  transition: foo;
}
```

### What minimal configuration is needed to reproduce the bug?

.

### How did you run Stylelint?

.

### Which Stylelint-related dependencies are you using?

.

### What did you expect to happen?

.

### What actually happened?

https://github.com/stylelint/stylelint/blob/ee3118d2460cddf469f959b5438d8aeab7e9584e/lib/reference/properties.mjs#L601-L610

### Do you have a proposal to fix the bug?

The low browser support—[under 90%](https://caniuse.com/mdn-css_properties_transition-behavior)—is not a problem for `declaration-block-no-redundant-longhand-properties` because we provide the `ignoreLonghands` option.
Nonetheless Id prefer if the issue was labeled _status: agreed but held_ for now.

**Comment by ybiquitous** [comment]
@Mouvedia Thanks for the report. Supporting `transition-timing-function` sounds good to me. Just to make sure, we can confirm this bug on [this demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdugLjgTkpgM4CWOpEmAtAA74S0z44Ce8KSANlwNxa4CRMhSrUoAV0KjMHAAwA6AEwBWYv2x5CJcpRoUAtqUwBzagDMJmMDI4wkxGBsHaRe8TC5J2KOeoFawrpiAEYwABZIAG6U+BzcXBAA7uKkxGD4MDhOWAC+IAA0IOakXDAAckgGcIgwAB5VtGUKYMTEheBUJSYIIBiYKCjoIPXZmFDEwxwA2liDg8PEbGVcxjjUkJjd1EtEUEj4UMNzKAC6eR2b3QBiEPgGSDi9AFbEVB2wtO2I-QsgS6wVmspkMQF5skthgUTotlp41hsuqQzLtxgcjghQeCYJCQBdckA):

```css
a {
	transition-property: all;
	transition-duration: 0.25s;
	transition-timing-function: ease;
	transition-delay: 0s;
	transition-behavior: allow-discrete;
}

/* ❌ it is autofixed to: */
a {
	transition: all 0.25s ease 0s;
	transition-behavior: allow-discrete;
}

/* ✅ but the following should be: */
a {
	transition: all 0.25s ease 0s allow-discrete;
}
```

I've labeled the issue as **ready to implement**. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to fix a bug in a rule](https://stylelint.io/developer-guide/rules#fix-a-bug-in-a-rule) in the Developer guide.

**Comment by ybiquitous** [comment]
Additionally, [this demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdugLjgTkpgM4CWOpEmAtAEYwAWSAbpfvCkgDZcQDu1KKWJh8MHDADcWXASJkKVDty4oADADoATAFZiKGEmIx1xaZgC+IADQgAZqS4wAckgC2cRDAAe7gA5OGmDExDbgVA4A5gggGJgoKOggPhKYUMRJHADaWAkJScQ4AJ5OXKSYONSQmFHUhURQSPhQSbkoALpYVrbVUQBiEPhuSDgxAFbEVGGwfqGIcfkghSUwZRWZiSBcIzCFSdZtBcWl5ZW9pJF1OA1NLQib2xJ7IF0gFkA) shows a *false negative* bug for `declaration-block-no-shorthand-property-overrides`:

```css
a {
	transition-behavior: allow-discrete;
/* ❌ It is not reported now, but it should be reported. */
	transition: all 0.25s ease 0s;
/*  ^^^^^^^^^^ Unexpected shorthand "transition" after "transition-behavior" */
}
```

**Comment by Mouvedia** [comment]
I am of the opinion that this fix should be accompanied by a PR on `stylelint-config-standard`'s side that adds `"ignoreLonghands": ["transition-behavior"]`.

**Comment by ybiquitous** [comment]
@Mouvedia What reason do you think so?

IMO, it seems more reasonable to change the existing logic `declaration-block-no-redundant-longhand-properties` than adding `ignoreLonghands` to `stylelint-config-standard`:

https://github.com/stylelint/stylelint/blob/ee3118d2460cddf469f959b5438d8aeab7e9584e/lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs#L116-L117

See also:

```js
		'declaration-block-no-redundant-longhand-properties': true,
```

-- https://github.com/stylelint/stylelint-config-standard/blob/d319b67e7b8a546bca84c6a909764171df587d7e/index.js#L55

**Comment by Mouvedia** [comment]
It's my subjective opinion since #301 is still opened.

**Comment by ybiquitous** [comment]
I see that you are concerned about "the low browser support". But even if `declaration-block-no-redundant-longhand-properties` and `declaration-block-no-shorthand-property-overrides` support `transition-behavior`, the backward compatibility will be kept, right?

**Comment by romainmenke** [comment]
Correct, we only need to be concerned about _forwards_ compat issues that arise by not adding new properties to these rules :)

See: https://github.com/stylelint/stylelint/issues/7630

**Comment by Mouvedia** [comment]
@ybiquitous here's an demonstration of the problem once the fix has been merged:

```json
{
  "rules": {
    "declaration-block-no-redundant-longhand-properties": true
  }
}
```

```css
a {
  transition-property: all;
  transition-duration: 0.25s;
  transition-timing-function: ease;
  transition-delay: 0s;
  transition-behavior: allow-discrete;
}
/* becomes */
a {
  transition: all 0.25s ease 0s allow-discrete;
}
```

On browsers that don't support `transition-behavior` the `transition` property will dropped altogether because `allow-discrete` makes it invalid. Since the browser support—**in my point of view**—is at this stage too low according to caniuse, the option should be used so that it would be instead be fixed to:

```css
a {
  transition: all 0.25s ease 0s;
  transition-behavior: allow-discrete;
}
```

Is that clearer?
`ignoreLonghands` was exactly introduced to handle that kind of cases.

**Comment by romainmenke** [comment]
You are right, @Mouvedia, there are two disruptive cases.

Can we already [warn for the order](https://github.com/stylelint/stylelint/issues/7917#issuecomment-2282362078)?
But not yet have the autofix?

**Comment by Mouvedia** [comment]
@romainmenke I didn't want to talk about it here because it's off-topic and a general issue with the fix of this rule.
i.e. we are currently assuming, _without any justification_, that someone would always put the exception last so that after the autofix it would end up after the shorthand

What's on topic is that the resolver of the `transition` autofix will have to reorder the properties if the exceptions are not placed last before attempting the autofix. This is not so newcomer-friendly anymore.

**Comment by romainmenke** [comment]
No, I meant can we make it so that `declaration-block-no-shorthand-property-overrides` warns for :

```css
a {
	transition-behavior: allow-discrete;
/* ❌ It is not reported now, but it should be reported. */
	transition: all 0.25s ease 0s;
/*  ^^^^^^^^^^ Unexpected shorthand "transition" after "transition-behavior" */
}
```

But not yet update `declaration-block-no-redundant-longhand-properties` until support is good enough.

Is that possible? Would that cause minimal issues for users?
