### ISSUE TITLE
Fix `declaration-block-no-redundant-longhand-properties` autofix for `grid-area` property

### ISSUE THREAD

**Issue by geofferb** [stylelint/stylelint#7933]
### What minimal example or steps are needed to reproduce the bug?

```css
div {
            grid-column-start: line-outer-left;
            grid-column-end: line-outer-right;
            grid-row-start: line-inner-top;
            grid-row-end: line-inner-bottom;
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "extends": [
    "stylelint-config-standard"
  ]
}
```

### How did you run Stylelint?

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdinu84HMAnASygFpIAbAVwFtNyBnAFySJfhSpMxnIg0WMIuSowAZiwDcWfPJTEylCLQbkYmKFx58BQkeVIEAFjLkK8SikQgB3Zmw47e-Xn1EsIAB1nZLuNZG9hpaLnruhgBGECxedH4AvlggADQgEiTiAHJIdHCIMAAeed7iAHRgTExp4BCYmQQIIBj+6CDFwlpM7VwA2hY47awAnuK6LCoNJASOSFrsUO0WALpYibWQ0wQAYhBEdEgszQBWTPW1sN41iK1DIKPjvCy9KO1URzCs7akWwyxjGATKaNOYLIhLBBvEAfYTfEDrECJIA)

### Which Stylelint-related dependencies are you using?

```json 
{		"stylelint": "^16.8.2",
		"stylelint-config-prettier-scss": "^1.0.0",
		"stylelint-config-standard": "^36.0.1",
		"stylelint-config-standard-scss": "^13.1.0",
}
```

### What did you expect to happen?

```css
div {
            grid-column: line-outer-left / line-outer-right;
            grid-row: line-inner-top / line-inner-bottom;
}
```

or 
```css
div {
            grid-area: line-inner-top / line-outer-left / line-inner-bottom / line-outer-right;
}
```

### What actually happened?

```css
div {
            grid-column: line-outer-left / line-outer-right;
}
```

### Do you have a proposal to fix the bug?

Looks like it is expecting `grid-column`, `grid-row`, `grid-area`, to all be the fix to this, when it should just be expecting `grid-column` and `grid-row`, or `grid-area` to be the fix.

I am currently using the below config as a workaround:
```json 
    "rules": {
        "declaration-block-no-redundant-longhand-properties" : [
            true,
            {
                "ignoreShorthands": ["grid-area"]
            }
        ]
    }
 ```
