### ISSUE TITLE
Add `ignoreFunctions: []` to `media-query-no-invalid`

### ISSUE THREAD

**Issue by MrOxMasTer** [stylelint/stylelint#7934]
### What minimal example or steps are needed to reproduce the bug?

```css
/* tailwindcss *\
@media (min-width: theme(screens.mt)) {
  ...
}
```

### What minimal configuration is needed to reproduce the bug?

```js
{
'function-no-unknown': [
      true,
      {
        ignoreFunctions: ['theme'],
      },
    ],
}
```

### How did you run Stylelint?

vs code extension

### Which Stylelint-related dependencies are you using?

```json 
{
   "stylelint": "^16.8.2",
   "stylelint-config-standard": "^36.0.1",
   "stylelint-order": "^6.0.4",
   "stylelint-selector-bem-pattern": "^4.0.0",
   "tailwindcss": "^3.4.9",
}
```

### What did you expect to happen?

It will not be underlined
![image](https://github.com/user-attachments/assets/d614629b-aac9-4a69-8da7-ad739713cd3a)

### What actually happened?

https://stylelint.io/user-guide/rules/media-query-no-invalid/

**Comment by romainmenke** [comment]
@MrOxMasTer thank you for reporting this.

Is this [demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIACBbGUCWBDABAChQwDsBaAdwygBcALeHWmNPAZzACcYYiWA6FKgEpBOYAB0iOHLwBmECKIliqyyABsI7epygBuJVQC+EwyAA0IGRjUwAcljQIQMAB4OADjd5gWLc+AgiKwBzJ3FJHDFnFypuKBYo+gBtCSkpKJYqAE8bNWIqEkggjGCSTKwiKCx2KCjUnABdE38ikIAxTRQsKicAKxZA-1h3P0Rw9JBMnJg8ohUESJA1bphMqLN6jOzc-MLAkLKqCqqaxMXl2LWQZsMgA) an accurate reproduction?

```css
@media (min-width: theme(screens.mt)) {
  .foo {
		color: red;
	}
}
```

```
1:8-38 error Unexpected invalid media query "(min-width: theme(screens.mt))" (media-query-no-invalid)
```

-----

This error message isn't coming from `function-no-unknown`.

It is from `media-query-no-invalid`.
This rule should not be used with non-standard syntaxes and `theme()` isn't standard.
This is also mentioned in [the rule docs](https://stylelint.io/user-guide/rules/media-query-no-invalid).

You could disable `media-query-no-invalid` or add a configuration command:

```css
/* stylelint-disable-next-line media-query-no-invalid */
@media (min-width: theme(screens.mt)) {
  .foo {
		color: red;
	}
}
```
