### ISSUE TITLE
Fix `declaration-property-value-no-unknown` false negatives for `position-try-options`

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/stylelint#7964]
### What minimal example or steps are needed to reproduce the bug?

```css
a {
  position-try: foo;
  position-try-fallbacks: foo;
  position-try-options: foo;
  position-try-order: foo;
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": { "declaration-property-value-no-unknown": true }
}
```

### How did you run Stylelint?

[demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdilAHCAzgJYAuREmAtCQE4Ce8KAZhBANxY77FkXX2UmSADbCARkjABrAoxbtOeQqXJVadShFy9Ms5qw7YlPVfw0QasGnINYAviAA0IJkWEwAckgC2cRDAAPH1x3ADowAgIncApXAHMEEED8GhIUWCEAV2E0jCN0EBpsmAICxmAUAtgwYSQaJB1KXBotGFSNADcRTJhKTAhKTMwpfoB3TDKUWh6UO3ssaMhMeIAxC28GxIISOndhIkwScNiiONDvACso51hcKMQ8nALt3Zh9w8mC2pISkgLHRTPHZ7A4kShLeKUbZITBQOpQT4gb6-Ar2EB2IA)

### What did you expect to happen?

`Unexpected unknown value "foo" for property "position-try-options"`

### What actually happened?

`✅ No problems!`

### Resources

mdn/browser-compat-data#23651 w3c/csswg-drafts#10395
https://caniuse.com/?search=position-try
