### ISSUE TITLE
Add `custom-property-notation`

### ISSUE THREAD

**Issue by fpetrakov** [stylelint/stylelint#7974]
### What is the problem you're trying to solve?

`@property` at-rule is now supported by all major browsers, so I suggest adding a new rule that would specify which custom-property notation to use: at-rule or "default one" (don't know the appropriate name, correct me) 

### What solution would you like to see?

A rule with two options: "at-rule" | "default". 

**"at-rule":**
The following patterns are considered problems:
```css
--foo-bar: 40%
```

The following patterns are NOT considered problems:
```css
@property --foo-bar {
  syntax: "<percentage>";
  inherits: true;
  initial-value: 40%;
}
```

**"default":**
The following patterns are considered problems:
```css
@property --foo-bar {
  syntax: "<percentage>";
  inherits: true;
  initial-value: 40%;
}
```

The following patterns are NOT considered problems:
```css
--foo-bar: 40%
```

**Comment by romainmenke** [comment]
Hi @fpetrakov,

Thank you for opening this issue.

One concern I have with such a rule is that the notation isn't syntactic sugar.
There specific behavior changes that are associated with registering a custom property.

`@property` rule
- can be strongly typed
- can be set to not inherit
- can be given an `initial` value
- some typed values have subtle behavior changes:
  - `<url>` is resolved relative to the stylesheet in which it is assigned a value
  - `<color>`, `<number>`, ... changes can be animated

custom property declarations:
- always loosely typed
- always inherit
- values retain their default behavior:
  - `<url>` is resolved relative to the stylesheet where the value is used
  - `<color>`, `<number>`, ... changes are never animated

I am not sure we should be promoting one over the other.
I think it is totally fine if a single code base uses both notations depending on the specific scenario.

I personally only use an `@property` rule when there is a specific effect that is only possible through that notation.

Otherwise I use the shorter custom property declarations.

I want to avoid that people think one is always better or that you should always use one notation consistently.

-------

But I can also understand that some might want to enforce one style over the other.

Is there a good reason to enforce either over the other?

**Comment by romainmenke** [comment]
Another challenge with this rule is that `@property` and regular declarations aren't the same.

`@property` describes specific aspects of a custom property but you will still need to use regular declarations to assign values.

Most developers will organize their `@property` declarations in a different file and override in various elements.

```css
/* properties.css */
@property --foo-bar {
  syntax: "<percentage>";
  inherits: true;
  initial-value: 40%;
}
```

```css
/* components.css */
.component {
  --foo-bar: 12%;
}
```

From the perspective of Stylelint it would appear that `--foo-bar: 12%` was written without an `@property` rule because it isn't aware of contents of other files.

So I think we need to at least implement https://github.com/stylelint/stylelint/issues/4088 first.

**Comment by romainmenke** [comment]
Other thought :D

Is the intention actually to enforce loose or strict typing of custom properties?

Such a rule would also error on:

```css
@property --foo-bar {
  syntax: "*";
  inherits: true;
  initial-value: 40%;
}
```

It might be too early for something like this as the [allowed syntax definitions](https://developer.mozilla.org/en-US/docs/Web/CSS/@property/syntax) are very limited at this time.

**Comment by Mouvedia** [comment]
This rule addition request will need a convincing rationale for it to be accepted.
<sub>#5985 is relevant in that manner</sub>

I think it would be wrong of us to try to sway the usage one way or another.
Both usages are legitimate and it shouldn't be enforced indiscriminately.
I would recommend to wait until #4088 is resolved for its addition to be considered again.

**Comment by jeddy3** [comment]
[This is a nice article](https://moderncss.dev/providing-type-definitions-for-css-with-at-property/) about some of the differences that @romainmenke mentioned in https://github.com/stylelint/stylelint/issues/7974#issuecomment-2322093686, and how users may want to mix both.

For example, strengthening container style queries especially when registering properties to act as toggles or enums:

```css
@property --theme {
  syntax: "light | dark";
  inherits: true;
  initial-value: light;
}

:root {
  --theme: dark;
}

@container style(--theme: dark) {
  body {
    background-color: black;
    color: white;
  }
}
```

---

However, if you want to disallow either, you can use the existing `at-rule-disallowed-list` and `rule-selector-property-disallowed-list` rules.

To disallow `@property`:

```json
{
  "rules": {
    "at-rule-disallowed-list": ["property"]
  }
}
```

To disallow assigning custom properties everywhere:

```json
{
  "rules": {
    "rule-selector-property-disallowed-list": {
      "/.*/": ["/^--/"]
    }
  }
}
```

Or just disallowing assigning them within `:root`:

```json
{
  "rules": {
    "rule-selector-property-disallowed-list": {
      ":root": ["/^--/"]
    }
  }
}
```

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcCBOEIBcAEwA6A7baAtIWAK4DOaEAtoQA4p3wYBmqA3HgL554ACDCHRhI0ATwzE2EQgCMAhkix4MGcmNxp5AD2bYQAHmFIwMTfIDmMAHz7OuVQEtcACxGO05ZmiSkY9p1wPR3kAG0IANzC-ZgAWAAYAUnsuEAAaEBZHUJgAOXlqOEQYbQK6HIA6MHJydPAIXCyLBBAcBwx9XxzyfWY21VV9eSIumEIoR3Iw0IgAdxgoQlDJtF6MAG19QWNxfQBdNJUBztIcwnIYHLAqJHpGEXFxyem5haWVtf6BwZAAegqAFS-NabP4APWIwJAeyOqh4uHhqQykEajgsADEIEhqMMWgArcgNOqwOi1RBffSUMQ5ZaaNb6ULDGCUfSHdqU8Q05xEFFNc5aXBQRRQekgRloZmrEDcEBcIA0).
