### ISSUE TITLE
Fix `length-zero-no-unit` false positives for Sass variables

### ISSUE THREAD

**Issue by ArianeBouchardConformit** [stylelint/stylelint#8034]
### What is the problem you're trying to solve?

We left the rule enabled, and it broke some of our Sass calculations.

Consider the following calculation (simplified, as getting there in our actual codebase requires a mixin and a function that would be useless to pollute this thread with).

```scss
.my-element {
  $padding-top-base-offset: 5px;
  $padding-top-extra-offset: 0px;

  padding-top: calc($padding-top-base-offset + $padding-top-extra-offset); // Simplified in the output by Sass to 5px
  padding-left: 0px;
}
```

After autofixing, Stylelint gives the following result:

```scss
  $padding-top-base-offset: 5px;
  $padding-top-extra-offset: 0;

  padding-top: calc($padding-top-base-offset + $padding-top-extra-offset); // Error!
  padding-left: 0;
```

Sass now gives me an error like this:

![Image](https://github.com/user-attachments/assets/b84f6570-53db-4a68-b77b-367c1e8c4343)

### What solution would you like to see?

It's a bit unfortunate that Sass can't handle unitless zeros in calculations (and I've opened an issue [here](https://github.com/sass/sass/issues/3959)), but unless they decide to support them, it might be wise for Stylelint to either directly implement an exception for Sass variables or give us an option to exclude properties with a regex.

Sass has historically not been very open to my improvement suggestions on philosophical/edge case grounds, so I would be grateful if you guys could move on this.

As things stand, we sadly just cannot use this rule here in our project.
