### ISSUE TITLE
When using --fix flag, remove prefixed properties when they're duplicated by unprefixed properties.

### ISSUE THREAD

**Issue by davmillar** [stylelint/stylelint#8114]
### What minimal example or steps are needed to reproduce the bug?

When given the following input:

```css
div {
	-webkit-transform: rotate(-90deg);
	transform: rotate(-90deg);
}
```

the 'fixed' output is:

```css
div {
	transform: rotate(-90deg);
	transform: rotate(-90deg);
}
```

Ideally if a style declaration contains the prefixed and unprefixed versions of a property with the same value, the prefixed version should simply be removed instead of switched to unprefixed.

### What minimal configuration is needed to reproduce the bug?

Default configuration.

### How did you run Stylelint?

Via npm/shell script, e.g.:
```json
{
    "scripts": {
	"stylelint-fix": "stylelint \"src/**/*.{css,scss}\" --fix"
    }
}
```

### Which Stylelint-related dependencies are you using?

```json
{
    "devDependencies": {
        "stylelint": "^16.10.0",
        "stylelint-config-standard-scss": "^13.1.0"
    }
}
```

### What did you expect to happen?

I expected that the vendor-prefixed property would be removed since the rule already contained the same property without a prefix.

### What actually happened?

The vendor-prefixed property had its prefix removed but didn't remove the duplicate property.

### Do you have a proposal to fix the bug?

Check if there is the same property already present on the rule and simply remove it if there is no need for it. Optionally, provide a configuration option to enable this behavior in case there are folks that rely on the current behavior.

**Comment by ryo-manba** [comment]
In your example, it seems you would need to run the `--fix` command twice to remove duplicates.

1. The [property-no-vendor-prefix](https://stylelint.io/user-guide/rules/property-no-vendor-prefix/) rule removes the vendor prefix:

```css
div {
  transform: rotate(-90deg);
  transform: rotate(-90deg);
}
```

2. Then, the [declaration-block-no-duplicate-properties](https://stylelint.io/user-guide/rules/declaration-block-no-duplicate-properties/) rule removes the duplicate:

```css
div {
  transform: rotate(-90deg);
}
```

This might be difficult to implement, as rules need to be re-applied based on the modifications made by previous ones.

For example, another case, se, the [declaration-block-no-redundant-longhand-properties](https://stylelint.io/user-guide/rules/declaration-block-no-redundant-longhand-properties) rule would first consolidate longhand properties, followed by duplicate removal.

```css
a {
  padding-top: 2px;
  padding-right: 2px;
  padding-bottom: 2px;
  padding-left: 2px; 
  padding: 2px; /* Only this line remains after duplicate removal */
}
```
