### ISSUE TITLE
--fix creates invalid CSS due to comments

### ISSUE THREAD

**Issue by alexander-turner** [stylelint/stylelint#8132]
### What minimal example or steps are needed to reproduce the bug?

When I run `npx stylelint --fix` on:

```scss
body {
  vertical-align: 0.25em; // Because not using full height numbers
  text-decoration-thickness: 0.75px; // Underline is too heavy
}
```

this produces

```scss
body {
  vertical-align: 0.25em; // Because not using full height numbers
  text-decoration-thickness: 0.75px;Becausenotusingfullheightnumberstext-decoration-thickness // Underline is too heavy
}
```

### What minimal configuration is needed to reproduce the bug?

```scss
body {
  vertical-align: 0.25em; // Because not using full height numbers
  text-decoration-thickness: 0.75px; // Underline is too heavy
}
```

### How did you run Stylelint?

`npx stylelint --fix test.scss`

### Which Stylelint-related dependencies are you using?

```json                                                                                                                                     
    "stylelint": "^16.10.0",
    "stylelint-config-standard": "^36.0.1",
    "stylelint-config-standard-scss": "^13.1.0",
```

### What did you expect to happen?

I expected nothing to happen on the given file.

### What actually happened?

```
test.scss
  2:27  ✖  Unexpected double-slash CSS comment  no-invalid-double-slash-comments
  2:27  ✖  Unexpected unknown property "//"     property-no-unknown

✖ 2 problems (2 errors, 0 warnings)
```
