### ISSUE TITLE
Add `nesting`

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#8160]
### What is the problem you're trying to solve?

Require or disallow [nesting](https://drafts.csswg.org/css-nesting-1/#nested-declarations-rule).

For example:

```css
a {
  color: red;

  &:hover {
    color: blue;
  }
}
```

or

```css
a {
  color: red;
}

a:hover {
  color: blue;
}
```

### What solution would you like to see?

A new rule:

- Name: `nesting`
- Description: Require or disallow nesting
- Messages: 
   - `expected` = Expected nesting
   - `rejected` = Unexpected nesting
- Primary option: `"always"|"never"`
- Secondary options: `exceptSelectors: []`
- Category: Enforce conventions > Allowed, disallowed & required > Nesting
- Autofix?: Yes for `"always"`
- Included in sharable configs?: No

Prior art: [`stylelint-use-nesting`](https://github.com/csstools/stylelint-use-nesting)
