### ISSUE TITLE
Add `selector-explicit-nesting`

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#8161]
### What is the problem you're trying to solve?

Require or disallow explicit [nesting selector](https://drafts.csswg.org/css-nesting-1/#nest-selector).

```css
a {
  & > b {}
}
```

or 

```css
a {
  > b {}
}
```

### What solution would you like to see?

A new rule:

- Name: `selector-explicit-nesting`
- Description: Require or disallow explicit nesting selectors
- Messages: 
   - `expected` = Expected explicit nesting selector
   - `rejected` = Unexpected explicit nesting selector
- Primary option: `"always"|"never"`
- Secondary options: none
- Category: Enforce conventions > Allowed, disallowed & required > Nesting
- Autofix?: Yes 
- Included in sharable configs?: Yes, `"always"`

**Comment by Mouvedia** [comment]
`never` will have to ignore compound selectors and pseudo-elements/classes that are not after the descendant combinator.
e.g. `&:foo`, `&.bar`

**Comment by romainmenke** [comment]
Thank you @jeddy3 for opening this issue.

There is one more curious case:

```css
.foo {
  :is(&, .a) {
    color: green;
  }
}

.foo {
  :is([&=foo], .b) { /* & is not even valid in that position */
    color: green;
  }
}
```

https://codepen.io/romainmenke/pen/raBVMPV

Implicit nesting logic only kicks in when there is no `&` in a selector in the tokens stream.
It doesn't consider the validity of the parsed selectors or how selector lists can have multiple arms.

So you can "escape" the nesting and selector completely unrelated parts of the DOM.

In the examples above the `.a`/`.b` selector will select any `class="a"`/`class="b"` element, regardless of these having a `.foo` parent. Their actual selector will simply be `.a`/`.b` without any implicit nesting being applied.

Even weirder is that you can affect the specificity of the selectors in this way:

```css
#does-not-exist {
  :is(&, .a) { /* .a has a specificity of [1 0 0]
    color: green;
  }
}
```

I think that authors will almost never want to leverage this loophole and that when they write this it will have been a typo.

So I think we should also warn when encountering functional pseudos that contain "unbalanced" lists.

This is fine:

```css
.foo {
  :is(&, &.a) {
    color: green;
  }
}
```

This should error:

```css
.foo {
  :is(&, .a) {
    color: green;
  }
}
```

------

(to clarify)

> `never` will have to ignore compound selectors and pseudo-elements/classes that are not after the descendant combinator.
e.g. `&:foo`, `&.bar`

Because implicit nesting is `& <some-selector>` we can only removing `&` for `never` when there is a singular `&` followed by whitespace at the start of a selector.

explicit nesting:
- `.foo { &:hover }`
- `.foo:hover`

implicit nesting:
- `.foo { :hover }`
- `.foo :hover` notice the space between `.foo` and `:hover`

**Comment by jeddy3** [comment]
I should've suggested `selector-nesting-notation` with `"implicit"|"explicit"` options to align with [our conventions](https://stylelint.io/developer-guide/rules#primary), i.e. [enforce one representation](https://stylelint.io/user-guide/rules#notation) of the nesting selector.

> Implicit nesting logic only kicks in when there is no `&` in a selector in the tokens stream.

We can lean into that.

For `"explicit"`:

- for every selector in a selector list
- if the selector doesn't include `&` anywhere
- we append `&` and a space at the front

For example:

```css
a {
  .foo,
  > .bar,
  &:hover,
  .baz & {}
}
```

Becomes:

```css
a {
  & .foo,
  & > .bar,
  &:hover,
  .baz & {}
}
```

For `"implicit"`:

- for every selector in a selector list
- if the selector starts with `&` followed by a space
- we remove that `&` and space

For example:

```css
a {
  & .foo,
  & > .bar,
  &:hover,
  .baz & {}
}
```

Becomes:

```css
a {
  .foo,
  > .bar,
  &:hover,
  .baz & {}
}
```

Does that sound about right?

---

That loophole is bonkers. Although, it makes sense if:

```css
#does-not-exist {
  :is(&, .a) {
    color: green;
  }
}
```

is desugared by browsers to:

```css
:is(#does-not-exist, .a) {
  color: green;
}
```

Shall we handle that in a separate rule, like `selector-pseudo-class-no-unbalanced-nesting-selectors`?

**Comment by jeddy3** [comment]
Judging by [this example](https://drafts.csswg.org/css-nesting/#syntax-examples) in spec, I may of got the rule logic wrong:

```css
/* But if you use a relative selector an initial & is implied automatically */

.foo {
  color: red;
  + .bar + & { color: blue; }
}

/* equivalent to
  .foo { color: red; }
  .foo + .bar + .foo { color: blue; }
*/
```

How do we tweak the rule logic to fit that?
