### ISSUE TITLE
Add `selector-no-solo-nesting`

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#8162]
### What is the problem you're trying to solve?

Disallow solo nesting selectors.

```css
a {
  color: red;

  & {
    background: green;
  }
}
```

### What solution would you like to see?

- Name: `selector-no-solo-nesting`
- Description: Disallow solo nesting selector in selectors
- Messages: - `rejected` = Unexpected solo nesting selector
- Primary option: `true`
- Secondary options: none
- Category: Enforce conventions > Allowed, disallowed & required > Nesting
- Autofix?: Maybe, if possible 
- Included in sharable configs?: Recommended, `true`

(Needs a better name 😅)

**Comment by romainmenke** [comment]
Thank you for splitting this out @jeddy3 

I think this should indeed warn:

```css
a {
  color: red;

  & {
    background: green;
  }
}
```

But this should be fine (possibly gated behind a rule option):

```css
a {
  color: red;

  @media print {
    color: black;
  }

  & {
    background: green;
  }
}
```

Browsers initially shipped a version of nesting where 

```css
a {
  color: red;

  @media print {
    color: black;
  }

  background: green;
}
```

Would internally become:

```css
a {
  color: red;
  background: green; /* this is now in a different position */

  @media print {
    color: black;
  }
}
```

This was a breaking change and authors might still want to be prudent if they need to support some of the older browser versions that have the old behavior.

------

There is also:

```css
@scope (.foo) {
  & {}
  :scope {}
}
```

Where `:scope` has different specificity from `&`.
As also explained here: https://developer.mozilla.org/en-US/docs/Web/CSS/@scope#specificity_in_scope

So authors writing `&` in `@scope {}` are likely opting-in to that behavior and are not writing a needless nested rule.

I am unsure what the boundaries are.
For example:

```css
@scope (.foo) {
  @media screen {
    & {}
    :scope {}
  }
}
```

----

We should make sure that we only warn about `& {}` when it is truly not needed and that authors aren't writing it to work around one of the legacy issues or to opt-in to specific behaviors.

**Comment by jeddy3** [comment]
Thanks for the insightful breakdown.

I agree with adding a secondary option to make the rule more permissive  for:

```css
a {
  color: red;

  @media print {
    color: black;
  }

  & {
    background: green;
  }
}
```

Perhaps, `ignore: ["after-at-rule-block"]`?

(I assume this behaviour predated the introduction of [nested declarations rules](https://drafts.csswg.org/css-nesting/#nested-declarations-rule) into the spec?)

I also agree that it's unlikely needless in `@scope`. Shall we play it safe by ignoring everything within `@scope`?

As an aside, my head went 🤯 when I saw the [use case of chaining `&` multiple times](https://developer.mozilla.org/en-US/docs/Web/CSS/@scope#the_difference_between_scope_and_inside_scope):

```css
@scope (.feature) {
  /* Selects a .feature inside the matched root .feature */
  & & { }
}
```
