### ISSUE TITLE
`declaration-block-no-duplicate-properties`: check other rules as well

### ISSUE THREAD

**Issue by silverwind** [stylelint/stylelint#8192]
### What is the problem you're trying to solve?

`declaration-block-no-duplicate-properties` is currently limited to detecting duplicate properties within the same rule, so this goes undetected:

```css
.foo {
  color: red;
}

.foo,
.bar {
  color: red;
}
```

### What solution would you like to see?

It could check for duplicates within other rule and report any where the selector+prop+value combination is the same. This would not be completely safe to fix, so I don't recommend adding `--fix` for this.

**Comment by Mouvedia** [comment]
Hello @silverwind,

This rule is scoped to `declaration-block` so it should not have access to other declaration blocks.
There would still be problems even if we were to ignore the declared scope.
e.g.

- selector lists would have to be ignored or require very complex fixers

```css
.foo, .qux {
  color: red;
}

.foo, .bar {
  color: red;
}
```
would be fixed to
```css
.foo, .bar, .qux {
  color: red;
}
```
but
```css
.foo, .qux {
  color: red;
  display: block;
}

.foo, .bar {
  color: red;
  background: black;
}
```
would be fixed to
```css
.foo, .qux {
  display: block;
}

.foo, .bar {
  background: black;
}

.foo, .bar, .qux {
  color: red;
}
```

- once the scope restriction lifted we would expect the fixer to remove empty blocks

e.g.
```css
.foo {
  color: red;
}

.foo,
.bar {
  color: red;
}
```
would be fixed to
```css
.foo,
.bar {
  color: red;
}
```

- the fixer while extracting the common properties in a new declaration will require to be aware of the format style of the file
so that it won't force a second linter run

e.g.
```css
.foo, .qux {
  color: red;
  display: block;
}

.foo, .bar {
  color: red;
  background: black;
}
```
could be fixed to
```css
.foo, .qux {
  display: block;
}

.foo, .bar {
  background: black;
}

.foo,
.bar,
.qux { color: red; }
```
but we probably want
```css
.foo, .qux {
  display: block;
}

.foo, .bar {
  background: black;
}

.foo, .bar, .qux {
  color: red;
}
```
