### ISSUE TITLE
Add `syntax-string-no-invalid`

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#8213]
### What is the problem you're trying to solve?

There are specific rules for [syntax strings](https://drafts.css-houdini.org/css-properties-values-api/#syntax-strings).

```css
@property --foo {
  syntax: "this-string"
}
```

It's easy for people to make mistakes when defining them.

Ref: https://github.com/stylelint/stylelint/pull/8211#discussion_r1892711278

### What solution would you like to see?

A new rule to flag invalid syntax strings.

I don't even know if validating the syntax is viable, but I figured it was worth discussing.

It could start simple and only flag [unsupported names](https://drafts.css-houdini.org/css-properties-values-api/#supported-names), for example:

```css
@property --foo {
  syntax: "<alpha-value>"
}
```
