### ISSUE TITLE
Fix `declaration-block-no-redundant-longhand-properties` false positives for properties with `!important`

### ISSUE THREAD

**Issue by dangreen** [stylelint/stylelint#8323]
### What minimal example or steps are needed to reproduce the bug?

```css
a {
	top: 0;
	right: 0;
	bottom: 0 !important;
	left: 0;
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "declaration-block-no-redundant-longhand-properties": true
  }
}
```

### How did you run Stylelint?

https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdugLjiADvCgAwDcWuATgJYDmAFjseZTgEYR4QC2LKAQho8CEKjiSYcFbDgA2MAGbNSMgL5YQAGhCKaCgHJIecRDAAexggoB0YAM73t4CJj10EIDJhQp0ICxwYTCh7f2IAbSxfX397HABPBTkaKQBaSDd6NPjJKCQqKH9olABdLDVnTPcAMTEeJBxPACt7V2dYAidEb1iQeKSYFKlwvxA5Rph4-y0SuMTk1JwM13cciRCCooQxiaDpkAqQNSA

### Which Stylelint-related dependencies are you using?

latest

### What did you expect to happen?

```css
a {
	top: 0;
	right: 0;
	bottom: 0 !important;
	left: 0;
}
```

should not be formatted as 

```css
a {
	inset: 0;
}
```

because of `!important`

### What actually happened?

```css
a {
	top: 0;
	right: 0;
	bottom: 0 !important;
	left: 0;
}
```

formatted as

```css
a {
	inset: 0;
}
```
