### ISSUE TITLE
Fix `declaration-property-value-no-unknown` false positives for `overflow-*`

### ISSUE THREAD

**Issue by coderaiser** [stylelint/stylelint#8339]
### What is the problem you're trying to solve?

I have next code:

```css
@supports (overflow: overlay) {
    .files {
        overflow-y: overlay;
    }
}
```

As I see:

> Note: The keyword value `overlay` is a legacy value alias for `auto`. With overlay, the scroll bars are drawn on top of the content instead of taking up space.

https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-y

### What solution would you like to see?

Would be great to have auto fix for this:

```css
@supports (overflow: overlay) {
    .files {
        overflow-y: auto;
    }
}
```

---

`overlay` is not the only case.

e.g.
```css
a {
  overflow-x: -moz-hidden-unscrollable;
}
```

We just need to reuse [`<-non-standard-overflow>`](https://csstree.github.io/docs/syntax/#Type:-non-standard-overflow).
