### ISSUE TITLE
Allow overlapping stylelint-disable ranges

### ISSUE THREAD

**Issue by kristerkari** [stylelint/stylelint#840]
Currently it is not possible to use `stylelint-disable` comments with nested selectors. That limits the usage of the feature in cases where you are using nesting and want to disable certain rules inside the nested selectors.

After adding support for `stylelint-disable` and nesting, this should be possible:

```scss
/* stylelint-disable any-rule */
.foo {
  /* stylelint-disable selector-no-id */
  .bar,
  #bar {
  /* stylelint-enable selector-no-id */
   color: black;
  }
}
```
