### ISSUE TITLE
Compound warnings with data URI's and function-url-quotes

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#841]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

When using the rule `function-url-quotes` alongside `number-leading-zero`, and `function-comma-space-after` rules then those rules will throw the related warnings when using `data` URI's.

> Which rule, if any, is this issue related to?

`function-url-quotes`, `number-leading-zero`, and `function-comma-space-after`

> What CSS is needed to reproduce this issue?

```css
/* A couple of basic url examples, triggers "function-comma-space-after" rule warnings */
a { background: url(data:image/gif;base64,BESE64ENCODEDSTRING==); }
a { background-image: url(data:image/png;base64,BASE64ENCODEDSTRING==); }

/* An example that contains a number less than zero without a leading zero, triggers "number-leading-zero" rule warnings */
a { background-image: url(data:image/svg+xml;charset=utf8,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.example.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2020%2020%27%3E%3Cpath%20d%3D%27M14.5%2012q1.24%200%202.12.88T17.5%2015t-.88%202.12-2.12.88-2.12-.88T11.5%2015q0-.34.09-.69l-4.38-2.3Q6.32%2013%205%2013q-1.24%200-2.12-.88T2%2010t.88-2.12T5%207q1.3%200%202.21.99l4.38-2.3q-.09-.35-.09-.69%200-1.24.88-2.12T14.5%202t2.12.88T17.5%205t-.88%202.12T14.5%208q-1.3%200-2.21-.99l-4.38%202.3Q8%209.66%208%2010t-.09.69l4.38%202.3q.89-.99%202.21-.99z%27%20fill%3D%27%230073aa%27%2F%3E%3C%2Fsvg%3E); }
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "function-comma-space-after": "always",
    "function-url-quotes": "none",
    "number-leading-zero": "always",
  }
}
```

> Which version of stylelint are you using? `4.4.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint --config node_modules/stylelint-config-wordpress/index.js src/test.css`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)? No

> What did you expect to happen?

In a perfect world, no warnings to be flagged.

> What actually happened (e.g. what warnings or errors you are getting)?

Both these warnings were flagged for the example CSS above:

```shell
test.css
16:39	⚠  Expected single space after "," (function-comma-space-after) [stylelint]
61:209	⚠  Expected a leading zero (number-leading-zero) [stylelint]
```

Currently I'm working around this using:
`/* stylelint-disable function-comma-space-after, number-leading-zero */`

I'm not sure if there is an easy way to modify the `function-url-quotes` rule here, or if some exceptions should be added to the `number-leading-zero` and `function-comma-space-after` rules
