### ISSUE TITLE
Add `container-name-pattern`

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#8432]
### What is the problem you're trying to solve?

I want to enforce consistent naming conventions for my [container names](https://drafts.csswg.org/css-conditional-5/#container-name).

```css
@container --foo {};

a {
  container-name: --bar;
  container: --baz / inline-size;
}
```

### What solution would you like to see?

A new rule:

- Name: `container-name-pattern`
- Description: Specify a pattern for container names.
- Message: `Expected "${name}" to match pattern "${pattern}"`
- Primary option: `string|regex`
- Secondary options: None
- Category: Enforce conventions > Patterns
- Autofix?: No
- Included in sharable configs?: Yes (kebab case with `--` prefix)
- Expanded description: N/A
