### ISSUE TITLE
Fix missing fixes in computed `EditInfo`

### ISSUE THREAD

**Issue by pamelalozano16** [stylelint/stylelint#8639]
### What minimal example or steps are needed to reproduce the bug?

This example returns a fix only for `declaration-block-no-redundant-longhand-properties`, so it's missing both fixes for `rule-empty-line-before`:
```scss
// declaration-block-no-redundant-longhand-properties and rule-empty-line-before
.baz {
  padding-top: 11px;
  padding-right: 12px;
  padding-bottom: 13px;
  padding-left: 14px;
}

// rule-empty-line-before
.foo {
  color: blue;
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "extends": [
    "stylelint-config-standard-scss"
  ],
  "rules": {
    "rule-empty-line-before": "always"
  }
}
```

### How did you run Stylelint?

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcID0SAEswBsCGAnbALgJYQB2AtAEaYRgDW5pE5uMUArqVNqQeTaQDmACx5RyAB1wQJMXMRgBnVGNS52mGORgBbCQQCe-IqS2UYAMwisAOqQB0lbAC9UwO6lQTsUKCcHkBDLwqACMoRIAHgDcHl4+fkIsRCIEIaEATFGxpJ7evv5UEARBOukAzNlx+YkBmhZpYQAsVaQAvnZ2KGoaWrr6RpgmZpbWMHb2VhBucZA0uCHU7DA5bSAANCAWRJoActg6cIgwkQcSmvaKYIqKG+Bk24IIIO65qDYgJwQwXIofIQBtOKeD6KQyaIa8ciQUiPchgsR4cRXG4fOIAXXWcQ+6k0fwQMzeIJAuL6ekMxlMVFGtgJH2wmAA7tgDPi4h12ncYY8AGLWHSEZ4AK0UZDusAkt0Qr2JYIMEJMfBR+JCHxw3zBHyxb1B4JgkL43JS8IIiNwyOuKveIHVSgIaM5bSAA)

### Which Stylelint-related dependencies are you using?

```json
{
    "postcss": "^8.5.6",
    "stylelint": "^16.21.0",
    "stylelint-config-standard-scss": "^15.0.0",
    "stylelint-scss": "^6.12.1",
}
```

### What did you expect to happen?

For this case:
```scss
// declaration-block-no-redundant-longhand-properties and rule-empty-line-before
.baz {
  padding-top: 11px;
  padding-right: 12px;
  padding-bottom: 13px;
  padding-left: 14px;
}

// rule-empty-line-before
.foo {
  color: blue;
}
```
The warnings should be
```json
{
  "warnings": [
    {
      "line": 6,
      "column": 3,
      "endLine": 6,
      "endColumn": 15,
      "fix": {
        "text": ": 11px 12px 13px",
        "range": [
          70,
          144
        ]
      },
      "rule": "declaration-block-no-redundant-longhand-properties",
      "severity": "warning",
      "text": "Expected shorthand property \"padding\" (declaration-block-no-redundant-longhand-properties)"
    },
    {
      "line": 1,
      "column": 1,
      "endLine": 7,
      "endColumn": 2,
      "rule": "rule-empty-line-before",
      "fix": {
        "text": "\n\n",
        "range": [...]
      },
      "severity": "warning",
      "text": "Expected empty line before rule (rule-empty-line-before)"
    },
    {
      "line": 10,
      "column": 1,
      "endLine": 12,
      "endColumn": 2,
      "rule": "rule-empty-line-before",
      "fix": {
        "text": "\n\n",
        "range": [...]
      },
      "severity": "warning",
      "text": "Expected empty line before rule (rule-empty-line-before)"
    }
  ]
}
```

### What actually happened?

```json
{
  "warnings": [
    {
      "line": 6,
      "column": 3,
      "endLine": 6,
      "endColumn": 15,
      "fix": {
        "text": ": 11px 12px 13px",
        "range": [
          70,
          144
        ]
      },
      "rule": "declaration-block-no-redundant-longhand-properties",
      "severity": "warning",
      "text": "Expected shorthand property \"padding\" (declaration-block-no-redundant-longhand-properties)"
    },
    {
      "line": 2,
      "column": 1,
      "endLine": 7,
      "endColumn": 2,
      "rule": "rule-empty-line-before",
      "severity": "warning",
      "text": "Expected empty line before rule (rule-empty-line-before)"
    },
    {
      "line": 10,
      "column": 1,
      "endLine": 12,
      "endColumn": 2,
      "rule": "rule-empty-line-before",
      "severity": "warning",
      "text": "Expected empty line before rule (rule-empty-line-before)"
    }
  ]
}
```

However, this example returns the fix for the first `rule-empty-line-before` violation, but is missing the fixes for `shorthand-property-no-redundant-values` and the second `rule-empty-line-before` rule break:
```scss 
// shorthand-property-no-redundant-values and rule-empty-line-before
.baz {
  padding: 10px 10px 10px 10px;
}

// rule-empty-line-before
.red {
  color: blue;
}
```
```json
{
  "warnings": [
    {
      "line": 2,
      "column": 1,
      "endLine": 4,
      "endColumn": 2,
      "fix": {
        "text": "* shorthand-property-no-redundant-values and rule-empty-line-before*/\n\n.baz {\n  padding: 10px 10px 10px 10px;\n}\n\n/* rule-empty-line-before*/",
        "range": [
          1,
          136
        ]
      },
      "rule": "rule-empty-line-before",
      "severity": "warning",
      "text": "Expected empty line before rule (rule-empty-line-before)"
    },
    {
      "line": 7,
      "column": 1,
      "endLine": 9,
      "endColumn": 2,
      "rule": "rule-empty-line-before",
      "severity": "warning",
      "text": "Expected empty line before rule (rule-empty-line-before)"
    },
    {
      "line": 3,
      "column": 12,
      "endLine": 3,
      "endColumn": 31,
      "rule": "shorthand-property-no-redundant-values",
      "severity": "warning",
      "text": "Expected \"10px 10px 10px 10px\" to be \"10px\" (shorthand-property-no-redundant-values)"
    }
  ]
}
```
