### ISSUE TITLE
Rule for block/inline comments in SCSS

### ISSUE THREAD

**Issue by XOP** [stylelint/stylelint#866]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

I'd like to propose a rule for distinction comments' usage in SCSS.
In my guidelines, there is a basic principle, that separates block comments from inline.
Inline comments can only be used inside of braces (thus pointing to nesting and/or context),
and block comments used for all other purposes.
So this is correct:
```scss
/* comment */
.foo {
    color: #fff; // comment
}
```

And this is incorrect:
```scss
// comment
.bar {
    /* comment */
    color: #bbb;
}
```
Of course, this is only valid for **scss syntax**.

> Which rule, if any, is this issue related to?

There are some related rules:
`comment-empty-line-before`
`no-invalid-double-slash-comments`
`at-rule-empty-line-before`
`rule-non-nested-empty-line-before`
`rule-nested-empty-line-before`

> What CSS is needed to reproduce this issue?

here's all in places:
```scss
/* comment */
.foo {
    color: #fff; // comment
}
```

and there should be 2 errors:
- inline comment outside of braces
- block comment inside of braces
```scss
// comment
.bar {
    /* comment */
    color: #bbb;
}
```

> What stylelint configuration is needed to reproduce this issue?

Here's my config that is WIP currently,  
just because it needs some more rules to be accurate.
[https://www.npmjs.com/package/stylelint-config-xop](https://www.npmjs.com/package/stylelint-config-xop) 

> Which version of stylelint are you using?

`4.4.0`, will change to `4.5.0` since it has useful feature for disabling lines of rules and some extra.

> How are you running stylelint: CLI, PostCSS plugin, Node API?

I'm using Node API, 
CLI didn't work for me (different results on linting, but I guess this is _another issue_)

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

SCSS syntax, nesting, yes. And to most of CSS preprocessors, since they allow inline comments usage.

> What did you expect to happen?

errors / warnings as described above

> What actually happened (e.g. what warnings or errors you are getting)?

nothing, it's not implemented

So, finally. If I need this behaviour, should I go for plugin or rule is ok?
For me it looks more like combination of rules.
Something for disallowing usage of inline comments outside of braces etc.
