### ISSUE TITLE
stylelint-disable-reason

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#907]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

We work in big command and some development use browser's hack (not only `*`, `_`, see all working hack in http://browserhacks.com/). Because of this we have to turn off the stylelint in specific places, but then the other person starts to work on the code and it becomes difficult to understand what was used in the hack and why this place has been turned off. It would be convenient to force developer add comments, where they turn off linter.

> Which rule, if any, is this issue related to?

e.g. `require-reason-disable-linter`

> What CSS is needed to reproduce this issue?

e.g.

```css
.foo {
   color: #000;
}

/* stylelint-disable selector-root-no-composition, selector-no-vendor-prefix, root-no-standard-properties */
/* Reason: Need white color for IE >= 11 */
_:-ms-fullscreen,
:root .foo {
    color: #fff;
}
/* stylelint-enable selector-root-no-composition, selector-no-vendor-prefix, root-no-standard-properties */
```

> What stylelint configuration is needed to reproduce this issue?

e.g.

```json
{
  "rules": {
    "require-reason-disable-linter": true
  }
}
```

> Which version of stylelint are you using?

`5.0.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

PostCSS plugin

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

SCSS

> What did you expect to happen?

Throw error if comment not present.

> What actually happened (e.g. what warnings or errors you are getting)?

Nothing

**Comment by jeddy3** [comment]
@davidtheclark Would this make a good candidate for a plugin as:

1. It's quite a specific use case.
2. It's kind of related to methodology as this rule could just enforce that a stylelint command comment is followed by another comment, but each team would probably want to ensure something specific within that comment e.g. in the example above it is that it begins with "Reason: ".
3. I can see edge-cases emerging if we make it generic e.g. what about `stylelint-disable-line` commands.

**Comment by evilebottnawi** [comment]
@jeddy3 `Reason` it is simple example, need only comment node after disable rule. I think rule good look in core, not plugin. Scss-lint have same rule - https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#disablelinterreason. Sometimes need comments not only for browsers hack. Example:
```css
.foo {
    display: block;
    /* stylelint-disable declaration-block-no-duplicate-properties */
    /* For browsers supports flex */
    display: flex;
    /* stylelint-enable declaration-block-no-duplicate-properties */
}
```
