### ISSUE TITLE
Comments should be allowed above hierarchical selectors in indentation

### ISSUE THREAD

**Issue by magsout** [stylelint/stylelint#940]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

it's a bug

> Which rule, if any, is this issue related to?

`indentation`

> What CSS is needed to reproduce this issue?

e.g.

```css
:root {
  --r-Grid-baseFontSize: 1rem;
  --r-Grid-gutter: 1rem;
}

.r-Grid {
  padding: 0;
  margin: 0;
}

  .r-Grid-cell {
    font-size: var(--r-Grid-baseFontSize);
    width: 100%;
    padding: 0;
  }

  /* Modifier --withGutter */
  .r-Grid--withGutter {
    margin: 0 calc(-0.5 * var(--r-Grid-gutter));
  }

    .r-Grid--withGutter > .r-Grid-cell {
      padding: 0 calc(0.5 * var(--r-Grid-gutter));
    }
```

> What stylelint configuration is needed to reproduce this issue?

```json
"stylelint": {
    "extends": "stylelint-config-standard",
    "rules": {
      "indentation": [ 2, {
        "hierarchicalSelectors": true
        }]
    }
  },
```

> Which version of stylelint are you using?

`stylelint@5.0.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

`stylelint ./lib/base.css`

> What did you expect to happen?

 "No warnings to be flagged."

> What actually happened (e.g. what warnings or errors you are getting)?

```shell
lib/base.css
17:3	Expected indentation of 0 spaces (indentation)
18:3	Expected indentation of 0 spaces (indentation)
19:5	Expected indentation of 2 spaces (indentation)
20:3	Expected indentation of 0 spaces (indentation)
```

If I removed my comment `/* Modifier --withGutter */` there is no more warning.
