### ISSUE TITLE
no-duplicate-selectors: using identical selectors within separate @mixins / @includes causes error.

### ISSUE THREAD

**Issue by timothyneiljohnson** [stylelint/stylelint#947]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug where using SCSS multiple @mixin or @include containing similar selectors triggers a 'no-duplicate-selectors' error.

> Which rule, if any, is this issue related to?

`no-duplicate-selectors`

> What CSS is needed to reproduce this issue?

```css
@mixin no-margin-at-ends {
  &:last-child {
    margin-bottom: 0;
  }
  &:first-child {
    margin-top: 0;
  }
}

@mixin no-side-margin-at-ends {
  &:last-child {
    margin-right: 0;
  }
  &:first-child {
    margin-left: 0;
  }
}
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "'no-duplicate-selectors": true
  }
}
```

> Which version of stylelint are you using?

`5.0.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

PostCSS plugin in Gulp with
```
var stylelint = require('stylelint');
var syntax_scss = require('postcss-scss');

gulp.task('stylelint', function() {
  var processors = [
    stylelint(),
    reporter({
      clearMessages: true,
      throwError: true
    })
  ];

  return gulp.src([
    paths.source.css + '**/*.scss',
  ])
  .pipe(postcss(processors, {syntax: syntax_scss}));
});
```

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Yes, it's related to SCSS @mixin and/or @include.

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors you are getting)?

e.g. "The following warnings were flagged:"

```shell
88:3	⚠  Unexpected duplicate selector "&:last-child" (no-duplicate-selectors) [stylelint]
91:3	⚠  Unexpected duplicate selector "&:first-child" (no-duplicate-selectors) [stylelint]
```
