### ISSUE TITLE
selector-nested-pattern

### ISSUE THREAD

**Issue by mmacartney10** [stylelint/stylelint#962]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A new rule to only allow pseudo classes to be nested. When I write SASS 

> Which rule, if any, is this issue related to?

e.g. `number-leading-zero`

> What CSS is needed to reproduce this issue?

**Valid**

```css
.item {
	 &:before {
	 	content: '';
	 }
}
```

**Invalid**

```css
.item {
	.child {
		background: #FFF;
	}
}
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "only-nest-pseudo-classes": true 
  }
}
```

> Which version of stylelint are you using?

`5.0.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Using the PostCss plugin

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

SCSS syntax
