### ISSUE TITLE
Add alignBlockClosingBrace option to indentation

### ISSUE THREAD

**Issue by pepelsbey** [stylelint/stylelint#984]
Here’s the feature request for a rule that could enforce closing brace to be indented. Let’s say `block-closing-brace-indent-before`. There’s a code style I inherited a long time ago from Dan Cederholm ([Simplebits](http://simplebits.com/)), he’s [still using it](https://github.com/simplebits/Pears/blob/master/css/screen.less), so [am I](https://github.com/shower/ribbon/blob/master/styles/slide/content/code.scss#L39-L41).

```css
.foo {
    color: pink;
    }
/** ↑
The indent before this brace */
    .bar {
        color: pink;
        }
/**     ↑
The indent before this brace */
```

This code style makes it easier to parse through a list of selectors and really useful when you’re trying to build an indented tree of your declaration blocks.

I went through all issues and existing rules but haven’t found anything similar. I’ll be glad to supply any additional information or file this request properly in case of any problems here. Or, who knows, even send a PR once I get a general approval.
