### ISSUE TITLE
function-url-data-uris

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#996]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Disable usage inline media in `url` function.

> Which rule, if any, is this issue related to?

`function-url-no-inline`

> What CSS is needed to reproduce this issue?

e.g.

```css
.foo {
  background-image: url(data:image/gif;base64,R0lGODlhDAANANUAAPv7+/r6+vn5+ff39/b29vX19fPz8/Dw8O/v7+7u7u3t7ezs7Onp6ejo6Ofn5+bm5uTk5OPj4+Hh4eDg4N/f397e3tzc3Nvb29ra2tnZ2dbW1tXV1dPT09LS0tHR0c3NzcjIyMfHx8bGxsXFxby8vLe3t7W1tbOzs62traurq6mpqaioqKenp6ampqWlpaOjo6KioqGhoaCgoJ+fn5qampmZmf///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAUUADYALAAAAAAMAA0AAAZxQJtwyGYrVaLEQswGYWAOAygxWELxaFwCVUWi/bRyZaJM5nUezjInkcjHi8U2rVNhmJY++QZDg0NBgTExEPhxJ+NCogDY6PjiMqGisLCJeYDTIaNikmCgOhAwgnKUICKCsdBgYdMSgCRBgogSgZQ0EAOw==);
}
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "function-url-no-inline": true
  }
}
```

> Which version of stylelint are you using?

`5.2.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

no matter

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

no matter

> What did you expect to happen?

Throw errors.

> What actually happened (e.g. what warnings or errors you are getting)?

Nothing
